### PR TITLE
Title fix for Small & Minority Businesses

### PR DESCRIPTION
**Pull request by KimberlyMunoz**
Fixing the title on Small & Minority Businesses

## Changes

- Fixed title on small and minority businesses

## Testing
- Visit http://localhost:8000/doing-business-with-us/small-businesses/

## Review

- @sebworks 
- @anselmbradford 
- @jimmynotjim 

## Preview

image

[Preview this PR without the whitespace changes](?w=0)

## Notes

- I confirmed with @sarahsimpson09 that only the title on the top should be changed. Navigation items should stay the same.
- DFJR-81 on the JIRA board

### CODE REVIEW

**Comment by Scotchester** [comment]
What's going on with the mixed capitalization in the breadcrumb?

**Comment by anselmbradford** [comment]
Shouldn't the sidebar menu item and the main title be the same? cc @schaferjh

**Comment by KimberlyMunoz** [comment]
I confirmed with @sarahsimpson09 that only the title on the top should be changed. Navigation items should stay the same.

**Comment by anselmbradford** [comment]
> I confirmed with @sarahsimpson09 that only the title on the top should be changed. Navigation items should stay the same.

This looks like a mistake to me, but okay.

**Comment by jimmynotjim** [comment]
:+1: after addressing @Scotchester's breadcrumb question

**Comment by sebworks** [comment]
:+1:

**Comment by KimberlyMunoz** [comment]
Breadcrumb thing is being addressed in #1030

**Pull request merged**
