### PR TITLE
Fix up Events processor

### PR DESCRIPTION
**Pull request by kurtw**
The Events processor needed some love. This should take all the fields from Wordpress and put them into the Elasticsearch index.

### Review
@anselmbradford @jimmynotjim @sebworks @KimberlyMunoz

### CODE REVIEW

**Comment by jimmynotjim** [comment]
Does this require the updates made in CMS Toolkit and wp-flapjack?

**Comment by anselmbradford** [comment]
So in jira task DF-1782 I wrote awhile back: 

> Add filter for now and before, based on the end time of the event, in _queries/events_archive.json
 See http://www.elastic.co/guide/en/elasticsearch/reference/1.4/query-dsl-range-filter.html and  newsroom.json file in _queries

With the disappearance of `events_archive.json`, how should filtering for the archive work?

**Comment by sebworks** [comment]
@kurtw are we using ending_time to determine if the event is archived? I realize that local time then becomes problematic.

**Comment by kurtw** [comment]
@jimmynotjim It requires an update to wp-flapjack to work and I've reflected that in the description now.

@anselmbradford @sebworks the filtering for the archive should be to get any events with an ending_time after the current time. There is no conflict with "local time" because each of these dates have a timezone selected for them.

To the point of filtering for archived events, I'll put in another query that will get these events instead of us doing a filter every time.

**Comment by kurtw** [comment]
Changes are up! Thanks for pointing that out everyone :+1:

**Comment by kurtw** [comment]
The dependent PR's have been pulled in and are being reviewed for deployment. You can use the master branches of cms-toolkit and wp-flapjack in order to test it out now. Will update when the updated code is on content/prod.

**Comment by jimmynotjim** [comment]
Tested locally and the data in Elasticsearch with a new indexing looks good. :+1:

**Pull request merged**
