### PR TITLE
Updates test deps + removes extraneous

### PR DESCRIPTION
**Pull request by anselmbradford**
## Removals

- `fastdom` and `marked`, which are extraneous.

## Changes

- Updates `browser-sync`, `psi `, `require-dir`, `cucumber`, `protractor `, `protractor-cucumber-framework`, `snyk`.
- Updates deprecated cucumber import statements. See https://github.com/cucumber/cucumber-js/blob/master/CHANGELOG.md#deprecations

## Testing

1. `./frontend.sh`
2. `gulp build`
3. `gulp test:acceptance`
4. `npm test` (if you have snyk creds)

## Notes

- I was getting two failures in the global-search and webpack feature files, but when run individually with the `--specs` flag they'd pass. I also see this on master. Curious if Travis will fail or if you have failures.

### CODE REVIEW

**Comment by anselmbradford** [comment]
@sebworks Have you seen this from `gulp test:acceptance --fast`? 
I get it on master and here.
(Sorry about the formatting)

```
Failures:

1) Scenario: Large Size, after entering Text # [90mtest/browser_tests/cucumber/features/suites/default/global-search.feature:22[39m
   [32m✔ Before[39m # [90mtest/browser_tests/cucumber/step_definitions/global-search.js:24[39m
   [32m✔ Before[39m # [90mtest/browser_tests/cucumber/step_definitions/header.js:30[39m
   [32m✔ Before[39m # [90mtest/browser_tests/cucumber/step_definitions/mega-menu.js:20[39m
   [32m✔ Before[39m # [90mtest/browser_tests/cucumber/step_definitions/multi-select.js:14[39m
   [32m✔ Given I goto URL "/"[39m # [90mtest/browser_tests/cucumber/step_definitions/application.js:9[39m
   [32m✔ When I enter "test" in the search molecule[39m # [90mtest/browser_tests/cucumber/step_definitions/global-search.js:43[39m
   [31m✖ Then it should have a clear button label[39m # [90mtest/browser_tests/cucumber/step_definitions/global-search.js:77[39m
       [31mAssertionError[39m
           [31m+ expected[39m [32m- actual[39m

           [32m-false[39m
           [31m+true[39m
       [90m
           at getBasePromise.then.then.newArgs (/Users/bradforda/Projects/cfgov-refresh/node_modules/chai-as-promised/lib/chai-as-promised.js:302:22)
           at ManagedPromise.invokeCallback_ (/Users/bradforda/Projects/cfgov-refresh/node_modules/selenium-webdriver/lib/promise.js:1376:14)
           at TaskQueue.execute_ (/Users/bradforda/Projects/cfgov-refresh/node_modules/selenium-webdriver/lib/promise.js:3084:14)
           at TaskQueue.executeNext_ (/Users/bradforda/Projects/cfgov-refresh/node_modules/selenium-webdriver/lib/promise.js:3067:27)
           at asyncRun (/Users/bradforda/Projects/cfgov-refresh/node_modules/selenium-webdriver/lib/promise.js:2927:27)
           at /Users/bradforda/Projects/cfgov-refresh/node_modules/selenium-webdriver/lib/promise.js:668:7
           at <anonymous>
           at process._tickCallback (internal/process/next_tick.js:188:7)[39m
   [32m✔ After[39m # [90mtest/browser_tests/cucumber/step_definitions/wagtail-admin-rich-text-editor.js:14[39m
   [32m✔ After[39m # [90mtest/browser_tests/cucumber/step_definitions/filterable-page.js:22[39m

2) Scenario: The following transpilers should have run: # [90mtest/browser_tests/cucumber/features/suites/default/webpack-build.feature:10[39m
   [32m✔ Before[39m # [90mtest/browser_tests/cucumber/step_definitions/global-search.js:24[39m
   [32m✔ Before[39m # [90mtest/browser_tests/cucumber/step_definitions/header.js:30[39m
   [32m✔ Before[39m # [90mtest/browser_tests/cucumber/step_definitions/mega-menu.js:20[39m
   [32m✔ Before[39m # [90mtest/browser_tests/cucumber/step_definitions/multi-select.js:14[39m
   [32m✔ Given I run gulp build to generate JS bundles[39m # [90mtest/browser_tests/cucumber/step_definitions/webpack-build.js:12[39m
   [31m✖ Then the JS bundles shouldn't contain double arrows or constants[39m # [90mtest/browser_tests/cucumber/step_definitions/webpack-build.js:16[39m
       [31mError: routes/on-demand/table.js contains const or ()=>[39m[90m
           at fs.readFile (/Users/bradforda/Projects/cfgov-refresh/test/browser_tests/cucumber/step_definitions/webpack-build.js:31:23)
           at tryToString (fs.js:513:3)
           at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:501:12)[39m
   [32m✔ After[39m # [90mtest/browser_tests/cucumber/step_definitions/wagtail-admin-rich-text-editor.js:14[39m
   [32m✔ After[39m # [90mtest/browser_tests/cucumber/step_definitions/filterable-page.js:22[39m
```

**Comment by sebworks** [comment]
Yeah, it's the animations. I'll look at it tonight.

**Comment by sebworks** [comment]
@anselmbradford, I think you can remove `gulp-babel` as well.

**Comment by anselmbradford** [comment]
`gulp-babel` removed in https://github.com/cfpb/cfgov-refresh/pull/3892

**Pull request merged**
