### PR TITLE
Customize social media share link content 

### PR DESCRIPTION
**Pull request by virginiacc**
As part of the OAH updates, we want to individually customize the content for each of the social media share types on OAH Wagtail pages. This PR adds the ability to specify separate content in the Wagtail social media module for a page's email, LinkedIn, and Twitter links.
       
## Additions

- New fields for email, LinkedIn, and Twitter content

## Changes

- Use new content values in generating links in `social-media.html`

## Review
@schaferjh 
@higs4281 
@cfpb/cfgov-frontends  
@cfpb/cfgov-backends 

## Testing

- Create a page and add a social media block in its sidebar. 
- Add custom content for email, LinkedIn, and Twitter links.
- Preview page and verify that links work as expected.

## Screenshots

screen shot 2016-11-30 at 8 58 40 am

screen shot 2016-11-29 at 9 21 57 pm

screen shot 2016-11-29 at 9 21 17 pm

screen shot 2016-11-29 at 9 20 35 pm

## Checklist

* [ ] Changes are limited to a single goal (no scope creep)
* [ ] Code can be automatically merged (no conflicts)
* [ ] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [ ] Passes all existing automated tests
* [ ] New functions include new tests
* [ ] New functions are documented (with a description, list of inputs, and expected output)
* [ ] Placeholder code is flagged
* [ ] Visually tested in supported browsers and devices
* [ ] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)
* [ ] Reviewers requested with the [Assignee tool](https://help.github.com/articles/assigning-issues-and-pull-requests-to-other-github-users/) :arrow_right:

### CODE REVIEW

**Comment by schaferjh** [comment]
@virginiacc The intention of this PR sounds great. I'm curious how the new fields are integrated with the existing fields in the Wagtail admin --- 

Just for reference, this is the current admin for the Social Media module, which automatically adds Facebook, Twitter, Linkedin, and Email buttons:
screen shot 2016-11-30 at 1 09 31 pm

Questions:
- Do these new fields appear above, below, or integrated with current fields?
- I'd like it to be more obvious that these new fields are all optional. Assuming these new fields are being added below the current fields, is it possible to put an "Optional" heading above all the fields below Blurb? Since all of them are essentially optional?
  - If that's not possible, for the fields that don't have a default value, it'd be great to modify the hint text to start the hint with "Optional, ...". For Email signature, I would remove "No default if blank" -- unless you want to add that for Linkedin text field as well so they're similar.

And finally --
- While you're in there, is it easy to change the hint text for the check box at the top of the module? This has been a source of some confusion and it would be great to update it. This is **not critical**, but if easy would be appreciated!
  - Current checkbox title: "Create sharing links:", New checkbox title: "Desired action: share this page"
  - Current hint text: "If deselected, links to visit CFPB profiles will be created", New hint text: "If unchecked, social media icons will link users to official CFPB accounts. Do not fill in any further fields."

**Comment by higs4281** [comment]
👍 fields work locally as advertised.

**Comment by virginiacc** [comment]
@schaferjh I updated the label/text for social media module check box. I don't think there's a straightforward way to group the optional fields under a header, so I added an `optional` indicator on each hint.

untitled

I was debating whether to add the new fields at the end of the form or integrate them, but I decided to go with alphabetical(ish) order and put them between the `Blurb` and `Twitter related` fields. Do you have a preference? I did wonder if the existing Twitter fields (or any set of the new fields?) were likely to be used more -- I could reorder if that's the case...

**Comment by higs4281** [comment]
👍 New label and optional help text show up correctly.

**Comment by schaferjh** [comment]
Looks good, thanks @virginiacc 

> I did wonder if the existing Twitter fields (or any set of the new fields?) were likely to be used more -- I could reorder if that's the case...
I do think the Twitter fields are more likely to be used -- so how about moving those fields to directly under Blurb, followed by email and Linkedin?

**Comment by virginiacc** [comment]
@schaferjh That sounds good! Here's the updated order:

revised

**Comment by schaferjh** [comment]
Thanks @virginiacc 

My field labeling mania is satisfied...for now. :)

**Comment by rosskarchner** [comment]
Now that's it's merged, I'll work to make this compatable with the changes in #2567

**Pull request merged**
