### PR TITLE
Add disabled overview pages

### PR DESCRIPTION
**Pull request by anselmbradford**
## Changes

- Adds logic to show overview—but disabled—links for Consumer Tools and Education Resources.

## Testing

- Check in desktop and mobile menu Consumer Tools and Educational Resources.

## Review

- @KimberlyMunoz 
- @jimmynotjim 
- @sebworks 

## Screenshots

screen shot 2016-03-20 at 9 41 52 pm

screen shot 2016-03-20 at 9 42 11 pm

### CODE REVIEW

**Comment by schaferjh** [comment]
I'm having doubts on this one. @anselmbradford and I discussed it earlier and I was thinking it would be nice to have the overview label as a placeholder at the mobile scale since it serves as a piece of descriptive information even without a link at that scale. However, seeing it grayed out at desktop size worries me that it will just lead to more confusion than help.

Maybe we think about this a bit more before doing it -- interested to hear other thoughts?

**Comment by KimberlyMunoz** [comment]
I think having it greyed out with the rest being blue links signals "coming soon" which is pretty accurate for what these pages are. I'd want to ask someone who hasn't been on the project for as long what their thoughts are.

**Comment by KimberlyMunoz** [comment]
:+1: on the implementation. Glad to see my TODO basically stays the same in this situation.

**Comment by jimmynotjim** [comment]
:+1: dependent on @schaferjh final decision.

**Comment by anselmbradford** [comment]
Usurped by https://github.com/cfpb/cfgov-refresh/pull/1704

**Pull request closed without merging**
