### PR TITLE
Adds delete db instruction to readme

### PR DESCRIPTION
**Pull request by anselmbradford**
Adds delete db instruction to readme

@jimmynotjim 
@kurtw

### CODE REVIEW

**Comment by kave** [comment]
while we're making readme changes can you change this line:
`python cfgov/manage.py loaddata cfgov/v1/fixtures/initial_data.json`
to
`./initial-data.sh`

**Comment by anselmbradford** [comment]
@kave fixed in https://github.com/cfpb/cfgov-refresh/commit/36bc8a6b42b994d28ec6e4df6e5f4959aa902d22

**Comment by jimmynotjim** [comment]
Thanks, I probably should have done this months ago to save Kurt some time. :+1:

**Comment by kave** [comment]
:+1:

**Comment by KimberlyMunoz** [comment]
:+1:

**Pull request merged**
