### PR TITLE
Adding link button option to text introduction

### PR DESCRIPTION
**Pull request by sebworks**
Adding link button option to text introduction

## Changes

- Modified `cfgov/jinja2/v1/_includes/molecules/text-introduction.html` to add `link_is_button` boolean option. 

## Testing

- Create a sub-landing page.
- Add a text introduction to the page.
- Add a link.
- Check the `link_is_button` flag.
- Verify that the button is operable and looks as expected.

## Screenshots

screen shot 2017-04-14 at 12 14 05 pm

## Notes

- This is being suggested by the Mosaic team. This code is essentially the same as within the info unit.

## Todos

-

## Checklist

* [ ] PR has an informative and human-readable title
* [ ] Changes are limited to a single goal (no scope creep)
* [ ] Code can be automatically merged (no conflicts)
* [ ] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [ ] Passes all existing automated tests
* [ ] New functions include new tests
* [ ] New functions are documented (with a description, list of inputs, and expected output)
* [ ] Placeholder code is flagged
* [ ] Visually tested in supported browsers and devices
* [ ] Project documentation has been updated
* [ ] Reviewers requested with the [Assignee tool](https://help.github.com/articles/assigning-issues-and-pull-requests-to-other-github-users/) :arrow_right:

### CODE REVIEW

**Comment by schaferjh** [comment]
@nataliafitzgerald @caheberer does the spacing between the text and that button look correct?

**Comment by caheberer** [comment]
@schaferjh That definitely feels too tight. Although not explicitly stated in the manual, I've always used 30px between text and a button. @nataliafitzgerald agree?

**Comment by schaferjh** [comment]
thanks for checking @caheberer. 

Before we move forward with this, I also want to confirm whether this is the change we want or if modifying Full Width Text to include the Call to Action option on sublanding pages better fits your use case. (Email I just sent) -- I think that's a relatively similar level of effort and possibly more useful change.

**Comment by caheberer** [comment]
I'd assume this is for the Submit a complaint landing page, but @anselmbradford can you confirm? 

If that's the case, it seems you're right @schaferjh and the decision around this in the wagtail documentation would be to make the adjustment to full width text, not text introduction.

**Comment by caheberer** [comment]
Also, would this PR cover super buttons as well? That's what we are using for Submit a complaint.

**Comment by sebworks** [comment]
@schaferjh, why would this change be to the full width text organism instead of the text introduction?

**Comment by schaferjh** [comment]
@caheberer I don't know what a super button is? 

@sebworks because the use case the project team is accommodating is on a page with a hero -- it causes hierarchy issues to use a text introduction on the same page. Instead, on [GHE] flapjack/wagtail-documentation/issues/41, we had discussed making the "Call to Action" module within Full Width Text an option on sub-landing pages. @anselmbradford may be better set up to submit the PR if he understands the use case and needs (such as button size variation?).

**Comment by caheberer** [comment]
@schaferjh ha, sorry, maybe that's a graphic design team term. I should have said Large primary button.

**Comment by kurzn** [comment]
> I'd assume this is for the Submit a complaint landing page, but @anselmbradford can you confirm?

Yes, this is for the new Submit complaint landing page.

**Comment by sebworks** [comment]
ok, i'm going to close this PR. Will reopen if this is necessary.

**Comment by anselmbradford** [comment]
Yup, you all are right! Full width text needs a button, thanks for the catch! @caheberer "Submit a Complaint" should be a large button? Should it be large on the "before you get started" page also? It looks the same as the log in button there (other than color):

screen shot 2017-04-14 at 5 17 25 pm

**Comment by nataliafitzgerald** [comment]
Sorry team, I was out at a doctor's appointment this afternoon so catching up now. 

@schaferjh - Do we intend for this pattern to be available for Wagtail users outside of the "Submit a complaint" landing page? If so, do we have other known existing use cases or potential use cases? Who will be in charge of updating documentation (DM and Wagtail documentation) to reflect content strategy and proper use? Is this task up to the project team or the Platform team? If we're going to make this option available to all users I just want to be sure we provide supporting documentation and a communicated strategy. 

@sebworks - Can you post a screenshot of where we landed? The space above the button in @anselmbradford's post looks like more than 30px. I agree with @caheberer that in your original screenshot the spacing of 15px felt tight.

**Comment by schaferjh** [comment]
@anselmbradford @caheberer @nataliafitzgerald @willbarton 
I think it might be best to take this discussion to another issue or to a quick chat since we're no longer talking about this PR (and Steven has closed this PR). 

Yes, making the call-to-action (CTA) module available within full width text on sub-landing page templates will be available to anyone using our CMS. 

You raise good points on documentation and strategy, Natalia.  Ideally, the project team would be responsible for updating documentation, but usage of the CTA within full width text has never been specifically defined and I do not know why it wasn't part of the sub-landing page template from the start. It might be helpful to reach out and talk about what additional documentation updates feel appropriate, especially given that the Platform team is actively assessing documentation needs right now.

**Comment by nataliafitzgerald** [comment]
@schaferjh 
That sounds like a good next step. If there is strategy work to be done who would that work fall to? @sarahsimpson09? 

@caheberer @anselmbradford 
Once you have a GH issue set up for the documentation piece of this can you send it to @ielerol and me? Once you start working on that task perhaps we can hop on a call to talk through what you plan to add and identify whether there are any remaining gaps.

**Pull request closed without merging**
