### PR TITLE
Fixes DF-1485 - adds modification date pattern

### PR DESCRIPTION
**Pull request by anselmbradford**
Fixes DF-1485 - adds modification date pattern.

### CODE REVIEW

**Comment by anselmbradford** [comment]
Struggling a bit on how to perform the alignment of this with the share buttons. They have layers of slight top and bottom margin:

screen shot 2015-02-20 at 6 32 36 pm

Making it hard to align an element floated next to them:

screen shot 2015-02-20 at 6 44 29 pm

Any ideas? cc @Scotchester

**Comment by Scotchester** [comment]
Glad to take a look on Monday.

**Comment by anselmbradford** [comment]
Thanks! Have a good weekend!

**Comment by jimmynotjim** [comment]
@anselmbradford, did you figure out the alignment issue?

**Comment by Scotchester** [comment]
Thanks for the poke, @jimmynotjim.

@anselmbradford, how is it supposed to look?

**Comment by anselmbradford** [comment]
@Scotchester [GHE] /github-enterprise-assets/0000/0087/0000/4569/c4ba6336-1f28-11e4-8020-4975317d52d1.png Might be fine to proceed, but it's not pixel perfect. In the screenshot where I've added a horizontal line, share buttons are ~2px lower because of their own internal height difference between their container and child. 
The structure is like:

```
li
  a
    span
      :before
```

The `li` has a height of 28px and the `span` has a height of 26px and I haven't been able to dig into why. Ideally the share button pattern wouldn't be adding margin/padding internally and would just be added on the enclosing `<ul>` parent element.

**Comment by anselmbradford** [comment]
Sounds like we're going to proceed with merging this as the issue is really with the share button pattern, not the updated-at pattern. @Scotchester if you have a quick moment, maybe you could give some input on whether the padding on the left/right should follow an existing CF convention I don't know about. Otherwise should be good to merge.

**Comment by Scotchester** [comment]
Yeah, lots of complexities to the share button pattern, but I think it entirely boils down to this:

First, at `font-size: 26px` (or its em equivalent), the actual rendered height of the icon is 23x23. In this pattern, `line-height` is set to 1, but that gives a 23px icon in a 26px line, so that's why it's nudged down a couple pixels from the container height. This is something that might get addressed by cfpb/design-manual#277 in the next month – i.e., I think it might be a good idea to say that full-height icons (like the ones on square or round backgrounds) should render at exactly the height of the `font-size`.

Until that time, I think your best option for a hacky workaround is  `position: relative; top: 2px;` on the floating date.

You might also need or want to set `display: block` on the `a` elements, which show a height of 30px, bizarrely, but I don't think that's actually affecting things in this case.

Re: left/right padding. On the date's green box? I don't think we have a standard for that. @duelj?

**Comment by anselmbradford** [comment]
Thanks for the detailed summary @Scotchester ! Yeah, it really sounds like this is an out of scope issue for this particular PR. I hesitate to add `position: relative; top: 2px;` and have that get forgotten in the CSS, I'd prefer it to just live with the 2px discrepancy till the icon pattern is looked at.

> Re: left/right padding. On the date's green box? I don't think we have a standard for that. @duelj?
Yeah, sorry, you got it, the green box!

**Comment by anselmbradford** [comment]
Just fixed conflicts w/ `sprint-21`, anything else need to happen before a merge here?

**Comment by sebworks** [comment]
@anselmbradford , :+1:

**Pull request merged**
