### PR TITLE
Brandeis attorney program updates

### PR DESCRIPTION
**Pull request by virginiacc**
Update Brandeis attorney program section on Students and Graduates page (issue 53)

## Additions

- PDF

## Changes

- Text about applying

## Testing

- Navigate to http://localhost:8000/about-us/careers/students-and-graduates/ and check that Brandeis program subheader is updated & links to pdf

## Review

- @contolini 
- @sebworks 

## Screenshots
screen shot 2016-07-18 at 7 48 46 am

## Notes

- Is the download link styled correctly?

## Checklist

* [ ] Changes are limited to a single goal (no scope creep)
* [ ] Code can be automatically merged (no conflicts)
* [ ] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [ ] Passes all existing automated tests
* [ ] New functions include new tests
* [ ] New functions are documented (with a description, list of inputs, and expected output)
* [ ] Placeholder code is flagged
* [ ] Visually tested in supported browsers and devices
* [ ] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)

### CODE REVIEW

**Comment by sebworks** [comment]
LGTM, @schaferjh what do you think?

**Comment by schaferjh** [comment]
Could we break the bolded h5 text into two lines? Once that's done, looks good. thanks!

(download link looks fine)

**Comment by virginiacc** [comment]
Line break added:

screen shot 2016-07-18 at 1 45 52 pm

**Comment by sebworks** [comment]
👍

**Comment by sebworks** [comment]
Do we need a period on the second line?

**Comment by virginiacc** [comment]
@sebworks Good question. Wasn't sure if it would look strange with the icon/spacing:
screen shot 2016-07-18 at 2 20 20 pm

**Comment by sebworks** [comment]
yeah, I'm not sure. LGTM. Merge when ready.

**Pull request merged**
