### PR TITLE
Updates for Elasticsearch 2.3

### PR DESCRIPTION
**Pull request by rosskarchner**
This covers the changes in cfgov-refresh needed for ES 2.4, with a few incidental extra's:

It's worth noting, there will be a PR for the 'knowledgebase' package, with some minor indexing tweaks.

## Additions

- Docker-compose file that spins up MySQL 5.7 and Elasticsearch 2.4, for local development purposes.

## Removals

- the 'pages' sheerlike indexer (and the SHEER_PROCESSORS setting entirely)

## Changes

- allow sheerlike to proceed when there's not a SHEER_PROCESSORS setting.
- updates the 'elasticsearch' and 'django-haystack' packages

## Testing

- coming soon

## Notes

-

## Todos

-

## Checklist

* [ ] PR has an informative and human-readable title
* [ ] Changes are limited to a single goal (no scope creep)
* [ ] Code can be automatically merged (no conflicts)
* [ ] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [ ] Passes all existing automated tests
* [ ] New functions include new tests
* [ ] New functions are documented (with a description, list of inputs, and expected output)
* [ ] Placeholder code is flagged
* [ ] Visually tested in supported browsers and devices
* [ ] Project documentation has been updated
* [ ] Reviewers requested with the [Assignee tool](https://help.github.com/articles/assigning-issues-and-pull-requests-to-other-github-users/) :arrow_right:

### CODE REVIEW

**Comment by willbarton** [comment]
> Docker-compose file that spins up MySQL 5.7 and Elasticsearch 2.4, for local development purposes.

a8gouggmcosim

**Comment by rosskarchner** [comment]
if you squint, it's like docker-compose.yml isn't even there!

**Comment by rosskarchner** [comment]
knowledgebase changes are at: [GHE]/CFPB/knowledgebase/pull/213

**Comment by rosskarchner** [comment]
After some internal discussion, it seems like we should move forward with 2.3 for now.

**Pull request merged**
