### PR TITLE
Removes block enhancements that are in CF

### PR DESCRIPTION
**Pull request by anselmbradford**
Removes block enhancements that are in CF.

## Removals

- Removes `.block` code that's now being delivered via cf-layout since https://github.com/cfpb/cf-layout/pull/20

## Testing

- Run `./setup.sh local`
- Should be no change between refresh and `http://localhost:8000/the-bureau/`.

## Review

- @jimmynotjim 
- @sebworks 
- @KimberlyMunoz

### CODE REVIEW

**Comment by KimberlyMunoz** [comment]
I'm getting this on `the-bureau`

image

**Comment by anselmbradford** [comment]
@KimberlyMunoz Did you run `./setup.sh` or `npm install`? (Sorry added to Testing section) 
Check that `./vendor/cf-layout/bower.json` has version `1.2.0`.

**Comment by KimberlyMunoz** [comment]
I ran ./setup.sh. I'll give another try.

**Comment by jimmynotjim** [comment]
I'm getting the same as Kim and `bower list` says that I have `1.2.0` of `cf-layout`

**Comment by anselmbradford** [comment]
If you restart the server with `./runserver.sh` and check what happens?

**Comment by jimmynotjim** [comment]
I tried that, tried again just to be sure and same issue. Maybe it's time we try to change to individual imports since we've worked out all the cf-v1 bugs??

**Comment by KimberlyMunoz** [comment]
> Maybe it's time we try to change to individual imports since we've worked out all the cf-v1 bugs??

Honestly, this might be a good thing to do anyway since we can't predict when everything will come in for the design manual surge.

**Comment by anselmbradford** [comment]
Hmmm... I'll have to look at this closer, it's in [`1.2.0`](https://github.com/cfpb/cf-layout/blob/1.2.0/src/cf-layout.less#L1337) so it seems like the downloaded vendor CSS is not updating locally for you for some reason.

**Comment by jimmynotjim** [comment]
This might be related to the old `/static` directory @kave found in my directory, because it's working for me now

**Comment by anselmbradford** [comment]
@KimberlyMunoz This good for you?

**Comment by KimberlyMunoz** [comment]
:+1:

**Pull request merged**
