### PR TITLE
Update Capital Framework to latest

### PR DESCRIPTION
**Pull request by jimmynotjim**
Update Capital Framework to get the 60px -> 45px main content change

## Testing

- `npm install && gulp build` and check out http://localhost:8000/policy-compliance/rulemaking/final-rules/ There should be 45px padding on top of the main content instead of 60px

## Review

- @sebworks 
- @anselmbradford 
- @KimberlyMunoz 

## Checklist

* [x] Changes are limited to a single goal (no scope creep)
* [x] Code can be automatically merged (no conflicts)
* [x] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [x] Passes all existing automated tests
* [x] New functions include new tests
* [x] New functions are documented (with a description, list of inputs, and expected output)
* [x] Placeholder code is flagged
* [x] Visually tested in supported browsers and devices
* [x] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)

### CODE REVIEW

**Comment by anselmbradford** [comment]
Just a note that with the funky things we are doing with protractor in the ./frontend.sh script, this PR needs `./frontend.sh && gulp build` to be run instead of `npm install`, otherwise there will be a build error.

**Comment by anselmbradford** [comment]
Hmm I'm still seeing 60px + 45px for the breadcrumbs:

screen shot 2016-05-11 at 3 40 10 pm

**Comment by jimmynotjim** [comment]
@KimberlyMunoz figured out we need to run `npm prune` to remove old packages. Give that a shot, then run `./frontend.sh` again.

**Comment by KimberlyMunoz** [comment]
LGTM. We have 45px on .content_main, right?

**Comment by anselmbradford** [comment]
👍

**Comment by jimmynotjim** [comment]
@KimberlyMunoz correct.

Updating and merging.

**Pull request merged**
