### PR TITLE
Removing jQuery CDN from base.html

### PR DESCRIPTION
**Pull request by sebworks**
Removing jQuery CDN from base.html

## Changes

- Removing jQuery CDN from `base.html`.

## Testing

- Visit `http://localhost:8000/`
- View the page source.
- Click on the link script and verify that it loaded correctly.

## Checklist

* [ ] PR has an informative and human-readable title
* [ ] Changes are limited to a single goal (no scope creep)
* [ ] Code can be automatically merged (no conflicts)
* [ ] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [ ] Passes all existing automated tests
* [ ] New functions include new tests
* [ ] New functions are documented (with a description, list of inputs, and expected output)
* [ ] Placeholder code is flagged
* [ ] Visually tested in supported browsers and devices
* [ ] Project documentation has been updated
* [ ] Reviewers requested with the [Assignee tool](https://help.github.com/articles/assigning-issues-and-pull-requests-to-other-github-users/) :arrow_right:

### CODE REVIEW

**Comment by ascott1** [comment]
👍

**Comment by konklone** [comment]
🎉 Nice!

**Comment by jimmynotjim** [comment]
@sebworks where are we still using jQuery?

**Pull request merged**
