### PR TITLE
Fix for hero image

### PR DESCRIPTION
**Pull request by sebworks**
Fix for hero image

## Changes

- Modified `cfgov/jinja2/v1/_includes/molecules/hero.html` to remove `image-set` properties.

## Testing

1. Add hero to page
2. Add background image to page.
3. Visit page using Chrome.
4. Verify image has the proper width.

## Checklist

* [ ] PR has an informative and human-readable title
* [ ] Changes are limited to a single goal (no scope creep)
* [ ] Code can be automatically merged (no conflicts)
* [ ] Code follows the standards laid out in the [development playbook](https://github.com/cfpb/development)
* [ ] Passes all existing automated tests
* [ ] New functions include new tests
* [ ] New functions are documented (with a description, list of inputs, and expected output)
* [ ] Placeholder code is flagged
* [ ] Visually tested in supported browsers and devices
* [ ] Project documentation has been updated
* [ ] Reviewers requested with the [Assignee tool](https://help.github.com/articles/assigning-issues-and-pull-requests-to-other-github-users/) :arrow_right:

### CODE REVIEW

**Comment by jimmynotjim** [comment]
That's so weird. We tested it thoroughly in the CF Docs site and Sandbox in Chrome, Safari, FF, and IE/Edge. Especially weird because all the options were currently the exact same image since we don't have a way to serve multiple from the backend at the moment. Hopefully they work it out soonish.

**Comment by Scotchester** [comment]
Hmm... Now I'm wondering if what I said was accurate. I can think of
something else that might be going on. Let's discuss later.

**Comment by jimmynotjim** [comment]
Just for future clarity, the issue was we provided a 1x image but telling the browser it's a 2x image, so it downsized it by 50%. When I tested, I tested with a 2x image, not realizing what would happen the other way around.

**Pull request merged**
