### PR TITLE
Update jsdom from 7.2.2. to 8.0.4

### PR DESCRIPTION
**Pull request by anselmbradford**
## Changes

- Update jsdom from 7.2.2. to [8.0.4](https://github.com/tmpvar/jsdom/blob/master/Changelog.md#800)

## Testing

- `./setup.sh`
- `gulp test:acceptance --sauce=false` or `gulp test:acceptance`

## Review

- @sebworks 
- @KimberlyMunoz 
- @jimmynotjim

### CODE REVIEW

**Comment by KimberlyMunoz** [comment]
Getting one failed test. Going to re-run and make sure it just isn't flakey.

```  1) Beta Banner State "before all" hook:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
      at Object.done (node_modules/mocha-jsdom/index.js:70:7)
      at node_modules/jsdom/lib/jsdom.js:275:18
```

**Comment by KimberlyMunoz** [comment]
:+1: All good now, we've seen the timeout error before, but we might want to have one other person run the test suite.

**Comment by jimmynotjim** [comment]
Acceptance tests still won't run for me, I'll defer to @KimberlyMunoz and @sebworks

**Comment by sebworks** [comment]
:+1:

**Pull request merged**
