### PR TITLE
Add view more back in

### PR DESCRIPTION
**Pull request by kurtw**
I think this bit of code got incorrectly rolled back in a rebase or something.

@kave @rosskarchner @richaagarwal

### CODE REVIEW

**Comment by rosskarchner** [comment]
where should I be able to test this? I'm not seeing it on blog posts, for instance

screen shot 2016-04-21 at 11 06 34 am

**Comment by schaferjh** [comment]
Not seeing them on Blog is a seperate issue: I think @kurtw has another fix up for that, but now I can't find it in the list of PRs...

While that is happening, this module shows up on all the reports pages under data-research, so you could look there.

**Comment by kurtw** [comment]
@rosskarchner go to any of the reports http://localhost:8000/data-research/research-reports

**Comment by kave** [comment]
verified `view_more` display and routes to the correct activity-log with filter 👍

**Comment by rosskarchner** [comment]
Looks good

**Pull request merged**
