### PR TITLE
Remove ansi-colors

### PR DESCRIPTION
**Pull request by anselmbradford**
Red output was only used in one error state place. Probably not worth having the dependency for that (which includes a bunch of colors and bold, etc.).

## Removals

- Removes `ansi-colors` dependency in favor of inlining red color.

### CODE REVIEW

**Comment by Scotchester** [comment]
Got a lint error there on 201: https://travis-ci.org/cfpb/cfgov-refresh/jobs/377004563#L845

**Comment by anselmbradford** [comment]
Blergh… try now

**Comment by Scotchester** [comment]
Wait, did you restart the job?

**Comment by anselmbradford** [comment]
No I didn't

**Pull request merged**
