### PR TITLE
Stop footer link underlines from going under icon

### PR DESCRIPTION
**Pull request by Scotchester**
## Changes

- Adds `span.icon-link_text` into external links in footer to prevent their underlines from going under the icon.

## Review

- @jimmynotjim 
- @KimberlyMunoz 
- @sebworks 
- @anselmbradford 

## Checklist

* [ ] Changes are limited to a single goal (no scope creep)
* [ ] Code can be automatically merged (no conflicts)
* [ ] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [ ] Passes all existing automated tests
* [ ] New functions include new tests
* [ ] New functions are documented (with a description, list of inputs, and expected output)
* [ ] Placeholder code is flagged
* [ ] Visually tested in supported browsers and devices
* [ ] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)

### CODE REVIEW

**Comment by anselmbradford** [comment]
Hm, not sure this is working as expected? Still looks the same to me (except icon has its own underline that's overlapping):

screen shot 2016-03-21 at 4 53 59 pm

**Comment by Scotchester** [comment]
Hmmm, now that I take a closer look, it occurs to me that if they were standard `icon-link`s, there would be NO underline without the `span`. Maybe it's the `list__links` stuff interfering somehow. I'll dig deeper tomorrow.

**Comment by Scotchester** [comment]
I think I've fixed this, @anselmbradford, according to my rudimentary DevTools testing. Check again?

**Comment by jimmynotjim** [comment]
Tested and working locally :+1:

**Comment by KimberlyMunoz** [comment]
:+1: Please fix conflicts and rebase today so we can use this in the non-responsive footer on WordPress.

**Comment by jimmynotjim** [comment]
I already copied it over, but it would be nice for them to match tomorrow

**Comment by KimberlyMunoz** [comment]
@Scotchester

**Comment by Scotchester** [comment]
Ack, sorry. Forgot this was mine :)

**Comment by Scotchester** [comment]
I've made a huge mistake.

**Comment by Scotchester** [comment]
Hallelujah! Fixed it!

**Pull request merged**
