### PR TITLE
Update cfpb-chart-builder to 1.1.4

### PR DESCRIPTION
**Pull request by mistergone**
This PR updates `cfpb-chart-builder` to version `1.1.4`

## Changes
- Updated `cfpb-chart-builder` to `1.1.4`
- Ran `npm shrinkwrap`

## Checklist

* [ ] PR has an informative and human-readable title
* [ ] Changes are limited to a single goal (no scope creep)
* [ ] Code can be automatically merged (no conflicts)
* [ ] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [ ] Passes all existing automated tests
* [ ] New functions include new tests
* [ ] New functions are documented (with a description, list of inputs, and expected output)
* [ ] Placeholder code is flagged
* [ ] Visually tested in supported browsers and devices
* [ ] Project documentation has been updated
* [ ] Reviewers requested with the [Assignee tool](https://help.github.com/articles/assigning-issues-and-pull-requests-to-other-github-users/) :arrow_right:

### CODE REVIEW

**Comment by willbarton** [comment]
I don't see any of the shrinkwrap bugaboos that we've encountered recently, so this should be good. To be safe I'm going to build the branch in Jenkins before approving.

**Comment by willbarton** [comment]
This error happens in Jenkins and Travis, but the frontend build doesn't stop: 

https://travis-ci.org/cfpb/cfgov-refresh/jobs/205924299#L1973

Is it anything to worry about?

**Comment by cfarm** [comment]
@willbarton I just pushed a fix - let's confirm the Travis build doesn't show this error this time.

**Comment by cfarm** [comment]
The build CSS error is fixed! I'm merging master back in

**Pull request merged**
