### PR TITLE
Updated legacy code to remove old jQuery dependency

### PR DESCRIPTION
**Pull request by sebworks**
Updated legacy code to remove old jQuery dependency and unnecessary code.

## Changes
- Updated `src/budget/strategic-plan/interactive/index.html` to remove old version of jQuery.
- Updated `src/static-legacy/css/styles.css` to remove whitespace and make report nav fixed.
- Updated `src/static-legacy/js/functions.js` to remove unnecessary code.
- Added `src/static-legacy/js/jquery-1.11.3.js` to upgrade the jQuery version.
- Removed `src/static-legacy/js/jquery-1.9.1.min.js` to upgrade the jQuery version.

## Testing
- Visit 'http://localhost:3000/budget/strategic-plan/interactive/#goal3`.

## Screenshots
- 
screen shot 2015-08-11 at 7 31 55 am

## Review
@anselmbradford 
@KimberlyMunoz

### CODE REVIEW

**Comment by anselmbradford** [comment]
I feel like we should minify jquery, like it is with `1.9.1`. `/static-legacy/` is being directly copied over to `/dist/` so jquery won't be post-processed and minified elsewhere.

Otherwise looks good :+1: (and removes a ton! Yes!).

**Postscript:**
The following seem like issues, but I wouldn't include them in this PR:
- There are a few broken links for reference docs in the appendix and the `THE CFPB STRATEGIC PLAN, BUDGET, AND PERFORMANCE PLAN AND REPORT`.
- Bar charts can be clicked and they change from green to grey. Why? The code for this interaction could probably be removed.

**Comment by sebworks** [comment]
So the links are relative (coming from content ) but I can write some js fix that issue.

**Comment by sebworks** [comment]
@anselmbradford, the interaction on the bar chart is a function of Highcharts ( the code for that is coming from content ). I think we should just change it on the content side in this instance.

**Comment by anselmbradford** [comment]
> the interaction on the bar chart is a function of Highcharts ( the code for that is coming from content ). I think we should just change it on the content side in this instance.

Sounds good. Yeah, I'd say just minify the jquery and merge this PR. The links and bar charts are really out of scope for this PR and I'm not sure if it's even something we need resources on, but worth noting.

**Pull request merged**
