### PR TITLE
Removes beep :sob: :sob: :sob:

### PR DESCRIPTION
**Pull request by anselmbradford**
Removes the beep task for audibly saying the build is done. I vow to bring it back some day!

## Removals

- gulp beep task

## Review

- @vickumar1981 
- @kave

### CODE REVIEW

**Comment by kave** [comment]
cry

**Comment by anselmbradford** [comment]
@kave I'm so conflicted by your sign off. :+1: /:-1:

**Comment by jimmynotjim** [comment]
:+1:

**Comment by KimberlyMunoz** [comment]
Gone but never forgotten. :+1:

**Pull request merged**
