### PR TITLE
Update CHANGELOG.md + 3.10.2 backports

### PR DESCRIPTION
**Pull request by rosskarchner**
This marks the previously "unreleased" changes as being part of 3.10

### CODE REVIEW

**Comment by Scotchester** [comment]
Should probably create a new unreleased section as part of this?

**Comment by richaagarwal** [comment]
Oh that reminds me, the TableBlock changes should be moved to 3.10 - can I piggyback on this PR?

**Comment by rosskarchner** [comment]
@richaagarwal yeah, go ahead

**Comment by rosskarchner** [comment]
I'm also going to pull in some commits I made to the 3.10 branch, while troubleshooting beta

**Comment by rosskarchner** [comment]
@Scotchester I've restored the "unreleased" section

**Comment by Scotchester** [comment]
Thanks!

**Comment by willbarton** [comment]
*mutters something about automation*

**Comment by rosskarchner** [comment]
@richaagarwal I'm going to make that change, so we can get this merged

**Pull request merged**
