### PR TITLE
Fix calendar times until bigger fix comes along

### PR DESCRIPTION
**Pull request by richaagarwal**
Since my other in progress PR depends on a fix from Wagtail (I think), this patches things up for now. Not ideal but best we can do.

## Testing

- Locally, pull down the branch & run `cfgov/manage.py sheer_index -r`
- Compare times here: [http://localhost:8000/about-us/the-bureau/leadership-calendar/](http://localhost:8000/about-us/the-bureau/leadership-calendar/) with times here: http://www.consumerfinance.gov/leadership-calendar/2015/8/#calendar-anchor
- The times should now be the same
- If you go back to the flapjack branch, you will notice they are off by 4 hours.

## Review

- @kave @rosskarchner @kave 

## Todos

- TODO noted in the code. We will eventually want to fix this because it is bad that we are storing incorrect times in our database and will require a migration down the road.

## Checklist

* [x] Changes are limited to a single goal (no scope creep)
* [x] Code can be automatically merged (no conflicts)
* [ ] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [x] Passes all existing automated tests
* [ ] New functions include new tests
* [ ] New functions are documented (with a description, list of inputs, and expected output)
* [ ] Placeholder code is flagged
* [ ] Visually tested in supported browsers and devices
* [x] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)

### CODE REVIEW

**Comment by rosskarchner** [comment]
do I need to wipe my elasticsearch settings for this to work?

**Comment by richaagarwal** [comment]
Sorry! Run `sheer_index` with `-r`. Will add above.

**Comment by rosskarchner** [comment]
ah, cool-- will retest

**Comment by kurtw** [comment]
Looks good to me. :+1: I'm wondering why we're missing calendar events from before Aug 31 though.

**Comment by richaagarwal** [comment]
@kurtw Yeah it's been like that, probably because we have a limit on it?
'''{
  "name": "Calendar Events",
  "query": {
    "doc_type": "calendar_event",
    "size": 20,
    "sort": "dtstart:desc"
  }
}
'''

**Pull request merged**
