### PR TITLE
Legacy template overrides + sheerlike config for know-before-you-owe

### PR DESCRIPTION
**Pull request by rosskarchner**
With this PR, all work needed to apply the new headers to Sheer and django apps can be done within this repo. Sheer templates can be overridden globally by putting a replacement in:

cfgov-refresh/cfgov/jinja2/sheer_overrides/common

or, on a project-by-project basis:

cfgov-refresh/cfgov/jinja2/sheer_overrides/know-before-you-owe

## Additions

- a few new directories are added to the template search path for sheerlike sites, cfgov/jinja2/sheer_overrides/common and cfgov/jinja2/sheer_overrides/(site-name), which is the dictionary key from settings.SHEER_SITES
- I snuck in the settings and url configuration to support the know-before-you-owe sheer app

## Testing

- check out this PR
- check out know-before-you-owe as a sibling directory of cfgov-refresh, and build it (`npm install && grunt build`)
- `cfgov/manage.py runserver`
- observe that http://localhost:8000/know-before-you-owe/  works.
- view source, and observe the comment `<!-- this header is coming from cfgov-refresh! -->`. this file is at cfgov/jinja2/sheer_overrides/common/nemo_header.html
- If you followed along with the testing instructions for #1798 you can view http://localhost:8000/company-signup/ and view source to find the comment `<!-- this code is coming from cfgov-refresh! --!>` . That code is coming from the django template at cfgov/legacy_common/templates/front/base_update.html.

## Review

- @anselmbradford @KimberlyMunoz @richaagarwal @kave @kurtw @Scotchester 

## Checklist

* [ ] Changes are limited to a single goal (no scope creep)
* [x] Code can be automatically merged (no conflicts)
* [ ] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [x] Passes all existing automated tests
* [ ] New functions include new tests
* [ ] New functions are documented (with a description, list of inputs, and expected output)
* [ ] Placeholder code is flagged
* [ ] Visually tested in supported browsers and devices
* [ ] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)

### CODE REVIEW

**Comment by rosskarchner** [comment]
Re-thinking the wholesale copying of django-cfgov-common, so I've removed that from this PR for now.

**Comment by kave** [comment]
First part of testing works fine.
screen shot 2016-04-04 at 3 09 19 pm

but couldn't get #1798  working to test

**Comment by rosskarchner** [comment]
@kave where did that testing break down?

**Comment by kave** [comment]
@rosskarchner mainly building fin-ed-resources

**Comment by rosskarchner** [comment]
Nobody seems to want the new feature provided here, and the URL has been added in https://github.com/cfpb/cfgov-refresh/pull/1863

**Pull request closed without merging**
