### PR TITLE
Rebuilt Nemo Grunt tasks in Gulp

### PR DESCRIPTION
**Pull request by jimmynotjim**
The Nemo styles and scripts were moved to the project but have no way of being updated. Created gulp tasks for the Nemo styles and scripts to make it possible to make changes and rebuild the assets.

## Additions

- Added gulp task for nemo styles
- Added gulp task for nemo scripts

## Testing

- run `gulp scripts:nemo && gulp styles:nemo` and it should rebuild the necessary files

## Review

- @rosskarchner 
- @Scotchester 
- @KimberlyMunoz 

## Checklist

* [x] Changes are limited to a single goal (no scope creep)
* [x] Code can be automatically merged (no conflicts)
* [x] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [x] Passes all existing automated tests
* [x] New functions include new tests
* [x] New functions are documented (with a description, list of inputs, and expected output)
* [x] Placeholder code is flagged
* [x] Visually tested in supported browsers and devices
* [ ] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)

### CODE REVIEW

**Comment by rosskarchner** [comment]
Is the intention here to run this just when those files change, and keep the built result in git?

If we want to treat these the same way we treat other gulp-built assets, we could:

- store them in static_built/nemo
- remove the built versions from git

**Comment by jimmynotjim** [comment]
@rosskarchner I'm all for that, I was just trying to stay as close to the existing process as possible to keep the scope reigned in. Do you know where the assets paths are set in the template for retrieval on page load?

**Comment by rosskarchner** [comment]
They don't neccessarily need to: that's one of the good parts about the wacky things Django does with static files:

A file at:
static_built/nemo/beiber.css

Or at:
and at legacy/static/nemo/beiber.css

Are both accessible at the URL /static/nemo/beiber.css

**Comment by jimmynotjim** [comment]
@rosskarchner that makes no sense but let's go for it!

**Comment by jimmynotjim** [comment]
@rosskarchner Updated but I'm not sure how to test this since I can't get UnityBox running. Any thoughts?

**Comment by rosskarchner** [comment]
I'll test using Spanish AskCFPB, standby!

**Comment by rosskarchner** [comment]
Looks good to me, and inspecting the actual minified CSS, I see:

```css
/*!
 *               ad$$               $$
 *              d$"                 $$
 *              $$                  $$
 *   ,adPYba.   $$$$$  $$.,dPYba.   $$.,dPYba.
 *  aP'    `$:  $$     $$P'    `$a  $$P'    `$a
 *  $(          $$     $$(      )$  $$(      )$
 *  "b.    ,$:  $$     $$b.    ,$"  $$b.    ,$"
 *   `"Ybd$"'   $$     $$`"YbdP"'   $$`"YbdP"'
 *                     $$
 *                     $$
 *                     $$
 *
 *  cfgov-refresh - v3.0.0-3.3.20
 *  https://github.com/cfpb/cfgov-refresh
 *  A public domain work of the Consumer Financial Protection Bureau
```

screencapture-localhost-8000-es-obtener-respuestas-c-adquirir-credito-1341-que-es-un-congelamiento-de-seguridad-de-mi-informe-de-credito-html-1466523913089

**Pull request merged**
