### PR TITLE
Removed unnecessary expandables

### PR DESCRIPTION
**Pull request by KimberlyMunoz**
Removing the mobile-only expandables.This goes with DFJR-25 in JIRA

## Removals

- Removed unnecessary mobile expandables

## Testing

- Run browser tests and visit any office page, `/the-bureau`, and `/careers/application-process`

## Review

- @jimmynotjim 
- @sebworks 
- @anselmbradford 

## Checklist

* [x] Changes are limited to a single goal (no scope creep)
* [x] Code can be automatically merged (no conflicts)
* [x] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [x] Passes all existing automated tests
* [x] New functions include new tests
* [x] Visually tested in supported browsers and devices 
* [x] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)

### CODE REVIEW

**Comment by jimmynotjim** [comment]
:+1:

**Comment by sebworks** [comment]
:+1:

**Comment by KimberlyMunoz** [comment]
I just realized that the expandables had associated JS that should be removed. Mind giving it another look over?

**Comment by jimmynotjim** [comment]
Oh, no more mobile only! :tada:

**Comment by anselmbradford** [comment]
:tada::tada::tada::+1:

**Comment by sebworks** [comment]
:+1:

**Comment by anselmbradford** [comment]
screen shot 2015-09-25 at 4 51 26 pm
:heart_eyes:

**Pull request merged**
