### PR TITLE
Back to simple single quotes

### PR DESCRIPTION
**Pull request by Scotchester**
I now remember one of the main impetuses for finding a different character: they have to be escaped, unfortunately. Ah well.

### CODE REVIEW

**Comment by KimberlyMunoz** [comment]
:+1:

**Comment by jimmynotjim** [comment]
Built correctly for me locally. Here's hoping Jenkins or whatever does as well. :+1:

**Comment by Scotchester** [comment]
Anyone tested this?

**Comment by KimberlyMunoz** [comment]
image

**Comment by Scotchester** [comment]
Woohoo!

**Pull request merged**
