### PR TITLE
refactored get_form_id into the filterable mixin class

### PR DESCRIPTION
**Pull request by grapesmoker**
This PR refactors the function get_form_id into the FilterableMixin class, which it needs to be called on anyway in order to produce the correct result.

## Additions

- adds form_id to the FilterableMixin class

## Changes

- change calls to util.get_form_id(page) into calls to page.form_id()

## Testing

- no new tests required; all current tests should pass

## Review

@chosak @richaagarwal @willbarton 

## Todos

The plan is to eventually replace all the weird get_whatever functions that take pages as arguments with class instance methods. These functions result in a great deal of confusing spaghetti code and logical fragmentation of the codebase.

## Checklist

* [ ] Changes are limited to a single goal (no scope creep)
* [ ] Code can be automatically merged (no conflicts)
* [ ] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [ ] Passes all existing automated tests
* [ ] New functions include new tests
* [ ] New functions are documented (with a description, list of inputs, and expected output)
* [ ] Placeholder code is flagged
* [ ] Visually tested in supported browsers and devices
* [ ] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)

### CODE REVIEW

**Comment by grapesmoker** [comment]
Indeed, forgot to commit that. Tests all still pass.

**Comment by richaagarwal** [comment]
👍

**Comment by grapesmoker** [comment]
Is there something I'm supposed to do with regards to the review? It has a big red X on it; I'm not sure how to tell github that I've satisfied the reviewer or whether it's something the reviewer has to accept.

**Comment by willbarton** [comment]
@grapesmoker It just needs another review.

**Comment by grapesmoker** [comment]
pinging @richaagarwal

**Comment by richaagarwal** [comment]
Weird, what an awful interface. I'm on mobile right now and not seeing an option to approve. I'll have to do it when I get home from an appointment.

**Comment by richaagarwal** [comment]
Merging this now.  Idk if I recommend using the Github PR approval flow bc of stuff like this.

**Pull request merged**
