### PR TITLE
Migrate to wagtail-flags for our feature flags

### PR DESCRIPTION
**Pull request by anselmbradford**
## Removals

- Removes flag app and moves it to https://github.com/cfpb/wagtail-flags

## Changes

- Fixes CSS structure on Wagtail CSS.

## Testing

- Follow https://github.com/cfpb/wagtail-flags#installation

## Notes

- Don't merge before Feb 1, EOD.

### CODE REVIEW

**Comment by willbarton** [comment]
Before we merge this I'd like to get the tests working in wagtail-flags too.

**Comment by chosak** [comment]
I've [submitted a PR](https://github.com/cfpb/wagtail-flags/pull/1) to wagtail-flags that fixes the tests over there and should be compatible with how we're using it here.

**Comment by willbarton** [comment]
It would also be good if we could make a release of wagtail-flags and pin the version so we're not constantly building the same code. I think [this PR in wagtail-flags](https://github.com/cfpb/wagtail-flags/pull/3) should be merged before we do that. Once it's reviewed and merged I can create a release, and add the pin.

**Comment by rosskarchner** [comment]
Have you thought about uploading it to PyPI?

https://packaging.python.org/distributing/#uploading-your-project-to-pypi

**Comment by willbarton** [comment]
@rosskarchner yes, I would very much like us to.

**Pull request merged**
