### PR TITLE
Remove redundant throttle function

### PR DESCRIPTION
**Pull request by anselmbradford**
~~The throttle function was included in email-popup-helpers.js, but there's an identical throttle module that could be used.~~

## Changes

- Replaces `throttle.js` with `lodash.throttle`

## Testing

1. `gulp build` should pass.
2. Pages such as /consumer-tools/debt-collection should show popup.

### CODE REVIEW

**Comment by sebworks** [comment]
I would say lets remove it and go with `https://www.npmjs.com/package/lodash.throttle`.

**Comment by anselmbradford** [comment]
> I say lets remove it and go with https://www.npmjs.com/package/lodash.throttle.

That gives us the whole lodash library in node_modules, even with only `lodash.throttle` in `package.json`, doesn't seem worth it?

screen shot 2018-03-15 at 11 00 00 am

**Comment by anselmbradford** [comment]
Oh wait, nevermind, looks like we're already installing the full library as it's a dep of a bunch of things.

**Comment by anselmbradford** [comment]
Okay, @sebworks, replaced it! You can force showing the popup with https://github.com/cfpb/cfgov-refresh/pull/3883/commits/be7fd7e19962b0e6f87463a402e12d2913f44d96

**Comment by sebworks** [comment]
Looks good, I think it's also used on the `/ask-cfpb/` type ahead.

**Pull request merged**
