### PR TITLE
Fixes to housing counselor semantics

### PR DESCRIPTION
**Pull request by anselmbradford**
## Changes

- Adds URL-encoding to text in Facebook sharing link URL to handle spaces (`Find a housing counselor` to `Find%20a%20housing%20counselor`).
- Removes extraneous spaces in email address link.
- Convert `View Paperwork Reduction Act statement` link that doesn't go to a page to a button link.

## Testing

1. pull down branch and visit /find-a-housing-counselor/?zipcode=05201&s3=True
2. Scroll to bottom and see `View Paperwork Reduction Act statement`.

## Screenshots

Before
screen shot 2017-07-20 at 12 58 31 pm

After
screen shot 2017-07-20 at 12 58 40 pm

## Notes

- I think the link styles before were incorrect, because now they're our link button styles from CFv4.

### CODE REVIEW

**Comment by anselmbradford** [comment]
@nataliafitzgerald Are the link style updates here correct? (See screenshots). Link is at the bottom of e.g. https://www.consumerfinance.gov/find-a-housing-counselor/?zipcode=05201

**Comment by Scotchester** [comment]
The link shouldn't be getting that extra `letter-spacing`. Where's that coming from?

**Comment by anselmbradford** [comment]
> The link shouldn't be getting that extra letter-spacing. Where's that coming from?

The reset apparently

https://github.com/cfpb/cfgov-refresh/blob/master/cfgov/legacy/static/nemo/_/c/styles.css#L269

**Comment by Scotchester** [comment]
Ugh, OK. Can you toss in a style in that file to override that for `.a-btn`s?

**Comment by anselmbradford** [comment]
@Scotchester Added!

screen shot 2017-07-27 at 2 16 56 pm

**Pull request merged**
