### PR TITLE
Migrate pull quote to cfv4

### PR DESCRIPTION
**Pull request by anselmbradford**
## Changes

- Updates `m-quote` and `pull-quote` to Capital Framework v4 `m-pull-quote`.
- Adds "is large" option to Wagtail to include large pull quote style from CF.

## Testing

1. Create a test page in Wagtail.
2. Add a full-width text component.
3. Add a quote to the full-width text.
4. Preview changes to see pull quote.

## Screenshots

Before:
screen shot 2017-06-23 at 6 22 25 pm

After:
screen shot 2017-06-23 at 6 15 53 pm

Wagtail:
screen shot 2017-06-23 at 6 42 52 pm

## Todos

- This probably needs tests for the wagtail changes, but I need guidance on how to add them. Anyone?

### CODE REVIEW

**Comment by sebworks** [comment]
@anselmbradford, you will need to add a migration for the model change. I am surprised it didn't fail the back-end test.

**Comment by sebworks** [comment]
what pages are we currently using this on?

**Comment by anselmbradford** [comment]
> you will need to add a migration for the model change. I am surprised it didn't fail the back-end test.

How do I do that? I think this is my first Wagtail change PR!

> what pages are we currently using this on?

Here're two https://www.consumerfinance.gov/about-us/blog/hundreds-thousands-accounts-secretly-created-wells-fargo-bank-employees-leads-historic-100-million-fine-cfpb/ https://www.consumerfinance.gov/about-us/blog/cientos-de-miles-de-cuentas-creadas-en-secreto-por-los-empleados-de-wells-fargo-bank-resultan-en-una-multa-historica-de-100-millones-por-parte-del-cfpb/

**Comment by sebworks** [comment]
@chosak, why no migration error for this PR?

**Comment by sebworks** [comment]
@anselmbradford, https://docs.djangoproject.com/en/1.11/topics/migrations/#adding-migrations-to-apps

**Comment by anselmbradford** [comment]
Normal size:
screen shot 2017-06-26 at 10 18 10 am

Large size:

screen shot 2017-06-26 at 10 18 04 am


Added a change requested by @jordanafyne to make citation optional. Large pull quote without citation:
screen shot 2017-06-26 at 10 14 23 am

**Comment by anselmbradford** [comment]
@sebworks Added migration in https://github.com/cfpb/cfgov-refresh/pull/3078/commits/d6eaf7adf14643b50a6314e558d229f2fb6fc42e

**Comment by willbarton** [comment]
> @chosak, why no migration error for this PR?

Not @chosak, but I *think* it's because the change is to the StructBlock and not the model itself.

**Comment by sebworks** [comment]
@willbarton, awww that is right. We should just add a dirty check for that somehow. @anselmbradford looks good to me. Just rename the migration to something more meaningful. 

I would wait for a BEWD to sign off as well.

**Comment by anselmbradford** [comment]
> Just rename the migration to something more meaningful.

Done! Is there a command to do that? I just manually edited it.

**Comment by willbarton** [comment]
It's manual.

**Comment by contolini** [comment]
> Done! Is there a command to do that? I just manually edited it.

It doesn't save a whole lot of time but you can name the migration when you create it: `python cfgov/manage.py makemigrations --name=pull_quote_is_large_option`

**Comment by Scotchester** [comment]
> we run without migrations now in Travis

Oooohhhh, like @sebworks I'd really like to figure out a way to get that test back in Travis.

**Comment by willbarton** [comment]
>> we run without migrations now in Travis
> Oooohhhh, like @sebworks I'd really like to figure out a way to get that test back in Travis.

I'd be interested in @chosak's suggestion, but the only thing I can think of is a separate `--dry-run` in the Travis script instead of a unit test.

**Comment by chosak** [comment]
@sebworks @willbarton sorry I missed this yesterday. I think your suggestion about sticking it into the `run_travis.sh` is right, we can't do it as a unit test anymore because we've turned off migrations on Travis. A missing migration would still fail the build/deploy pipeline.

**Pull request merged**
