### PR TITLE
Update optional form input style

### PR DESCRIPTION
**Pull request by anselmbradford**
Required/optional fields were inconsistently styled. See https://[GHE]/CFGOV/platform/issues/465. This makes them consistent.

## Changes

- Remove asterisk for required fields on conference registration form.
- Makes optional fields have `(optional)` text next to them.

## Testing

1. Create a new browse page in Wagtail.
2. Add the conference registration form.
3. Preview the page and view the optional/required fields.
4. Change https://github.com/cfpb/cfgov-refresh/blob/master/cfgov/jinja2/v1/_includes/conference-registration-form.html#L99 to false to see checkbox optional style.

## Screenshots

Before:

screen shot 2017-08-04 at 5 54 00 pm

After:
screen shot 2017-08-04 at 5 53 17 pm

## Notes

- Checkbox background is messed up, but that was that way outside of this PR.

### CODE REVIEW

**Comment by cfarm** [comment]
Looks good to me. I am tagging @marteki because she worked on Research Conference form and I just want to make sure these changes meet her approval for how that form was intended to function.

**Comment by anselmbradford** [comment]
> We should check in and at a minimum inform her that this change is being made to match our site-wide standards, rather than having it be an uncomfortable surprise when the next conference is scheduled.

@marteki Would you be able to do this?

**Comment by marteki** [comment]
@anselmbradford Yeah, I can do that by e-mail, since the project ended this spring and I'm not in regular contact with the internal owner anymore. I'll CC @cfarm on it, as she served as scrum master for the project and I think she has a tighter relationship with the internal owner than I might.

**Comment by anselmbradford** [comment]
Thanks! I'll merge this in the mean time.

**Pull request merged**
