### PR TITLE
Beta review fixes

### PR DESCRIPTION
**Pull request by anselmbradford**
Fixes for minor issues surfaced in 8/3 beta review.

## Changes

- Fixed incorrect code comment in active-filters macro.
- Fixed grammar issues.
- Fixed indentation and spacing issues.
- Added missing links to /about-us/ landing page.

## Review

- @KimberlyMunoz 
- @sebworks

### CODE REVIEW

**Comment by KimberlyMunoz** [comment]
Just about to do a quick test, but any reason why this isn't a hotfix to beta?

**Comment by KimberlyMunoz** [comment]
LGTM

**Comment by anselmbradford** [comment]
> Just about to do a quick test, but any reason why this isn't a hotfix to beta?

The project catalyst and advisory group page updates are still on refresh and haven't bubbled up to beta yet, so best to bubble these fixes up normally. It's not fixing anything that's functionally broken, so no rush.

**Comment by KimberlyMunoz** [comment]
I totally can get behind that. :+1:

**Pull request merged**
