### PR TITLE
Delete and recreate Django migrations

### PR DESCRIPTION
**Pull request by chosak**
This commit deletes and recreates all Django migrations for the various apps in this project. It generates a similar outcome to how built-in Django squashing works, but works better with the large backlog of `RunPython` commands we've used over time.

This should significantly speed up the time it takes to create a new test database (i.e. using `tox`), although, unfortunately, this is still somewhat slow due to the number of models and migrations in third-party apps like Wagtail.

It has the effect of recreating a set of new migrations that describe the current state of all of our models, with these critical side effects:

1. Databases that exist at some migration state before the one at the point of this commit (7fddfdd) will no longer be able to be migrated to this current state, as the intermediate changes will have been lost. This means that those databases will need to be recreated.

    This also means that historical database archives will require a bit more work to resurrect; they'll need to first be migrated to the point just before this gets committed, and then updated to code at or after this point.

2. Any open pull requests that reference or depend on some of the existing migrations will need to be modified to instead refer to these new migration files. (fyi @virginiacc)

For the record, these new migrations were generated using this approach:

1. Remove all existing migration files:

    ```sh
    $ rm -f -v cfgov/*/migrations/0*
    ```

2. Create new migration files from the state of model Python code:

    ```sh
    $ cfgov/manage.py makemigrations --noinput
    ```

    As it happens this creates new initial migrations (`0001_initial`) for all apps, plus some subsequent migrations (`0002_something`) for apps that depend on other apps (for example, `ask_cfpb` has its own initial migration and then some changes that rely on `v1`).

3. Rename the created migration files so that they follow in sequence the migration files that used to exist. For example, currently there are 101 `v1` migrations, so the first new migration is numbered 102.

4. Manually alter all new migration files to indicate that they replace the old migration files.

    This involves adding lines to these files like:

    ```py
    includes = [('app_name', '0002_foo'), ('app_name', '0003_bar'), ...]
    ```

    This tells Django that these new files replace the old files, so that when migrations are run again, it doesn't need to do anything.

    Also manually update any new subsequent migration files so that they properly refer to each other. For example, if an app has two new migrations 102 and 103, the 103 file needs to properly depend on 102.

To apply these new migration files to an existing database, you can simply run:

```sh
$ cfgov/manage.py migrate --noinput
```

You'll see that there are no changes to apply, as the new files should exactly describe the current model state in the same way that the old migrations did.

This change also deletes a few unit tests that were testing functions in migrations that are removed here.

## Notes

This is a big change so a good review would be much appreciated.

## Checklist

* [X] PR has an informative and human-readable title
* [X] Changes are limited to a single goal (no scope creep)
* [X] Code can be automatically merged (no conflicts)
* [X] Code follows the standards laid out in the [development playbook](https://github.com/cfpb/development)
* [X] Passes all existing automated tests
* [X] Any *change* in functionality is tested
* [X] Reviewers requested with the [Reviewer tool](https://help.github.com/articles/about-pull-request-reviews/) :arrow_right:

### CODE REVIEW

**Comment by chosak** [comment]
Adding the "hold" label because these changes need to be recreated since a migration-altering PR has been merged in (#3748). Feedback on the implementation and decision to move ahead is still welcome.

**Comment by willbarton** [comment]
> 1. Databases that exist at some migration state before the one at the point of this commit (7fd3fa5) will no longer be able to be migrated to this current state, as the intermediate changes will have been lost. This means that those databases will need to be recreated.
>
> This also means that historical database archives will require a bit more work to resurrect; they'll need to first be migrated to the point just before this gets committed, and then updated to code at or after this point.

I don't think this is much of a problem. Maybe it's worth creating a git tag/release right before this change is merged (maybe this is the PR that gets us to 6.0)? That way the process in a hypothetical database restore would be to check out that tag, migrate, then checkout master and migrate again, right?

**Comment by chosak** [comment]
> Maybe it's worth creating a git tag/release right before this change is merged

I think that makes sense, at least a minor release and then some documentation changes that include instructions for using it.

> maybe this is the PR that gets us to 6.0

6.0 we need to save for Django/Wagtail/Python version bump. 😄

> That way the process in a hypothetical database restore would be to check out that tag, migrate, then checkout master and migrate again, right?

Yes, that's what I had in mind.

**Comment by willbarton** [comment]
> One question: Without some sort of cleanup on non-wagtail entries, the django_migrations table will be left with lots of orphaned migration references. Isn't it possible that a future migration could match one of the orphan entry names and thus refuse to run? 

@higs4281 I actually think the PostgreSQL migration might solve that problem by itself [if we use the approach in the linked PR instead of trying to munge a compatible SQL file](https://github.com/cfpb/cfgov-refresh/pull/3734).

**Comment by willbarton** [comment]
@higs4281 also, I can't reactji your review post apparently (annoying, GitHub!), but 💯 for trying to old-dump restore method!

**Comment by chosak** [comment]
Thanks all for the review, and apologies that it's taken me so long to come back to this. @higs4281 you raised an excellent point. By reusing the old migration numbers, we'd introduce a small change of conflict down the road.

To avoid that, I've recreated the migrations (and force-pushed them here) so that they continue the existing numbering. So, e.g. if `v1` had migrations 1-101, the new migration is numbered 102, and marked as replacing all that came before. For apps with multiple new migration files, both new files are marked as replacement, so e.g. `ask_cfpb` has new migrations 13 and 14 that are both marked as replacing 1-12.

I've updated the instructions above for future reference should we want to redo this; I played a bit with creating an automated script but it's a bit tricky as you need to edit the contents of the migration files.

If people wouldn't mind re-reviewing this, I'd very much appreciate it. As before, this is something we'll have to update if any new migrations get merged in before this does.

**Comment by chosak** [comment]
Thanks for the re-review @higs4281! The merge commit (a588589) shows no changes to migration files so this PR should still be good to go in. For future reference the commit that this is going in after is 8aa57b0.

**Pull request merged**
