### PR TITLE
Corrects 50/50 removal in 4241811

### PR DESCRIPTION
**Pull request by jimmynotjim**
The 50/50 molecule was accidentally removed in 4241811, this reverts that.

### CODE REVIEW

**Comment by sebworks** [comment]
:+1:

**Comment by anselmbradford** [comment]
:+1: But I noticed @kave renamed this `image-text-5050.html`, does that matter in this context?

**Comment by jimmynotjim** [comment]
@anselmbradford I'm not quite sure, because all the files are changed to use `_` instead of `-` as well. I'll defer to @kave

**Comment by kave** [comment]
Whoops! that was my fault. it can stay named `image-text-50-50.html` for consistency

**Pull request merged**
