### PR TITLE
Content updates from EA

### PR DESCRIPTION
**Pull request by jimmynotjim**
These edits come straight from EA and have been approved for release.

## Changes

- Updated `doing-business-with-us` and `doing-business-with-us/upcoming-procurement-needs`

## Testing

- navigation to `/doing-business-with-us/` and `/doing-business-with-us/upcoming-procurement-needs/`. Content should match the doc in Jira DFJR-1284

## Review

- @schaferjh 
- @anselmbradford 
- @sebworks 
- @sarahsimpson09 

## Screenshots

screen shot 2016-04-20 at 11 20 34 pm

screen shot 2016-04-20 at 11 20 57 pm

## Checklist

* [ ] Changes are limited to a single goal (no scope creep)
* [ ] Code can be automatically merged (no conflicts)
* [ ] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [ ] Passes all existing automated tests
* [ ] New functions include new tests
* [ ] New functions are documented (with a description, list of inputs, and expected output)
* [ ] Placeholder code is flagged
* [ ] Visually tested in supported browsers and devices
* [ ] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)

### CODE REVIEW

**Comment by schaferjh** [comment]
👍

**Comment by schaferjh** [comment]
Actually. Going through the live site right now and just realized that the "Future needs" table on the live site has been updated and we need those updates reflected on Upcoming Procurement Needs --
Current site: http://www.consumerfinance.gov/doing-business-with-us/
Beta: Upcoming Procurement needs /about-us/doing-business-with-us/upcoming-procurement-needs/

Is this table in WordPress or is something that could be updated as part of this PR?

**Comment by jimmynotjim** [comment]
@schaferjh that part is coming from WordPress, but other than the function used to grab it, I don't have any info where it is `get_document('pages', '36601')`. Yesterday @sarahsimpson09 said she tried the ID swap trick in urls and came up empty.

**Comment by schaferjh** [comment]
@kurtw now that the WordPress `pages` was restored in #1948  will that page ID work again and be editable in WP?

**Comment by KimberlyMunoz** [comment]
Assuming Sarah can find that last thing to edit. :+1:

**Pull request merged**
