### PR TITLE
Updated the homepage links

### PR DESCRIPTION
**Pull request by jimmynotjim**
Updated the homepage links

## Changes

- Updated the links on the homepage

## Testing

- `gulp build` and hover each link, cross reference the slugs with DFJR-1093

## Review

- @anselmbradford 
- @sebworks 
- @KimberlyMunoz 

## Checklist

* [ ] Changes are limited to a single goal (no scope creep)
* [ ] Code can be automatically merged (no conflicts)
* [ ] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [ ] Passes all existing automated tests
* [ ] New functions include new tests
* [ ] New functions are documented (with a description, list of inputs, and expected output)
* [ ] Placeholder code is flagged
* [ ] Visually tested in supported browsers and devices
* [ ] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)

### CODE REVIEW

**Comment by schaferjh** [comment]
Oh, what coincidental timing! Quick, while you're in here -- Tanya just noticed that "Latest Updates" needs to be "Latest updates" -- can you do that as part of this PR?

**Comment by jimmynotjim** [comment]
@schaferjh done

**Comment by sebworks** [comment]
:+1:

**Comment by KimberlyMunoz** [comment]
:+1:

**Pull request merged**
