### PR TITLE
Sprint PR cleanup

### PR DESCRIPTION
**Pull request by anselmbradford**
Sprint 0 PR cleanup.

## Changes

- Code comment and style cleanup.
- Changes `big_radio` macro to `radio_big` and `checkbox_bg` to `checkbox_big`.

## Review

- @KimberlyMunoz 
- @jimmynotjim 
- @sebworks

### CODE REVIEW

**Comment by KimberlyMunoz** [comment]
:disappointed: #974  https://www.youtube.com/watch?v=tKdcjJoXeEY

I'll check to see if there's anything this one didn't catch and close mine.

**Comment by KimberlyMunoz** [comment]
LGTM

**Comment by jimmynotjim** [comment]
:+1:

**Comment by sebworks** [comment]
:+1:

**Pull request merged**
