### PR TITLE
READY: Updated the nav for the upcoming conference page

### PR DESCRIPTION
**Pull request by jimmynotjim**
Data & Research will be publishing a new page for the Research Conference (whooo!). Adding the link to the nav so that it will be discoverable.

## Additions

- Added new conference url in the nav

## Testing

- checkout the branch and make sure the link is in the nav

## Review

- @KimberlyMunoz 
- @cfarm 
- @schaferjh 

## Screenshots

screen shot 2016-08-12 at 2 09 04 pm

## Notes

- It doesn't go anywhere yet, but when the page is published next tue/wed this should get merged shortly so it can go out with the following release.

## Checklist

* [x] Changes are limited to a single goal (no scope creep)
* [ ] Code can be automatically merged (no conflicts)
* [x] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [x] Passes all existing automated tests
* [x] New functions include new tests
* [x] New functions are documented (with a description, list of inputs, and expected output)
* [x] Placeholder code is flagged
* [x] Visually tested in supported browsers and devices
* [x] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)

### CODE REVIEW

**Comment by schaferjh** [comment]
I have staged the page for stakeholder approval and will make an update here when it is published.

**Comment by schaferjh** [comment]
@jimmynotjim page is published: http://www.consumerfinance.gov/data-research/cfpb-research-conference/

**Comment by jimmynotjim** [comment]
@KimberlyMunoz, @HilaryGibson, @kurtrwall Can an of you sign off on this today? Anyone from Platform is invited as well.

**Comment by sebworks** [comment]
👍

**Comment by jimmynotjim** [comment]
Bot is assigned, if the changelog updates before this self merges, I'll need someone to push a fix to this branch. I'll be traveling from 10am-6pm EDT and filming with Media thru Fri.

**Comment by willbarton** [comment]
:+1:

**Pull request merged**
