### PR TITLE
Leadership Calendar: Back to Django

### PR DESCRIPTION
**Pull request by rosskarchner**
This brings the leadership calendar back into plain-old-Django, and removes the Sheer processor. This will make lives easier in a number of ways: content managers won't have to worry about the "sheer index", and dev team should see less unexplainable test failures in Travis and elsewhere (because the processor was so flaky).

There's also been some simplification around PDF generation:
- We're passing rendered HTML to PDFReactor, instead of A URL (that it would need to turn around and fetch). This should reduce the amount of different ways PDF generation can fail. In other words, the current path is: Django  ->  PDFReactor -> Django, with this PR it's just Django-> PDFReactor.
- The download form now uses GET instead of POST, meaning the generated PDF's should be cachable in Akamai.

Also, somewhere along the way we broke [this page](http://www.consumerfinance.gov/credit-cards/knowbeforeyouowe/) and nobody noticed. I've re-added that URL in this PR. (cc @schaferjh )

## Testing

- `pip uninstall leadership-calendar`
- Load this SQL into your DB: [calendar.sql.zip](https://github.com/cfpb/cfgov-refresh/files/321190/calendar.sql.zip)
- Check out http://localhost:8000/about-us/the-bureau/leadership-calendar/ and try filtering by person and date.
- Try the download form too-- if you are on a machine without PDFReactor (or PDFReactor is failing somehow), it should fail over to showing you the HTML representation (inspired by @kave's #2193)

## Review

- @kurtw @richaagarwal 

## Todos

- see how this interacts with the work in #2188

## Checklist

* [ ] Changes are limited to a single goal (no scope creep)
* [ ] Code can be automatically merged (no conflicts)
* [ ] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [ ] Passes all existing automated tests
* [ ] New functions include new tests
* [ ] New functions are documented (with a description, list of inputs, and expected output)
* [ ] Placeholder code is flagged
* [ ] Visually tested in supported browsers and devices
* [ ] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)

### CODE REVIEW

**Comment by schaferjh** [comment]
Thanks for working on this. I am still looking into the product owner question you asked me -- it may take some time to get a solid answer, but it's not forgotten!

**Comment by rosskarchner** [comment]
Rebased on top of #2188

**Comment by rosskarchner** [comment]
and back to being rebased on flapjack, now that #2188 is in

**Comment by kurtw** [comment]
Once we figure out how to get styles in the PDF generated, 👍

**Comment by richaagarwal** [comment]
I think there are conflicting migrations right now - 
``` 
CommandError: Conflicting migrations detected (0090_auto_20160609_1603, 0091_cfgovpage_has_unshared_changes in v1).
To fix them run 'python manage.py makemigrations --merge'
```

**Comment by rosskarchner** [comment]
Weird-- it shouldn't be reffering to the v1 migrations at all

**Comment by rosskarchner** [comment]
I've rebased and can't duplicate that error-- can you see if this works better?

**Comment by richaagarwal** [comment]
Ah, sorry - I think that was my bad. It appears to be working now.

**Comment by kurtw** [comment]
Bumping my 👍

**Comment by richaagarwal** [comment]
This PR introduced these 3 test failures: 

```
Failures:
1) The Leadership Calendar Page Search Filter should include a search filter search filter results
  Message:
    Expected 0 to be greater than 0.
  Stack:
    Error: Failed expectation
        at Object.<anonymous> (/Users/agarwalr/apps/cfgov-refresh/test/browser_tests/spec_suites/leadership-calendar.js:77:52)
        at process._tickCallback (node.js:401:9)

2) The Leadership Calendar Page Download Filter should be included
  Message:
    Expected false to be true.
  Stack:
    Error: Failed expectation
        at Object.<anonymous> (/Users/agarwalr/apps/cfgov-refresh/test/browser_tests/spec_suites/leadership-calendar.js:86:51)
        at process._tickCallback (node.js:401:9)

3) The Leadership Calendar Page should include pagination form
  Message:
    Expected false to be true.
  Stack:
    Error: Failed expectation
        at Object.<anonymous> (/Users/agarwalr/apps/cfgov-refresh/test/browser_tests/spec_suites/leadership-calendar.js:116:49)
        at process._tickCallback (node.js:401:9)
```

**Comment by rosskarchner** [comment]
Thanks @richaagarwal- I wonder why Travis didn't fail.

**Comment by rosskarchner** [comment]
OK, this works for me because I have the events database, which probably isn't part of the dumps people are working with, or the test data:

```
 rk@:~/projects/cfgov-refresh$ gulp test:acceptance --specs=leadership-calendar.js
[07:36:55] Using gulpfile ~/projects/cfgov-refresh/gulpfile.js
[07:36:55] Starting 'test:acceptance:browser'...
[07:36:55] Finished 'test:acceptance:browser' after 4.35 ms
[07:36:55] Starting 'test:acceptance'...
[07:36:55] Finished 'test:acceptance' after 7.41 μs
Starting selenium standalone server...
[launcher] Running 1 instances of WebDriver
Selenium standalone server started at http://192.168.43.132:49321/wd/hub
Started
Executing... cfgov-refresh screen test spec_suites/**/*leadership-calendar.js, running chrome on Windows at 1200,900px
..............


14 specs, 0 failures
Finished in 4.079 seconds
Shutting down selenium standalone server.
[launcher] 0 instance(s) of WebDriver still running
[launcher] chrome #01 passed
[07:37:03] Protractor tests done!
```

So, that's a thing to fix.

**Pull request merged**
