### PR TITLE
Fixing lodash dependency error

### PR DESCRIPTION
**Pull request by sebworks**
Fixing lodash dependency error

# Reveiw

@kave 

# Test

Run `gulp test`

### CODE REVIEW

**Comment by kave** [comment]
@sebworks hmm so i'm getting like 47 errors locally when it runs browser tests but i'm not convinced its due to the lodash because if you navigate to `/events/field-hearing-on-arbitration/` its erroring out on twitter_options `'dict object' has no attribute 'twitter_options'`

**Comment by anselmbradford** [comment]
LGTM pending Emmanuel's comment

**Comment by sebworks** [comment]
@kave, please test this again

**Comment by kave** [comment]
@sebworks seems to be a fluke :+1:

**Pull request merged**
