### PR TITLE
Click-to-dial phone number (header)

### PR DESCRIPTION
**Pull request by mistergone**
This PR adds markup to the phone number in the "eyebrow" - this markup allows users to click to dial the number.

## Additions
- Markup added to `global-eyebrow.html` and `mega-menu-for-ia-testing.html`
 - I'm not sure what `mega-menu-for-ia-testing.html` is for, but I found the number there, so I marked it up!

## Testing
1. Install this branch and run a server
2. Open the homepage in a mobile browser
3. Click the phone number (in the hamburger menu) to dial!

## Screenshots
screen shot 2017-06-13 at 10 46 47 am

## Notes
- The "hamburger menu" does not appear for me in Blackberry, so I was not able to test this in Blackberry. This also occurs on production, so I suspect a bug for the Blackberry browser.
- The code in `cfgov-refresh` for the Spanish language site already has `tel:` anchors. Hooray!

## Todos
- This is only one instance of the phone number on the site. Other instances are being tracked down.

## Checklist
* [x] PR has an informative and human-readable title
* [x] Changes are limited to a single goal (no scope creep)
* [ ] Code can be automatically merged (no conflicts)
* [x] Code follows the standards laid out in the [development playbook](https://github.com/cfpb/development)
* [ ] Passes all existing automated tests
* [x] New functions include new tests
* [x] New functions are documented (with a description, list of inputs, and expected output)
* [x] Placeholder code is flagged
* [x] Visually tested in supported browsers and devices
* [x] Project documentation has been updated
* [ ] Reviewers requested with the [Assignee tool](https://help.github.com/articles/assigning-issues-and-pull-requests-to-other-github-users/) :arrow_right:

### CODE REVIEW

**Comment by anselmbradford** [comment]
Should this be a link on all browsers, or only on mobile browsers? https://stackoverflow.com/questions/15003205/make-a-telephone-number-clickable-on-mobile-browsers-only

**Comment by willbarton** [comment]
@anselmbradford anecdotally, I kind of like being able to click a phone number on my personal computer and have it use my phone to call that number.

**Comment by anselmbradford** [comment]
> anecdotally, I kind of like being able to click a phone number on my personal computer and have it use my phone to call that number.

Yeah, not saying it shouldn't be on all browsers, just checking that there isn't an expectation from UX that it would only be a link on mobile devices. Not sure who's in charge of that.

**Comment by willbarton** [comment]
@ielerol @schaferjh?

**Comment by schaferjh** [comment]
I have some concerns about making this clickable on desktop and whether that's inviting more errors than it's worth -- I don't think the vast majority of people have a set up on desktop like Will describes, though it sounds nice. I don't know of testing or research around how people respond to phone number links on desktop.

At the end of the day, we are not intent on restricting this functionality to mobile browsers only, rather the requirement is that it must work on mobile browsers at the very least.

@ascott1 do you have opinions on this?

**Comment by Scotchester** [comment]
I agree with @schaferjh's concerns about making it clickable on desktop-ish devices, though I also have no data to back it up.

That aside, it seems like it's extremely difficult to ascertain within a reasonable margin of error whether the device you're using is a phone-esque device or not. Phone screen resolutions are insane, most laptops sold these days have touchscreens, etc.

**Comment by ielerol** [comment]
I looked a bit for testing or research around desktop phone number links, and didn't find anything useful. I also share @Scotchester's concern about the difficulty of accurately detecting whether a device is "phone-like" or not. I'd rather err on the side of providing the functionality to people who don't need it than accidentally hide it from from people who do want it.

**Comment by mistergone** [comment]
I'll throw my opinion on the fire, which is to agree with @Scotchester and @ielerol that detecting whether a device has "phone capabilities" is very difficult, including distinguishing between non-phone tablets and smartphones.

Perhaps it's worth researching what various "desktop" setups do when a `tel:` link is clicked might be worth our time. I'm sure it depends on a whole lot more than, say, browser type. For instance, my Mac wants to fire up Facetime, whereas my Windows 10 laptop prompts me to "Pick an App".

Also, our Spanish site has had a clickable phone number for an indefinite (to me) amount of time. Have we seen any negative feedback on that?

**Comment by jimmynotjim** [comment]
For what it's worth, [Google suggests always linking it](https://developers.google.com/web/fundamentals/native-hardware/click-to-call/), as well as using international formatting and telling Safari not to auto-format it.

**Comment by mistergone** [comment]
Google also suggests there that one uses hyphens (-) to increase readability, which I didn't do. Anyone have opinions on that? It seems like a fine idea, and I'm happy to update to that format.

**Comment by mistergone** [comment]
I added a commit that formats the `tel` link with hyphens.

**Comment by mistergone** [comment]
I've got some approvals, and I think the discussion about mobile/desktop is basically resolved, so I'm going to merge this!

If there are any concerns, it's easy enough to revert. 😁

**Pull request merged**
