### PR TITLE
Consolidates similar copy code

### PR DESCRIPTION
**Pull request by anselmbradford**
Consolidates similar code noted in https://codeclimate.com/github/cfpb/cfgov-refresh/gulp/tasks/copy.js

## Changes

- In gulp copy task, consolidates similar code into a shared private function.

## Testing

- `gulp build` and `gulp watch` should work fine.

## Review

- @jimmynotjim 
- @sebworks 
- @KimberlyMunoz

### CODE REVIEW

**Comment by sebworks** [comment]
Should we place the task names in an array and loop them to create the gulp tasks?

**Comment by anselmbradford** [comment]
> Should we place the task names in an array and loop them to create the gulp tasks?

Generally defining functions within loops are discouraged --> https://jslinterrors.com/dont-make-functions-within-a-loop
We could define a helper function that creates the task, but it would prob be best to do that across the board so all gulp tasks are created the same way.

**Comment by sebworks** [comment]
I was thinking use `Function.bind` to create a partial but I see your point. :+1:

**Comment by anselmbradford** [comment]
> I was thinking use Function.bind to create a partial function but I see your point.

Ahh gotcha! I'll merge this for now, that could be an optimization cross the board for the gulp tasks.

**Pull request merged**
