### PR TITLE
Spelling amendments: browser-testing.md

### PR DESCRIPTION
**Pull request by Newman101**
Hi. I spotted few spelling mistakes in the documentation file docs/browser-tests.md. These have been now amended.

## Changes

- Documentation spelling amendments.

allowences -> allowances
webpage -> web page
compliancy -> compliance 

No functional changes to software itself. 

## Checklist

* [x] Changes are limited to a single goal (no scope creep)
* [x] Code can be automatically merged (no conflicts)
* [x] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [ ] Passes all existing automated tests
* [ ] New functions include new tests
* [ ] New functions are documented (with a description, list of inputs, and expected output)
* [ ] Placeholder code is flagged
* [ ] Visually tested in supported browsers and devices
* [ ] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)

### CODE REVIEW

**Comment by Newman101** [comment]
For some reason the branch was out of date. This has been updated.

**Comment by anselmbradford** [comment]
LGTM 👍

**Comment by sebworks** [comment]
👍

**Comment by anselmbradford** [comment]
@Newman101 Could you please update the branch again? Looks like it got out of date again.

**Comment by Newman101** [comment]
Sure, updated.

**Pull request merged**
