### PR TITLE
Update story categories

### PR DESCRIPTION
**Pull request by Scotchester**
Since my initial implementation, the name of one category changed. Also, new future categories needed to be added.

## Additions

- New story categories

## Changes

- Renamed one category

## Testing

- Pull the branch and verify the contents of a category dropdown.

## Checklist

* [ ] Changes are limited to a single goal (no scope creep)
* [ ] Code can be automatically merged (no conflicts)
* [ ] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [ ] Passes all existing automated tests
* [ ] New functions include new tests
* [ ] New functions are documented (with a description, list of inputs, and expected output)
* [ ] Placeholder code is flagged
* [ ] Visually tested in supported browsers and devices
* [ ] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)
* [ ] Reviewers requested with the [Assignee tool](https://help.github.com/articles/assigning-issues-and-pull-requests-to-other-github-users/) :arrow_right:

### CODE REVIEW

**Comment by willbarton** [comment]
Verified the contents of the categories dropdown locally. 

image

**Comment by Scotchester** [comment]
Look at me, change log proponent, forgetting to update it until mouseup of clicking the merge button. Sorry :\

**Comment by chosak** [comment]
I wonder if this might be made less painful in future by moving the choices out of the model (which requires a migration each time) and into the form. This would require this change:

```diff
--- a/cfgov/v1/models/base.py
+++ b/cfgov/v1/models/base.py
@@ -9,6 +9,7 @@ from django.conf import settings
 from django.contrib.auth.models import User
 from django.db import models
 from django.db.models import Q
+from django.forms.widgets import Select
 from django.http import (Http404, HttpResponse, HttpResponseBadRequest,
                          JsonResponse)
 from django.template.response import TemplateResponse
@@ -454,10 +455,10 @@ class CFGOVPage(Page):
 
 class CFGOVPageCategory(Orderable):
     page = ParentalKey(CFGOVPage, related_name='categories')
-    name = models.CharField(max_length=255, choices=ref.categories)
+    name = models.CharField(max_length=255)
 
     panels = [
-        FieldPanel('name'),
+        FieldPanel('name', widget=Select(choices=ref.categories)),
     ]
```

This has the drawback that categories aren't validated at the model level, but only at the form level. The form also appears slightly differently (still clickable, but no down arrow at right):

image

The advantage is that any changes to these options in future won't require a migration.

**Comment by willbarton** [comment]
@chosak I would fully support that change, given we had two of these in the last two days.

**Pull request merged**
