### PR TITLE
Enable the sortable tables scripting

### PR DESCRIPTION
**Pull request by jimmynotjim**
Now that Capital Framework has been updated in this project, the scripting for sortable tables is available. Added an on-demand script that initializes the scripting when tables are used on a page.

## Additions

- Added on-demand script to initialize cf-tables code when a page includes a table

## Testing

1. Locally, turn on the sortable tables flag
screen shot 2017-08-10 at 10 36 09 am

2. Create a page with a table inside a full-width text module, enable sortable table functionality and set the sorting options.

screen shot 2017-08-10 at 10 37 00 am

3. Save page and view it in the browser

screen shot 2017-08-10 at 10 37 39 am

4. Click the headings and the table should resort itself.

## Notes

- There is a bug in the chart builder override file causing the heading colors to be incorrectly set making it dark on dark. This needs to be fixed separately, but because the sortable functionality is behind a flag, it will not be an immediate issue.

## Todos

- Update CF to use real variables to avoid override bugs

## Checklist

* [x] PR has an informative and human-readable title
* [x] Changes are limited to a single goal (no scope creep)
* [x] Code can be automatically merged (no conflicts)
* [x] Code follows the standards laid out in the [development playbook](https://github.com/cfpb/development)
* [x] Passes all existing automated tests
* [x] New functions include new tests
* [x] New functions are documented (with a description, list of inputs, and expected output)
* [x] Placeholder code is flagged
* [x] Visually tested in supported browsers and devices
* [x] Project documentation has been updated
* [x] Reviewers requested with the [Assignee tool](https://help.github.com/articles/assigning-issues-and-pull-requests-to-other-github-users/) :arrow_right:

### CODE REVIEW

**Comment by cfarm** [comment]
I'M FIXING THE CHART BUILDER VARIABLES FILE NOW!!! 😿 sorry yall

**Comment by sebworks** [comment]
@jimmynotjim, please check this on IE.

**Comment by jimmynotjim** [comment]
@sebworks is there a specific problem you're seeing? This has already been extensively tested in IE9 and up as part of Capital Framework. We're not adding anything new here, just initializing it.

**Comment by sebworks** [comment]
I'm not sure why the `package-lock.json` file is being updated.

**Comment by sebworks** [comment]
> @sebworks is there a specific problem you're seeing? This has already been extensively tested in IE9 and up as part of Capital Framework. We're not adding anything new here, just initializing it.

Can you edit the component in Wagtail using IE?

**Comment by sebworks** [comment]
@jimmynotjim, looks like it's this line `https://github.com/cfpb/cfgov-refresh/blob/639bd89607bd69093ef9de3626522e4e23c2b088/cfgov/templates/wagtailadmin/js/table-block.js#L433`, which is using es5. We don't run these file through babel.

**Comment by jimmynotjim** [comment]
> looks like it's this line, which is using es5. We don't run these files through babel.

1. That code came from the fixed width input tables, which means it's broken there too.
2. This issue is outside the scope of this PR, there was a previous PR for the admin. This PR is only initializing the scripting on tables that have already been created. Unfortunately I'm out for the next three weeks, hopefully someone else can pick up the admin issue while I'm gone.

> I'm not sure why the package-lock.json file is being updated.

I don't understand that either, it seems to be happening randomly on every repo I've worked on.

**Comment by sebworks** [comment]
ok, just drop the change in the `package-lock.json` and I think it's good.

**Comment by jimmynotjim** [comment]
@sebworks reverted the `package-lock.json` changes

**Pull request merged**
