### PR TITLE
Update privacy links in footer

### PR DESCRIPTION
**Pull request by virginiacc**
Update text of privacy links in footer (GHE 342)

## Changes

- links in `cfgov/jinja2/v1/_includes/organisms/footer.html`

## Review

- @cfpb/cfgov-frontends 

## Screenshots

screen shot 2016-10-06 at 1 40 54 pm

## Checklist

* [ ] Changes are limited to a single goal (no scope creep)
* [ ] Code can be automatically merged (no conflicts)
* [ ] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [ ] Passes all existing automated tests
* [ ] New functions include new tests
* [ ] New functions are documented (with a description, list of inputs, and expected output)
* [ ] Placeholder code is flagged
* [ ] Visually tested in supported browsers and devices
* [ ] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)

### CODE REVIEW

**Comment by sebworks** [comment]
👍

**Comment by schaferjh** [comment]
One small nit: we use ampersands in navigation -- Website Privacy Policy & Legal Notices. Thanks!

**Comment by schaferjh** [comment]
@sebworks @contolini could we get another check on this so it can be merged for today's tagged release?

**Comment by sebworks** [comment]
👍

**Pull request merged**
