### PR TITLE
Add period to code comment.

### PR DESCRIPTION
**Pull request by anselmbradford**
Very minor code comment update in eslint file.

## Additions

- Adds missing period in code comment.

## Review

- @anselmbradford

### CODE REVIEW

**Comment by anselmbradford** [comment]
Gonna save you guys the time on this one...

**Comment by jimmynotjim** [comment]
I don't know, we specifically said at least one sign-off ;)

**Comment by anselmbradford** [comment]
And see, I listed one reviewer for sign-off! ;)

**Comment by sebworks** [comment]
lol

**Comment by jimmynotjim** [comment]
But you never gave yourself the :+1:

**Comment by anselmbradford** [comment]
lol :hear_no_evil:

**Pull request merged**
