### PR TITLE
Move jquery to package.json

### PR DESCRIPTION
**Pull request by anselmbradford**
Moves jquery to package.json to remove jQuery redundancy.

## Removals

- Removes jQuery from bower.json.

## Changes

- Downgrades jQuery in package.json for legacy browser compatibility.
- Notes earlier testing addition and related changes in the changelog.

## Testing

- Site JS that depends on jQuery should still work as expected and `grunt test` should show no errors.

## Review

- @KimberlyMunoz 
- @jimmynotjim 
- @sebworks 

## Notes

- I'm not sure of the conventions around what goes in bower.json vs package.json, but it looks like the trend may be to move everything to package.json https://github.com/bower/bower/issues/1626. Istanbul couldn't find jquery if it wasn't in package.json, so that's why I put it there.

### CODE REVIEW

**Comment by sebworks** [comment]
Shouldn't it be 'Istanbul'?

**Comment by anselmbradford** [comment]
> Shouldn't it be 'Istanbul'?

It sure should! Fixed in https://github.com/cfpb/cfgov-refresh/commit/2d430fc9b42cccec6588b7567f4dab701407a96a

**Comment by anselmbradford** [comment]
@sebworks pointed out that jquery was including a link to the jquery sourcemap that was throwing a 404.  https://github.com/cfpb/cfgov-refresh/commit/935b1cb952416452b2ef2a7e39d1989f2d530181 includes the unminified jquery library instead of the minified one (which includes the sourcemap comment) and moves the minifying step after the browserify-shim transform into package.json.

**Comment by sebworks** [comment]
:+1:

**Pull request merged**
