### PR TITLE
Sets tox tests to use coverage.

### PR DESCRIPTION
**Pull request by higs4281**
To help facilitate GHE issue 4 (increasing test coverage), this PR allows us to run `coverage report -m` after tox tests to see test coverage details. 
It would also allow us to add coveralls monitoring to the repo.

## Additions

- add coverage to test requirements
- .coveragerc config file

## Changes

- tox.ini changed to run tests with coverage

## Testing

- check out the coverage report with:

  ```
tox -e fast
coverage report -m
  ```

## Review

- @chosak @richaagarwal @grapesmoker 

* [x] CHANGELOG updated

### CODE REVIEW

**Comment by higs4281** [comment]
Holding while I check on failures to generate reports.

**Comment by higs4281** [comment]
@chosak 
Found the right incantations to get tox and coverage reports humming. 

```
tox -e fast
coverage report -m
```

**Comment by chosak** [comment]
:+1: This is great! Should we add [the coveralls badge](https://coveralls.io/github/cfpb/cfgov-refresh) to `README.md` as part of this PR?

**Comment by higs4281** [comment]
@chosak 
i thought I'd test that in another PR, but it would make sense in this one if we want our 69% badge now.

**Comment by chosak** [comment]
@higs4281 that's like a D+!

**Comment by higs4281** [comment]
badge ahoy; they take a while to show up.

**Comment by willbarton** [comment]
:+1:

**Pull request merged**
