### PR TITLE
Career Pages Adjustments from Design

### PR DESCRIPTION
**Pull request by KimberlyMunoz**
A batch of changes from @duelj based on his feedback in JIRA

## Changes

- Changing job posting date heading level
- Adjusting spacing between sidebar modules
- Mobile Module spacing adjustment
- Fixing Horizontal rule spacing inconsistency

## Testing
- Visit `/careers/` and look for the following
 1. there should be appropriate spacing between modules on mobile
 2. The job posting dates should be the same as the other job posting dates in the sidebar
 3. All horizontal rules should be the same size

## Notes
- This corresponds to JIRA issues: DF-2228, DF-2229, DF-2230, DF-2231

### CODE REVIEW

**Comment by KimberlyMunoz** [comment]
One sec. I just hopped off a hangout with @ajbush and have a few more adjustments.

**Comment by KimberlyMunoz** [comment]
Okay, adjustments made. @ajbush helped me out with this.

Apparently there should be about 60px of spacing between each block and 30px between the border and the top of a block under a border. This was tricky to do since `.block__sub` stacks margins and just using normal blocks doesn't get the appropriate spacing between the border and top of the block.

I'm not crazy about this markup, so feel free to offer alternatives to explore.

**Comment by jimmynotjim** [comment]
Looks good and can't think of any way to reduce the markup so :+1:

**Comment by sebworks** [comment]
:+1:

**Pull request merged**
