### PR TITLE
DF-1643: Hard Code Contacts

### PR DESCRIPTION
**Pull request by sebworks**
Display hard coded contact information :

## Changes

- Updates ' contact-us/_vars-contact-us.html' file to add hard coded data.
- Updates 'contact-us/submit-a-complaint.html' file to display hard coded data.

## Review

- @jimmynotjim 
- @anselmbradford 

## Preview
screen shot 2015-03-17 at 1 32 06 pm

### CODE REVIEW

**Comment by jimmynotjim** [comment]
LTGM :+1:

**Comment by Scotchester** [comment]
Our mailing address remains 1700 G Street NW.

**Comment by anselmbradford** [comment]
WP content will also need to be updated to remove "Administrative offices" and "Consumer contact center" in the expandables area on the left:

screen shot 2015-03-17 at 10 52 20 am

Not sure if that's a FEWD or Content Team task (cc @jameshupp), but a new task should be created for it if DF-1643 is closed without the content update part.

**Comment by sebworks** [comment]
@Scotchester , please review when you get a chance.

**Comment by Scotchester** [comment]
:+1: from me. I wonder if we do need to have the current office address somewhere though... @jameshupp?

**Pull request merged**
