### PR TITLE
Enforcement action page

### PR DESCRIPTION
**Pull request by wpears**
@cfarm 
Alternative implementation of https://github.com/cfpb/cfgov-refresh/pull/5475.

This creates a new page type EnforcementActionPage, which stores an enforcement action's metadata at the page level. 
Screen Shot 2020-02-13 at 12 03 39 PM

Categories & topics are always shown, so I didn't keep the "show categories" check since I figured it was crufty (however, maybe it's useful as a reminder to set in in the configuration section?)

Also, I removed the `date_filed` section because that should also be set in the configuration section. (we could also have a "show date filed" reminder here if we do for categories and topics).

Other pieces of the sidebar, like "related links" are still set in the sidebar tab

### CODE REVIEW

**Comment by cfarm** [comment]
@chosak When reviewing this with Wyatt, we had a question about whether putting the fields that are in the new Metadata tab in Configuration is 1) technically acceptable and 2) more usable for editors. Can you let us know what you think of the feasibility or advisability, code-wise?

**Comment by cfarm** [comment]
> Let's make the required fields required in the UI so it's obvious to the editor that the template requires these fields 💃 👍 🤔 🆗

@chosak what's the deal with the required fields and nullification business. Wyatt wants to know. pls help us we're but 2 half-time front ends

**Comment by cfarm** [comment]
@schbetsy @willbarton y'all are our helpers now! any thoughts on the questions I tagged Andy on above?

**Comment by wpears** [comment]
Seems like plenty of other fields in our models are nullable, so I'm assuming it's fine to make these nullable as well, change reflected in latest commit.

Something that I think would be the best possible UX would be if categories, tags(listed as "topics" in the template), and date_filed were settable from the metadata pane but whose values were bound to the same underlying variables in the configuration pane. Not really sure what this would look like in code, and I wouldn't want to change the underlying AbstractFilterPage without good reason, so maybe the current regime (unique metadata fields set in the metadata tab and categories, tags, date_filed set in Configuration) is acceptable.

**Comment by chosak** [comment]
>  putting the fields that are in the new Metadata tab in Configuration is 1) technically acceptable and 2) more usable for editors

Placement of fields into tabs is arbitrary from a technical POV; any field can go anywhere (except maybe the title field, which comes from the base Page class). In terms of editor usability, I think it'd be better UX to have a separate tab instead of putting these into the Configuration tab. See also the "Wagtail fundamentals" page in Hubcap, which says:

> To make it easier for users to edit specific parts of a page, the Wagtail page editing interface provides a tabbed layout that groups similar page content and settings together. For consumerfinance.gov, most pages are configured with three tabs following this general setup:

> - General content: the main content area of the page
> -Sidebar / Footer / "Sidefoot": the secondary content area of the page, appearing as a sidebar or page footer depending on the page layout and browser width
> -Configuration: settings controlling page behavior and other information that does not visually appear on the page
>
> Some page types use an alternate set of tabs to organize content; for example, EventPages have separate tabs about an event's venue and agenda. In general, though, the last tab is always used for page configuration.

In terms of nullability,

> Seems like plenty of other fields in our models are nullable, so I'm assuming it's fine to make these nullable as well

If a field is required, it should be `null=False`, and, if a text field, also `blank=False`. Were you running into a specific issue with doing this to make fields required?

**Comment by wpears** [comment]
>If a field is required, it should be null=False, and, if a text field, also blank=False. Were you running into a specific issue with doing this to make fields required?

I believe I was getting errors around providing a default value with `blank=False` and `null=False`. AFAICT, the `blank=False` bit is the only part necessary to make a `CharField` required, but I had to set `null=True` in order to do not set default values for these required fields.

It's possible that this is related to some intermediate database state where I've added data without required fields and so the migration is choking on that once I try to switch it to required. Does this sound likely?

**Comment by chosak** [comment]
> It's possible that this is related to some intermediate database state where I've added data without required fields and so the migration is choking on that once I try to switch it to required. Does this sound likely?

Yes, this happens when you first have a model state with an optional field and then make it non-optional. Since these models haven't been merged/deployed yet, a good strategy is to delete migrations from previous commits and recreate a new one.

**Comment by schbetsy** [comment]
Superseded by #5523

**Pull request closed without merging**
