### PR TITLE
Remove comments from the site

### PR DESCRIPTION
**Pull request by kurtw**
Removing Disqus. 

## Test

- Check blog posts and make sure they don't render comments

@richaagarwal 
@kave

### CODE REVIEW

**Comment by schaferjh** [comment]
Ahem. We love comments. :smile: We would like a commenting solution that abides by our information sharing and privacy policies and this one no longer does.

**Comment by kurtw** [comment]
Thanks for the info!

**Comment by richaagarwal** [comment]
Looks good but I would update `CHANGELOG.md`, especially for this one

**Comment by jimmynotjim** [comment]
Whoa, Disqus changed their policies? Glad we caught that :+1:

**Comment by Scotchester** [comment]
Don't we have a negotiated TOS with them?

**Comment by richaagarwal** [comment]
:+1: if that wasn't clear from my comment earlier :)

**Comment by schaferjh** [comment]
@Scotchester it expired. We'll be following up post-launch and hopefully Disqus or another service will be back soon!

**Pull request merged**
