### PR TITLE
General code style cleanup

### PR DESCRIPTION
**Pull request by anselmbradford**
General code style cleanup from beta PR https://github.com/cfpb/cfgov-refresh/pull/1041.

## Changes

- Fixes grammar.
- Normalizes quotes in python.
- Normalizes key-spacing in JS.
- Normalizes notes in readmes.
- Normalizes some stacked CSS classes.

## Review

- @jimmynotjim 
- @KimberlyMunoz 
- @sebworks 
- @kurtw 
- @kave

### CODE REVIEW

**Comment by sebworks** [comment]
:+1:

**Comment by jimmynotjim** [comment]
:

**Comment by anselmbradford** [comment]
Can I get one bewd +1?

**Comment by anselmbradford** [comment]
cc @kurtw @kave @rosskarchner

**Comment by kurtw** [comment]
:+1:

**Comment by kave** [comment]
:+1:

**Pull request merged**
