### PR TITLE
Replaced missing string_score library

### PR DESCRIPTION
**Pull request by jimmynotjim**
Fixes an filtering issue on /contact-us due to string_score being missing

## Additions

- adds string_score.js to `browser` object in package.json

## Removals

- None

## Changes

- requires string_score.sj in type-and-filter.js

## Testing

- navigate to `/contact-us` and utilize the offices filter

## Review

- @sebworks 
- @anselmbradford 
- @KimberlyMunoz 

## Preview

None

[Preview this PR without the whitespace changes](?w=0)

## Notes

- string_score.js was missed in #499 causing the Contact Us filter to throw errors

### CODE REVIEW

**Comment by anselmbradford** [comment]
:+1:

**Comment by jimmynotjim** [comment]
@dpford what's the likelihood we can get an extra beta deployment in next monday if we open a PR this week?

**Comment by anselmbradford** [comment]
Could add an entry to the `Fixed` section in the changelog.

**Comment by jimmynotjim** [comment]
I'll add it to the changelog before merging

**Comment by KimberlyMunoz** [comment]
Looks good to me.

**Comment by jimmynotjim** [comment]
Before I merge, are any of the other libraries in `/vendor` needing to be added to `package.json` and required in the appropriate modules/routes?

**Comment by anselmbradford** [comment]
I don't _think_ so. 

The pages that are using the slick-carousel are looking for the sourcemap `slick.css.map`, but that should only be showing up in the dev console, so should be safe to ignore for now.

**Comment by anselmbradford** [comment]
I found an issue with the slick carousel at mobile sizes, but it doesn't appear to be a package.json issue, so I'll fix separately.

**Comment by dpford** [comment]
@jimmynotjim highly likely

**Comment by jimmynotjim** [comment]
Squashed and merging.

@anselmbradford does that fix need to go to beta as well? Should I wait to open a new refresh -> beta PR?

**Comment by anselmbradford** [comment]
@jimmynotjim I think it's fine to wait till the next update cycle. The issue appears to be that since JS is still running on all pages, the slick carousel is throwing `Uncaught TypeError: Cannot read property '$slides' of null` at mobile sizes, except on `/the-bureau/bureau-structure/index.html` where it has the HTML it's looking for. However, the functionality of the carousels appears fine. Mobile users won't see the console error. But it should be fixed regardless and I'm working on it.

**Pull request merged**
