### PR TITLE
Move Housing Counselor tool from legacy app into its own app

### PR DESCRIPTION
**Pull request by schbetsy**
Create a project within cfgov-refresh to encapsulate all code related to the Find A Housing Counselor tool. This should not change anything about the look or functionality of FAHC; it is only a back-end organizational refactor.

I'm definitely open to feedback on naming conventions, file structure, and anything else.

**Note:** I'm opening this PR (from the cfpb fork) to replace #4618 (which came from my fork) so it's easier for @anselmbradford to add commits and collaborate.

## Changes

- Move all HUD/Housing Counselor code from `legacy` into a new app called `housing_counselor`

## Todos

- [x] ~~@anselmbradford will move static files associated with the HUD tool to the appropriate place. The files listed below will go in `cfgov/unprocessed/apps/find-a-housing-counselor/`, and their built versions in `cfgov/static_built/apps/find-a-housing-counselor`~~ EDIT: The files were actually outdated and unused, so I deleted them.
- [x] Manually test the management commands for this code to ensure they still work as intended. EDIT: I did a little manual testing, but I don't have the correct s3 access to do a full test. I think we should merge and watch for failures in the management tasks.

## Checklist

- [x] PR has an informative and human-readable title
- [x] Changes are limited to a single goal (no scope creep)
- [ ] Code can be automatically merged (no conflicts)
- [ ] Code follows the standards laid out in the [development playbook](https://github.com/cfpb/development)
- [ ] Passes all existing automated tests
- [x] Any _change_ in functionality is tested
- [x] New functions are documented (with a description, list of inputs, and expected output)
- [ ] Placeholder code is flagged / future todos are captured in comments
- [ ] Visually tested in supported browsers and devices (see checklist below :point_down:)
- [ ] Project documentation has been updated
- [ ] Reviewers requested with the [Reviewers tool](https://help.github.com/articles/requesting-a-pull-request-review/) :arrow_right:

### Browsers

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Internet Explorer 8, 9, 10, and 11
- [ ] Edge
- [ ] iOS Safari
- [ ] Chrome for Android

### Accessibility

- [ ] Keyboard friendly
- [ ] Screen reader friendly

### Other

- [ ] Is useable without CSS
- [ ] Is useable without JS
- [ ] Flexible from small to large screens
- [ ] No linting errors or warnings
- [ ] JavaScript tests are passing

### CODE REVIEW

**Comment by chosak** [comment]
Unfortunately we currently have a whitelist (undocumented) of our "first party" apps for isort, maintained [here](https://github.com/cfpb/cfgov-refresh/blob/master/.isort.cfg#L12). Any new app should probably go into this list, unless there's a nicer way to avoid needing to do this? (ping @willbarton)

**Comment by willbarton** [comment]
@chosak @schbetsy I don't think there's a better way to do it if we want to maintain the distinction between our first-party apps and others.

**Comment by schbetsy** [comment]
@anselmbradford Turns out the styles in `/nemo/` for this tool weren't even being used. All of the actual styles for the housing counselor page are in `housing_counselor/static/hud/` now. I deleted the following, and it seems to be working as usual:
  - `cfgov/legacy/static/nemo/_/c/hud-hca-api-pdf-style.css`
  - `cfgov/legacy/static/nemo/_/c/hud-hca-api-print-style.css`
  - `cfgov/legacy/static/nemo/_/c/styles.css` lines 2476 - 2733

**Comment by schbetsy** [comment]
Thanks @chosak and @willbarton. Good to know. I made that change in fbe3265.

**Pull request merged**
