### PR TITLE
Set up logging locally

### PR DESCRIPTION
**Pull request by richaagarwal**
So that we don't have to use print statements.  I updated `archive_events` as an example, although I don't actually think we use it anymore. 

Run `python cfgov/manage.py runscript archive_events` to see the logging in action.

@cfpb/cfgov-backends

### CODE REVIEW

**Comment by rosskarchner** [comment]
Thanks for figuring this out! 👍 

I would have expected to see the "No events to archive found...." message, but that's probably unrelated to your work here.

**Comment by grapesmoker** [comment]
Where does the log information get logged to?

**Comment by rosskarchner** [comment]
@grapesmoker the console-- which makes sense for local users, at least.

**Comment by Scotchester** [comment]
🚨 n00b alert 🚨 

If it's just logging to the console, why is it better than using `print` statements?

**Comment by rosskarchner** [comment]
In deployment, logging can be configured to go elsewhere

**Comment by Scotchester** [comment]
Ahah.

**Comment by rosskarchner** [comment]
... and then, it's a settings change, the call to `logger.info` serves both purposes

**Comment by chosak** [comment]
:+1:

**Pull request merged**
