### PR TITLE
Adding Webpack stats option to gulp build script build flow

### PR DESCRIPTION
**Pull request by sebworks**
## Changes

- Modified code to add Webpack stats option
- Modified code to rename config variables to be consistent with other files. 

## Testing

1. Run `gulp scripts` and ensure there are no errors.
2. Run `gulp scripts:ondemand` and ensure there are no errors.
3. Run `gulp scripts:ondemand --stats` and you should see some stats about each chunk. There are plenty available [here](https://webpack.js.org/configuration/stats/#stats), but I just chose some I thought would be relevant. 

## Checklist

* [ ] PR has an informative and human-readable title
* [ ] Changes are limited to a single goal (no scope creep)
* [ ] Code can be automatically merged (no conflicts)
* [ ] Code follows the standards laid out in the [development playbook](https://github.com/cfpb/development)
* [ ] Passes all existing automated tests
* [ ] Any *change* in functionality is tested
* [ ] New functions are documented (with a description, list of inputs, and expected output)
* [ ] Placeholder code is flagged
* [ ] Visually tested in supported browsers and devices
* [ ] Project documentation has been updated
* [ ] Reviewers requested with the [Reviewer tool](https://help.github.com/articles/about-pull-request-reviews/) :arrow_right:

### CODE REVIEW

**Comment by anselmbradford** [comment]
Works as advertised! What does this show us? E.g. this is all the sources that go into header.js?
screen shot 2017-11-06 at 1 43 32 pm

We should probably add documentation in the readme that this is available and what it's showing?

**Comment by sebworks** [comment]
> Works as advertised! What does this show us? E.g. this is all the sources that go into header.js?

It shows the following info about each module: 
- Module name
- Module size
- Other chunks where the module is used (`{2}, {3}, {5}, etc..`).

**Comment by sebworks** [comment]
> We should probably add documentation in the readme that this is available and what it's showing?

Yeah, I'll add that info on this PR.

**Comment by jimmynotjim** [comment]
Are we sure the ondemand task is being used outside of the nonresponsive header? Scott and I were working on improving the speed of these tasks and noticed that the ondemand files that are loaded come from `/routes` not `/atomic`.

**Comment by sebworks** [comment]
Closing this while I explore a better option.

**Pull request closed without merging**
