### PR TITLE
Stop crawlers from trying filter combinations

### PR DESCRIPTION
**Pull request by rosskarchner**
This came out of the investigation of crawler errors (GHE 1015). It doesn't really provide us with any benefit for Google, etc to crawl every filter combination. Every page is accessible by paginating through the primary set of results.

## Additions

- add the line `Disallow: *form-id=*` to robots.txt

## Checklist

* [ ] PR has an informative and human-readable title
* [ ] Changes are limited to a single goal (no scope creep)
* [ ] Code can be automatically merged (no conflicts)
* [ ] Code follows the standards laid out in the [development playbook](https://github.com/cfpb/development)
* [ ] Passes all existing automated tests
* [ ] New functions include new tests
* [ ] New functions are documented (with a description, list of inputs, and expected output)
* [ ] Placeholder code is flagged
* [ ] Visually tested in supported browsers and devices
* [ ] Project documentation has been updated
* [ ] Reviewers requested with the [Assignee tool](https://help.github.com/articles/assigning-issues-and-pull-requests-to-other-github-users/) :arrow_right:

### CODE REVIEW

**Comment by chosak** [comment]
Unfortunately the robots.txt standard [doesn't seem to support](http://www.robotstxt.org/robotstxt.html) use of wildcards like this:

> Note also that globbing and regular expression are not supported in either the User-agent or Disallow lines. The '\*' in the User-agent field is a special value meaning "any robot". Specifically, you cannot have lines like "User-agent: *bot*", "Disallow: /tmp/*" or "Disallow: *.gif".

**Comment by chosak** [comment]
Although then again [Wikipedia says](https://en.wikipedia.org/wiki/Robots_exclusion_standard#Universal_.22.2A.22_match):

> The Robot Exclusion Standard does not mention anything about the "*" character in the Disallow: statement. Some crawlers like Googlebot recognize strings containing "*", while MSNbot and Teoma interpret it in different ways. _[citation needed]_

So worth a try?

**Comment by rosskarchner** [comment]
There are definitely some crawlers in the wild that don't support it-- but I think the big ones do?

**Comment by rosskarchner** [comment]
According to https://developers.google.com/search/reference/robots_txt#allow

"Google, Bing, Yahoo, and Ask" support it

**Comment by chosak** [comment]
@rosskarchner nice find! :+1:

**Pull request merged**
