### PR TITLE
Fixes linting errors

### PR DESCRIPTION
**Pull request by anselmbradford**
Fixes JS linting errors

## Changes

- Fixes several minor linting errors (max-len mostly). Adds `BASE_JS_PATH` constant where applicable.

## Testing

- No change other than less linting warnings.

## Review

- @jimmynotjim 
- @KimberlyMunoz 
- @sebworks

### CODE REVIEW

**Comment by jimmynotjim** [comment]
:+1:

**Comment by jimmynotjim** [comment]
Sorry, should have waited to finish what I was doing and run it locally. I'm getting line length warnings on `L:14` and `L:22` of `browse-basic/index.js`

**Comment by anselmbradford** [comment]
> Sorry, should have waited to finish what I was doing and run it locally. I'm getting line length warnings on L:14 and L:22 of browse-basic/index.js

Yeah saw that too, but since that prototype page will be disappearing I left it as is.

**Comment by sebworks** [comment]
Instead of using `BASE_JS_PATH` how about creating a resolver module?

**Comment by jimmynotjim** [comment]
> since that prototype page will be disappearing I left it as is.

But you updated that index file here -> https://github.com/cfpb/cfgov-refresh/pull/1189/files#diff-ab5532b35635d4f7336eda8c7e4b7b34R19

Might as well do it so that if this gets copied to it's final home, we're not adding more warnings.

**Comment by anselmbradford** [comment]
> Instead of using BASE_JS_PATH how about creating a resolver module?

Like as a npm module or as a js module in the test directory (otherwise the resolver module itself would have the same path resolution issue)? Any idea if `path` do what I'm trying to do here?

**Comment by anselmbradford** [comment]
> Might as well do it so that if this gets copied to it's final home, we're not adding more warnings.
Alright, fine! :-)

Fixed in https://github.com/cfpb/cfgov-refresh/commit/4d33e5597f8a3966a7fc36c9cba9b8bd0fd70fd9

**Comment by sebworks** [comment]
Are you referring to https://nodejs.org/api/path.html#path_path_relative_from_to?

**Comment by anselmbradford** [comment]
@sebworks I'm not seeing a unified test entry point for a global path resolver function. JS is used in both the acceptance tests (protractor) and the unit tests (not-protractor) so the only layer that knows about those is gulp and that seems like too far up to be defining functions those use. I think a npm module is the way to go, but that would have to happen outside of this PR.

**Comment by sebworks** [comment]
sounds good :+1:

**Comment by jimmynotjim** [comment]
:+1:

**Pull request merged**
