### PR TITLE
DF-2255 - adds accessibility page

### PR DESCRIPTION
**Pull request by anselmbradford**
Adds accessibility page.

## Additions

- Adds link to accessibility page in footer.
- Adds acceptance tests for accessibility page in form of offices pattern.

## Testing

- Reindex sheer, visit homepage, navigate to footer. Find `Accessibility` link and open to reach page. 
- Run tests with `gulp test`

## Review

- @KimberlyMunoz 
- @sebworks 

## Screenshots

screen shot 2015-08-03 at 3 57 07 pm

## Todos

- Add tests for subpages.

### CODE REVIEW

**Comment by KimberlyMunoz** [comment]
Can we check with @sarahsimpson09 tomorrow that `//` needs all those detailed instructions ~AND~ a form? This could be split into another PR, but would have to get resolved before that JIRA task gets added to the completed column.

image

**Comment by anselmbradford** [comment]
> Can we check with @sarahsimpson09 tomorrow that sub-pages/file-a-formal-accessibility-complaint-or-website-feedback/ needs all those detailed instructions ~AND~ a form? This could be split into another PR, but would have to get resolved before that JIRA task gets added to the completed column.

Sure, I also want to add tests for the sub-pages, but in a separate PR.

**Comment by sarahsimpson09** [comment]
Yup, unfortunately we do need those instructions, since we're asking people to use the same form for two similar, but different, submissions. If there's a better way to organize the "Complaint filing process" instructions that go on top of the form, that would be great. Maybe we put the form after step 2 and add steps 3-5 below the form? That might look strange to break up the directions like that, though...

**Comment by KimberlyMunoz** [comment]
gulp test just passed. :+1: for this PR.

**Comment by KimberlyMunoz** [comment]
Hey @sarahsimpson09, it probably wouldn't be easy to put the form halfway through step 2 and 3. Why couldn't we do two forms and have this page link to the form that needs to be filled out. Right now, it seems like a lot of reading that a screenreader would have to do in order to submit a complaint.

**Comment by sarahsimpson09** [comment]
Ok, I like that idea.

**Comment by KimberlyMunoz** [comment]
:icecream: Let's talk about it at tomorrow's working session.

**Pull request merged**
