### PR TITLE
Add settings for picard-jenkins integration

### PR DESCRIPTION
**Pull request by m3brown**
Short description explaining the high-level reason for the pull request

## Additions

- Optional settings for transitioning picard from shell to jenkins

## Removals

-

## Changes

-

## Testing

- manually tested on one of the new web servers (http://awswebl04.cfpbext.local/tasks/)

## Notes

-

## Todos

- This change will have no effect until the appropriate environment variables are added

## Checklist

* [x] Changes are limited to a single goal (no scope creep)
* [x] Code can be automatically merged (no conflicts)
* [ ] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [ ] Passes all existing automated tests
* [ ] New functions include new tests
* [ ] New functions are documented (with a description, list of inputs, and expected output)
* [ ] Placeholder code is flagged
* [ ] Visually tested in supported browsers and devices
* [x] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)
* [ ] Reviewers requested with the [Assignee tool](https://help.github.com/articles/assigning-issues-and-pull-requests-to-other-github-users/) :arrow_right:

### CODE REVIEW

**Comment by rosskarchner** [comment]
This looks fine to me 👍

**Comment by Scotchester** [comment]
Please for the love of God wait to merge until Travis finishes running and I can merge my video player PR :)

**Comment by Scotchester** [comment]
P.S.: Don't forget to update the change log, but wait until just before merging, to reduce possible conflicts.

**Comment by m3brown** [comment]
Thanks for the reminder on the changelog

**Comment by Scotchester** [comment]
Gahhhh!

> wait until just before merging

😁 

Pull down from master to get the correct change log and move your line into the Unreleased section.

**Comment by m3brown** [comment]
Done!

**Comment by m3brown** [comment]
Update: I tagged the latest updates to Picard and decided to bring that into this PR as they're so closely related.

The 1.5.3 release of picard was primarily to add basic auth support for the Jenkins task runner.  Since picard is currently set to 'shell' task runner, this upgrade will have no immediate impact on the existing servers.

**Comment by m3brown** [comment]
Another update: please don't merge, I need to make another change in response to a changing requirement.

**Comment by m3brown** [comment]
@rosskarchner @Scotchester I'm bumping up one more version of Picard (1.5.4) which added the ability to override the jenkins from (CONTENT) and to (PRODUCTION) environments.  This will allow us to test, for example, from build1 to build2 in dev.

Again, all of this has no impact on the current production system until we flip the PICARD_TASK_RUNNER to 'jenkins'.  At this point I'm fairly certain that my changes are complete, let me know if there's anything else you require to get this merged.

**Comment by Scotchester** [comment]
I have no opinion about the substantive changes in this PR 😁

**Comment by m3brown** [comment]
In that case I'll go ahead and merge before the tests have completed :trollface:

**Comment by m3brown** [comment]
@willbarton done!

**Pull request merged**
