### PR TITLE
Fixing CFPB banner

### LINKED ISSUE #951: CSS banner is mangled after minification
The CSS banner should be built so that it survives minification. Possibly it should be added post-minifying.

screen shot 2015-09-03 at 2 59 57 pm

### PR DESCRIPTION
**Pull request by KimberlyMunoz**
For some reason the CFPB banner is being mangled. [see here](http://beta.consumerfinance.gov/static/css/main.css)

This replaces the ticks with curly quotes to see if we can prevent character replacement from happening.

Fixes #951

## Review
- @anselmbradford 
- @Scotchester

### CODE REVIEW

**Comment by sebworks** [comment]
:+1:

**Comment by Scotchester** [comment]
Does this work for you locally?

**Comment by KimberlyMunoz** [comment]
They both work locally. It's only when we deploy that the banner gets warped.

**Comment by Scotchester** [comment]
Well, that's annoying. Looks good for now. :+1:

**Pull request merged**
