### PR TITLE
Updated request a speaker w/ static content

### PR DESCRIPTION
**Pull request by jimmynotjim**
Updated request a speaker template w/ static content instead of relying on the CMS content

## Additions

- None

## Removals

- None

## Changes

- Replaced placeholder content with true content

## Testing

- navigate to `/events/request-a-speaker/`

## Review

- @KimberlyMunoz 
- @anselmbradford 
- @sebworks 

## Preview

screen shot 2015-06-12 at 3 58 31 pm

[Preview this PR without the whitespace changes](?w=0)

## Notes

- RaS is not related to an office, using static content until further notice
- All content copied from RaS sub-page and FAQ on WordPress

### CODE REVIEW

**Comment by anselmbradford** [comment]
:+1: The spacing looks a little weird in the first half of the page, but that's just due to the length of the content.

**Comment by KimberlyMunoz** [comment]
Minor: but it looks like there should be a little bit of whitespace between "Don't see your question here..." and the expandable faqs. 

[ghe]/flapjack/event/blob/gh-pages/design/Request_a_speaker_page/Request_a_speaker_JS_CLEARED-01.png

**Comment by jimmynotjim** [comment]
@KimberlyMunoz I'm going to push off the spacing thing to @sebworks FAQ macro. Once he's finished with that, I'll submit another PR updating the Event RaS FAQ.

**Comment by KimberlyMunoz** [comment]
:+1:

**Comment by sebworks** [comment]
:+1:

**Pull request merged**
