### PR TITLE
Converted all references to dept dir, removed fuchs assets

### PR DESCRIPTION
**Pull request by jimmynotjim**
Converted all references to dept dir, removed fuchs assets

## Additions

- David Silberman's assets

## Removals

- Meredith Fuchs assets

## Changes

- Converted references and asset urls from Fuchs to Silberman

## Testing

Navigate to the following

- `/about-us/`
- `/the-bureau/`
- `/the-bureau/about-deputy-director/`
- `/the-bureau/about-director/`
- `/the-bureau/leadership-calendar/`
- `/newsroom/press-resources/`

## Review

- @sebworks 
- @anselmbradford 
- @KimberlyMunoz 

## Screenshots

screen shot 2016-02-29 at 1 06 59 pm

## Checklist

* [ ] Changes are limited to a single goal (no scope creep)
* [ ] Code can be automatically merged (no conflicts)
* [ ] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [ ] Passes all existing automated tests
* [ ] New functions include new tests
* [ ] New functions are documented (with a description, list of inputs, and expected output)
* [ ] Placeholder code is flagged
* [ ] Visually tested in supported browsers and devices
* [ ] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)

### CODE REVIEW

**Comment by sebworks** [comment]
I think there is another item in : https://github.com/cfpb/cfgov-refresh/blob/e6a99dd9990697da950b22d76e76e4ce6dbc7065/cfgov/v1/models/ref.py

**Comment by sebworks** [comment]
:+1:

**Comment by jimmynotjim** [comment]
Thanks for catching that @sebworks, updated.

**Comment by anselmbradford** [comment]
:+1:

**Pull request merged**
