### PR TITLE
removed depreciated sheer index processors/mappings

### PR DESCRIPTION
**Pull request by kave**
## Testing

- Run sheer index, notice these items no longer index

## Review

- @kurtw @rosskarchner @richaagarwal

### CODE REVIEW

**Comment by rosskarchner** [comment]
💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯

**Comment by anselmbradford** [comment]
This is like a technical debt massacre

**Comment by richaagarwal** [comment]
👍 
lol @ above

this means we won't need to do any wordpress imports going forward, right?

**Comment by schaferjh** [comment]
> This is like a technical debt massacre

the best kind of massacre?

**Comment by rosskarchner** [comment]
We still need processors for the leadership calendar, those three odd pages, Owning a Home and FinEd Resources (the later two don't live in v1)

**Comment by kave** [comment]
@rosskarchner yea i'll need to go through the rest of these processors again and see whats still really necessary.

**Pull request merged**
