### PR TITLE
Removes unused spanish language templates

### PR DESCRIPTION
**Pull request by wpears**
## Removals

- Old spanish langage templates. These now live in the CMS

## Testing

1. Navigate to localhost:8000/es
2. Navigate to whatever spanish subpages you like (http://localhost:8000/es/comprar-casa/, http://localhost:8000/es/quienes-somos/, etc)

These pages should exist and be formatted correctly.

### CODE REVIEW

**Comment by virginiacc** [comment]
One thing I'm wondering -- could `base-common.html` be merged back into `base.html` now that it's no longer needed for `es-base.html`?

**Comment by wpears** [comment]
Probably! I'll open a new issue for that!

**Comment by wpears** [comment]
https://github.com/cfpb/cfgov-refresh/issues/5132

**Comment by anselmbradford** [comment]
Did this fix https://github.cfpb.gov/CFGOV/platform/issues/2877 ?

**Comment by Scotchester** [comment]
> Did this fix https://GHE/CFGOV/platform/issues/2877 ?

No, but https://github.com/cfpb/cfgov-refresh/pull/5127 did.

**Pull request merged**
