### PR TITLE
Add working with tribal governments link

### PR DESCRIPTION
**Pull request by KimberlyMunoz**
## Additions

- Add working with tribal governments link to the footer

## Testing

- Check out the footer.

## Review

- @anselmbradford 
- @sebworks 
- @jimmynotjim 
- @schaferjh 

## Screenshots

image

## Checklist

* [ ] Changes are limited to a single goal (no scope creep)
* [ ] Code can be automatically merged (no conflicts)
* [ ] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [ ] Passes all existing automated tests
* [ ] New functions include new tests
* [ ] New functions are documented (with a description, list of inputs, and expected output)
* [ ] Placeholder code is flagged
* [ ] Visually tested in supported browsers and devices
* [ ] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)

### CODE REVIEW

**Comment by sebworks** [comment]
:+1:

**Comment by schaferjh** [comment]
I may have failed to specify in the task, but the link should simply read "Tribal"

**Comment by jimmynotjim** [comment]
:+1: after you've address Jess's comment.

**Comment by KimberlyMunoz** [comment]
That addresses the only concern I had about that line being too long. Merging.

**Pull request merged**
