### PR TITLE
Run optional public apps as part of Travis testing

### PR DESCRIPTION
**Pull request by chosak**
This PR installs public satellite apps in `requirements/optional-public.txt` and includes their tests as part of Travis testing.

## Changes

- The `travis` tox environment installs `requirements/optional-public.txt` before testing.

## Testing

- `tox -e travis`

## Todos

- Fix all of the tests so that they work within the context of this repository.

## Checklist

* [X] Changes are limited to a single goal (no scope creep)
* [X] Code can be automatically merged (no conflicts)
* [ ] Passes all existing automated tests
* [X] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)
* [ ] Reviewers requested with the [Assignee tool](https://help.github.com/articles/assigning-issues-and-pull-requests-to-other-github-users/) :arrow_right:

### CODE REVIEW

**Comment by willbarton** [comment]
excited minions

**Comment by chosak** [comment]
Unfortunately it looks like some of the satellite apps have custom test setups that aren't reflected in how this repository runs tests:

```sh
Ran 765 tests in 40.508s
FAILED (failures=1, errors=10)
```

See [Travis log](https://travis-ci.org/cfpb/cfgov-refresh/builds/195269582) for more details on which tests fail.

**Comment by higs4281** [comment]
> some of the satellite apps

I can work on the retirement and college-costs tests that aren't flying.

**Comment by chosak** [comment]
I'd like to close this PR as we're moving in the direction of testing both public/private optional apps as part of the larger deployment process. Any objections? @willbarton @higs4281

**Comment by higs4281** [comment]
no objection here.

**Comment by willbarton** [comment]
Sounds good to me.

**Pull request closed without merging**
