### PR TITLE
Local fonts proposal

### PR DESCRIPTION
**Pull request by rosskarchner**
This implements (a slight variation) on what I proposed here:
https://github.com/cfpb/capital-framework/pull/672#issuecomment-342245169

a new directory is added to the root of the repository, called static.in. Any subdirectory of *that* is added to Django's [STATICFILES_DIRS](https://docs.djangoproject.com/en/1.11/ref/settings/#std:setting-STATICFILES_DIRS).

So, to test this, go in to static.in and git clone GHE/CFGOV/cfgov-fonts/ into that dir, start (or restart) your local dev server, and note that you should be able to reference fonts at URL's like:

http://localhost:8000/static/fonts/181c847e-cdbc-43d5-ae14-03a81c8953b4.woff

## Additions

- a 'static.in' directory

## Changes

- every subdirectory of static.in is added to STATICFILES_DIRS

## Checklist

* [ ] PR has an informative and human-readable title
* [ ] Changes are limited to a single goal (no scope creep)
* [ ] Code can be automatically merged (no conflicts)
* [ ] Code follows the standards laid out in the [development playbook](https://github.com/cfpb/development)
* [ ] Passes all existing automated tests
* [ ] Any *change* in functionality is tested
* [ ] New functions are documented (with a description, list of inputs, and expected output)
* [ ] Placeholder code is flagged
* [ ] Visually tested in supported browsers and devices
* [ ] Project documentation has been updated
* [ ] Reviewers requested with the [Reviewer tool](https://help.github.com/articles/about-pull-request-reviews/) :arrow_right:

### CODE REVIEW

**Comment by anselmbradford** [comment]
Works as described. Why the name `static.in`? Is that standard?

**Comment by anselmbradford** [comment]
I restarted Travis to see if that's a transient issue.

**Comment by rosskarchner** [comment]
I'm not sure "standard" is the word, but it mirrors a similarly named directory provided by [drama free django](https://github.com/cfpb/drama-free-django/).

I'm open to other ideas!

**Comment by anselmbradford** [comment]
Looks like this is actually breaking Travis acceptance tests.

**Comment by rosskarchner** [comment]
OK, I'll look into it

**Comment by Scotchester** [comment]
Hey, the tests are passing again! I'll give this a quick local test run today to confirm.

**Comment by rosskarchner** [comment]
Yeah, I made a silly mistake that broken all *other* static files.

**Comment by Scotchester** [comment]
This is working great for me locally!

**Pull request merged**
