### PR TITLE
Removing Bower

### PR DESCRIPTION
**Pull request by sebworks**
Removing Bower in a move towards simplifying the front-end build process.

## Changes

- Modified `README.md`, `.travis.yml`,  `ansible/vars/app.yml`, `docs/front-end-build.md` to remove references  to Bower.

- Modified `frontend.sh` to remove Bower from the `frontend.sh` process.

- Modifed `gulp/config.js` to do the following:
 
  - Remove  unused assets:  the `/box-sizing-polyfill/boxsizing.htc` file didn't exist although it's being referenced in CSS file. Removed `/slick-carousel/slick/slick.css.map` as it's no longer being generated with `slick-carousel` version 1.6.  
  - Switch references from the `vendor` directory to the `node_modules` directory.

## Removals

- Removed `Bower.json` as it's no longer necessary.

## Testing

- Run `./frontend.sh`
- Verify that the necessary files are in your `static_built` directory.
- Browse the site; observe that there are no errors in the console and it operates as expected.

## Review

- @anselmbradford 
- @Scotchester 
- @jimmynotjim 
- @contolini 

## Notes

- `gulp copy` doesn't produce errors when the src files don't exist. 

## Checklist

* [ ] Changes are limited to a single goal (no scope creep)
* [ ] Code can be automatically merged (no conflicts)
* [ ] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [ ] Passes all existing automated tests
* [ ] New functions include new tests
* [ ] New functions are documented (with a description, list of inputs, and expected output)
* [ ] Placeholder code is flagged
* [ ] Visually tested in supported browsers and devices
* [ ] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)

### CODE REVIEW

**Comment by contolini** [comment]
Huh so we were just never using `boxsizing.htc`?

**Comment by sebworks** [comment]
> Huh so we were just never using boxsizing.htc?

We are but it wasn't being copied [over](https://github.com/cfpb/cfgov-refresh/blob/e0e0f874adb344f5afdd47a6404a7acdb5004478/cfgov/legacy/static/nemo/_/ccdb/ccdb-landing.css#L2300) because the file didn't exist.  I don't think it's still needed anyways.

**Comment by anselmbradford** [comment]
Yeah boxsizing is only needed for IE6/7 ... it should be removed from Capital Framework too IMO

**Comment by anselmbradford** [comment]
I vaguely recall looking into this before. The Slick API has changed in the version brought in via npm, so the Slick initialization code needs to be re-written in `/about-us/the-bureau/bureau-structure/`. As is it's broken at mobile size and there's `Uncaught TypeError: h.getSlick is not a function` error in the console. Try pulling in 1.3.7 from npm, but if I recall it's not a published release to npm unfortunately.

**Comment by contolini** [comment]
Seems like the main change is the removal of callbacks: https://github.com/kenwheeler/slick/#events

@anselmbradford @sebworks Yeah pinning it to 1.3.7 is probably the best bet. It looks like it's now on npm: https://registry.npmjs.org/slick-carousel

**Comment by sebworks** [comment]
ok, I'm going to remove `slick.js`. I'm going to swap it out for https://github.com/metafizzy/flickity.

**Comment by sebworks** [comment]
@anselmbradford @contolini, thanks for catching the API changes. I've adjusted the code to use the new API. Still searching for a decent slider which isn't huge. Hammertime might be a winner. https://rawgit.com/hammerjs/hammer.js/master/tests/manual/nested.html

**Comment by contolini** [comment]
👍 Works great!

**Comment by jimmynotjim** [comment]
You served us well Bower

taps

**Comment by sebworks** [comment]
> You served us well Bower

lol

**Comment by anselmbradford** [comment]
Should https://github.com/cfpb/cfgov-refresh/blob/master/.bowerrc be removed too?

**Comment by contolini** [comment]
@anselmbradford Yep

**Comment by sebworks** [comment]
Removed in #2368

**Pull request merged**
