### PR TITLE
282-fix-sourcemaps

### LINKED ISSUE #282: Fix Sourcemaps
Sourcemaps are broken/non-existent causing difficulty when tracking down style rules.

### PR DESCRIPTION
**Pull request by jimmynotjim**
Adds Sourcemaps and removes CSSMIN task

## Additions

- Creates sourcemap file (thinking this should be git ignored and devs just make sure they run grunt upon pulling from the repo, otherwise it's just another giant file in your diff)

## Removals

- CSSMIN from package.json and Gruntfile

## Changes

- Added sourcemap options to `less` task

## Testing

- fetch and run `grunt` or `grunt:cssdev`
- open project locally and inspect any elem
- check source file in upper right of style tab (should be a Less file)
- mindblown

tim-and-eric-mind-blown

## Review

Including all FEWDs because this could really be used Agency wide and it's worth a discussion (sorry if I forgot anyone):
- @anselmbradford 
- @sebworks 
- @Scotchester 
- @virginiacc 
- @sephcoster 
- @cfarm
- @kimberlymunoz
- @contolini
- @ascott1 
- @mistergone

## Preview

screen shot 2015-02-26 at 1 08 09 pm

## Notes

- Sourcemaps are incredibly important when tracking down styles in compiled less files
- CSSMIN and other minification tools remove the sourcemap reference from the css file
- Minification should really happen in the deployment process, not development process
- Fixes #282

### CODE REVIEW

**Comment by Scotchester** [comment]
This is a good step, but we need to make sure that we have minification up and running before we start deploying to our public beta site.

**Comment by jimmynotjim** [comment]
@Scotchester I'm not advocating we merge this until that happens. I wanted to start a discussion with a real world example rather than a general issue in the FEWD repo. Also couldn't help to nudge delivery team a bit ;)

**Comment by Scotchester** [comment]
Gottttcha. You should mention in the OP anytime you think a PR needs to wait on something before merging :)

**Comment by jimmynotjim** [comment]
Added to the notes. Will make sure to include it in the future.

**Comment by contolini** [comment]
:100:

Source maps are amazing. We should always be using them. Even in production so that curious visitors can inspect our code.

If I'm reading #282 correctly it sounds like you're having a hard time maintaining sourcemaps after minifying the compiled LESS. Have you tried the [`compress` flag](https://github.com/gruntjs/grunt-contrib-less#compress) with grunt-contrib-less instead of using cssmin?

**Comment by ascott1** [comment]
Nicely done @jimmynotjim. I just implemented sourcemaps for [regulations-site](https://github.com/cfpb/regulations-site/) (PR forthcoming), though we still need to work minification into deployment as well.

I'm using the less `compress` flag like @contolini suggested, which seems to minify without any issues.

**Comment by jimmynotjim** [comment]
Used `compress` option and everything is looking good. Thanks for the assist @contolini and @ascott1 

This should be ready for a review now.

**Comment by sebworks** [comment]
Great work on this @jimmynotjim. :100:

**Pull request merged**
