### PR TITLE
Root-relative flags

### PR DESCRIPTION
**Pull request by Scotchester**
As discussed with @anselmbradford, this PR sets the paths of the U.S. flag images to be root-relative. This allows sites that are relying on the on-demand versions of this CSS (such as my Sheer projects) to find those flag images in their canonical cfgov-refresh location, rather than having to add them to their static files, as well.

## Changes

- Changed `us-flag` image paths to be root-relative.

## Testing

1. Pull down this fork
2. Rebuild the CSS
3. Serve the site
4. Observe that the flag images still load

## Review

- @anselmbradford 
- @KimberlyMunoz 
- @sebworks  
- @jimmynotjim 

## Notes

- This would allow me to revert the last commit in cfpb/cfgov-sheer-templates#8, which would be great.

## Checklist

* [ ] Changes are limited to a single goal (no scope creep)
* [ ] Code can be automatically merged (no conflicts)
* [ ] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [ ] Passes all existing automated tests
* [ ] New functions include new tests
* [ ] New functions are documented (with a description, list of inputs, and expected output)
* [ ] Placeholder code is flagged
* [ ] Visually tested in supported browsers and devices
* [ ] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)

### CODE REVIEW

**Comment by anselmbradford** [comment]
LGTM :+1:

**Comment by sebworks** [comment]
:+1:

**Comment by Scotchester** [comment]
Thank you, gents. Just pushed a changelog update, as well.

**Comment by Scotchester** [comment]
I'll wait for Travis to finish before merging.

**Pull request merged**
