### PR TITLE
Adds mouseflow to connect-src

### PR DESCRIPTION
**Pull request by wpears**
See GHE/CFGOV/platform/issues/3061

### CODE REVIEW

**Comment by anselmbradford** [comment]
Are there any particular testing steps needed in this PR? It LGTM

**Comment by wpears** [comment]
Testing would be to checkout this branch, open it in latest Chrome, and ensure no mouseflow CSP errors occur by checking the console

**Comment by anselmbradford** [comment]
I see no mouseflow errors in this or master, seems fine to proactively add.

**Comment by wpears** [comment]
Hmm, looks to me like the mouseflow errors have vanished in the spooky Halloween spirit ^^;.  To not bloat the CSP, I'm just going to close this and will reopen if we encounter the CSP issue again.

**Comment by wpears** [comment]
Reopening re: GHE/CFGOV/platform/issues/3225

**Pull request merged**
