### PR TITLE
update front-end dependencies

### PR DESCRIPTION
**Pull request by ascott1**
This updates the minor and patch releases of all explicit front-end dependencies listed in `package.json` as well as declares `marked` as an explicit dependency.

### CODE REVIEW

**Comment by Scotchester** [comment]
This seems to only update axe-core, a subdependency of our protractor-accessibility-plugin dev dependency, from 2.5.0 to 2.6.1. What's the reason for doing this without updating protractor-accessibility-plugin?

**Comment by ascott1** [comment]
Ugh, npm. Commit incoming.

**Comment by ascott1** [comment]
@Scotchester @sebworks can you pull this down and review it?

**Comment by ascott1** [comment]
Ha, thanks @jimmynotjim!

**Pull request merged**
