### PR TITLE
DF 1965 1969 Breadcrumbs

### PR DESCRIPTION
**Pull request by jimmynotjim**
Adds markup and conditioning for breadcrumbs on sub-pages

## Additions

- Breadcrumb macro to create the markup
- Breadcrumb styles
- New `content__half-top-on-desk` class to reduce the padding when breadcrumbs are above the sidebar/content

## Removals

- None

## Changes

- Adds `breadcrumb_items` array to sub-pages
- Conditionally adds breadcrumbs to `pre_content` block
- Conditionally adds `content__half-top-on-desk` to sidebar and content blocks if a breadcrumb exists

## Testing

- navigate to `/sub-pages/plain-writing-act/`

## Review

- @sebworks 
- @anselmbradford 
- @KimberlyMunoz 

## Preview

screen shot 2015-06-12 at 4 18 55 pm

[Preview this PR without the whitespace changes](?w=0)

## Notes

- Side nav below is making the breadcrumb look mis-aligned, but it is correct. May want to consider moving the side-nav back to the left and using `outline` instead of border for the green lines

### CODE REVIEW

**Comment by Scotchester** [comment]
I think you attached the wrong image.

**Comment by jimmynotjim** [comment]
Whoops :D

**Comment by Scotchester** [comment]
Yeah, that's what I thought your note was getting at.  There are discussions underway among designers to recommend bringing the left edge of the sidenav text in line with the left edge of the logo/topnav (and now breadcrumbs), pushing the green lines (at the top level of the sidenav) into the margin on the left. I'm currently implementing it on the FinEd Resources section.

**Comment by KimberlyMunoz** [comment]
Are these breadcrumbs supposed to be on all "sub-pages", or just the ones called `/sub-page/`? None of the subpages under about have them. ex: `/budget/strategic-plan/`.

**Comment by jimmynotjim** [comment]
Just `sub-page` for now as an example. Originally @schaferjh suggested putting them on the Plain Writing sub-pages, but since all sub-pages are together, it's on all of them :) Eventually, the nav items should be set through the backend, and we should stop adding all these static nav arrays.

**Comment by jimmynotjim** [comment]
@Scotchester that'll give the nav text some room to breath as well. Currently at some mid-sizes, the text gets so tight it's hurting readability.

**Comment by KimberlyMunoz** [comment]
The mobile styles look a little off without any separation.

image

Here's where design landed on how the mobile breadcrumbs should look. [ghe]/flapjack/global/issues/21 I'm really not sure about their suggestion for longer breadcrumbs; I imagine the implementation would cause issues on older, slower phones, but :no_mouth:.

**Comment by jimmynotjim** [comment]
@KimberlyMunoz that's the fault of changes to the "in this section" nav, not the breadcrumbs. I'll open an issue about it

**Comment by KimberlyMunoz** [comment]
:+1:

**Comment by sebworks** [comment]
:+1:

**Comment by jimmynotjim** [comment]
@Scotchester do you have something I can look at? Going to try and implement that here as well (based on a go-ahead by @duelj)

**Pull request merged**
