### PR TITLE
Add Wand for animated gif handling

### PR DESCRIPTION
**Pull request by kurtw**
Animated gifs are supported for use in Wagtail, but you must follow Wand's [installation instructions](http://docs.wand-py.org/en/0.4.2/guide/install.html) to get it working.

## Additions

- Wand

## Testing

- go through the installation instructions to install ImageMagick
- `pip install -r requirements/base.txt`
- find a gif and upload it. add it to a page to see it in action

## Review

- @richaagarwal 
- @kave 
- @rosskarchner 

## Todos

- the servers need to install `ImageMagick` before this can work

### CODE REVIEW

**Comment by richaagarwal** [comment]
Hmmm I went through those steps (`brew install imagemagick`, `pip install -r requirements/base.txt`) and uploaded a couple gifs but it doesn't seem to be working :(

**Comment by rosskarchner** [comment]
Does this prove it's working? 
out

**Comment by kurtw** [comment]
@rosskarchner yeah that should be it.

**Comment by rosskarchner** [comment]
I'm curious what it's (not) doing for @richaagarwal then

**Comment by kave** [comment]
👍  
kfxtzkvfcs

**Comment by richaagarwal** [comment]
👍

**Pull request merged**
