### PR TITLE
Added Contact Us to navigation

### PR DESCRIPTION
**Pull request by jimmynotjim**
Added Contact Us to navigation

## Additions

- None

## Removals

- None

## Changes

- Reverted navs from Contact Us redacting

## Testing

- Find Contact Us in header and footer navigation

## Review

- @anselmbradford 
- @KimberlyMunoz 
- @sebworks 

## Preview

screen shot 2015-04-27 at 4 55 15 pm

screen shot 2015-04-27 at 4 55 24 pm

## Notes

- None

### CODE REVIEW

**Comment by sebworks** [comment]
:+1:

**Comment by anselmbradford** [comment]
:+1:

**Comment by KimberlyMunoz** [comment]
Looks good.

**Comment by jimmynotjim** [comment]
Squashed and added to __Unreleased__ section of `CHANGELOG.md`

**Pull request merged**
