### PR TITLE
Update django-college-costs-comparison to 1.6

### PR DESCRIPTION
**Pull request by mistergone**
A new version (`1.6.1`) of "Paying for College" (`django-college-costs-comparison`) has been released. Changes can be found [in this pull request](https://github.com/cfpb/django-college-costs-comparison/pull/11) and [this pull request](https://github.com/cfpb/django-college-costs-comparison/pull/12).

The changes to Paying for College here focus on the removal of Raphael, a package with known security issues. There are also minor fixes with regards to quotes and `rel="noopener noreferrer"` on some links.

Please note this is a security fix for an existing application. There are many known issues (see testing below) that this PR will not address.

## Changes
- Update optional-public.txt to use version 1.6.1 of the Paying for College repo, django-college-costs-comparison

## Testing
1. Download the `django-college-costs-comparison` repo.
2. From inside `cfgov-refresh`, install Paying for College with `pip install -e /path/to/django-college-costs-comparison/`
3. Check the url at [http://127.0.0.1:8000/paying-for-college/compare-financial-aid-and-college-cost/](http://127.0.0.1:8000/paying-for-college/compare-financial-aid-and-college-cost/)
4. Nothing should be visually or functionally different from the live site.

## Notes
- This update to Paying for College removes Raphael, but patches the application so that it has exactly the same functionality and appearance.
- The application (which relies on Javascript) does not have a graceful failure for no-js/IE8, but it didn't before. Adding one is outside the scope of this work.
- There is an unrelated bug in IE9 that I'll file a separate issue about.

## Checklist
- [ ] PR has an informative and human-readable title
- [ ] Changes are limited to a single goal (no scope creep)
- [ ] Code can be automatically merged (no conflicts)
- [ ] Code follows the standards laid out in the [development playbook](https://github.com/cfpb/development)
- [ ] Passes all existing automated tests
- [ ] Any _change_ in functionality is tested
- [ ] New functions are documented (with a description, list of inputs, and expected output)
- [ ] Placeholder code is flagged / future todos are captured in comments
- [ ] Visually tested in supported browsers and devices (see checklist below :point_down:)
- [ ] Project documentation has been updated
- [ ] Reviewers requested with the [Reviewers tool](https://help.github.com/articles/requesting-a-pull-request-review/) :arrow_right:

### Browsers
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Internet Explorer 8, 9, 10, and 11 (Known issues in IE8 and IE9, see Notes above)
- [ ] Edge
- [ ] iOS Safari
- [ ] Chrome for Android

### Accessibility
- [ ] Keyboard friendly (Known issues, this PR will not fix. Accessibility audit forthcoming.)
- [ ] Screen reader friendly (Known issues, this PR will not fix. Accessibility audit forthcoming.)

### Other
- [ ] Is useable without CSS
- [ ] Is useable without JS (Known issue, this PR will not fix)
- [ ] Flexible from small to large screens (Known issues, this PR will not fix)
- [ ] No linting errors or warnings (Known issue, this PR will not fix)
- [ ] JavaScript tests are passing (Known issue, this PR will not fix)

### CODE REVIEW

**Comment by anselmbradford** [comment]
I have a minor patch in https://github.com/cfpb/django-college-costs-comparison/pull/12. Perhaps we would want to merge and release that first and update here? It doesn't really matter as we can do two version bumps too.

**Comment by mistergone** [comment]
@anselmbradford - I consider that a friendly amendment. I'll hold this until we merge cfpb/django-college-costs-comparison#12 and bump the release.

**Comment by hillaryj** [comment]
I've merged that PR and created a new release, so we can update this once the wheel is ready

**Comment by hillaryj** [comment]
Wheel name will be 1.6.1

**Comment by mistergone** [comment]
I updated the `optional-public.txt` file to use version 1.6.1.

**Comment by anselmbradford** [comment]
Thanks! https://github.com/cfpb/cfgov-refresh/blob/4763fc1b3ff5cd81457e59bf7c06fb0f27af97e5/requirements/optional-public.txt#L2 could be updated to 1.4.6 too, if you want while you're in there.

**Pull request merged**
