### PR TITLE
Prettifying django admin

### PR DESCRIPTION
**Pull request by kave**
## Additions

- Included django-suit package to prettify the admin page so it doesn't looks so generic

## Testing

- Access and view django-admin `/django-admin`

## Review

- @kurtw 
- @rosskarchner 
- @anselmbradford 

## Screenshots
- Before and ugly
disgusting_1
disgusting_2

- After Make-over
pretty_1
pretty_2

### CODE REVIEW

**Comment by rosskarchner** [comment]
It looks cool, but I'm not sure it adds enough value to justify integrating something that isn't really open source (even if we are technically "non-commercial"), and adds another thing we need to keep up-to-date.

**Comment by kave** [comment]
:'(

**Comment by rosskarchner** [comment]
I'm of course open to being convinced ;)

**Comment by kurtw** [comment]
Will there still be things being handled in the Django admin? Or are we converting _every_ app that's being editing in the Django admin?

**Comment by kave** [comment]
@rosskarchner So i've been spending more time in django-admin to select all delete objects quickly during development & testing, and wanted to include django-suit because its visually pleasing, light weight and requires virtually no management besides including it in the installed apps & an additional template contact processor besides that your done. It just overrides default django admin styles/templates with its own.

@kurtw Django admin will only allow you to manipulate models that you manually register, so its at your discretion. For me registering contacts (other PR) made deleting multiple contacts a simple job as opposed to walking though the wagtail flow. 
so to answer your question, no we will not be handling every model in django-admin

**Comment by kurtw** [comment]
@kave Well what I was getting at was if we are going to handle _any_ in the admin.

**Comment by rosskarchner** [comment]
I think there will definitely still be stuff managed in Django admin-- anything that doesn't make sense as a page type or snippet. Off the top of my head, the leaderhship calendar, or data that drives API's (like the paying for college data)

**Comment by higs4281** [comment]
we're hoping to store semi-constants for paying for college in the db that would be accessible via django admin. values that change at most a few times a year, such as a set interest rate.

**Comment by higs4281** [comment]
also, retirement stores content snippets in the admin. that would either have to be integrated with wagtail or left avail in django admin.

**Comment by kurtw** [comment]
Then making the admin more user friendly is a plus :+1:

**Comment by rosskarchner** [comment]
In the end-- we can debate the technical merits of this (my hunch is that there's more cost than benefit, but that's all it is, a hunch).

I don't think the licensing situation is up for debate, though, and that's pretty goofy: Even if we qualify as "non-commercial" users, [Creative Commons licenses are not meant for use with software](http://www.wired.co.uk/news/archive/2011-12/14/what-does-creative-commons-mean-for-software). This isn't open source software, it's "freeware", We don't have a precedent for using or depending on freeware.

I'm uneasy about being the ones to set that precedent. Maybe we need input from people outside our team, like @amymok @willbarton @higs4281

**Comment by jimmynotjim** [comment]
Should this be closed? At this point it's way behind

**Comment by kave** [comment]
yea we can close it.

**Pull request closed without merging**
