### PR TITLE
Add note about server error and pyc fix to usage docs

### PR DESCRIPTION
**Pull request by cfarm**
i ran into this issue today, searched chat, and fixed it. inspired by the dialogue i found:
screen shot 2017-05-25 at 4 59 08 pm
and scene

## Added
Note to the Gulp Watch task section:
screen shot 2017-05-25 at 5 01 53 pm

## Test

1. To preview docs locally, first `pip install -r requirements/manual.txt`
1. `mkdocs serve`
1. go to http://127.0.0.1:8000/usage/ and scroll down to Gulp Watch to see the Note I added

## Checklist

* [ ] PR has an informative and human-readable title
* [ ] Changes are limited to a single goal (no scope creep)
* [ ] Code can be automatically merged (no conflicts)
* [ ] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [ ] Passes all existing automated tests
* [ ] New functions include new tests
* [ ] New functions are documented (with a description, list of inputs, and expected output)
* [ ] Placeholder code is flagged
* [ ] Visually tested in supported browsers and devices
* [ ] Project documentation has been updated
* [ ] Reviewers requested with the [Assignee tool](https://help.github.com/articles/assigning-issues-and-pull-requests-to-other-github-users/) :arrow_right:

### CODE REVIEW

**Comment by richaagarwal** [comment]
Minor thing but I would maybe edit it to suggest "you likely need to" since technically the error could occur for other reasons.

**Comment by cfarm** [comment]
@richaagarwal done.

**Comment by anselmbradford** [comment]
Can we make this a warning and give a gap between the boxes by adding an empty blockquote between them? Also, while you're in there could you update the note above it to read "The watch task will only re-run the tasks that have changed files." … which unless anyone disagrees I think would be clearer.

This would be the code:

```
!!! note
    The watch task will only re-run the tasks that have changed files.
    Also, you must run `gulp build` at least once before watching.

>

!!! warning "Server error"
    If you get this message on the page when running `gulp watch`:
    "A server error occurred.  Please contact the administrator."
    You likely need to delete files with the `.pyc` extension from the project with the following command:    
    `find . -name \"*.pyc\" -exec rm -rf {} \;`
```

Which outputs:

screen shot 2017-05-26 at 5 03 57 pm

**Comment by JeffreyMFarley** [comment]
FYI, I use `find . -name \"*.pyc" -delete`

**Comment by cfarm** [comment]
@anselmbradford updated the note + warning as you specified

@JeffreyMFarley used your -delete command in the text too - i like the brevity.

**Comment by cfarm** [comment]
@anselmbradford can I get a plus one on this now?

**Pull request merged**
