### PR TITLE
clean up whitespace + formatting for success notification html

### PR DESCRIPTION
**Pull request by cfarm**
Whitespace + styling improvements for the conference registration form success notification.

## Additions

- Adds a `block` element around the success message for the conference registration form so that the whitespace below is increased

## Changes
- Changes `h4` element for the message inside the success notification template to a `div` element - this allows for rich text fields to output child content inside the message container. This won't affect styling in other notifications elsewhere, because the `.h4` class is still applied to the `div` element.

## Testing

- check out locally
- Create a 'conference registration form' element in the Wagtail admin
- Add some text to the "Success message" field - here's mine:
  > Thank you for registering for the CFPB research conference on December 15–16, 2016. We are looking forward to seeing you there!
  > Let us know if your plans change, and you can’t make the days you registered to attend. Also, let us know if you have any questions about the event and how to attend. Feel free to email us at CFPB_ResearchConference@cfpb.gov.
- View page, submit form, and see that the green notification message appears formatted as expected

## Review

- @chosak 
- @nataliafitzgerald 

## Screenshots

screen shot 2016-11-21 at 12 52 06 pm

screen shot 2016-11-21 at 1 52 16 pm

## Notes

-

## Todos

-

## Checklist

* [ ] Changes are limited to a single goal (no scope creep)
* [ ] Code can be automatically merged (no conflicts)
* [ ] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [ ] Passes all existing automated tests
* [ ] New functions include new tests
* [ ] New functions are documented (with a description, list of inputs, and expected output)
* [ ] Placeholder code is flagged
* [ ] Visually tested in supported browsers and devices
* [ ] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)

### CODE REVIEW

**Comment by chosak** [comment]
:+1: given that the change to the notification organism 

> won't affect styling in other notifications elsewhere

**Comment by cfarm** [comment]
I'm looking for examples to confirm that claim

**Comment by cfarm** [comment]
http://www.consumerfinance.gov/activity-log/?form-id=0&filter0_title=&filter0_categories=speech&filter0_topics=enforcement&filter0_from_date=&filter0_to_date=

**Comment by cfarm** [comment]
Just pushed an additional CSS fix for changing the `p` tag to a `div` which fixes whitespace on other notifications on cf.gov:

screen shot 2016-11-21 at 3 47 22 pm

screen shot 2016-11-21 at 3 48 00 pm

**Comment by cfarm** [comment]
For future reference, I'm creating an issue for this on GHE so we can track how to update the notification template to better work with Wagtail-editable notification messages. As far as we know, this is the first such Wagtail notification in the site, and we think there might be more elegant and flexible solutions for coding that notification message to allow content editors to add HTML formatted content within them.

**Comment by sebworks** [comment]
👍

**Pull request merged**
