### PR TITLE
Updated the progress charts

### PR DESCRIPTION
**Pull request by jimmynotjim**
Updated the progress charts on the homepage to be more in line w/ where we're at

## Additions

None

## Removals

None

## Changes

Updated percentages based on recent updates

## Testing

- homepage

## Review

- @schaferjh 
- @anselmbradford 
- @KimberlyMunoz 
- @sebworks 

## Preview

screen shot 2015-07-08 at 10 19 41 am

[Preview this PR without the whitespace changes](?w=0)

## Notes

- These are guesstimates based on today's In-Progress Review, feel free to question them

### CODE REVIEW

**Comment by anselmbradford** [comment]
Well this is an exciting moment! :+1:

**Comment by anselmbradford** [comment]
One thought: Sounds like policy and compliance should still be 0% at this point, considering what pages are on the site.

**Comment by jimmynotjim** [comment]
Oh right, it specifically says published. Maybe we should update that text as well. Thoughts @schaferjh?

**Comment by schaferjh** [comment]
Darnnit. @anselmbradford  makes a good point. Move the Policy & Compliance circle back to 0. :disappointed:

**Comment by jimmynotjim** [comment]
Updated and merging

**Pull request merged**
