### PR TITLE
Initial work to create the records page

### PR DESCRIPTION
**Pull request by jimmynotjim**
Initial work to create the FOIA Frequently Requested Records page

## Additions

- Added static records page (will need to be made into a macro/base template for all list browse pages)
- Added records query, not sure how we'll handle this in the future for the child/detail pages

## Removals

- None

## Changes

- Updated vars to include the records query. This will also need to be updated down the line.

## Testing

- navigate to `initiatives/foia-records/` and test the filters/pagination

## Review

- @schaferjh 
- @kurtw 
- @anselmbradford 
- @KimberlyMunoz 
- @sebworks 

## Preview

screen shot 2015-05-28 at 1 22 12 pm

[Preview this PR without the whitespace changes](?w=0)

## Notes

- Creates a paginated posts page based on Newsroom
- Borrowing posts from Newsroom for the time being (no Records posts yet)
- Nav title will need to be updated when @kurtw completes the WP admin side

### CODE REVIEW

**Comment by kurtw** [comment]
Looks like it's fine except [the non-paginated results look weird](https://cloud.githubusercontent.com/assets/1412978/7867660/6063e99e-0545-11e5-9584-42d4f472d890.png).

**Comment by KimberlyMunoz** [comment]
A note to anyone testing this, be sure to reindex sheer if you don't see anything coming up!

Ditto on Kurt's issue. When I looked at the wireframe, it didn't have anything under it, but the wireframe might be out of date. I'd check with @schaferjh to see if there's supposed to be an activity feed at the bottom of this page to provide spacing.

**Comment by jimmynotjim** [comment]
Not sure why you needed to re-index, it's not grabbing any new content, just borrowing the existing newsroom query.

@kurtw & @KimberlyMunoz good catch. It's actually an issue w/ the template, I need to update it to match blog/newsroom. Even if there's something under there eventually, we still need some spacing.

**Comment by KimberlyMunoz** [comment]
I had an old slug for for the records page and all the content was on `initiatives/frequently-requested-records-log-quarterly-reports/`.

Is the spacing issue going to get tackled in this PR, or saved for templating after?

**Comment by jimmynotjim** [comment]
@KimberlyMunoz ah, sorry, I completely forgot I had James change that slug to make it shorter. I am going to tackle the spacing, should be completed right after scrum.

**Comment by jimmynotjim** [comment]
Fixed the padding issue, this PR is ready for review again.

**Comment by kurtw** [comment]
Nice. Looks good to me :+1:

**Comment by jimmynotjim** [comment]
@KimberlyMunoz could you take another look at this on Monday?

**Comment by KimberlyMunoz** [comment]
Yep. Taking a look now.

**Comment by KimberlyMunoz** [comment]
Looks good to me!

**Pull request merged**
