### PR TITLE
Disable htmlmin 4.0

### PR DESCRIPTION
**Pull request by rosskarchner**
### Removals
- django-htmlmin removed from middleware and dependencies.

### CODE REVIEW

**Comment by willbarton** [comment]
😢 👋

**Comment by chosak** [comment]
:+1: Mind also removing [this](https://github.com/cfpb/cfgov-refresh/pull/2470/files#diff-0cf61f1e9bb958eff38a3fae3fd25a3fR3) reference to leave no trace behind?

**Comment by sebworks** [comment]
why is it being disbled?

**Comment by rosskarchner** [comment]
@sebworks it's causing some rendering issues, chiefly code like:

`<b>hey you </b> too` is becoming `<b>hey you</b>too`

**Comment by rosskarchner** [comment]
compare AskCFPB on content and prod

screen shot 2016-11-03 at 4 01 35 pm

screen shot 2016-11-03 at 4 01 26 pm

**Comment by sebworks** [comment]
thanks @rosskarchner

**Comment by rosskarchner** [comment]
@chosak done!

**Pull request merged**
