### PR TITLE
Browser tests for button functionality within the RTE

### PR DESCRIPTION
**Pull request by sebworks**
Browser tests for button functionality within the RTE

## Changes

- Modified files to create the necessary menus, pages, and workflows for testing the Rich Text Editor.  Fixed all of the linting errors but didn't resolve the warnings. 

## Testing

- run `tox -e acceptance`

## Notes

- There is currently an error on the insert link button.

## Todos

- Need to write tests for the following buttons:
  - Add Edit / Link
  - Remove Link
  - Documents
  - Images
  - Embed

## Checklist

* [ ] PR has an informative and human-readable title
* [ ] Changes are limited to a single goal (no scope creep)
* [ ] Code can be automatically merged (no conflicts)
* [ ] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [ ] Passes all existing automated tests
* [ ] New functions include new tests
* [ ] New functions are documented (with a description, list of inputs, and expected output)
* [ ] Placeholder code is flagged
* [ ] Visually tested in supported browsers and devices
* [ ] Project documentation has been updated
* [ ] Reviewers requested with the [Assignee tool](https://help.github.com/articles/assigning-issues-and-pull-requests-to-other-github-users/) :arrow_right:

### CODE REVIEW

**Comment by richaagarwal** [comment]
So exciting! I'll give this a thorough review tonight

**Comment by richaagarwal** [comment]
This gets through all the steps OK until it hits "And I select the full width text organism", which errors out again and again with a message like 
```
  Scenario: Italicize Text
[ Entry {
    level: Level { name_: 'SEVERE', value_: 1000 },
    message: 'http://localhost:9000/path/to/my/custom.js - Failed to load resource: the server responded with a status of 404 (NOT FOUND)',
    timestamp: 1495787047738,
    type: '' },
  Entry {
    level: Level { name_: 'SEVERE', value_: 1000 },
    message: 'http://localhost:9000/path/to/my/custom.css - Failed to load resource: the server responded with a status of 404 (NOT FOUND)',
    timestamp: 1495787047769,
    type: '' },
  Entry {
    level: Level { name_: 'SEVERE', value_: 1000 },
    message: 'http://localhost:9000/path/to/my/custom.js - Failed to load resource: the server responded with a status of 404 (NOT FOUND)',
    timestamp: 1495787047836,
    type: '' },
  Entry {
    level: Level { name_: 'WARNING', value_: 900 },
    message: 'http://localhost:9000/static/wagtailadmin/js/vendor/rangy-core.js 79 The behavior that Selection.addRange() merges existing Range and the specified Range was removed. See https://www.chromestatus.com/features/6680566019653632 for more details.',
    timestamp: 1495787048008,
    type: '' } ]
```

**Comment by sebworks** [comment]
@richaagarwal, I think that was just the console log from the browser. I've commented out those lines. Please run again when you get a chance.

**Comment by sebworks** [comment]
You should get:
screen shot 2017-05-26 at 6 24 01 am

**Comment by chosak** [comment]
I've made two changes to get this to work on Travis: first, I reverted the use of headless mode in Chrome as that doesn't seem to work well with selecting elements (possibly due to screen size? not sure). Also now instead of using beta Chrome we just use the stable version as described in the [newly merged](https://github.com/travis-ci/docs-travis-ci-com/pull/1136) docs on Travis [here](https://docs.travis-ci.com/user/chrome).

My change in 8234bb9 fixes a minor thing related to how we parse the Wagtail inserted link attributes.

**Pull request merged**
