### PR TITLE
Changed to banner based on banner at Owning a Home

### PR DESCRIPTION
**Pull request by KimberlyMunoz**
Our old banner looks something like this:

image

This replaces the banner with Owning a Home's banner to prevent that weird mangling.

### CODE REVIEW

**Comment by KimberlyMunoz** [comment]
Closes https://github.com/cfpb/cfgov-refresh/issues/951

**Comment by sebworks** [comment]
:+1:

**Comment by Scotchester** [comment]
I'd appreciate one more attempt at just changing the problem character. That old ASCII logo isn't very close to our actual logo. Using the straight single quote should solve the problem.

**Comment by KimberlyMunoz** [comment]
Do you mind making that PR? I'll hold off on merging this if someone else is willing to play with it.

**Comment by Scotchester** [comment]
Don't mind at all! Stand by.

**Comment by Scotchester** [comment]
#1142

**Pull request closed without merging**
