### PR TITLE
removed unnecessary route specific js, as routes no longer exist

### PR DESCRIPTION
**Pull request by kave**
## Removals

- removed unnecessary route specific js, as routes no longer exist

## Review

- @KimberlyMunoz 
- @anselmbradford 
- @jimmynotjim 
- @sebworks 

## Checklist

* [x] Changes are limited to a single goal (no scope creep)
* [x] Code can be automatically merged (no conflicts)
* [ ] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [x] Passes all existing automated tests
* [ ] New functions include new tests
* [ ] New functions are documented (with a description, list of inputs, and expected output)
* [ ] Placeholder code is flagged
* [ ] Visually tested in supported browsers and devices
* [ ] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)

### CODE REVIEW

**Comment by sebworks** [comment]
should the routes be removed from `urls.py` as well?

**Comment by kave** [comment]
@sebworks yea they are already removed

**Comment by sebworks** [comment]
nice, :+1:

**Comment by anselmbradford** [comment]
:+1:

**Pull request merged**
