### PR TITLE
Sprint 32, part 2

### PR DESCRIPTION
**Pull request by anselmbradford**

### CODE REVIEW

**Comment by KimberlyMunoz** [comment]
A few navigation issues on tablet:

- There is no link to the About Overview page on mobile.
- When a user scrolls with a expanded menu, there's a strange gap at the top of the webpage.

image

**Comment by anselmbradford** [comment]
> When a user scrolls with a expanded menu, there's a strange gap at the top of the webpage.

Sounds like https://github.com/cfpb/cfgov-refresh/issues/375

**Comment by KimberlyMunoz** [comment]
Yep. Although it looks like now that the menu is longer, this issue can occur without resizing.

**Comment by KimberlyMunoz** [comment]
`/careers/` and all the `/careers/*/` pages are not loading. I'm looking into it.

**Comment by sebworks** [comment]
So we are currently hiding the `About Overview` link on mobile but I'll submit a PR to fix the issue.

https://github.com/cfpb/cfgov-refresh/blob/flapjack/src/_includes/macros/sub-nav.html#L26

**Comment by KimberlyMunoz** [comment]
This should be in an header style that matches what we have in the activity feed. I know it got fixed earlier, but it was reverted in bff26ac. 

image

**Comment by KimberlyMunoz** [comment]
Images don't seem to be loading on IE8

screen shot 2015-07-27 at 6 37 00 pm

**Comment by anselmbradford** [comment]
> Images don't seem to be loading on IE8

Hm, I noticed this on the main logo too. I would be curious to see this on an actual machine.
screen_shot_2015-07-27_at_3 34 56_pm_720

**Comment by KimberlyMunoz** [comment]
@anselmbradford I found that error on an IE8 WinXP VM on the flapjack server.  I think that's as close as we're going to get to an actual machine. Did you test on a VM or Sauce?

**Comment by anselmbradford** [comment]
> I found that error on an IE8 WinXP VM on the flapjack server. I think that's as close as we're going to get to an actual machine. Did you test on a VM or Sauce?

This is from Sauce.

**Comment by jimmynotjim** [comment]
The content footer on the offices pages should have a top and right border, correct?

screen shot 2015-07-28 at 5 24 34 pm

**Comment by jimmynotjim** [comment]
Individual career postings should have 'Careers / Current Openings' breadcrumb (I missed that in the mockup)

**Comment by jimmynotjim** [comment]
Should the line height be tweaked for multi-line items in the main nav? It feels like these are two different items till you hover.

screen shot 2015-07-28 at 5 33 29 pm

**Comment by jimmynotjim** [comment]
Clicking the video in the main nav no longer auto-starts the video. @sebworks this was working at one point right? Or did we just discuss it?

**Comment by jimmynotjim** [comment]
About video image is missing on individual career postings (looks like it's a relative url issue).

**Comment by jimmynotjim** [comment]
Double underline in a hero `jump-link__right`
screen shot 2015-07-28 at 5 42 01 pm

**Comment by jimmynotjim** [comment]
Double borders on stacked expandables

screen shot 2015-07-28 at 5 43 55 pm

**Comment by jimmynotjim** [comment]
Official website notice feels wicked crammed here

screen shot 2015-07-28 at 5 45 52 pm

**Comment by jimmynotjim** [comment]
Expandables on Payments to Harmed Consumers are missing borders

screen shot 2015-07-28 at 5 52 06 pm

**Comment by jimmynotjim** [comment]
Alternating borders are weird on small screens (simple table styles are adding background to the first `td`)

screen shot 2015-07-28 at 5 54 30 pm

**Comment by jimmynotjim** [comment]
Everything is merged or logged, we all good to merge?

**Comment by sebworks** [comment]
:+1:

**Comment by KimberlyMunoz** [comment]
:+1:

**Comment by jimmynotjim** [comment]
Merging!

a-goose-o

**Pull request merged**
