### PR TITLE
Remove deprecated Django calendar app

### PR DESCRIPTION
**Pull request by chosak**
Now that the leadership calendar has been moved to Wagtail, we can remove the deprecated Django calendar application. This PR removes the application completely.

## Removals

- Django `cal` app, and reference to it from settings.

## Testing

- Using a production data dump, verify that leadership calendar can be viewed at [http://localhost:8000/about-us/the-bureau/leadership-calendar/](http://localhost:8000/about-us/the-bureau/leadership-calendar/), and that the Django/Wagtail admins can be browsed with no legacy calendar references.

## Notes

- This PR will leave behind `cal` database tables and references to `cal` types in the Django `contenttypes` table. These can be manually removed.

## Checklist

* [X] Changes are limited to a single goal (no scope creep)
* [X] Code can be automatically merged (no conflicts)
* [X] Passes all existing automated tests
* [X] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)
* [X] Reviewers requested with the [Assignee tool](https://help.github.com/articles/assigning-issues-and-pull-requests-to-other-github-users/) :arrow_right:

### CODE REVIEW

**Comment by sebworks** [comment]
@chosak, I think you can probably delete:

-  https://github.com/cfpb/cfgov-refresh/tree/master/cfgov/jinja2/v1/about-us/the-bureau/leadership-calendar/

-  https://github.com/cfpb/cfgov-refresh/blob/master/cfgov/jinja2/v1/_includes/leadership-calendar-table.html.

**Comment by sebworks** [comment]
There is also some associated pdf-reactor code but I'm unsure about it.

- https://github.com/cfpb/cfgov-refresh/blob/master/cfgov/jinja2/v1/_includes/pdfreactor-footer.html

- https://github.com/cfpb/cfgov-refresh/tree/master/cfgov/unprocessed/fonts/pdfreactor

- https://github.com/cfpb/cfgov-refresh/blob/master/cfgov/unprocessed/css/pdfreactor-fonts.css

**Comment by rosskarchner** [comment]
Some of that stuff *might* be used for find-a-housing-counselor

**Comment by chosak** [comment]
@rosskarchner thanks, that's possible. The second set of links from @sebworks might still be in use. The first set can be deleted (9adc522).

**Pull request merged**
