### PR TITLE
Move Blog into Wagtail

### PR DESCRIPTION
**Pull request by kurtw**
Short description explaining the high-level reason for the pull request

## Additions

- LegacyBlogPage
 - model and migration scripts

## Removals

- Sheer blog

## Changes

- some minor inconsequential stuff

## Testing

- Create a `blog` browse filterable page under about us with a filter
- Run `./cfgov/manage.py import_data posts legacyblogpage --parent blog -u user -p pass`
- Go to `/blog/` and see it in all its glory.

## Review

- @kave 
- @richaagarwal 
- @rosskarchner 

## Screenshots
screen shot 2016-04-15 at 8 53 11 am

## Todos

- The new BlogPage class needs to be made
- Still need to set up an RSS feed
- Need to convert newsroom into wagtail

### CODE REVIEW

**Comment by rosskarchner** [comment]
💣

**Comment by rosskarchner** [comment]
Is this warning interesting?

```
/Users/karchnerr/.virtualenvs/cfgov-refresh/lib/python2.7/site-packages/django/forms/fields.py:222: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if value in self.empty_values:
```

**Comment by kurtw** [comment]
Yeah I'm not sure of the source of that one to be totally honest. The two lines above the regular output are basically saying that those slugs from the data never got saved properly, corresponding to the 2 errors. Seems to work fine anyway.

**Comment by kave** [comment]
yea i got 
```
694 migrated
0 overwritten
3 existed
2 errors
```

**Comment by kurtw** [comment]
Moving into single PR

**Pull request closed without merging**
