### PR TITLE
Adding download icons to PIAs

### PR DESCRIPTION
**Pull request by KimberlyMunoz**
Adding download icons to pias

## Additions

- Added logic to make it easier to add classes to specific pages.
- Added styles to add links to all the links in the PIA page. I can future proof it more by applying this only on links that end in .pdf, but that might be making things too specific.

## Testing

- Visit /sub-pages/privacy-impact-assessments-pias/

## Review

- @sebworks 
- @jimmynotjim 
- @anselmbradford 

## Preview

image

[Preview this PR without the whitespace changes](?w=0)

### CODE REVIEW

**Comment by anselmbradford** [comment]
Have we standardized whether the download icon appears before or after the link? cc @duelj  

Also note there's an existing `list__download` class that appears like it might be able to be used here https://github.com/cfpb/cfgov-refresh/blob/a2c7bcb21295edb8f29305725cf89bf2d05622c4/src/static/css/cf-enhancements.less#L715

**Comment by KimberlyMunoz** [comment]
The `list__download` class had some issues where the icon would appear on the second line.

The wireframe has them appear after the link, but I'll confirm with @schaferjh.

**Comment by duelj** [comment]
The icons for downloads do appear after the link. Currently it seems the contact icons for email, phone, etc. are the only thing that might get used in front of a link. **This looks good to me.**

**Comment by schaferjh** [comment]
:+1:

**Comment by jimmynotjim** [comment]
Tested locally and code looks good. Any way we can tie this type of link list together? It's also used at `/budget/performance-plan-report/`, although those icons appear to be incorrect, falling before the link text instead of after it.

For this page, I'd think we should make all the entries uniform, instead of the two with plain text around the link, but that's something I'm assuming happens in the CMS?

**Comment by anselmbradford** [comment]
> The list__download class had some issues where the icon would appear on the second line.

IIRC it needs the following structure:
```
ul.list__download
  li.list_item
    span.list_icon
    span.list_text
```

If the icon is spilling over, the link and/or the icon likely aren't wrapped in a span.

However, this is needed to reliably support list items that span two lines. If all of these link download lists will have the icons after the link, there's a lot that can be dropped from the CSS (unless it matters if in multi-line links the text runs over the top of the icon).

> although those icons appear to be incorrect, falling before the link text instead of after it.

The lists in content.cf.gov haven't been ramped, so content.cf.gov has the correct HTML and www has the correct CSS.

**Comment by KimberlyMunoz** [comment]
> @jimmynotjim:  For this page, I'd think we should make all the entries uniform, instead of the two with plain text around the link, but that's something I'm assuming happens in the CMS?

Yep.

@anselmbradford: Re: `.list__download` that's going to require way more markup that content will have to be responsible for, and I don't feel comfortable adding more there that non-developers will be asked to update.

**Comment by anselmbradford** [comment]
> Re: .list__download that's going to require way more markup that content will have to be responsible for, and I don't feel comfortable adding more there that non-developers will be asked to update.

@KimberlyMunoz Yeah, it's systematic of our larger content management challenges. Simple no-frills unordered lists entered into the CMS will be difficult to decorate with icons that manage things like single and multi-line text that still positions the icon in a way that makes sense (though something like flexbox might be a way to go—in which case modern browsers would look good and legacy browsers not so much). I looked into this issue for awhile when we had a task open for it several months ago and the most reliable means I came to then was to wrap the icon and text in a container (the span) and apply table-cell display values. This was a considerable improvement from the HTML that existed in the CMS, which was already quite a bit more complicated than that. But yeah, sounds like for new content we may want to re-think the approach.

**Comment by jimmynotjim** [comment]
Lets merge this for now and open a new issue for next sprint to solve the complexity problem. :+1:

**Pull request merged**
