### PR TITLE
Add support for monitoring with New Relic

### PR DESCRIPTION
**Pull request by chosak**
This commit upgrades the version of the New Relic Python agent used in cf.gov deploys and adds a newrelic.ini file to this repository. It also adds support for New Relic initialization into the wsgi.py file used when cf.gov is deployed and served via mod_wsgi.

The version of the agent used on cf.gov right now is 2.96.0.80, released October 16, 2017. This commit upgrades it to the latest, 4.18.0.118, released April 17, 2019. There have been many changes and improvements in that time, including security fixes. The full changelog is [here](https://docs.newrelic.com/docs/release-notes/agent-release-notes/python-release-notes).

This latest version of the agent was used to generate an initial version of the newrelic.ini configuration file added here, using:

```
$ newrelic-admin generate-config
```

This file was then updated using values from the existing cf.gov New Relic configuration file, currently brought in from an internal repository. This file purposefully excludes values for certain settings, that must be set via environment variable:

 - license_key must be set by `NEW_RELIC_LICENSE_KEY`
 - app_name must be set by `NEW_RELIC_APP_NAME`
 - log_file must be set by `NEW_RELIC_LOG`

A related PR is being opened against our internal Ansible repository to properly set these environment variables on deploy.

Relatedly, this commit changes how New Relic is initialized in the cf.gov wsgi.py file. Instead of relying on drama-free-django to insert that logic at build time, the logic is now permanently part of wsgi.py. By default it is turned off, and only enabled if `NEW_RELIC_LICENSE_KEY` is set in the environment.

If set, the wsgi.py file now initializes New Relic using the newrelic.ini file added in this commit.

## Testing

To validate the newrelic.ini file, you can run the following command from the root of this repository:

```
$ NEW_RELIC_LICENSE_KEY=<insert license key here> newrelic-admin validate-config cfgov/newrelic.ini
```

This will connect to our New Relic account and generate some traffic against an app named "Python Agent Test". You should be able to see it under New Relic APM, although it may take a few minutes for the traffic to show up.

Testing the actual functionality in wsgi.py is a bit harder, as this repository isn't really set up to run using that file. If you'd like to do this, though, you can use uwsgi. First, install uwsgi into your virtual environment:

```
$ pip install uwsgi
```

Make sure that you have the standard local cfgov-refresh requirements in your virtual environment, and that your standard environment variables are loaded.

Then, run against wsgi.py without New Relic, making sure that the `NEW_RELIC_LICENSE_KEY` environment variable is not set. Use the following command line from the root of this repository:

```
$ PYTHONPATH=cfgov uwsgi --http :8000 --wsgi-file cfgov/cfgov/wsgi.py --enable-threads --single-interpreter
```

You'll see a whole bunch of output in the console. You should be able to visit http://localhost:8000 in the browser, and see the content of the cf.gov homepage. None of the static assets will work, so it'll look broken, but you should be able to convince yourself that the Django application is running using wsgi.py.

Now, to test using New Relic, set both `NEW_RELIC_LICENSE_KEY` and `NEW_RELIC_APP_NAME`. This latter variable should be set to something unique so that you can identify it in the New Relic console, and so it won't interfere with any live apps. I recommend something like "cf.gov testing python":

```
$ NEW_RELIC_LICENSE_KEY=<insert license key here> NEW_RELIC_APP_NAME="cf.gov testing python" PYTHONPATH=cfgov uwsgi --http :8000 --wsgi-file cfgov/cfgov/wsgi.py --enable-threads --single-interpreter
```

Again, you'll see a whole bunch of output. Visit http://localhost:8000 and you should see some console messages about connecting to New Relic. Importantly, you should see that it's using High Security Mode. Make some more requests against http://localhost:8000 and its children, wait a few minutes, and head back to the New Relic console. You should see the traffic generated against your locally running cf.gov instance.

(For cleanup purposes, when you're done with all of your testing, if you wait a few minutes, you'll see your apps turn from green to grey in the New Relic APM dashboard. Once they do, you should be able to click on the settings icon and choose "Delete app" to remove them.)

## Checklist

- [X] PR has an informative and human-readable title
- [X] Changes are limited to a single goal (no scope creep)
- [X] Code can be automatically merged (no conflicts)
- [X] Code follows the standards laid out in the [CFPB development guidelines](https://github.com/cfpb/development)
- [X] Passes all existing automated tests
- [X] Any _change_ in functionality is tested
- [X] New functions are documented (with a description, list of inputs, and expected output)
- [X] Placeholder code is flagged / future todos are captured in comments
- [X] Visually tested in supported browsers and devices (see checklist below :point_down:)
- [ ] Project documentation has been updated
- [X] Reviewers requested with the [Reviewers tool](https://help.github.com/articles/requesting-a-pull-request-review/) :arrow_right:

### CODE REVIEW

**Comment by chosak** [comment]
> Only thing I see is that you've added some great info about how to setup and test this new New Relic setup here on this PR. Should that live on somewhere under docs?

@hkeeler what stopped me from adding this to the docs is that with this implementation, NR is only invoked via wsgi.py, which is never touched during regular local development. If and when we move some kind of Apache-based serving to this repository, then I would definitely want to add documentation about how to use New Relic locally.

I also considered documenting how to run New Relic when using the Django runserver (something like [this](https://blog.newrelic.com/engineering/monitoring-django-management-commands/)), but, similarly, I had doubts if we want to document/recommend that people do this, at least yet.

Is there anything specific that you think would make sense to put in the docs today?

**Comment by rosskarchner** [comment]
> which is never touched during regular local development.

Are you sure about that? Django's runserver uses `get_internal_wsgi_application`

https://github.com/django/django/blob/b9cf764be62e77b4777b3a75ec256f6209a57671/django/core/management/commands/runserver.py#L62

Which uses the WSGI_APPLICATION setting:

https://github.com/django/django/blob/7785e03ba89aafbd949191f126361fb9103cb980/django/core/servers/basehttp.py#L26

**Comment by chosak** [comment]
@rosskarchner TIL! Thank you for pointing that out. If that's the case this definitely warrants some more testing and documentation. I'll play around with that.

**Comment by chosak** [comment]
Thanks all for the reviews and comments. Per the feedback above, because of how wsgi.py _is_ invoked by Django runserver, it's now easily possible to run locally against New Relic, should you need or want to.

To that end, I've added documentation on how to do this to a new "Debugging and Monitoring" page in the documentation, as well as placeholder environment variables in .env_SAMPLE. The rendered section about New Relic is below. As part of this I did some moderate refactoring of the current [Usage](https://cfpb.github.io/cfgov-refresh/usage/) documentation. This section is now organized like this:

image

Ping @cfarm @Scotchester @willbarton if you're able to review these documentation changes. I fully realize that there is _much_ more we could do to improve our installation and usage docs. My goal here was to make an incremental improvement while adding some new content.

image

**Pull request merged**
