### PR TITLE
FlyoutMenu: No transition support fixes

### PR DESCRIPTION
**Pull request by anselmbradford**
## Changes

- When no transition event is present `transitionEnd` was dispatched twice. This fixes that.
- Move public static constants outside constructor.
- Fix order of addEventListener on transition in FlyoutMenu when there is no transition support.

## Test

- `gulp build` and look at dev console in IE9. There should be no js script error. 

## Review

- @jimmynotjim

### CODE REVIEW

**Comment by sebworks** [comment]
:+1:

**Comment by anselmbradford** [comment]
@sebworks found one more issue where if transitions weren't supported the `transitionEnd` event would fire before it was being listened for, so `expandEnd` would never fire. Pushed up https://github.com/cfpb/cfgov-refresh/pull/1641/commits/9d1f7739b799cc27989eff22bea6efb38a5fa7ff that fixes the order. Should fix the desktop menu in IE9 (mobile size on IE9 still has issues).

**Comment by KimberlyMunoz** [comment]
:+1: If #1639 doesn't fix the mobile issues, we should note those in issue.

**Comment by anselmbradford** [comment]
The remaining issue I'm seeing on IE9 is:
- Resize to mobile
- Expand mega menu
- Click to second level menu (e.g. About Us)
- Click search button (mega menu collapses, search expands)
- Click mega menu button (search collapses, mega menu should expand but **ONLY OVERLAY SHOWS**)

**Comment by sebworks** [comment]
Late to the game but LGTM

**Pull request merged**
