### PR TITLE
Updated the dep dir page title to include "Acting"

### PR DESCRIPTION
**Pull request by jimmynotjim**
Updated the dep dir page title to include "Acting"

## Testing

Navigate to `/the-bureau/about-deputy-director/`

## Review

- @KimberlyMunoz 
- @sebworks 
- @anselmbradford 

## Preview

screen shot 2015-09-21 at 3 17 36 pm

[Preview this PR without the whitespace changes](?w=0)

### CODE REVIEW

**Comment by anselmbradford** [comment]
Didn't know she was acting :+1:

**Comment by KimberlyMunoz** [comment]
Should this also change on the about page?

image

**Comment by anselmbradford** [comment]
Oops, this broke a test too https://github.com/cfpb/cfgov-refresh/blob/flapjack/test/browser_tests/spec_suites/about-deputy-director.js#L40

**Comment by jimmynotjim** [comment]
@KimberlyMunoz it wasn't in the Jira issue, asking there.

**Comment by schaferjh** [comment]
@KimberlyMunoz I think we're okay with leaving her title as is on the About landing page and the navigation. Just want to get it right on the actual page title.

**Pull request merged**
