### PR TITLE
Updated Jinja2 shorthand if statements to include an empty else case.…

### PR DESCRIPTION
**Pull request by kave**
Updated Jinja2 shorthand if statements to include an empty else case to fix it returning undefined in the negative case.

@kurtw

### CODE REVIEW

**Comment by sebworks** [comment]
Is there a terser syntax other than `else ' '`?

**Comment by kurtw** [comment]
Possibly `else None` is more readable but less terse.

**Comment by anselmbradford** [comment]
`or None` might work too? _(Note that I haven't tested that)_

**Comment by sebworks** [comment]
ok, sounds like `else ''` is the best options for now.

**Comment by jimmynotjim** [comment]
I think @rosskarchner had the same discussion when he switched everything over to `else ''` 

GTM :+1:

**Pull request merged**
