### PR TITLE
post preview snapshot is now fixed.

### PR DESCRIPTION
**Pull request by kave**
## Changes

- Post preview snapshot is rendering correctly.

## Testing
- Import Refresh Db
- visit page `policy-compliance/amicus/` to verify 500 error is gone and post preview items render correctly

## Review

- @kurtw 
- @richaagarwal 

## Screenshots
screen shot 2016-03-09 at 4 54 18 pm

## Checklist

* [x] Changes are limited to a single goal (no scope creep)
* [x] Code can be automatically merged (no conflicts)
* [ ] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [ ] Passes all existing automated tests
* [ ] New functions include new tests
* [ ] New functions are documented (with a description, list of inputs, and expected output)
* [ ] Placeholder code is flagged
* [x] Visually tested in supported browsers and devices
* [x] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)

### CODE REVIEW

**Comment by schaferjh** [comment]
Following up on something I mentioned in the task: We need to be able to select *which* child filterable browse page the post preview snapshot should pull from. Is allowing content editors to make that selection part of this? 

(The use case is for adding it to the Notice and Comment sublanding page which has 2 children filtrable browse pages)

**Comment by kave** [comment]
@schaferjh ah i missed that line... hmm.. i'll have to think about how we can allow this

**Comment by kurtw** [comment]
@schaferjh right now the snapshot looks at all the child browse filterable pages, sorts them by the date_published field, then renders the number that was specified.

**Comment by kurtw** [comment]
@kave [here](https://github.com/cfpb/cfgov-refresh/pull/1562/files#diff-2ba27f15d5ce948b3f9483f62581c805R66) is where self.get_descendants() grabs _any_ page so that should sort out the shared/live thing. We can make this change in another PR as well.

**Comment by schaferjh** [comment]
@kurtw ok, that should work for now. Looking forward to seeing it in action!

**Comment by kave** [comment]
ok great, i'll make the shared/live fix in another PR so content can atleast render the pages for now.

**Pull request merged**
