### PR TITLE
Fix related posts URLs for duplicate slugs

### PR DESCRIPTION
**Pull request by chosak**
The current logic in the Related Posts template is using the built-in Wagtail
[`slugurl`](http://docs.wagtail.io/en/v2.0/topics/writing_templates.html#slugurl) template tag, which returns an undetermined link if there are multiple pages with the same slug anywhere in the site.

This change fixes GHE#2533 which was generating an incorrect link due to two pages having the same slug. It instead uses the built-in `page.url` property which returns the best URL for the page.

## Changes

- Use `page.url` instead of `slugurl(page.slug)` in related posts template.

## Testing

To test, use a production dump and visit http://localhost:8000/data-research/ and observe that the "2018 CFPB Research Conference" link properly points to an event page, not the conference landing page.

## Screenshots

image

## Notes

1. Note that due to the current way we have our production Wagtail Sites configured (we have multiple), `page.url` may return a full absolute URL rather than a relative URL here. I think the downside of this is outweighed by the simplicity of the required code change. Otherwise we'd
have to put in some complex logic like `page.relative_url(page.get_site())` which I would rather not stick in the template.

    If, hopefully, in future we move to a single Wagtail Site in production these links will properly be relative ones.

2. @higs4281 the only other places where `slugurl` is used in this repository is in Ask templates, e.g. [here](https://github.com/cfpb/cfgov-refresh/blob/master/cfgov/jinja2/v1/ask-cfpb/answer-page-spanish-printable.html#L47) or [here](https://github.com/cfpb/cfgov-refresh/blob/master/cfgov/jinja2/v1/ask-cfpb/answer-page.html#L135). Is there a chance that any of these places (there are 6 in total, try `git grep slugurl`) would ever be checking against a duplicate slug, and thus need a similar replacement?

## Checklist

* [X] PR has an informative and human-readable title
* [X] Changes are limited to a single goal (no scope creep)
* [X] Code can be automatically merged (no conflicts)
* [X] Code follows the standards laid out in the [development playbook](https://github.com/cfpb/development)
* [X] Passes all existing automated tests
* [X] Any *change* in functionality is tested
* [X] New functions are documented (with a description, list of inputs, and expected output)
* [X] Placeholder code is flagged
* [X] Visually tested in supported browsers and devices
* [X] Project documentation has been updated
* [ ] Reviewers requested with the [Reviewer tool](https://help.github.com/articles/about-pull-request-reviews/) :arrow_right:

### CODE REVIEW

**Comment by chosak** [comment]
@higs4281 thanks for reviewing. Just to clarify, the risk is that any page across the entire site might have that slug, not just within the same section of Ask. So if, say, the Auto section of CCT [that ends in `/auto-loans/`](https://www.consumerfinance.gov/data-research/consumer-credit-trends/auto-loans/) instead had a slug and ended in `/category-auto-loans/`, there'd be a conflict with Ask's [`/category-auto-loans/` page](https://www.consumerfinance.gov/ask-cfpb/category-auto-loans/), and we'd run into this problem.

**Comment by richaagarwal** [comment]
Would it be worth creating a test that fails before this change, and passes with this change?

**Comment by chosak** [comment]
@richaagarwal thanks for the review;  thought about that and decided against it, since it would essentially be testing that the code was written in a certain way (using `page.url`) and not really testing the functionality of anything. We could potentially have tests for organisms like this that verify that their HTML renders in a certain way, but that seemed out of scope for this minor bug fix.

**Comment by higs4281** [comment]
Late to the party, but you have a good point, @chosak 
slugurl's assumption that the provided slug is unique site-wide means it should only be used in narrow cases, if at all.

**Pull request merged**
