### PR TITLE
Fix Office/Initiative pages

### PR DESCRIPTION
**Pull request by kurtw**
This makes changes to the sheer processors, the templates, and the directory structure for those pages.

## Review

- @KimberlyMunoz 
- @dpford 
- @jimmynotjim 
- @anselmbradford 
- @sebworks 

## Notes

- You should create an Office in Wordpress then Initiatives that are related to the Office for the Office page
- Make child Initiatives of a parent Initiative
- Index everything
- go to `localhost:8080/offices/<office-slug>/` and confirm all the parent initiatives that are related to that office are present in Our Work and the nav
- go to `localhost:8080/initiatives/<initiative-slug>/` and confirm all the child initiatives that are children of that initiative are present and the nav is still correct

### CODE REVIEW

**Comment by KimberlyMunoz** [comment]
Indexing off our current offices and initiatives, there's a parsing error that prevent me from testing.

~~~
(cfgov-refresh)~/Projects/cfgov-refresh DF-1938 🐐  sheer index --reindex
reindexing content
No handlers could be found for logger "elasticsearch"
creating mapping for calendar_event (django_calendar_event_processor)
indexed 16495 calendar_event
creating mapping for contact (wordpress_contact_processor)
indexed 48 contact
creating mapping for history (wordpress_history_processor)
indexed 58 history
creating mapping for initiative (wordpress_initiative_processor)
Traceback (most recent call last):
  File "/Users/munozk/.virtualenvs/cfgov-refresh/bin/sheer", line 10, in <module>
    sys.exit(run_cli())
  File "/Users/munozk/Projects/sheer/sheer/cli.py", line 64, in run_cli
    args.func(args, config)
  File "/Users/munozk/Projects/sheer/sheer/indexer.py", line 214, in index_location
    index_processor(es, index_name, default_mapping, processor, reindex=args.reindex)
  File "/Users/munozk/Projects/sheer/sheer/indexer.py", line 128, in index_processor
    index_document(es, index_name, processor, document)
  File "/Users/munozk/Projects/sheer/sheer/indexer.py", line 81, in index_document
    raise e
elasticsearch.exceptions.TransportError: TransportError(400, u'MapperParsingException[failed to parse [date]]; nested: MapperParsingException[failed to parse date field [2015-05-06 18:38:34], tried both date format [dateOptionalTime], and timestamp number with locale []]; nested: IllegalArgumentException[Invalid format: "2015-05-06 18:38:34" is malformed at " 18:38:34"]; ')
~~~

**Comment by kurtw** [comment]
Sorry about that. I didn't realize I was using different code for
wp-json-api which would fix this. Will push up that code ASAP.

**Comment by kurtw** [comment]
Indexing should be fixed now @KimberlyMunoz

**Comment by KimberlyMunoz** [comment]
:sob: It works and it's beautiful. :sob:

There's some weird artifacts in the stuff that's getting pulled in, but I say merge it now so they have something to show tomorrow.

image

**Comment by kurtw** [comment]
I can fix that. Hold on. Does that only occur on the Office page?

**Comment by KimberlyMunoz** [comment]
I get a different error on the Initiatives page. I get the same error when I delete most of my custom content on the front end.

image

**Comment by kurtw** [comment]
Bug fixes are in! @KimberlyMunoz

**Comment by KimberlyMunoz** [comment]
:+1:

**Comment by jimmynotjim** [comment]
I'm going to have to rely on @KimberlyMunoz for testing, but the code looks good :+1:

**Comment by dpford** [comment]
looking good here

**Pull request merged**
