### PR TITLE
[TDP] Bump TDP to version 1.0.18

### PR DESCRIPTION
**Pull request by nbucknor**
Bump teachers_digital_platform from version 1.0.16 to 1.0.17

## Reviewers:

@Scotchester @willbarton @higs4281 @chosak

### CODE REVIEW

**Comment by chosak** [comment]
Has something changed with the way the frontend build is built? On Travis after the tests finish the workspace looks like this:

```sh
modified:   package-lock.json
modified:   teachers_digital_platform/crtool/package-lock.json
```

See [teachers-digital-platform#213](https://github.com/cfpb/teachers-digital-platform/pull/213) that fixed this previously.

**Comment by nbucknor** [comment]
These are all the changes we've made to TDP since the last release. I don't see and obvious changes to the build.

https://github.com/cfpb/teachers-digital-platform/compare/1.0.16...1.0.17

**Comment by chosak** [comment]
I've opened [teachers-digital-platform#262](https://github.com/cfpb/teachers-digital-platform/pull/262) which should hopefully fix the dirty wheel name. I'd recommend merging that PR and then either recreating the 1.0.5 TDP tag and release or creating a new 1.0.6 release.

**Comment by nbucknor** [comment]
@Scotchester @chosak I've updated the bug version to 1.0.18 and confirmed that the wheel filename is correct https://github.com/cfpb/teachers-digital-platform/releases/download/1.0.18/teachers_digital_platform-1.0.18-py2-none-any.whl

Could one of you review and merge? Also, we'll need to run ./cfgov/manage.py update_index -r teachers_digital_platform

**Pull request merged**
