### PR TITLE
Paying for College - Update to version 1.3.1

### PR DESCRIPTION
**Pull request by mistergone**
This pull request updates __Paying for College__ to version 1.3.1, which will update interest rates and limits in the Comparison Tool, and in the text of the 'About this tool' page. 

## Changes
- `requirements/optional-private.txt` updated

## Testing
1. Kick out the jams with this rad branch
2. Clone the latest super-dank version `django-college-costs-comparison` from GHE
3. `pip install -e /path/to/django-college-costs-comparison/`
4. Load up the Comparison Tool and check out the tight changes to federal interest rates!

## Screenshots
giphy

## Checklist
* [x] PR has an informative and human-readable title
* [x] Changes are limited to a single goal (no scope creep)
* [x] Code can be automatically merged (no conflicts)
* [x] Code follows the standards laid out in the [development playbook](https://github.com/cfpb/development)
* [x] Passes all existing automated tests
* [x] New functions include new tests
* [x] New functions are documented (with a description, list of inputs, and expected output)
* [x] Placeholder code is flagged
* [x] Visually tested in supported browsers and devices
* [x] Project documentation has been updated
* [x] Reviewers requested with the [Assignee tool](https://help.github.com/articles/assigning-issues-and-pull-requests-to-other-github-users/) :arrow_right:

### CODE REVIEW

**Comment by richaagarwal** [comment]
How come it's jumping up to 1.3.1?  What was in 1.3.0?

**Comment by richaagarwal** [comment]
Also is there a changelog for PfC?

**Comment by mistergone** [comment]
@richaagarwal - There was a release `1.3.0` but it seems like maybe it didn't get released to production. (Check out GHE/django-college-cost-comparison/tree/1.3.0 ).

**Comment by mistergone** [comment]
@richaagarwal - There's no CHANGELOG in the internal PfC repo, no.

**Comment by mistergone** [comment]
Merging!

**Pull request merged**
