### PR TITLE
Add ability to unit test Jinja2 macros with Macro Polo

### PR DESCRIPTION
**Pull request by willbarton**
This PR adds utilities for unit testing Jinja2 macros with [Macro Polo](https://github.com/cfpb/macropolo) based on JSON specifications and includes a couple of example specifications in `tests/`. 
 
**Additions**
 
- An base test case Python class for Macro Polo
- `test_macros.py`, which will run the tests in `tests/`
  
**Testing**
 
From within the `_tests/macro_testing` directory:

- Install the requirements: `pip install -r requirements.txt`
- Run the test runner: `python test_macros.py`
 
**Review**
 
- @anselmbradford 
- @sebworks 
- @jimmynotjim 

**Notes**

This won't work until [Macro Polo PR#1](https://github.com/cfpb/macropolo/pull/1) is merged.

### CODE REVIEW

**Comment by jimmynotjim** [comment]
This is looking good. Can't wait to give it a try after Macro Polo is merged.

**Comment by willbarton** [comment]
This PR is now up-to-date with the `flapjack` branch and ready to be reviewed.

**Comment by sebworks** [comment]
:+1:

**Comment by jimmynotjim** [comment]
Yay tests!

**Pull request merged**
