### PR TITLE
Updates the project w/ PR and Issue templates for Github

### PR DESCRIPTION
**Pull request by jimmynotjim**
Updates the project w/ PR and Issue templates for Github

## Additions

- Adds new PR template
- Adds new Issue template

## Testing

- I have no idea

## Review

- @KimberlyMunoz 
- @anselmbradford 
- @sebworks 
- @richaagarwal 
- @kave 
- @rosskarchner 

## Screenshots

I can't until it's merged :cry: 

## Notes

- See https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/

## Todos

- 

## Checklist

* [ ] Changes are limited to a single goal (no scope creep)
* [ ] Code can be automatically merged (no conflicts)
* [ ] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [ ] Passes all existing automated tests
* [ ] New functions include new tests
* [ ] New functions are documented (with a description, list of inputs, and expected output)
* [ ] Placeholder code is flagged
* [ ] Visually tested in supported browsers and devices 
* [ ] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)

### CODE REVIEW

**Comment by anselmbradford** [comment]
I'm wondering about whether `Notes` and `Todos` in the PR template could be merged. It's likely anything covered in the notes that isn't a todo could be covered in the description at the beginning of the PR. I'm fine with it either way though.

**Comment by jimmynotjim** [comment]
They were, but I re-added `Notes` because I find I add notes all the time that aren't `Todos`. Perfect example is this PR where I linked to the GH blog post about this new feature. I feel it calls attention to important information that's not really necessary in the description. I can cut it though if I'm the only one and add them manually.

**Comment by anselmbradford** [comment]
:+1:

**Comment by sebworks** [comment]
:

**Pull request merged**
