### PR TITLE
Update the homepage based on user feedback

### PR DESCRIPTION
**Pull request by jimmynotjim**
Update the homepage based on user feedback

## Additions

- Header slug above the hero news snippets

## Changes

- Updates the hero images

## Testing

- `gulp build` and check out the home page

## Review

- @KimberlyMunoz 
- @anselmbradford 
- @sebworks 

## Screenshots

screen shot 2016-03-02 at 3 38 40 pm

screen shot 2016-03-02 at 3 38 52 pm

## Checklist

* [x] Changes are limited to a single goal (no scope creep)
* [x] Code can be automatically merged (no conflicts)
* [x] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [x] Passes all existing automated tests
* [x] New functions include new tests
* [x] New functions are documented (with a description, list of inputs, and expected output)
* [x] Placeholder code is flagged
* [x] Visually tested in supported browsers and devices
* [x] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)

### CODE REVIEW

**Comment by sebworks** [comment]
Does ` o-well__home` still exist? Should it be ` o-well__full`?

**Comment by sebworks** [comment]
looks great, :+1:

**Comment by jimmynotjim** [comment]
@sebworks thanks for noticing that, I hadn't even noticed. It's fixed now.

**Comment by sebworks** [comment]
:+1:

**Comment by anselmbradford** [comment]
:+1:

**Pull request merged**
