### PR TITLE
WIP - Adding Protractor to Travis

### PR DESCRIPTION
**Pull request by KimberlyMunoz**
Don't review this yet. I'm checking to see if there's a way we can add protractor tests to run on each pull request.

### CODE REVIEW

**Comment by jimmynotjim** [comment]
@KimberlyMunoz once they're in the build process (either Grunt or Gulp), can all the tests can be run with `[gulp/grunt] test` from within Travis?

**Comment by KimberlyMunoz** [comment]
Yes, but the tricky part is getting it running on Sauce.

**Comment by anselmbradford** [comment]
We should keep in mind the option to run on sauce locally too.

**Comment by KimberlyMunoz** [comment]
:/ This might have been a bad idea. Travis really can't consistently host the site. I think we might just have to stick with Jenkins for this.

**Comment by jimmynotjim** [comment]
Aw, bummer.

**Pull request closed without merging**
