### PR TITLE
Updated processors to use Elasticsearch bulk indexing

### PR DESCRIPTION
**Pull request by dpford**
**WARNING: This PR requires an update to sheer, specifically [this PR](https://github.com/cfpb/sheer/pull/104).  Do not merge this until that PR is merged.**

This update greatly speeds up the Elasticsearch indexing process by using bulk indexing instead of indexing each document individually.  See the aforementioned PR for more information.

The default mapping was also deleted; the functionality that used it was removed in [sheer 2.0.3](https://github.com/cfpb/sheer/releases/tag/2.0.3).

Also, some formatting fixes were thrown in (mainly single quotes -> double quotes to maintain consistently, as much as it sickened me to do so).

### CODE REVIEW

**Comment by Scotchester** [comment]
@dpford You should totally reverse course on those quote fixes and convert them all to single quotes.

Double quotes in bracket notation skeeve me out.

**Comment by kurtw** [comment]
That's a big :+1: from me.

**Comment by kurtw** [comment]
http://blog.99jobs.com/wp-content/uploads/2014/07/really-nice-o.gif

**Comment by dpford** [comment]
It looks like the Travis build failed because this PR requires an update to Sheer that hasn't been merged yet

**Comment by kurtw** [comment]
Everything is good :+1: Merge when ready.

**Pull request merged**
