### PR TITLE
Test runner

### PR DESCRIPTION
**Pull request by jimmynotjim**
Created a test runner to auto-run every test right from the project root

## Additions

- test.sh to loop through the directories and run their tests
- run.sh in each directory with commands for that test framework

## Removals

- none

## Changes

- none

## Testing

- checkout branch and run `./test.sh`

## Review

- @KimberlyMunoz 
- @dpford 
- @sebworks 
- @kurtw 
- @anselmbradford 

[Preview this PR without the whitespace changes](?w=0)

## Notes

- Should we change the TEST.md to show instructions on using this rather than each test framework?
- Should we make this extensible so we can pass specific tests to run?
- Should we update grunt to use this? What about if we made it extensible?

### CODE REVIEW

**Comment by anselmbradford** [comment]
Why not use https://github.com/jharding/grunt-exec to run the tests via `grunt test`, `grunt test:integration`, `grunt test:unit`, etc.? Requiring shell scripts in the subdirectories for this operation doesn't feel like the right approach.

**Comment by jimmynotjim** [comment]
@anselmbradford I've used grunt-exec in the past, but that project has long been dormant and I don't see it moving forward any time soon

**Comment by anselmbradford** [comment]
@jimmynotjim I don't mean that package specifically, but I mean that conceptually. What about https://github.com/sindresorhus/grunt-shell?

**Comment by jimmynotjim** [comment]
Personally, running python with JS doesn't feel right, and having to add each test manually instead of automating it seemed the simpler solution as far as workflow goes

**Comment by sebworks** [comment]
I would go with using https://github.com/bahamas10/node-exec.  I would also consider adding a grunt setup task which would call the `setup.sh` as well.

**Comment by KimberlyMunoz** [comment]
One nice thing about shell is that we can use it to keep Travis up-to-date if the script we use is the same that the machines use. I've been admiring what 18F has in their [readme](https://github.com/18F/18f.gsa.gov) for building their page and how [Travis can just use that](https://github.com/18F/18f.gsa.gov/blob/staging/.travis.yml).

**Comment by imuchnik** [comment]
I disagree about a shell script. I think shell scripts are nice way to keep everything you need tidy and in one place. Having a shell build scripts means that you can execute the same script locally, Travis and Jenkins. If we standardize the naming and the location of the script, it makes it easier to move from project to project.

**Comment by anselmbradford** [comment]
Let me articulate my thoughts on this a little deeper...

So two things:

1. Shell script:
I'm not opposed to shell scripts, but I'm unclear in this case how it integrates into existing infrastructure. Unless I'm misunderstanding `setup.sh` covers the concerns with Jenkins/Travis, as they'd want to do the full build, right? Additionally, we run linting from within grunt, so I'm not clear how this is intended to work with the existing `grunt test` task. Does it replace it? Are linting and testing being separated as tasks?

2. subdirectory scripts:
I can appreciate the uniformity of having a command across both the project and for each test suite (though for uniformity it seems like the script should perhaps be `test.sh` in the subdirectories too?). However, this creates a cross-folder dependency, in that each project that uses `test.sh` needs to be sure all their test subdirectories also have `run.sh` located in the right place as well. Could the main `test.sh` file contain all the testing commands and be the only file? Breaking apart large opaque files is definitely a good idea, but in this case the size seems minimal. Two other thoughts are it could have flags like `test.sh --unit` and `test.sh --integration` to run specific types of tests. Or it could work like how eslint or jshint work, where if a config file is found in a subdirectory, it uses that in place of the defaults, that way subdirectory scripts aren't required, but can be provided.

**Comment by jimmynotjim** [comment]
1. Yes, I could see this replacing the _testing_ part of `grunt test` rather than having to create individual runners for each suite. My only concern is that macro and processor tests aren't front-end components and I don't know that they belong in grunt (see note 3 in the PR)

2. The idea behind the `run.sh` file is to abstract all the disparate testing suites because only two are anything alike, and as I said they're not even testing front-end components. Yes, we could easily use flags to limit which suites we're running by matching the flag to the directory. ex `./test.sh --browser_tests` would just run the browser tests, I just didn't know if this was worth pursuing (see note 2 in the PR)

**Comment by anselmbradford** [comment]
> Yes, I could see this replacing the testing part of grunt test rather than having to create individual runners for each suite. 

This is still unclear to me, we'd have two commands to run testing and linting? It seems desirable to run all code quality checks together. Doesn't this just off-load individual runners to other files. Conceptually good, but what about offloading the task to a /tasks/ directory instead, so tasks can consistently reference an external location? If grunt or whatever was calling the test scripts, why not just keep it in the grunt world?

> My only concern is that macro and processor tests aren't front-end components and I don't know that they belong in grunt (see note 3 in the PR)

The testing is for the repo's code, not specifically front-end, so that seems fine? Also, looks like I totally overlooked/forgot your notes and you covered ideas I brought up later in the thread! sorry to re-hash :stuck_out_tongue:

> ex ./test.sh --browser_tests would just run the browser tests, I just didn't know if this was worth pursuing (see note 2 in the PR)

Tangentially related, but I'm realizing it would be valuable in moving these testing directories toward the type of testing being done, not the implementation. The browser_tests are all integration tests (is that right @imuchnik ?) If we updated the directories to follow the type of test it means another project that followed our structure here but was all backend wouldn't have to make any changes in `/test/`, ala testing pyramid

**Comment by jimmynotjim** [comment]
After adding these tests to the gulp WIP, I'm on board with them being in the build task. Gulp running them concurrently means they're completed even faster than they are here.

**Pull request closed without merging**
