### PR TITLE
Fixes for Ustream invalid certificate and Event copy changes

### PR DESCRIPTION
**Pull request by sebworks**
Fixes for Ustream invalid certificate and Event copy changes

## Changes

- Modified `cfgov/jinja2/v1/events/_event-detail.html` to fix copy changes. 
- Modified `package.json` to add ustream embed module. 
- Modified `cfgov/unprocessed/css/video-player.less`  to fix hierarchy bug.
- Modified `gulp/config.js` to add reference to static file. Static ustream file will be hot loaded when needed.

## Testing

- run `npm install`
- run gulp build
- Modify the date on a future event to make it a live event.
- Enter `https://www.ustream.tv/embed/10414700?html5ui` as the live stream URL.
- Visit the `http://localhost:8000/about-us/events/`
- Select the event that should be live.
- Hit play and watch the event without any errors.

## Screenshots

screen shot 2017-02-22 at 6 49 48 pm

screen shot 2017-02-22 at 6 51 27 pm

## Notes

-

## Todos

-

## Checklist

* [ ] PR has an informative and human-readable title
* [ ] Changes are limited to a single goal (no scope creep)
* [ ] Code can be automatically merged (no conflicts)
* [ ] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [ ] Passes all existing automated tests
* [ ] New functions include new tests
* [ ] New functions are documented (with a description, list of inputs, and expected output)
* [ ] Placeholder code is flagged
* [ ] Visually tested in supported browsers and devices
* [ ] Project documentation has been updated
* [ ] Reviewers requested with the [Assignee tool](https://help.github.com/articles/assigning-issues-and-pull-requests-to-other-github-users/) :arrow_right:

### CODE REVIEW

**Comment by schaferjh** [comment]
@sebworks In a comment on the GHE issue, it appeared that we are not able to get a HTTPS embed link from Ustream -- if we can only get an HTTP embed link, will this fix still work?

Does this also include the change to the help link Jordana mentioned?

**Comment by sebworks** [comment]
@schaferjh, I'm unsure if it would cause a problem.  My guess is that you would just get a mixed content error but it would still be operable. Yes, I've updated the copy and help link as Jordana requested.

**Comment by sebworks** [comment]
I'm running some test on codepen.io with various browsers. Will update with results.

**Comment by schaferjh** [comment]
> Yes, I've updated the copy and help link as Jordana requested.

Great, thanks!

**Pull request merged**
