### PR TITLE
Fix for using import statements with Mocha / Instanbul

### PR DESCRIPTION
**Pull request by sebworks**
Fix for using import statements with Mocha / Instanbul

## Changes

- Modified test script to fix issue with requiring scripts that contain import statements. 

## Testing

1. Run `gulp test:unit`.

## Checklist

* [ ] PR has an informative and human-readable title
* [ ] Changes are limited to a single goal (no scope creep)
* [ ] Code can be automatically merged (no conflicts)
* [ ] Code follows the standards laid out in the [development playbook](https://github.com/cfpb/development)
* [ ] Passes all existing automated tests
* [ ] Any *change* in functionality is tested
* [ ] New functions are documented (with a description, list of inputs, and expected output)
* [ ] Placeholder code is flagged
* [ ] Visually tested in supported browsers and devices
* [ ] Project documentation has been updated
* [ ] Reviewers requested with the [Reviewer tool](https://help.github.com/articles/about-pull-request-reviews/) :arrow_right:

### CODE REVIEW

**Comment by anselmbradford** [comment]
Hm I dunno, it doesn't seem worth an extra package/copy of babel and the processing just so we can use `import` syntax in test cases. Is there something wrong with the `require` statements as they are that necessitates this?

**Comment by sebworks** [comment]
>> m I dunno, it doesn't seem worth an extra package/copy of babel and the processing just so we can use import syntax in test cases. Is there something wrong with the require statements as they are that necessitates this?

Sorry, so the purpose of this PR is so we can use the import / export syntax is regular modules. If you we don't use babel then we can't use import / export syntax in modules with have tests.

**Comment by anselmbradford** [comment]
Well that's a shame. Would it make sense to share the babel config with webpack. Like export https://github.com/cfpb/cfgov-refresh/blob/master/config/webpack-config.js#L16 and use it in the test.js?

**Comment by sebworks** [comment]
>> Would it make sense to share the babel config with webpack? Like export https://github.com/cfpb/cfgov-refresh/blob/master/config/webpack-config.js#L16 and use it in test.js?

Because we are using gulp and not webpack, then it wouldn't make sense.

**Comment by anselmbradford** [comment]
> Because we are using gulp and not webpack, then it wouldn't make sense.

Why does that matter? They're identical?
https://github.com/cfpb/cfgov-refresh/blob/master/config/webpack-config.js#L22-L27

**Comment by sebworks** [comment]
>> Why does that matter? They're identical?

ok, I thought you were referring to line 16. If we use it in another place then we can swap it to using a config.

**Comment by anselmbradford** [comment]
No worries, I was just thinking if the test babel config was out of sync of the production babel config it could potentially falsely pass, but I approved because I'm not sure it's really worth the extra infrastructure considering we are already sharing the browser list.

**Pull request merged**
