### PR TITLE
adding django mptt

### PR DESCRIPTION
**Pull request by nbucknor**
Added requirements for work on ActivityPage model

## Additions

- Added django-mptt-0.9.0 and django-js-asset-1.1.0 to support nested topic checkboxes in ActivityPage model.

## Removals

- N/A

## Changes

- Updated settings/base.py to import 'mptt' alongside 'teachers_digital_platform' 

## Checklist

- [ ] PR has an informative and human-readable title
- [ ] Changes are limited to a single goal (no scope creep)
- [ ] Code can be automatically merged (no conflicts)
- [ ] Code follows the standards laid out in the [development playbook](https://github.com/cfpb/development)
- [ ] Passes all existing automated tests
- [ ] Any _change_ in functionality is tested
- [ ] New functions are documented (with a description, list of inputs, and expected output)
- [ ] Placeholder code is flagged / future todos are captured in comments
- [ ] Visually tested in supported browsers and devices (see checklist below :point_down:)
- [ ] Project documentation has been updated
- [ ] Reviewers requested with the [Reviewers tool](https://help.github.com/articles/requesting-a-pull-request-review/) :arrow_right:

### Browsers

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Internet Explorer 8, 9, 10, and 11
- [ ] Edge
- [ ] iOS Safari
- [ ] Chrome for Android

### Accessibility

- [ ] Keyboard friendly
- [ ] Screen reader friendly

### Other

- [ ] Is useable without CSS
- [ ] Is useable without JS
- [ ] Flexible from small to large screens
- [ ] No linting errors or warnings
- [ ] JavaScript tests are passing

### CODE REVIEW

**Comment by chosak** [comment]
If these packages are specific to the teachers-digital-platform repo, can they be added to `install_requires` in that repo's [setup.py](https://github.com/cfpb/teachers-digital-platform/blob/master/setup.py#L10) file, instead of adding them globally here? Ideally satellite/third-party packages should bring in/specify their own dependencies.

**Comment by nbucknor** [comment]
Thanks @chosak  I'll do that instead.

**Comment by chosak** [comment]
This looks good but will break until [the version of TDP in the requirements](https://github.com/cfpb/cfgov-refresh/blob/master/requirements/optional-public.txt#L10) has MPTT in its setup.py `install_requires`. Otherwise the settings will be trying to import an app that hasn't been installed.

Please don't merge this until that MPTT release has been made, and the version upgraded in `requirements/optional-public.txt`.

**Comment by nbucknor** [comment]
closing this pull request in favor of pull request #4359

**Pull request closed without merging**
