### PR TITLE
Updated Teachers Digital Platform URL for release

### PR DESCRIPTION
**Pull request by atuggle**
The current release of the Teachers Digital Platform needs the base url to be:
https://www.consumerfinance.gov/practitioner-resources/youth-financial-education/curriculum-review/

[Short description explaining the high-level reason for the pull request]

## Additions

- None

## Removals

- None

## Changes

- Changed 'tdp' to 'practitioner-resources/youth-financial-education/curriculum-review/' in the urls.py

## Testing

1. Verify the new url redirects to the current tdp develop-apps/teachers-digital-platform app

## Checklist

- [x] PR has an informative and human-readable title
- [x] Changes are limited to a single goal (no scope creep)
- [x] Code can be automatically merged (no conflicts)
- [x] Code follows the standards laid out in the [development playbook](https://github.com/cfpb/development)
- [x] Passes all existing automated tests
- [x] Any _change_ in functionality is tested
- [x] New functions are documented (with a description, list of inputs, and expected output)
- [x] Placeholder code is flagged / future todos are captured in comments
- [x] Visually tested in supported browsers and devices (see checklist below :point_down:)
- [x] Project documentation has been updated
- [x] Reviewers requested with the [Reviewers tool](https://help.github.com/articles/requesting-a-pull-request-review/) :arrow_right:

### Browsers

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Internet Explorer 8, 9, 10, and 11
- [ ] Edge
- [ ] iOS Safari
- [ ] Chrome for Android

### Accessibility

- [ ] Keyboard friendly
- [ ] Screen reader friendly

### Other

- [ ] Is useable without CSS
- [ ] Is useable without JS
- [ ] Flexible from small to large screens
- [ ] No linting errors or warnings
- [ ] JavaScript tests are passing

### CODE REVIEW

**Comment by Scotchester** [comment]
@atuggle The Travis failure is for the line length being too long now. Can you either break that onto two lines, or add `  # noqa: E501` at the end of the line? (I am not sure if we have a preference; both are done in this file.)

**Comment by dcmouyard** [comment]
@atuggle Can you update the `requirements/optional-public.txt` file to bump the version of the TDP app to 0.5.11?

That release isn’t ready yet, but it will be shortly after I merge in your work.

**Comment by dcmouyard** [comment]
@atuggle The 0.5.11 release is now ready.

**Comment by atuggle** [comment]
@Scotchester I would like to move forward with this for now, because in another PR request I will have additional feature flags for them. Though I will keep that in mind if it makes sense going forward

**Pull request merged**
