### PR TITLE
Support EmailSignUp organisms in Blog/LearnPage content

### PR DESCRIPTION
**Pull request by chosak**
This PR adds the EmailSignUp organism as an option for content blocks on BlogPage (and thus its descendant NewsroomPage) and LearnPage page types.

## Additions

- New unit tests for EmailSignUp organism.

## Changes

- Added EmailSignUp as an option to the `content` field on BlogPage and LearnPage.

## Testing

- In the Wagtail admin, create a new BlogPage or LearnPage and note that you can now add an EmailSignUp organism to its Content field.

## Screenshots

Content options now include EmailSignUp:

image

EmailSignUp organism rendered as part of blog content:

image

## Checklist

* [X] PR has an informative and human-readable title
* [X] Changes are limited to a single goal (no scope creep)
* [X] Code can be automatically merged (no conflicts)
* [X] Passes all existing automated tests
* [X] New functions include new tests
* [X] Reviewers requested with the [Assignee tool](https://help.github.com/articles/assigning-issues-and-pull-requests-to-other-github-users/) :arrow_right:

### CODE REVIEW

**Comment by sebworks** [comment]
Looks good on my end.  @nataliafitzgerald, should it have a bottom border? background?

**Comment by nataliafitzgerald** [comment]
@sebworks 
I'd like to take a look at this more closely in the habitat where it will live. It would be helpful to see it on a page so that I can see how it interacts with other page components. Is this available to play around with on build or content? 

- Initially I can see that the input field is too wide (I'll want to set it to a narrower width - I'll make a recommendation once I've had a chance to take a closer look). 
- I also don't know about going full width with the slug header (I'll take a closer look)
- When we include an email sign up we typically include a link to the Privacy Act statement. Do we plan to include that here (instead of "We won't share your email address)? 
- If the language for the button is standard across the board what I've typically seen is "Sign up" rather than "Subscribe"

Here's an existing email sign up (that includes the "Privacy Act statement" link and the "Sign up" button language.
screen shot 2017-02-10 at 10 41 50 am


@sarahsimpson09 should probably take a look as well.

**Comment by sarahsimpson09** [comment]
Here is what we use for the email signup module on blog pages currently, and I think we should keep it consistent so that the modules don't vary from page to page within the blog:

Heading: Stay informed
Blog subscription text (This changes slightly based on the subject of newsletter/page type): Subscribe to our email newsletter. We will update you on new blogs.
Btn text: Sign up
Disclaimer: Privacy Act statement

**Comment by chosak** [comment]
I'm going to merge this in so that @nataliafitzgerald can experiment with it on build and propose suggestions.

@sarahsimpson09 are you proposing an alternate approach where there's a distinct BlogEmailSignUp organism with those values hardcoded? Or just defining a convention about how EmailSignUp should be used on blog pages?

**Comment by sarahsimpson09** [comment]
@chosak This is just the convention we use. We have it written down for Wagtail editors here: https://github.cfpb.gov/pages/flapjack/wagtail-documentation/blog_posts.html

*Ideally* this is why I would love for email signups to become snippets so that there are distinct organisms for each email list, so that this all becomes easier.

**Comment by nataliafitzgerald** [comment]
@chosak - I didn't get a chance to review this today but it's on my list for next week. Thanks!

**Comment by nataliafitzgerald** [comment]
@chosak
- It appears that at screen widths of 900-600 the entire sign up module is shifting to half width. This creates a lot of empty space to the right of the sign up module. 
screen shot 2017-02-16 at 8 01 49 pm

**My proposal:** 
- "Heading" element: Full width at all screen widths
- Text field: Behaves like other "Full width text" field body text - 670px wide (full width at screen widths less than 740px)
-  Form field: 370 px (full width at screen widths less than 430px)

**Pull request merged**
