### PR TITLE
Multiselect: Remove client-side data check

### PR DESCRIPTION
**Pull request by anselmbradford**
Now that https://github.com/cfpb/cfgov-refresh/pull/4758 is in, which I think this logic was added for, we can strip out this client-side data check of the select menu options. If this throws an error it seems like it should be fixed on the backend data generating the markup.

## Removals

- `stringValid` utility class.
- Logic in multiselect to check value option values against a restricted character regex.

## Testing

1. `gulp clean && gulp build` should pass and the multiselect in the filter should work as before on http://localhost:8000/about-us/blog/

### CODE REVIEW

**Comment by Scotchester** [comment]
I'm not sure I follow the connection between this and #4758.

Regardless, I agree that it doesn't seem like this code should be needed. The filter form that takes the value of the option and puts it into the query string should just encode the value. If we want people to avoid using characters that would need encoding for aesthetic reasons, that should be a check on the tags when they are created.

**Comment by anselmbradford** [comment]
> I'm not sure I follow the connection between this and #4758.

The old behavior was to show the filter, but there was nothing to filter. Since, I think there were no posts to pull topics from (I think?), the multiselect would bail out and render as regular select markup (see [this wayback machine snapshot](https://web.archive.org/web/20170816162626/https://www.consumerfinance.gov/about-us/events/)). In theory that's good, but the page should really just not show the filter, which Betsy fixed.

**Comment by chosak** [comment]
@wpears by creation time do you mean when a Wagtail editor adds a tag to a page? I believe that Wagtail uses [django-taggit](https://github.com/alex/django-taggit) on the backend and [jQuery Tag-it!](https://github.com/wagtail/wagtail/blob/master/wagtail/admin/static_src/wagtailadmin/js/vendor/tag-it.js) on the frontend. The interface in the admin to add or edit tags on a page looks like this:

image

When rendered on the page (in master) this looks like this:

image


The UI doesn't let you enter a `<` character.

**Comment by wpears** [comment]
@chosak Cool. html escaping was the main worry here.

**Pull request merged**
