### PR TITLE
Use Capital Framework v1.x.x

### PR DESCRIPTION
**Pull request by contolini**
Transition this repo to CF v1.0.0. It's listed as `^1.0.0` in bower.json meaning it will install the latest 1.x.x version (which for now is 1.0.0).

## Additions

- `capital-framework` in bower.json.

## Removals

- Concat task from Gruntfile.js. It's no longer needed.
- All the individual CF components from bower.json.

## Changes

- Import path in main.less.
- Updated CHANGELOG.

## Testing

- Pull down and run `./setup.sh`. Continue as normal and LMK if anything weird happens. The transition should be seamless.

## Review

- @jimmynotjim 
- @anselmbradford 
- @sebworks 
- @KimberlyMunoz 

## Notes

- Should I not be including the compiled `main.css` in pull requests?

### CODE REVIEW

**Comment by jimmynotjim** [comment]
:+1: We should wait to do this till after the sprint PR has been merged to make sure we have time to debug any issues that happen to pop up.

**Comment by contolini** [comment]
@jimmynotjim That makes a lot of sense.

**Comment by Scotchester** [comment]
Posting this here to recap what I said in chat with @contolini and @anselmbradford:

I don't think this change should be accepted for this project. Flapjack is a big and complex enough project that it should keep the flexibility to update individual components one at a time. But that's just my opinion; the actual project team may see it differently :)

**Comment by jimmynotjim** [comment]
I've been running this locally (and then switching out when committing) and I don't see an issue. If we allow ourselves to fall behind, we simply end up behind everyone else. On top of that, updating each component manually requires time away from project tasks, and time is something we are already short on.

The _only_ issue I see is someone not running the latest, then compiling, and our assets being incorrect (I've done this in reverse, forgetting I'm ahead of everyone else). This is a temporary problem and it won't happen once we get the compiled assets out of git.

**Comment by Scotchester** [comment]
It's not an issue until you get a version or two behind in multiple components, then when you go to upgrade, you have to test a lot more changes all at once.

**Comment by Scotchester** [comment]
Testing a whole-framework upgrade is "time away from project tasks" too, and I'd argue that it would take as much time as updating components individually, and would be more error prone.

**Comment by jimmynotjim** [comment]
I guess I look at it from a "if we were using Bootstrap or Foundation, would this be an issue"? With Semver, I don't really think so. If CF components are breaking things that often, then we have bigger issues with how we're releasing code.

**Comment by contolini** [comment]
You'll probably want to kill this PR now that there are conflicts but the changes are easy to implement: https://github.com/contolini/cfgov-refresh/compare/flapjack...contolini:dev?diff=split&expand=1&name=dev

Note: If you choose to list the individual components in bower.json, be sure to have an `@import` rule for each component. Or, you can modify the current Grunt task to concat them into a single file.

**Comment by jimmynotjim** [comment]
I think we can discuss it when everyone is in next Tue.

**Comment by jimmynotjim** [comment]
Going to close because the conflicts will be impossible to fix. We should discuss this tomorrow though.

**Comment by jimmynotjim** [comment]
The more I think about this the more I think we _should_ be using a single CF import. If we were using Bootstrap or Foundation or any other framework it'd be a single source. If a single module were to include a breaking change, it would get a full release, which would also mean CF should get a full release as well.

@contolini I've got this rebased and looking good. Feel free to give me push rights to your repo and I'll send up the fixed version of this code. (viewable here https://github.com/cfpb/cfgov-refresh/compare/cf-v1?expand=1)

@sebworks, @KimberlyMunoz, @anselmbradford We never heard your opinions. How do you feel about a single import that's pegged to a major version?

**Comment by Scotchester** [comment]
I still don't get it.

The entire purpose of modularizing was it to avoid the need to test truckloads of changes (changes to multiple to components) in a single update. Updating one component at a time is much more manageable. We explicitly set out to avoid the pitfall of the big nasty situation you find yourself in when you go to update something like Bootstrap after customizing it a little.

Semantic versioning is a great idea, but on the front end, major/minor and "breaking/nonbreaking" are much more subjective. I think it's very risky to rely on the notion that "nothing will break unless it's a major update". I would much rather test updates to a single component at a time and make sure I'm happy with them or can remediate things I'm not happy with.

But as I said before, if the project team thinks that's what's best for them, vaya con Dios.

**Comment by KimberlyMunoz** [comment]
Testing Capital Framework updates has never been a huge pain point. What has been more of a pain point is useful LESS source maps.

image

I've spent a lot of energy memorizing what module does what in CF because of the concat method we use. I'd like to test the other method to see if it's easier for development.

**Comment by Scotchester** [comment]
@KimberlyMunoz You can still do that with individual Bower dependencies for each component.

**Comment by sebworks** [comment]
:+1:

**Comment by jimmynotjim** [comment]
There's a lot of assumptions that we won't know or be ready for updates, but we're also the team making most of the updates to CF and we use the most components, checking for updates constantly with our setup.sh setup. We also have a multi-step release process so the chances of a CF bug making it to production are very slim. Essentially, we're the team that's best set up to find and fix bugs in CF as they happen, _before_ they get a chance to go live in another project. Right now we're so far behind we're typically the last to know if there's a bug.

The innovation in T&I means we should be exploring and improving our processes. This project isn't live, any bugs that could conceivably make it through our releases to production are negligible. We should be taking advantage of the freedoms we have to push things while we can.

**Comment by anselmbradford** [comment]
Is there any way we can have both worlds? I can't find the thread, but the idea came up of importing the concatenated capital-framework, but overriding individual components with earlier versions if needed, like:

```
// package.json
"capital-framework": "^1.0.0",
"cf-buttons": "git://github.com/cfpb/cf-buttons.git#1.4.2",
```

I can appreciate what @Scotchester is saying here. Maybe I've forgotten, but I feel like we haven't had major architectural updates to CF since we started (maybe react in cf-buttons?), so we haven't had to handle a major breaking change across multiple components. With this change I would just like to know *if needed* that we can easily switch back to pulling in individual components if we find ourselves in an unmanageably large change. It looks like we would need to re-add the concat task for that to happen, which is too bad. Is there any way the selection of components could happen on the CF side and not require that concatenation happens on the importing project side? At very least it would help if the capital-framework repo kept 1 component update = 1 version increment. If something blows up, we can at least walk sequentially through the component updates that way.

I can also appreciate the overhead of keeping individual components up-to-date means many may be further behind than they otherwise might be if one dependency is maintained. So anyway, I'm fine with either (till it blows up :smile: ) ... pre-concatenated or not, neither seems like an ideal solution unfortunately.

**Comment by contolini** [comment]
> With this change I would just like to know if needed that we can easily switch back to pulling in individual components if we find ourselves in an unmanageably large change.

It would be easy.

> It looks like we would need to re-add the concat task for that to happen, which is too bad.

Nah, you would just do

```
@import (less) "@{loc-lib}/cf-icons/src/cf-icons.less";
@import (less) "@{loc-lib}/cf-buttons/src/cf-buttons.less";
@import (less) "@{loc-lib}/cf-expandables/src/cf-expandables.less";
...etc
```

instead of 

```
@import (less) "@{loc-lib}/capital-framework/src/capital-framework.less";
```

> At very least it would help if the capital-framework repo kept 1 component update = 1 version increment. If something blows up, we can at least walk sequentially through the component updates that way.

See versioning convention [proposed here](https://github.com/cfpb/capital-framework/issues/179).

**Comment by Scotchester** [comment]
@jimmynotjim My concern is that unless you're specifically testing out changes to each component that's updated, you might miss out on less obvious regressions, like a change to expandables that breaks the complex layout of something like the History page. If you know you're updating expandables and you specifically look for those kinds of things, you're more likely to catch that than just assuming someone will notice something like that if you update the whole framework.

Breakage isn't the only concern, though. How would you test a new component feature in the project before it's been officially released in the complete framework? If there's a way to override, like @anselmbradford suggests, that's great. If not, you've got to do all the work to release both the component update and the framework update before pulling it into the project, and then you might find out that the new feature doesn't work as well as you planned.

(In practice, I know a lot of this stuff is worked out via cf-enhancements, but I'd like to move away from that and more toward testing out component updates in branches, to increase the likelihood of and velocity which updates get migrated back to the component repos.)

**Comment by Scotchester** [comment]
> The innovation in T&I means we should be exploring and improving our processes. This project isn't live, any bugs that could conceivably make it through our releases to production are negligible. We should be taking advantage of the freedoms we have to push things while we can.

I totally agree with the sentiment; I'm just not seeing what the big advantage of doing this is.

**Comment by contolini** [comment]
The advantage is less maintenance in this repo -- you add CF as a dep and
never touch it. The disadvantage is a higher risk of regressions should we
fail at semver.

On Thursday, July 23, 2015, Scott Cranfill <notifications@github.com> wrote:

> The innovation in T&I means we should be exploring and improving our
> processes. This project isn't live, any bugs that could conceivably make it
> through our releases to production are negligible. We should be taking
> advantage of the freedoms we have to push things while we can.
>
> I totally agree with the sentiment; I'm just not seeing what the big
> advantage of doing this is.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cfpb/cfgov-refresh/pull/608#issuecomment-124214893>.
>


-- 
Chris

**Comment by jimmynotjim** [comment]
@Scotchester It would be awesome to start testing components the way you describe, but until we build a community that supports it, that's not a realistic scenario. Getting one person to even look at a Capital Framework PR is difficult, never mind having them change their project deps, rebuild everything, and test it extensively. Heck, no one's even looked at this variable PR and it's a component from another PR that's already been merged. https://github.com/cfpb/generator-cf/pull/86 I do get people are away this week, but this isn't something new.

On the other hand, if we were to mandate that CF changes must pass through this project and be thoroughly tested before getting the OK to be merged, you'll have me convinced it's worth continuing to keep the dependencies updated manually.

**Comment by Scotchester** [comment]
@jimmynotjim Fair points.

One other thing I realized is that my concern is null and void if the intention is to move to caret dependencies, anyway. Even with components listed as individual dependencies, if not pinned to a version number (or at least tilded), multiple things are going to update regularly, anyway.

I am _not_ in favor of careting front-end dependencies, again citing the fuzzy nature of front-end semver, but I've said my peace. Go for it, and even if I'm right, we'll at least learn the lesson from objective experience ;)

**Comment by jimmynotjim** [comment]
Fixed the issue w/ expandables clashing with the mobile-only utility but there's also a bug w/ cf-core that I've created a PR for https://github.com/cfpb/cf-core/pull/42

**Comment by KimberlyMunoz** [comment]
This needs https://github.com/cfpb/cf-core/pull/42 to be merged, but I'm okay merging this PR first so we can find anything else that might need tweaks earlier in the sprint. :+1:

**Comment by sebworks** [comment]
:+1:

**Comment by jimmynotjim** [comment]
Thanks for testing and @contolini thanks for the hard work toward v1!

**Comment by jimmynotjim** [comment]
Font weight bug auto-fixed itself on the deploy following cf-core update. I call that a win :D

**Comment by KimberlyMunoz** [comment]
And without the designers noticing! 👊🏽

**Pull request merged**
