### PR TITLE
Update the readme image to lose the 'beta' banner

### PR DESCRIPTION
**Pull request by higs4281**
We are live, are we not?

## Additions
homepage.png

## Removals
- screenshot.jpg

## Review

- @cfpb/cfgov-backends @cfpb/cfgov-frontends

### CODE REVIEW

**Comment by schaferjh** [comment]
💯

**Comment by sebworks** [comment]
👍

**Comment by Scotchester** [comment]
There's got to be a way to tell Travis to ignore commits/PRs with only x, y, z files in them, right?

**Comment by higs4281** [comment]
@Scotchester There is, but I forgot to try it. you can add [ci skip] to the commit message.

**Comment by Scotchester** [comment]
That's a pretty unreliable solution :\

I googled-up this concept: using the `before_script` option to immediately stop a build if the only changes are files that don't require a build. Example: https://github.com/facebook/react/pull/2000/files

**Comment by Scotchester** [comment]
Some comments from the Travis issue on the subject: https://github.com/travis-ci/travis-ci/issues/1468#issuecomment-243028101

Merge away, @higs4281.

**Pull request merged**
