### PR TITLE
Integrate wagtail-sharing for sharing of draft content

### PR DESCRIPTION
**Pull request by chosak**
This PR replaces #2664 with a refactored version of [wagtail-sharing](https://github.com/cfpb/wagtail-sharing/tree/shared-site) for improved sharing of Wagtail drafts.

## Additions

- Adds wagtail-sharing to `requirements/base.txt` and as an installed app.

## Removals

- Removes `before_serve_page` hook that would interfere with using e.g. content.localhost:8000 as a local sharing site.

## Changes

- Replace Wagtail fallback URL patterns with those from wagtail-sharing.

## Testing

- Install requirements, create a new local database, and run a local server:

 ```sh
 $ pip install -r requirements/local.txt
 $ ./drop-db.sh && create-mysql-db.sh && initial-data.sh
 $ ./runserver.sh
 ```

- Create a draft page under the root with title "testing" and verify that it is not visible at http://content.localhost:8000/testing/.
- In the Wagtail admin, go to Settings > Sharing Sites and create a new sharing site _for the default localhost:8000 site_ with domain `content.localhost` and port 8000.
- Verify that the draft page is now visible at http://content.localhost:8000/testing/.
- Publish the page, make some changes, and save a new draft.
- Verify that the published state on http://localhost:8000/testing/ and the draft state on http://content.localhost:8000/testing/ differ as expected.

## Screenshots

image

## Todos

- ~~This PR has been opened against [a PR branch](https://github.com/cfpb/wagtail-sharing/pull/7) in wagtail-sharing so will need to be updated when that is merged in.~~ That PR has been merged, requirements have been updated in 48d28b4 to remove the branch reference.
- I need to incorporate feedback from @schaferjh and others about the banner text and exposing the sharing link in the admin.

## Checklist

* [X] PR has an informative and human-readable title
* [X] Changes are limited to a single goal (no scope creep)
* [X] Code can be automatically merged (no conflicts)
* [X] Passes all existing automated tests
* [X] Reviewers requested with the [Assignee tool](https://help.github.com/articles/assigning-issues-and-pull-requests-to-other-github-users/) :arrow_right:

### CODE REVIEW

**Comment by higs4281** [comment]
👍 This works well for me, and will be useful for ask-cfpb workflow.

**Comment by higs4281** [comment]
One oddity I noted: the port number for the shared site seems to be ignored (for the purposes of the "SHARED" links) if the port number for the entries in "sites" is 80.

**Comment by chosak** [comment]
@higs4281 thanks; to clarify, the "SHARED" links functionality is deprecated with this PR, and will be replaced with a new dropdown link implemented in [wagtail-sharing#9](https://github.com/cfpb/wagtail-sharing/pull/9).

**Comment by schaferjh** [comment]
It's all happening!! @willbarton before this is live I would like to communicate about it to the team at large -- this is a note to remind you and me to connect re: deploy date once this is merged.

**Pull request merged**
