### PR TITLE
Output field required note in Spanish if page language is Spanish

### PR DESCRIPTION
**Pull request by Scotchester**
We're about to launch our first (I think) page in Spanish with an email signup form. This PR makes it so that the "(required)" note on a Form Field with Button molecule will appear in Spanish as "(se require)" if the page language is set to Spanish in its Configuration tab.

## Additions

- Template code to check whether a required form field is in English or Spanish and output the required note accordingly

## Testing

1. Pull branch
2. Run server
3. Preview a page with an email sign-up module, like http://localhost:8000/owning-a-home/
4. Observe that the "(required)" note is output as expected in English.
5. Edit that page and change its language to Spanish, then preview again.
6. Observe that the "(se require)" note is output as expected in Spanish.

## Screenshots

screen shot 2017-08-29 at 13 27 17

## Notes

- Need to revisit the class-based hiding/showing of alternate language messages being used on the Share and Expandable modules to see if we can check `page.language` there, as well. I feel like it may not have been possible on those templates for some reason, but I will double-check.

## Todos

- Add a test for this logic?

## Checklist

* [x] PR has an informative and human-readable title
* [x] Changes are limited to a single goal (no scope creep)
* [x] Code can be automatically merged (no conflicts)
* [x] Code follows the standards laid out in the [development playbook](https://github.com/cfpb/development)
* [x] Passes all existing automated tests
* [x] New functions include new tests
* [x] New functions are documented (with a description, list of inputs, and expected output)
* [x] Placeholder code is flagged
* [x] Visually tested in supported browsers and devices
* [x] Project documentation has been updated
* [x] Reviewers requested with the [Assignee tool](https://help.github.com/articles/assigning-issues-and-pull-requests-to-other-github-users/) :arrow_right:

### CODE REVIEW

**Comment by Scotchester** [comment]
**HOLD** on further reviewing for an update to this PR that takes a different approach, following a conversation with @chosak.

**Comment by Scotchester** [comment]
Updated with Andy's suggestion to get the translation via context!

**Comment by willbarton** [comment]
I guess this is fine. It seems like having a strategy to [actually use Django's built in translations](https://docs.djangoproject.com/en/1.11/topics/i18n/translation/) on the website would be better long-term. But I won't drag that soap box out here.

**Comment by Scotchester** [comment]
Updated with tests!

**Comment by Scotchester** [comment]
> I guess this is fine. It seems like having a strategy to actually use Django's built in translations on the website would be better long-term. But I won't drag that soap box out here.

You are, of course, not wrong. But until such a strategy is created...

**Comment by willbarton** [comment]
I'd like a teensy bit of time to see if we could use this as a place to start doing translation properly. If not, then you have my :+1:.

**Comment by willbarton** [comment]
@Scotchester I've opened PR #3295 to add Django translation support to cfgov-refresh. With that PR, the changes I made in 20c2bdb should work here.

The changes that are relevant to your interests are going to be [`form-field-with-button.html` line 35](https://github.com/cfpb/cfgov-refresh/pull/3288/files#diff-a726729d4c265247741944ea2e380d62R35) and [in `cfgov/locale/es/LC_MESSAGES/django.po` on lines 40-41](https://github.com/cfpb/cfgov-refresh/pull/3288/files#diff-5f613a37b47592d3c87460ebee9265e7R40). 

I've also deleted the unittest because it only ends up testing the Django translation system, which I don't think is necessary.

**Comment by willbarton** [comment]
Testing:

1. Pull branch
2. Merge `translation` branch
3. Run server
4. Preview a page with an email sign-up module, like http://localhost:8000/owning-a-home/
5. Observe that the "(required)" note is output as expected in English.
6. Edit that page and change its language to Spanish, then preview again.
7. Observe that the "(se require)" note is output as expected in Spanish.

**Comment by Scotchester** [comment]
Rebased! Merging when Travis finished.

**Pull request merged**
