### PR TITLE
Convert layout to atomic structure 

### PR DESCRIPTION
**Pull request by sebworks**
Convert layout to atomic structure

## Changes

- Modified layout templates to add classes necessary to target child components.

## Testing

- Visit the site and verify we aren't in the Upside Down. 
- Site should work as expected.

## Checklist

* [ ] PR has an informative and human-readable title
* [ ] Changes are limited to a single goal (no scope creep)
* [ ] Code can be automatically merged (no conflicts)
* [ ] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [ ] Passes all existing automated tests
* [ ] New functions include new tests
* [ ] New functions are documented (with a description, list of inputs, and expected output)
* [ ] Placeholder code is flagged
* [ ] Visually tested in supported browsers and devices
* [ ] Project documentation has been updated
* [ ] Reviewers requested with the [Assignee tool](https://help.github.com/articles/assigning-issues-and-pull-requests-to-other-github-users/) :arrow_right:

### CODE REVIEW

**Comment by Scotchester** [comment]
This doesn't require any Less updates?

**Comment by Scotchester** [comment]
Hmm, searching for those older `content__` classes in the Less turns up nothing. What's the point of these classes at all?

**Comment by sebworks** [comment]
no, not yet.  I'm just adding the structure here. The point in having these classes is to be able to target there child components. You can see an example here: https://github.com/cfpb/cfgov-refresh/pull/2785/files#diff-47c9d0d3bee56e6ebcba0cce8d9b46abR17.  The email signup organism looks differently depending on the template / organism.

**Comment by sebworks** [comment]
closing after discussion with @Scotchester.

**Pull request closed without merging**
