### PR TITLE
Remove version number from css banner and package.json

### PR DESCRIPTION
**Pull request by rosskarchner**
Including the version number in built output will lead to files being marked as "changed", even if there aren't actual changes to the code-- busting the cache on every release, instead of just when there are real changes.

This PR stops that from happening. Thank you for the consultation, @sebworks and @contolini!

## Removals

- no more version number in package.json
- no more version number in the 'banner' gulp template.

## Review

- @cfpb/cfgov-frontends 

## Checklist

* [ ] Changes are limited to a single goal (no scope creep)
* [ ] Code can be automatically merged (no conflicts)
* [ ] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [ ] Passes all existing automated tests
* [ ] New functions include new tests
* [ ] New functions are documented (with a description, list of inputs, and expected output)
* [ ] Placeholder code is flagged
* [ ] Visually tested in supported browsers and devices
* [ ] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)

### CODE REVIEW

**Comment by Scotchester** [comment]
I may be wrong, but I think we should keep it in `package.json`. It's a required field, and npm will throw warnings on every `npm install` if it's not there.

The update to `config.js` should be all you need to stop the unintentional cache busting.

**Comment by rosskarchner** [comment]
I figured that would be controversial, and officially have no opinion on it ;)

@contolini might disagree, though?

**Comment by Scotchester** [comment]
@rosskarchner Why was 10.0.3 released before this was merged?

**Comment by contolini** [comment]
Is it used for anything? If it's not (and I don't believe it is), I vote to remove it. Otherwise it's just another thing we have to remember to update when we release cf.gov.

@Scotchester w/ npm version 3.10.3 I don't see any warnings when running `npm install`.

**Comment by rosskarchner** [comment]
I think the side affect (not cache busting on simple on releases) was important enough to get out the door tomorrow with the other bandwidth-saving work, but the package.json change seemed to be worth discussion

**Comment by Scotchester** [comment]
If it's not putting up warnings, I'm cool. :shipit:

**Pull request merged**
