### PR TITLE
Removes unused npm packages.

### PR DESCRIPTION
**Pull request by anselmbradford**
Removes unused npm packages.

## Removals

- Removes `istanbul` and `jsdom` because these are used through `gulp-istanbul` and `mocha-jsdom` respectively.

## Testing

- `gulp test` or `gulp test --sauce=false` not be different from flapjack branch.

## Review

- @KimberlyMunoz 
- @jimmynotjim 
- @sebworks 

## Todos

- mocha-jsdom seems to be using an outdated version of jsdom. I'm going to open a PR over there for it and it'll pull automatically into our project.

### CODE REVIEW

**Comment by jimmynotjim** [comment]
Should we wait to see if we're going to stop using mocha-jsdom?

**Comment by KimberlyMunoz** [comment]
Why would we switch away from mocha-jsdom, @jimmynotjim?

**Comment by jimmynotjim** [comment]
@KimberlyMunoz @anselmbradford brought up a point about it last week. I'll defer to him since he knows better than I do what the issue is.

**Comment by anselmbradford** [comment]
@KimberlyMunoz Jimmy and I chatted about this at regroup because mocha-jsdom was woefully outdated with its jsdom dependency and the repo's tests were broken (running `npm install && npm test` on mocha-jsdom itself was broken), however, it looks like the maintainer may have fixed those issues so we might be good to keep it https://github.com/rstacruz/mocha-jsdom/pull/12 ... in which case this PR should proceed.

**Comment by jimmynotjim** [comment]
In that case :+1:

**Comment by rstacruz** [comment]
> mocha-jsdom seems to be using an outdated version of jsdom. I'm going to open a PR over there for it and it'll pull automatically into our project.

maintainer of mocha-jsdom here, let's see what we can do.

**Comment by rstacruz** [comment]
...just checked now: `jsdom` is not actually required by `mocha-jsdom` as a dependency, you're supposed to install it alongside as a peer dependency.

**Comment by anselmbradford** [comment]
@rstacruz Thanks for the input! We've kept both `jsdom` and `mocha-jsdom` as `devDependencies`, but should we actually add `jsdom` to a `peerDependencies` section like you have it in https://github.com/rstacruz/mocha-jsdom/blob/master/package.json#L29 ?

**Comment by contolini** [comment]
@anselmbradford leave 'em as dev deps. npm deprecated the `peerDependencies` object and in npm 3 it'll throw an error and not install anything. https://github.com/npm/npm/issues/6565

**Comment by anselmbradford** [comment]
So how does this work? `mocha-jsdom` has a version of `jsdom` pegged to `7.0.2` in `devDependencies` and any version in `peerDependencies`. If I pull in the latest major version in `devDependencies` in this project, what happens when jsdom goes to, say, `7.9.0`; all other things being equal? What version is `mocha-jsdom` using in that case?

**Comment by contolini** [comment]
`mocha-jsdom` has `jsdom` listed as a dev dependency because it uses it internally for its own tests. In your example, your project would be using `jsdom` v7.9.0.

```
my-project
├── src
└── node_modules
    ├── jsdom (7.9.0)
    └── mocha-jsdom
```

`devDependencies` are only installed when you run `npm install` from the directory's root. Unlike `dependencies`, they aren't pulled down when you install the project as a dependency of another project. If this was *not* the case, your tree would look like this:

```
my-project
├── src
└── node_modules
    ├── jsdom (7.9.0)
    └── mocha-jsdom
        └── node_modules
            └── jsdom (7.0.2)
```

And your project would use `jsdom` v7.0.2. Which would be bad because you probably wouldn't even realize that was happening and there'd be no way to stop it.

But what if the the module maintainer erroneously added jsdom as a normal dep instead of a dev dep? Then v7.0.2 would get installed and imported and you'd crawl into a corner bawling after spending six hours trying to figure out why you're seeing errors that should be fixed in v7.9.0. Fortunately, this isn't the case with mocha-jsdom because @rstacruz is a crazy smart guy who did everything correctly. But peer deps open up a lot of scary doors so npm decided to stop automatically installing them.

**Comment by rstacruz** [comment]
:point_up: yep, what he said! :)

**Pull request merged**
