### PR TITLE
Use mkDOCter theme for docs

### PR DESCRIPTION
**Pull request by willbarton**
This PR updates the MkDocs configuration to use mkDOCter, a theme for MkDocs that I created to mimic the look of DOCter, the Jekyll theme we use for all our other docs on https://cfpb.github.io. 

## Changes

- Use mkDOCter theme for docs

## Testing

- Visit http://cfpb.github.io/cfgov-refresh/

## Checklist

* [X] Changes are limited to a single goal (no scope creep)
* [X] Code can be automatically merged (no conflicts)
* [ ] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [ ] Passes all existing automated tests
* [ ] New functions include new tests
* [ ] New functions are documented (with a description, list of inputs, and expected output)
* [ ] Placeholder code is flagged
* [ ] Visually tested in supported browsers and devices
* [ ] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)

### CODE REVIEW

**Comment by grapesmoker** [comment]
that's pretty

**Comment by grapesmoker** [comment]
This looks good but I do think we should have images in a separate directory.

**Comment by willbarton** [comment]
@grapesmoker Done!

**Comment by grapesmoker** [comment]
👍

**Pull request merged**
