### PR TITLE
Updates ESLint to v3

### PR DESCRIPTION
**Pull request by anselmbradford**
## Changes

- Updates ESLint to v3 (latest).
- Minor linter file updates:
  - Adds new `line` and `block` sections to `spaced-comment` rule.
  - Adds (but doesn't enforce) the `multiline-ternary` rule.
  - Matches order of rules to ESLint docs.

## Testing

- `gulp lint` should have no errors.

## Review

- @sebworks 
- @jimmynotjim 
- @KimberlyMunoz 
- @contolini 
- @virginiacc

### CODE REVIEW

**Comment by sebworks** [comment]
@anselmbradford , can you provide some brief info about the changes?

**Comment by sebworks** [comment]
Are we just updating to a newer version?

**Comment by anselmbradford** [comment]
Sorry, yes! So ESLint is up to 3.x. This PR adds (but doesn't enforce) the new `multiline-ternary` rule and it updates the `spaced-comment` rule to add separate sections for handling single-line and multi-line comments. 3.x is mostly other changes outside of the rules.

**Comment by anselmbradford** [comment]
Also, I updated the order of the rules to match the ESLint docs.

**Comment by sebworks** [comment]
👍

**Comment by anselmbradford** [comment]
@sebworks This is failing on Travis but passing locally. With shrinkwrapping, does something else need to be updated to get Travis to use an ESLint 3.x version?

**Comment by sebworks** [comment]
> Sorry, yes! So ESLint is up to 3.x. This PR adds (but doesn't enforce) the new multiline-ternary rule and it updates the spaced-comment rule to add separate sections for handling single-line and multi-line comments. 3.x is mostly other changes outside of the rules.

Unsure, @contolini  any clue on this?

**Comment by contolini** [comment]
Dev dependencies aren't shrinkwrapped by default. To update npm-shrinkwrap.json with the new version of gulp-eslint, run the command with the `--dev` option: `npm shrinkwrap --dev`

**Pull request merged**
