### PR TITLE
add urls for legacy 'knowbeforeyouowe' pages

### PR DESCRIPTION
**Pull request by rosskarchner**
Adds a URL ruls for the Django page at /credit-cards/knowbeforeyouowe 

## Additions

- a url rule (pointing to a templateview)

## Testing

- clone  django-cfgov-common (or update your existing checkout) and make sure that you're on master
- clone CFPB/agreement_database (or update your existing checkout) and make sure that you're on master
- `pip install -r path/to/django-cfgov-common`
- `pip install -r path/to/agreement_database`
- observe that http://localhost:8000/credit-cards/knowbeforeyouowe works

## Review

- @kurtw @kave @richaagarwal 

## Checklist

* [x] Changes are limited to a single goal (no scope creep)
* [x] Code can be automatically merged (no conflicts)
* [ ] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [ ] Passes all existing automated tests
* [ ] New functions include new tests
* [ ] New functions are documented (with a description, list of inputs, and expected output)
* [ ] Placeholder code is flagged
* [ ] Visually tested in supported browsers and devices
* [ ] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)

### CODE REVIEW

**Comment by kave** [comment]
@rosskarchner hey theres a template tag for knowbeforeyouowe that it doesn't like
```
TemplateSyntaxError at /credit-cards/knowbeforeyouowe/
'agreements_extras' is not a valid tag library: Template library agreements_extras not found, tried 
```
screen shot 2016-04-19 at 12 31 19 pm

**Comment by rosskarchner** [comment]
ugh, updating the isntructions. That just means there's one more dependency I didn't realize

**Comment by rosskarchner** [comment]
OK, improved the instructions

**Comment by kave** [comment]
@rosskarchner hmm that didn't fix it... is there an additional step after pip install agreement_database

**Comment by kave** [comment]
👍

**Pull request merged**
