### PR TITLE
Update SublandingFilterablePage

### PR DESCRIPTION
**Pull request by richaagarwal**
Update SublandingFilterablePage to match specs - a follow-up to https://github.com/cfpb/cfgov-refresh/pull/1557

## Additions

- Added `text_introduction` and `featured_content` to SublandingFilterablePage

## Removals

-

## Changes

-

## Testing

- Create a SublandingFilterablePage and verify the needed modules are there.

## Review

- @kave @kurtw  @KimberlyMunoz @schaferjh 

## Screenshots

screen shot 2016-03-16 at 10 47 13 am

screen shot 2016-03-16 at 11 05 15 am

## Checklist

* [x] Changes are limited to a single goal (no scope creep)
* [x] Code can be automatically merged (no conflicts)
* [ ] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [x] Passes all existing automated tests
* [ ] New functions include new tests
* [ ] New functions are documented (with a description, list of inputs, and expected output)
* [ ] Placeholder code is flagged
* [x] Visually tested in supported browsers and devices
* [x] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)

### CODE REVIEW

**Comment by schaferjh** [comment]
Yes, that does look odd, which is why I believe the text intro is placed in the content area on the standard sublanding page template, even though it's a header item in concept. Wagtail setup for standard Sublanding pages:

screen shot 2016-03-16 at 9 23 31 am

**Comment by richaagarwal** [comment]
@schaferjh Got it, will do that! I got confused because featured content, as an example, is in the header in BrowseFilterable but in the content in Sublanding, so I thought the text intro might similarly move around.

**Comment by richaagarwal** [comment]
This is ready for review again

**Comment by KimberlyMunoz** [comment]
:+1:

**Comment by kave** [comment]
:+1: looks good to me

**Pull request merged**
