### PR TITLE
Tox environment cleanup

### PR DESCRIPTION
**Pull request by chosak**
This commit cleans up and simplifies the list of available tox environments in `tox.ini`. There's now a single supported main environment (`py27`) which is run with `tox` whether or not you have the `TOXENV` environment variable set.

Documentation in the `tox.ini` file now describes the following available commands:

- `tox -e fast`: run all project unit tests, use the same virtual environment as standard `tox`, don't recreate the virtualenv each time. Also uses special Django settings that skip unneeded migrations.
- `tox -e acceptance`: use the same virtualenv but run browser tests instead of Python unit tests. Also skips unneeded migrations.
- `tox -e acceptance-fast`: same as `acceptance`, but don't recreate the virtual environment each time.
- `tox -e optional`: using a separate virtual environment (named, e.g. `py27-optional`) install optional public Django apps and run their unit tests as well.
- `tox -e optional-fast`: using the same virtualenv as `optional`, run all unit tests but skip unneeded Django migrations.

This change also moves some Travis environment variables into the testing environment for simplification, to avoid needing a separate Travis environment.

In theory this reorganization should make it easier in future to add support for Python3 while maintaining all of these various environments.

## Changes

- `tox.ini` cleanup.

## Testing

- Try running any of the `tox` commands described above. Note that, for example, after you run `tox` once, you can run any of the `-fast` environments without needing to recreate it.

## Checklist

* [X] PR has an informative and human-readable title
* [X] Changes are limited to a single goal (no scope creep)
* [X] Code can be automatically merged (no conflicts)
* [X] Passes all existing automated tests
* [X] New functions are documented (with a description, list of inputs, and expected output)
* [ ] Project documentation has been updated
* [X] Reviewers requested with the [Assignee tool](https://help.github.com/articles/assigning-issues-and-pull-requests-to-other-github-users/) :arrow_right:

### CODE REVIEW

**Comment by sebworks** [comment]
why not have  `tox -e acceptance fast` which would be in line with `tox -e fast` ?

**Comment by sebworks** [comment]
would it be possible to use the verbose flag when running `tox`?

**Comment by chosak** [comment]
@sebworks unfortunately [I don't see a way](http://tox.readthedocs.io/en/latest/config.html) to include verbosity config in the `tox.ini` file. You can run with the `-v` flag which adds a bit more detail to the output.

Regarding running `tox -e acceptance fast`, are you looking to somehow combine two configuration sections into a single run? Unfortunately I couldn't figure out a nice way to do that. I was trying to reproduce that by providing `tox -e acceptance-fast` as a configuration section that brings in the important parts of `acceptance` (the commands) and `fast` (the virtualenv behavior).

**Comment by sebworks** [comment]
> Regarding running tox -e acceptance fast, are you looking to somehow combine two configuration sections into a single run?

yeah, but we can come back to that.

**Pull request merged**
