### PR TITLE
Hotfix: disable factor-bundle

### PR DESCRIPTION
**Pull request by anselmbradford**
Hotfix to disable factor-bundle. Factor-bundle was having issues of not fully writing page-specific
bundles. This commit removes factor-bundle till the issues can be
worked out.

## Removals
- Factor-bundle and dependencies.
- Removes unused `concat:bodyScripts` task and replaces it with
browserify.
- Removes `lintjs` task from `jsdev` till https://github.com/cfpb/cfgov-refresh/issues/300 is closed. It still can be run under `grunt test`.

## Changes

- Changes ESLint to correct alphabetical order in package.json.
- Changes watch task to only watch non-vendor JavaScript.

## Review

- @KimberlyMunoz 
- @sebworks 
- @jimmynotjim 

## Notes

- https://github.com/substack/intreq may be an option if we don't want browserify-shim exposing absolute paths (see https://github.com/thlorenz/browserify-shim/issues/43).
- No change needed to the changelog.

### CODE REVIEW

**Comment by jimmynotjim** [comment]
Looks good to me but I can't test locally now due to terrible conflicts. @KimberlyMunoz or @sebworks, either of you have a chance to test it?

**Comment by sebworks** [comment]
@jimmynotjim , I'll look at it now.

**Comment by sebworks** [comment]
:+1:. No errors or warnings in the console.

**Comment by jimmynotjim** [comment]
That's good enough for me :+1:

**Comment by KimberlyMunoz** [comment]
I'm still getting warnings on `grunt watch` but it seems to be working okay.

**Pull request merged**
