### PR TITLE
Prep the project for Node 8 and NPM 5

### PR DESCRIPTION
**Pull request by jimmynotjim**
NPM 5 introduced lock files, that while appearing to lock the dependencies, are actually updated any time `npm install` or `npm update` is run. To avoid updating the existing shrinkwrap file, the `--no-shrinkwrap` flag has to be passed. Additionally, Node 8 broke the `require-dir` dependency. v0.3.2 is a fix for this error.

## Changes

- Added `--no-shrinkwrap` flag to install task to avoid updating the shrinkwrap file.
- Updated `require-dir` for a bugfix for Node 8

## Testing

1. However you manage Node, update to `node v8.x.x`
2. Update NPM to v5 (be prepared for this to do weird things to your other repos)
3. Clean `node_modules`
4. Run `./frontend.sh`
5. Win!

## Todos

- Look into changing from a shrinkwrap file to package-lock file. I still don't quite understand the differences.

## Checklist

* [x] PR has an informative and human-readable title
* [x] Changes are limited to a single goal (no scope creep)
* [x] Code can be automatically merged (no conflicts)
* [x] Code follows the standards laid out in the [development playbook](https://github.com/cfpb/development)
* [x] Passes all existing automated tests
* [x] New functions include new tests
* [x] New functions are documented (with a description, list of inputs, and expected output)
* [x] Placeholder code is flagged
* [x] Visually tested in supported browsers and devices
* [x] Project documentation has been updated
* [x] Reviewers requested with the [Assignee tool](https://help.github.com/articles/assigning-issues-and-pull-requests-to-other-github-users/) :arrow_right:

### CODE REVIEW

**Comment by wpears** [comment]
:heart:

**Comment by anselmbradford** [comment]
Do we even need `require-dir`? What's it used for?

**Comment by jimmynotjim** [comment]
@wpears I've seen contradicting info on the flag. This seems to imply the deps installed are the versions from the shrinkwrap file, but the file is not updated - https://docs.npmjs.com/files/package-locks#using-locked-packages. 

> your woes will be resolved and it will behave like it says on the tin.

That was my hope, but @contolini and I witnessed the lockfile updating to newer sub deps on CF last week. Of course now that we've committed that file and I've updated Node and NPM locally I can't recreate that. Maybe my local versions were the issue?

Either way, after talking with @sebworks a bit, we figure it's best to go with the latest recommendation. I've updated the project to replace the shrinkwrap file with the package-lock file. Here's hoping it all works out. Travis and Jenkins need to be updated as well, so hold this PR till we get word from @marcesher that Jenkins is done.

**Comment by jimmynotjim** [comment]
Jenkins is done, @sebworks is taking care of Travis. This can be merged once he's finished.

**Comment by sebworks** [comment]
@jimmynotjim, I've modified the travis script.  Please check it out when you get a chance.

**Comment by jimmynotjim** [comment]
@sebworks building fine here. @wpears can you take a look one last time, we've made some changes since your last sign off

**Comment by sebworks** [comment]
This is a great read on it: http://jpospisil.com/2017/06/02/understanding-lock-files-in-npm-5.html

**Pull request merged**
