### PR TITLE
changed static root to global variable

### PR DESCRIPTION
**Pull request by kave**
@kurtw @rosskarchner

### CODE REVIEW

**Comment by rosskarchner** [comment]
Maybe we can split the difference on this?
```python
STATIC_ROOT = os.environ.get('STATIC_ROOT', '/var/www/html/static')
```
That way, there's a sensible default if STATIC_ROOT isn't defined.

I might lobby for DJANGO_STATIC_ROOT -- that way, an admin who isn't familiar with our code, wouldn't have to figure out that it's a django configuration.

**Comment by kave** [comment]
@rosskarchner ok i can agree with that, i've made the change

**Comment by rosskarchner** [comment]
:+1:

**Comment by kurtw** [comment]
:100:

**Pull request merged**
