### PR TITLE
Fix secondary navigation page highlighting

### PR DESCRIPTION
**Pull request by chosak**
This PR fixes a bug with how pages in sidebar navigation were not being highlighted after a transition from HTTP to HTTPS. Previously the logic to determine if a page was selected used

```py
request.url.startswith(item.url)
```
which was prone to problems if the scheme of the two requests differed (HTTP vs HTTPS, which could happen due to load balancers, etc). This change adds a new `item.active` parameter which indicates whether or not the page should be highlighted.

## Notes

Short description explaining the high-level reason for the pull request

## Changes

- Fix to `v1.util.get_secondary_nav_items` that properly indicates which sidebar item should be highlighted.

## Testing

- Using a production data dump, visit
  - http://localhost:8000/about-us/the-bureau/leadership-calendar/
  - http://localhost:8000/about-us/events/archive-past-events/

## Screenshots

image

## Notes

- This code is fairly convoluted which makes it difficult to test efficiently. The sharing logic is due to be removed soon so this will be a quick fix for now.

## Todos

- Clean up this function once sharing logic is removed.

## Checklist

* [X] PR has an informative and human-readable title
* [X] Changes are limited to a single goal (no scope creep)
* [X] Code can be automatically merged (no conflicts)
* [X] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [X] Passes all existing automated tests
* [X] Placeholder code is flagged
* [X] Visually tested in supported browsers and devices
* [X] Reviewers requested with the [Assignee tool](https://help.github.com/articles/assigning-issues-and-pull-requests-to-other-github-users/) :arrow_right:

### CODE REVIEW

**Comment by Scotchester** [comment]
Unfortuantely, this is not fixing the issue for me when running on https://localhost.

I don't know if I can debug why your changes aren't working as intended, but why not fix the root cause by making the generated `href`s in the sidenav be root-relative URLs with no protocol?

**Comment by chosak** [comment]
@Scotchester thanks very much for testing this; you're right that it wasn't working properly. I've pushed another fix in a200305 - would you mind testing again?

I agree it'd be better to have those sidebar pages be root-relative URLs -- frankly, the reason I didn't touch that logic is because it currently uses things like `get_appropriate_page_version` and `get_page_state_url`, both of which should go away once our custom sharing code is removed. The code currently (at least tries to) properly handle "shared" pages, and doing that with relative URLs is a bit more tricky. So if it's okay with you, I'd rather keep this band-aid and look forward to a more thorough cleanup in future.

**Comment by schaferjh** [comment]
@chosak thanks for this -- can you confirm (just because I don't see it called out in the overview above) that this solves the related bug of this section nav not being viewable on mobile? (and thus negating the need for @sebworks #2796?)

**Comment by chosak** [comment]
@schaferjh thanks for the reminder about that -- mobile still looks broken. I'm not super familiar with that code so let me take a quick look at that part of it.

**Comment by Scotchester** [comment]
After pairing with @chosak, I've tested the latest commits and this is working perfect for me locally. :+1:

**Comment by chosak** [comment]
Thanks @Scotchester! @schaferjh I think we have a working solution for both desktop and mobile browsing. As a nice side effect of our work we've fixed the sidebar links so they are now root-relative.

**Comment by schaferjh** [comment]
Exciting! 👍

**Comment by sebworks** [comment]
thanks @chosak @Scotchester

**Pull request merged**
