### PR TITLE
Add use_form field for sub-pages that have forms

### PR DESCRIPTION
**Pull request by kurtw**
This adds the field to determine if the sub-page has a form to show. The field can be accessed like so: sub_page.use_form`. 

## Review
@dford
@KimberlyMunoz 
@anselmbradford 
@sebworks

### CODE REVIEW

**Comment by anselmbradford** [comment]
Appears to warrant an entry in Unreleased > Added section of the changelog.

**Comment by dford** [comment]
I am unrelated to this project but got listed as a reviewer and got a notification.  I think there's been a mistake with names; Daniel Ford is a common name, and maybe you have the wrong username.

**Comment by kurtw** [comment]
Agreed. Updated. Force pull it down. I'm resetting the commit.

**Comment by dpford** [comment]
He's right.  According to [this site](http://howmanyofme.com/) there are 1,038 of us in America alone!

**Comment by anselmbradford** [comment]
I could swear @dpford 's avatar is a photo of him sailing in Massachusetts Bay during his time at Northeastern University.

**Comment by dpford** [comment]
Looks good.  May want to wait until the field is actually showing up in the data (and we confirm it works) before merging

**Pull request merged**
