### PR TITLE
Turns JS off in IE8

### PR DESCRIPTION
**Pull request by anselmbradford**
## Changes

- Disabled JavaScript in IE8 and earlier.

## Testing

- Site should work error-free in IE9 with the `js` class appearing in the `html` element. In IE8, `no-js` class should be present in `html` element and JS should not be loaded—other than the analytics and dependent jquery scripts.

## Review

- @sebworks
- @KimberlyMunoz 
- @jimmynotjim  

## Todos

- If/when https://github.com/azproduction/autopolyfiller/issues/11 is fixed we can use autopolyfiller to handle `classList` for IE9 and remove that polyfill from our codebase.

### CODE REVIEW

**Comment by sebworks** [comment]
I'm so happy about this PR. 

Can we conditionally include the `classList` polyfill?

**Comment by sebworks** [comment]
:+1:

**Comment by anselmbradford** [comment]
> Can we conditionally include the classList polyfill?

Added a modernizr check in https://github.com/cfpb/cfgov-refresh/commit/3430057224e3a24c1abded4045ba71221307e28d How's that look?

**Comment by sebworks** [comment]
yep, works on IE9. :100:

**Comment by KimberlyMunoz** [comment]
It looks like one of the unit tests is failing because modernizr is not defined.

> 1) Get Event States "before all" hook:
     ReferenceError: Modernizr is not defined
      at Object.<anonymous> (cfgov/unprocessed/js/modules/util/dom-traverse.js:9:84)
      at Object.Module._extensions.(anonymous function) [as .js] (node_modules/istanbul/lib/hook.js:107:24)
      at require (internal/module.js:13:17)
      at Object.<anonymous> (cfgov/unprocessed/js/modules/nav-primary.js:9:144)
      at Object.Module._extensions.(anonymous function) [as .js] (node_modules/istanbul/lib/hook.js:107:24)

**Comment by anselmbradford** [comment]
@KimberlyMunoz Fixed! https://github.com/cfpb/cfgov-refresh/commit/540bc46c5173968e5267d77195cf2ec74db6fc5c

**Comment by KimberlyMunoz** [comment]
Everything seems uglier, but working. There's a few things that I wanted to test but I couldn't since they aren't working on our live site: Filtering on the Activity Feed and validation and subscribing to our email list. Expandables look great. The navigation works.

The keyboard skip content link and some of the styles on `main` and `footer` don't seem to be applied. Is modernizr taking care of the HTML5 polyfill?

:+1:

**Comment by KimberlyMunoz** [comment]
:+1: Thanks for fixing the HTML5 shiv and lt-ie9 issues!

**Comment by jimmynotjim** [comment]
This is awesome! Nice work around for the `no-js` class

**Pull request merged**
