### PR TITLE
Fixes spacing on image and text 25/75 organism

### PR DESCRIPTION
**Pull request by anselmbradford**
Fixes spacing on image and text 25/75 organism noted in [GHE]/flapjack/Modules-V1/issues/5#issuecomment-56454

## Changes

- Changes 60px gaps between 25/75 organisms to 90px.

## Testing

- Visit `/landing-page-1/` and `/landing-page-2/`

## Review

- @duelj 
- @KimberlyMunoz 
- @jimmynotjim 
- @sebworks 

## Screenshots

screen shot 2015-10-27 at 2 35 49 pm

### CODE REVIEW

**Comment by jimmynotjim** [comment]
Shouldn't these include the line-rule atom?

**Comment by duelj** [comment]
I agree with @jimmynotjim the rule line should be included. Jimmy and I had been talking about revising the rule line to have padding build into it. Should we start trying to use it in updated form? It seems like it might help some of the spacing questions brought up earlier in this issue.

**Comment by anselmbradford** [comment]
The rule exists in these, but isn't shown in the mocks for the landing pages so I didn't turn it on. `image_text_25_75.render({…}, true)` would turn it on. I remember it was said to move the rule line to the top, but is the idea that it has its own macro? Like `rule_line.render()`? Currently it's a modifier class added to the image and text 25/75 organism that adds a bottom border. Probably best tackled in a separate PR though as 50/50 has the rule too.

**Comment by jimmynotjim** [comment]
It doesn't need to be it's own macro, but we're going to run into an issue if the atom itself isn't used consistently because the 30px of spacing below it will be built in. Molecules/Organisms that are designed with it in mind but don't use it in some situations will either be missing that 30px or need some kind of modifier to add the 30px. I'd like to see as much consistency as possible, so if it should be used in the 25/75, it should always be used. @duelj not sure how that fits into the current designs though.

**Comment by anselmbradford** [comment]
So for this I'd just need to turn https://github.com/cfpb/cfgov-refresh/blob/image_text_spacing/cfgov/preprocessed/css/molecules/image-text-25-75.less#L119 into `border-top`, is that right?

**Comment by anselmbradford** [comment]
Oh and remove the optional aspect?

**Comment by jimmynotjim** [comment]
@anselmbradford I think we need to add a `.rule-break` atom and you'd just include that at top. It doesn't need to be specific to this molecule.

**Comment by anselmbradford** [comment]
Updated and ready for review in https://github.com/cfpb/cfgov-refresh/commit/c295067805af9db04def644621532424d1bdbe4e

Here's what the variations of rules and no rules looks like:
screen shot 2015-10-28 at 1 40 51 pm

**Comment by jimmynotjim** [comment]
:+1:

**Comment by sebworks** [comment]
:+1:

**Pull request merged**
