### PR TITLE
Changing text of H1 above The Bureau intro paragraph

### PR DESCRIPTION
**Pull request by jameshupp**
## Change
The existing text, "Our mission," is not 100% accurate and ended up confusing people in testing. After some discussion, we decided to change.

"The Bureau" was also under consideration, as it mirrors the sidebar text. But the video hero at the top made putting the title there seem a bit anticlimactic. And it felt like that intro paragraph would need a bit of rework. "Who we are" seems like we can leave that text as-is.

## Review
* @schaferjh

### CODE REVIEW

**Comment by schaferjh** [comment]
Wait, I thought we were going with "The Bureau" at the moment? The page is called that in our navigation and it's straightforward if not lyrical.

**Comment by jameshupp** [comment]
You're right. Lyrical isn't the best standard here.

**Comment by sebworks** [comment]
:+1:

**Comment by schaferjh** [comment]
:+1:

**Pull request merged**
