### PR TITLE
Replace jsonfield's JSONField with djangos builtin postgres JSONField

### PR DESCRIPTION
**Pull request by alexm118**
Begins the process of removing the jsonfiled dependency. Creates a new migration that uses django's builting field as well as a squash migration. We need the squash migration so we can actively remove the jsonfield dependency.

---

## Additions

- Migrations around switching to Django's JSONField.

## Removals
 
- Usage of jsonfield library

## Changes

- Which JSONField we are using.

## How to test this PR

1. check the mortgage metadata constants such as FIPS
2. [PFC API](http://localhost:8000/paying-for-college2/understanding-your-financial-aid-offer/api/school/131469/)

## Notes and todos

- This is the first half of the process, once this rolls into production we should remove the old migration files and stick with the sole squashed migration.

## Checklist

- [ ] PR has an informative and human-readable title
  - PR titles are used to generate the change log in [releases](../../releases); good ones make that easier to scan.
  - Consider prefixing, e.g., "Mega Menu: fix layout bug", or "Docs: Update Docker installation instructions".
- [ ] Changes are limited to a single goal (no scope creep)
- [ ] Code follows the standards laid out in the [CFPB development guidelines](https://github.com/cfpb/development)
- [ ] Future todos are captured in comments and/or tickets
- [ ] Project documentation has been updated, potentially one or more of:
  - [This repo’s docs](https://cfpb.github.io/cfgov-refresh/) (edit the files in the `/docs` folder) – for basic, close-to-the-code docs on working with this repo
  - CFGOV/platform wiki on GHE – for internal CFPB developer guidance
  - CFPB/hubcap wiki on GHE – for internal CFPB design and content guidance

### CODE REVIEW

**Comment by alexm118** [comment]
One of the results of moving our JSONField is that we can now pass actual JSON in via fixtures, sorry that it ends up bloating this PR considerably with those changes.

**Comment by willbarton** [comment]
> we can now pass actual JSON in via fixtures

Makes it all worthwhile.

**Comment by alexm118** [comment]
@willbarton Do we want to rename the migration if the intent is to remove the file entirely and use the squashed file when we remove the dependency in a follow up PR?

**Comment by willbarton** [comment]
@alexm118 I think so, because it'll still be in the git history. Our convention is to make sure the migrations have a descriptive name, but there are also plenty of `auto` migrations in that history too.

I'll leave it to your discretion.

**Pull request merged**
