### PR TITLE
Set up new browser tests that use localhost

### PR DESCRIPTION
**Pull request by contolini**
This PR is an extension of https://github.com/cfpb/cfgov-refresh/pull/4407.

Here's what we've done:

1. Copied the current tests in `test/browser_tests/cucumber/` to `test/browser_tests/cucumber-new/` (hence all the new files below).
1. Modified the new tests to use localhost:8000 instead of tox.
1. Added some new Regs3K tests.
1. Created a `gulp test:acceptance:new` task for running the new browser tests. Specific specs can be run with `gulp test:acceptance:new --specs=regulations-search.feature`.

Travis will continue running the legacy tests via `gulp test:acceptance`. Once we [set up Jenkins to build public GitHub PRs](https://github.com/cfpb/cfgov-refresh/pull/4407#issuecomment-411284282), we'll delete the legacy tests.

## Testing

1. Pull down branch
1. Get your local version of cf.gov running at http://localhost:8000
1. Ensure that the following env vars are set (they should already be in your [`.env`](https://github.com/cfpb/cfgov-refresh/blob/master/.env_SAMPLE) file):
   - `export TEST_HTTP_HOST=localhost`
   - `export DJANGO_HTTP_PORT=8000`
1. Run `gulp test:acceptance:new`

## Notes

- Removing the ability to test with `tox` necessitates taking that step out of Travis, which has the side benefit of saving several minutes per Travis build. [This is planned for a future PR once we have another way to automate browser tests without tox, such as with Jenkins against a dev or staging server]

## Checklist

- [x] PR has an informative and human-readable title
- [x] Changes are limited to a single goal (no scope creep)
- [ ] Code can be automatically merged (no conflicts)
- [x] Code follows the standards laid out in the [development playbook](https://github.com/cfpb/development)
- [x] Passes all existing automated tests
- [x] Any _change_ in functionality is tested
- [x] New functions are documented (with a description, list of inputs, and expected output)
- [x] Placeholder code is flagged / future todos are captured in comments
- [x] Visually tested in supported browsers and devices (see checklist below :point_down:)
- [ ] Project documentation has been updated
- [x] Reviewers requested with the [Reviewers tool](https://help.github.com/articles/requesting-a-pull-request-review/) :arrow_right:

### CODE REVIEW

**Comment by cfarm** [comment]
Please clarify because the original PR Notes is confusing/contradicting what was said in FEWD meeting today: Does this PR still keep the tox environment for use on Travis for PRs?

**Comment by Scotchester** [comment]
> Please clarify because the original PR Notes is confusing/contradicting what was said in FEWD meeting today: Does this PR still keep the tox environment for use on Travis for PRs?

Yes. From the OP:

> Travis will continue running the legacy tests via `gulp test:acceptance`. Once we [set up Jenkins to build public GitHub PRs](https://github.com/cfpb/cfgov-refresh/pull/4407#issuecomment-411284282), we'll delete the legacy tests.

**Comment by cfarm** [comment]
Question! With the new tests, can we still run them with all the options documented on this page, such as in this section? https://cfpb.github.io/cfgov-refresh/browser-acceptance-tests/#manual-test-configuration

**Comment by Scotchester** [comment]
> Question! With the new tests, can we still run them with all the options documented on this page, such as in this section? https://cfpb.github.io/cfgov-refresh/browser-acceptance-tests/#manual-test-configuration

@cat Yes, it appears everything works the same way in that regard.

**Pull request merged**
