### PR TITLE
For discussion: Changing our approach to browser tests

### PR DESCRIPTION
**Pull request by Scotchester**
We'd like to make it easier for front-end developers to write browser tests. In the current setup, one of the biggest barriers to this is creating test data via Python. Secondarily, the time it takes to fire up `tox` to run the tests can be annoying, if your environment is out of date.

As most of our FEWDs are accustomed to running a full local environment for testing already, @contolini and I thought, "Why not just have the browser tests run against an already-running local server?"

This PR begins to implement that notion.

## Testing

1. Pull branch
1. Get a local server up and running
1. Ensure that the following env vars are set:
   - `export TEST_HTTP_HOST=localhost`
   - `export DJANGO_HTTP_PORT=8000`
1. Run `gulp test:acceptance:protractor`

## Notes

- Removing the ability to test with `tox` necessitates taking that step out of Travis, which has the side benefit of saving several minutes per Travis build

## Todos

- [ ] Remove all the tox cruft and simplify the `gulp` command to just `gulp test:acceptance`
- [ ] Simplify some of the common JS & config
- [ ] Add the two env vars mentioned above to our default env var lists in the sample files (reconcile with #4391)
- [ ] Modify Travis scripts to remove this step
- [ ] Set up post-deploy smoke tests against Beta in EXT Jenkins
- [ ] Figure out why the protractor-retry functionality isn't working as expected

## Checklist

- [ ] PR has an informative and human-readable title
- [ ] Changes are limited to a single goal (no scope creep)
- [ ] Code can be automatically merged (no conflicts)
- [ ] Code follows the standards laid out in the [development playbook](https://github.com/cfpb/development)
- [ ] Passes all existing automated tests
- [ ] Any _change_ in functionality is tested
- [ ] New functions are documented (with a description, list of inputs, and expected output)
- [ ] Placeholder code is flagged / future todos are captured in comments
- [ ] Visually tested in supported browsers and devices (see checklist below :point_down:)
- [ ] Project documentation has been updated
- [ ] Reviewers requested with the [Reviewers tool](https://help.github.com/articles/requesting-a-pull-request-review/) :arrow_right:

### CODE REVIEW

**Comment by Scotchester** [comment]
Notes from discussion in cf.gov office hours:

- Everyone generally agreed it was a good idea
- Removing the ability to test with `tox` necessitates taking that step out of Travis, which has the side benefit of saving several minutes per Travis build
  - That said, we'll need to do some socializing to set the expectation that folks should run the browser tests locally before merging a PR, since Travis won't be doing it anymore
- Additionally, we want to set up post-deploy and nightly smoke tests against Beta in EXT Jenkins to try and catch any regressions prior to deploying to production
- Folks are interested in having a suite of test pages with as many combinations of different Wagtail blocks and pages as practical
  - @chosak to draft a pitch for a project to develop a method of autogenerating such a suite of pages, with the goal of ending up with something like a [Pattern Lab](https://patternlab.io/) of our Wagtail pages and blocks.

**Comment by anselmbradford** [comment]
> That said, we'll need to do some socializing to set the expectation that folks should run the browser tests locally before merging a PR, since Travis won't be doing it anymore

I don't think this will go as expected. We've had `gulp lint` available to run locally for ages and linter errors frequently made it into the codebase. Myself included being guilty of this. It wasn't till Travis errored on linter errors that it was effectively stopped. Most often it happened when responding to review fixes and forgetting to run checks one final time before merging. Maybe the time saved is worth that, but it would be a good idea to have the infrastructure in place to test on Travis if needed.

**Comment by Scotchester** [comment]
@anselmbradford I hear that; that's a major part of the desire to have the backstop of post-deploy and nightly smoke tests on Jenkins.

I'm not entirely sure how to reconcile getting people to write more tests and still running them through tox. If getting folks to write more browser tests is indeed a goal of ours, I don't think the tox setup is sustainable.

**Comment by cfarm** [comment]
> I'm not entirely sure how to reconcile getting people to write more tests and still running them through tox. If getting folks to write more browser tests is indeed a goal of ours, I don't think the tox setup is sustainable.

The ideal solution would be to write more tests (so not having tox as the dependency here and making it more FEWD-friendly like this PR suggests) and still having the ability to run these in an automated fashion with Travis on PRs. How about building the branches on a dev server that Travis can run the tests against?

**Comment by contolini** [comment]
> How about building the branches on a dev server that Travis can run the tests against?

Travis wouldn't be able to access our dev servers but Jenkins can and there's a [plugin](https://medium.com/@mreigen/integrate-jenkins-builds-into-github-pull-requests-33bc053d6210) that lets it report build statuses the same way Travis does. We actually installed the plugin years ago but had to remove it because we're not allowed to have zusa's URL on a public website.

That policy is pretty silly for things like the demo proxy and I'd love to revisit it. We could create a new demo proxy URL just for PRs, e.g. https://github.demo.XXXX.gov.

**Comment by Scotchester** [comment]
Superseded by #4472.

**Pull request closed without merging**
