### PR TITLE
Fixing the acceptance tests

### PR DESCRIPTION
**Pull request by sebworks**
Fixing the acceptance tests

## Testing

- Run `gulp test:acceptance`

## Review

- @anselmbradford 
- @KimberlyMunoz 
- @jimmynotjim 
- @richaagarwal 
- @kurtw 

## Screenshots

screen shot 2016-02-12 at 6 57 43 pm

### CODE REVIEW

**Comment by richaagarwal** [comment]
:+1: Can we get this merged in sooner than later?

**Comment by kurtw** [comment]
:+1: lgtm

**Comment by jimmynotjim** [comment]
Am I the only one still getting a failure?

```
Failures:
1) The Header Component should load the stylesheet
  Message:
    Expected undefined to contain 'http://localhost:8000/static/css/main.css'.
```

**Comment by sebworks** [comment]
Did you run `gulp build`?

**Comment by jimmynotjim** [comment]
I did, but even if I didn't, the pages wouldn't have styles if this was a true error right?

**Comment by KimberlyMunoz** [comment]
I have 11 failing tests on IE 8.0, some of them have to do with turning of JS. It might be out of scope, but we should make a note to tackle.

**Comment by sebworks** [comment]
@jimmynotjim, I see your point. Is that the only error that you are getting?

**Comment by jimmynotjim** [comment]
It is, but it could also be killing the tests, cause they aren't taking very long.

**Comment by sebworks** [comment]
@KimberlyMunoz , I'll create a separate PR for the `no-js` experience.

**Comment by richaagarwal** [comment]
Jimmy, I think that's a different issue (and one I was running into last week). Try running setup.sh ?

**Comment by kave** [comment]
looks good to me. all pass :+1:

**Comment by anselmbradford** [comment]
:+1:

**Pull request merged**
