### PR TITLE
global_include in all supported template environments

### PR DESCRIPTION
**Pull request by rosskarchner**
Sheerlike sites need to run in their own isolated template environments, to avoid collisions with v1 and other sheer sites (for example, they all have their own 'index.html')

Similarly, legacy django apps exist in another silo, in that they can't reference v1's Jinja2 templates.

With this, we provide a way of breaking out of those silos, and pulling in (rendered) templates from v1. This will primarily be useful for applying a single header/footer to all of these pages.

## Additions

- a global_include function is made available across all Jinja2 pages (including Sheer sites)
- a similar django template tag is created

## Testing

- clone django-cfgov-common, cfgov-selfregistration, and fin-ed-resources as siblings to your checkout of cfgov-refresh.
- build fin-ed-resources per it's instructions
- for the other two repos, be sure to check out their 'django18' branch
- `pip install -e ../django-cfgov-common`
- `pip install -e ../cfgov-selfregistration`
- `cfgov/manage.py migrate`
- `cfgov/manage.py sheer_index`
- in fin-ed-resources/dist/_includes/nemo_header.html, try changing the whole file to:
```
 <div class="nemo">                                                               
      {{ global_include('organisms/header.html') }}                                
  </div> {# END .nemo #} 
```
- take a look at http://localhost:8000/tax-preparer-resources/ and see our header (minus css) displayed on that page
- in django-cfgov-common/cfpb_common/templates/front/base_update.html, add this to the top (after `{% load static %}`
```
{% load global_include %}
```
and, try deleteing the `<div class=nemo>` with just:
```
{% global_include "organisms/header.html" %} 
```
... and see as similarly busted version of the navigation.

(this test is just to demonstrate the functionality-- the work of applying the header globally certainly won't involve editing 'dist' files-- though django-cfgov-common will be important for legacy django apps, and may be the only place you need to apply the change)

## Review

- @anselmbradford @kave @richaagarwal @kurtw 

## Checklist

* [x] Changes are limited to a single goal (no scope creep)
* [x] Code can be automatically merged (no conflicts)
* [ ] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [x] Passes all existing automated tests
* [ ] New functions include new tests
* [ ] New functions are documented (with a description, list of inputs, and expected output)
* [ ] Placeholder code is flagged
* [ ] Visually tested in supported browsers and devices
* [ ] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)

### CODE REVIEW

**Comment by rosskarchner** [comment]
thanks @anselmbradford for pushing me on this-- my first inclination was to just change the header in every repo where the old one exists. That would work, but would be a huge headache every time we change the nav.

**Comment by schaferjh** [comment]
So this looks pretty awesome -- can you explain here or can we chat early on Monday to help me understand what this means for spreading the header/footer across everything on cfgov-next/beta in the next few days?

**Comment by rosskarchner** [comment]
In the short term,  it's probably not that different - instead of copying the header and footer everywhere,  we edit those projects to use global_include. 

Going forward though,  we can manage the header and footer in v1, and it'll propagate to those other projects,  reducing the maintenance effort. 

(doesn't help with WordPress and static pages though)

**Comment by Scotchester** [comment]
If I understand what's happening here, holy :poop:!

Gonna test this out today.

**Comment by kurtw** [comment]
No installation instructions [here](https://github.cfpb.gov/CFGOV/fin-ed-resources) @rosskarchner @Scotchester

**Comment by Scotchester** [comment]
Sorry about that, @kurtw. A bit of doc debt I keep forgetting about. What's the error you got?

**Comment by kurtw** [comment]
```
module.js:338
    throw err;
    ^

Error: Cannot find module 'lru-cache'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /Users/wallk/cfgov/projects/fin-ed-resources/node_modules/grunt/node_modules/findup-sync/node_modules/glob/node_modules/minimatch/minimatch.js:35:11
    at Object.<anonymous> (/Users/wallk/cfgov/projects/fin-ed-resources/node_modules/grunt/node_modules/findup-sync/node_modules/glob/node_modules/minimatch/minimatch.js:1057:3)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```

**Comment by Scotchester** [comment]
@kurtw Make sure you're using npm v3+

**Comment by kave** [comment]
@Scotchester i got an error on the grunt build

```
Running "less:main" (less) task
>> FileError: '../../normalize-css/normalize.css' wasn't found. Tried - node_modules/normalize-css/normalize.css,node_modules/normalize-css/normalize.css,node_modules/normalize-css/normalize.css,node_modules/normalize-css/normalize.css,node_modules/normalize-css/normalize.css,node_modules/normalize-css/normalize.css,node_modules/normalize-css/normalize.css,node_modules/normalize-css/normalize.css,node_modules/normalize-css/normalize.css,node_modules/normalize-css/normalize.css,../../normalize-css/normalize.css in node_modules/cf-core/src/cf-core.less on line 6, column 1:
>> 5 
>> 6 @import (less) "../../normalize-css/normalize.css";
>> 7 @import (less) "../../normalize-legacy-addon/normalize-legacy-addon.css";
Warning: Error compiling src/static/css/main.less Use --force to continue.

Aborted due to warnings.
```

**Comment by Scotchester** [comment]
@kave Are you using npm v3+?

**Comment by kave** [comment]
@Scotchester yea `3.8.5`

**Comment by Scotchester** [comment]
Not sure why it's not working for @kave, but I tested this yesterday with Ross and it seemed to work very well.

I'd like this to be merged, and then I will proceed with updating each of the Sheer projects to use this method. The override method from #1806 is clever, but doesn't provide an obvious way to get the necessary static assets (CSS and JS) into the template.

**Comment by rosskarchner** [comment]
Lend me thine thumbs!

**Comment by rosskarchner** [comment]
no, wait, @anselmbradford is going to pull these changes into #1796

**Comment by rosskarchner** [comment]
Not all of these changes made it into Ans's PR, so merging this

**Pull request merged**
