### PR TITLE
Compress outgoing HTML

### PR DESCRIPTION
**Pull request by rosskarchner**
This adds middleware that compresses our HTML output.  The improvement depends on the page, but in my tests page sizes are reduced about 20-40%

## Additions

- the django-htmlmin package and the middleware it provides

## Testing

- By default, this is *enabled* when DEBUG is *disabled*. To try it out while developing locally, temporary add `HTML_MINIFY = True` to your settings/local.py
- run the server and view source, and you should see the minified HTML

## Review

- @cfpb/cfgov-backends 
- @cfpb/cfgov-frontends 

## Checklist

* [x] Changes are limited to a single goal (no scope creep)
* [x] Code can be automatically merged (no conflicts)
* [ ] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [ ] Passes all existing automated tests
* [ ] New functions include new tests
* [ ] New functions are documented (with a description, list of inputs, and expected output)
* [ ] Placeholder code is flagged
* [ ] Visually tested in supported browsers and devices
* [ ] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)

### CODE REVIEW

**Comment by chosak** [comment]
Do we care about keeping [this](https://github.com/cfpb/cfgov-refresh/blob/master/cfgov/jinja2/v1/_layouts/base.html#L6) important comment in the HTML?

**Comment by rosskarchner** [comment]
That's an excellent question-- there is a 'KEEP_COMMENTS_ON_MINIFYING' if needed.

Recruiting via HTML comments seems very 2013 to me, though ;)

**Comment by sebworks** [comment]
> Recruiting via HTML comments seems very 2013 to me, though ;)

I agree, in addition no one views source on a phone / tablet. @ascott1, what do you think?

**Comment by KimberlyMunoz** [comment]
[We can always recruit via console.log](http://i.imgur.com/b7UtDLT.png)

**Comment by rosskarchner** [comment]
Or [HTTP headers](https://www.maxcdn.com/blog/recruiting-humans-http-headers/) ;)

**Comment by rosskarchner** [comment]
@chosak I just bugged Adam about this-- he's a little sad about losing the comment, but is OK with it.

**Pull request merged**
