### PR TITLE
DFJR-1122-career section content updates

### PR DESCRIPTION
**Pull request by anselmbradford**
## Changes

- Updates content in the careers section

## Testing

- Updates `/careers/` noted in gdoc linked in DFJR-1122 task.

## Review

- @tnferrell 
- @schaferjh 

## Screenshots

screen shot 2016-03-29 at 11 12 58 am

screen shot 2016-03-29 at 11 13 08 am

screen shot 2016-03-29 at 11 13 42 am

screen shot 2016-03-29 at 11 16 17 am

### CODE REVIEW

**Comment by jimmynotjim** [comment]
:+1:

**Comment by schaferjh** [comment]
Looking nice! Just one other thing -- did you update the link to the Office of Civil Rights in the Related links blob on all the career pages? I think that was 404ing.

**Comment by anselmbradford** [comment]
@schaferjh Yup! Updated here https://github.com/cfpb/cfgov-refresh/pull/1738/files#diff-ea674273701190fe56b548da23d3afaeR9 to `/office-civil-rights/`

**Comment by schaferjh** [comment]
Great, thanks!

**Pull request merged**
