### PR TITLE
Updates incorrect link

### PR DESCRIPTION
**Pull request by anselmbradford**
## Changes

- Updates incorrect link in mega menu.

## Testing

- Visit link in beta.

## Review

- @schaferjh

### CODE REVIEW

**Comment by schaferjh** [comment]
yup, thanks. :+1:

**Comment by KimberlyMunoz** [comment]
Does this have to get changed on WordPress?

**Comment by schaferjh** [comment]
@KimberlyMunoz I don't believe so as it's only present in the mobile nav in the 3rd level, which is not part of the static WordPress nav.

**Comment by KimberlyMunoz** [comment]
:relieved:

**Pull request merged**
