### PR TITLE
Secondary Navigation Fix

### LINKED ISSUE #652: New "In this Section" mobile nav needs some separation
@KimberlyMunoz [pointed out](https://github.com/cfpb/cfgov-refresh/pull/648#issuecomment-111629020) that with the new breadcrumb nav above the mobile nav, there's no separation between the two. Not sure when the mobile nav changed, but it used to look more like the breadcrumb mockup she linked to when I first started the breadcrumbs.

cc @ajbush @duelj @schaferjh

### PR DESCRIPTION
**Pull request by jimmynotjim**
Small fix for the secondary navigation background and border on small screens

## Additions

- None

## Removals

- None

## Changes

- Added a top border and 10% gray bg to the nav

## Testing

- navigate to any secondary page that uses the side-nav on a small screen

## Review

- @schaferjh 
- @sebworks 
- @KimberlyMunoz 
- @anselmbradford 

## Preview

screen shot 2015-06-15 at 2 09 59 pm

screen shot 2015-06-15 at 2 10 07 pm

[Preview this PR without the whitespace changes](?w=0)

## Notes

- Before the nav was a stack of buttons, because that changed, the styles were lost.
- Fixes #652

### CODE REVIEW

**Comment by ascott1** [comment]
Heads up on this to the Owning a Home team. @cfarm @stephanieosan @virginiacc

**Comment by jimmynotjim** [comment]
I wouldn't grab anything for Owning-A-Home just yet. @Scotchester and I are discussing other changes that are going to be made as well.

**Comment by KimberlyMunoz** [comment]
LGTM

**Comment by jimmynotjim** [comment]
Updated with latest from flapjack branch. Still ok to merge?

**Comment by sebworks** [comment]
LGTM

**Pull request merged**
