### PR TITLE
Squash migrations

### PR DESCRIPTION
**Pull request by richaagarwal**
Kurt started this work in another PR (https://github.com/cfpb/cfgov-refresh/pull/1402) but it seemed easier to start from scratch.

Custom migrations lived in:
```
# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# v1.migrations.0032_cfgovimage_cfgovrendition
# v1.migrations.0012_share_perms
# v1.migrations.0057_auto_20160304_1651
# v1.migrations.0055_auto_20160224_2201
```

@rosskarchner @kurtw @kave 

We will need to run `python cfgov/manage.py migrate --fake` on the servers after this is deployed.

## Testing

`./drop-db.sh && ./create-mysql-db.sh && python cfgov/manage.py migrate`

### CODE REVIEW

**Comment by rosskarchner** [comment]
- I think we should all agree to hold off on other models changes until this is merged.
- @richaagarwal , I did get an error, after running migrate on an empty database: https://gist.github.com/rosskarchner/96d931b23596dd0b4102763f49f89ec6

**Comment by richaagarwal** [comment]
@rosskarchner Ah thanks! I'll take a look.

**Comment by kave** [comment]
@richaagarwal hey could you look at https://github.com/cfpb/cfgov-refresh/pull/1402/files as a reference for the squashed migrations. we are doing some custom stuff like in 0002 (Creating share permissions) that will need to be maintained

**Comment by kave** [comment]
@rosskarchner @kurtw yea sure, i have no qualms with a model freeze until this is merged.

**Comment by richaagarwal** [comment]
Ready for review again.

**Comment by kave** [comment]
@richaagarwal after looking at those custom migrations the only important one is `v1.migrations.0012_share_perms` everything else can be ignored

**Comment by rosskarchner** [comment]
The travis error looks like it might actually be legit: https://travis-ci.org/cfpb/cfgov-refresh/builds/129816922#L2421

**Comment by richaagarwal** [comment]
So the travis error should go away after we run `python cfgov/manage.py migrate --fake` on the servers.  I think this is ready to be merged in assuming it's working locally (on a clean db) for everyone.

**Comment by kurtw** [comment]
👍

**Comment by kave** [comment]
@richaagarwal can we merge this yet?

**Comment by kave** [comment]
actually travis failure looks legit
```
$ python cfgov/manage.py migrate
Traceback (most recent call last):
  File "cfgov/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 93, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/db/migrations/executor.py", line 19, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/db/migrations/loader.py", line 47, in __init__
    self.build_graph()
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/db/migrations/loader.py", line 185, in build_graph
    self.load_disk()
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/db/migrations/loader.py", line 103, in load_disk
    migration_module = import_module("%s.%s" % (module_name, migration_name))
  File "/opt/python/2.7.9/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/travis/build/cfpb/cfgov-refresh/cfgov/v1/migrations/0001_initial.py", line 24, in <module>
    class Migration(migrations.Migration):
  File "/home/travis/build/cfpb/cfgov-refresh/cfgov/v1/migrations/0001_initial.py", line 60, in Migration
    ('collection', models.ForeignKey(related_name='+', default=wagtail.wagtailcore.models.get_root_collection_id, verbose_name='collection', to='wagtailcore.Collection')),
AttributeError: 'module' object has no attribute 'get_root_collection_id'
```

**Comment by jimmynotjim** [comment]
@richaagarwal I got

```
Traceback (most recent call last):
  File "cfgov/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/wilsong/.virtualenvs/cfgov-refresh/lib/python2.7/site-packages/django/core/management/__init__.py", line 351, in execute_from_command_line
    utility.execute()
  File "/Users/wilsong/.virtualenvs/cfgov-refresh/lib/python2.7/site-packages/django/core/management/__init__.py", line 343, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/wilsong/.virtualenvs/cfgov-refresh/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/wilsong/.virtualenvs/cfgov-refresh/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/Users/wilsong/.virtualenvs/cfgov-refresh/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 93, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/Users/wilsong/.virtualenvs/cfgov-refresh/lib/python2.7/site-packages/django/db/migrations/executor.py", line 19, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/Users/wilsong/.virtualenvs/cfgov-refresh/lib/python2.7/site-packages/django/db/migrations/loader.py", line 47, in __init__
    self.build_graph()
  File "/Users/wilsong/.virtualenvs/cfgov-refresh/lib/python2.7/site-packages/django/db/migrations/loader.py", line 176, in build_graph
    self.load_disk()
  File "/Users/wilsong/.virtualenvs/cfgov-refresh/lib/python2.7/site-packages/django/db/migrations/loader.py", line 102, in load_disk
    migration_module = import_module("%s.%s" % (module_name, migration_name))
  File "/Users/wilsong/homebrew/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/wilsong/repos/cfpb/cfgov-refresh/cfgov/v1/migrations/0001_initial.py", line 24, in <module>
    class Migration(migrations.Migration):
  File "/Users/wilsong/repos/cfpb/cfgov-refresh/cfgov/v1/migrations/0001_initial.py", line 60, in Migration
    ('collection', models.ForeignKey(related_name='+', default=wagtail.wagtailcore.models.get_root_collection_id, verbose_name='collection', to='wagtailcore.Collection')),
AttributeError: 'module' object has no attribute 'get_root_collection_id'
```

Sorry.

**Comment by richaagarwal** [comment]
Closing this while I debug further

**Pull request closed without merging**
