### PR TITLE
Add a slugified ID to snippet lists

### PR DESCRIPTION
**Pull request by jimmynotjim**
The team needs the ability to create anchor links that point to snippet lists,
especially when there are multiple lists to a page.

## Changes

- Added slugified ID attribute to the snippet list parent container.

## Testing

- Create a browse page with a snippet list, ensure you include a heading, but it doesn't even need snippets to work.
- Preview the page and inspect the `o-snippet-list` element.

## Screenshots

screen shot 2017-05-04 at 3 46 36 pm

## Notes

- Users must ensure they use unique snippet list headings __for the page__, not for all lists ever created, otherwise the page will have two identical IDs.

## Checklist

* [x] PR has an informative and human-readable title
* [x] Changes are limited to a single goal (no scope creep)
* [x] Code can be automatically merged (no conflicts)
* [x] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [x] Passes all existing automated tests
* [x] New functions include new tests
* [x] New functions are documented (with a description, list of inputs, and expected output)
* [x] Placeholder code is flagged
* [x] Visually tested in supported browsers and devices
* [x] Project documentation has been updated
* [x] Reviewers requested with the [Assignee tool](https://help.github.com/articles/assigning-issues-and-pull-requests-to-other-github-users/) :arrow_right:

### CODE REVIEW

**Comment by chosak** [comment]
I notice that if you leave the Snippet List Heading field blank, it generates this:

```html
<div class="o-snippet-list" id="">
```

Is this bad? Worth wrapping [this line](https://github.com/cfpb/cfgov-refresh/pull/2898/files#diff-2a2e6b06a3c86386763aeebfe04b9d55R40) in something like this?

```html
<div class="o-snippet-list"{% if value.heading %} id="{{ value.heading|slugify }}"{% endif %}>
```

**Comment by Scotchester** [comment]
@chosak It shouldn't have any ill effects.

**Comment by chosak** [comment]
@Scotchester good to know, although it does seem to [fail W3C validation](http://stackoverflow.com/a/6535989).

image

**Comment by Scotchester** [comment]
Ah dangit.

@jimmynotjim Which ever one of us is mucking around in cfgov-refresh next, let's fix that.

**Comment by jimmynotjim** [comment]
You know, I wrapped it for a minute after we discussed that, but decided the readability was better unwrapped. I'll fix it.

**Pull request merged**
