### PR TITLE
Adds a `grunt watch` config to watch for changes to .html files, and execute the copy task

### PR DESCRIPTION
**Pull request by rosskarchner**
I wonder if there's a way to make this more surgical: ie, only copy the file that
changed.

### CODE REVIEW

**Comment by jimmynotjim** [comment]
Ha, I was just doing the exact same thing. This is what I was going to use, for all file types not just html https://www.npmjs.com/package/grunt-changed

**Comment by jimmynotjim** [comment]
:+1:

**Comment by sebworks** [comment]
:100:

**Comment by rosskarchner** [comment]
That looks pretty slick, and probably better. Want me to close this one?

**Comment by jimmynotjim** [comment]
Oh no, merge this, it's a good first step

**Comment by jimmynotjim** [comment]
Hmmm, I've tried both grunt changed and https://github.com/tschaub/grunt-newer but no luck, it's still trying to move all the files. Also looked at https://github.com/tomusdrw/grunt-sync but it looks dead. This is the issue with Grunt, seems people are moving on and projects are stagnating.

**Comment by rosskarchner** [comment]
If we add a 'watch' rules for images and fonts, would that cover everything?

**Pull request merged**
