### PR TITLE
npm shrinkwrap and snyk

### PR DESCRIPTION
**Pull request by KimberlyMunoz**
Added npm shrinkwrap and ran snyk policy to patch vulnerable dependencies

## Additions

- Added npm shrinkwrap and ran snyk policy to patch vulnerable dependencies
- Added .npmrc file to keep our dependencies fixed

## Removals

- Removed gulp-sitespeedio since we weren't using it and the project isn't updated often enough to address their old dependencies

## Testing

- run frontend.sh

## Review

- @anselmbradford 
- @jimmynotjim 
- @sebworks 
- @ascott1 

## Notes

- There's still some vulnerabilities with browser-sync's dependencies, but since we're only using that locally, it should be okay for now.

## Checklist

* [ ] Changes are limited to a single goal (no scope creep)
* [ ] Code can be automatically merged (no conflicts)
* [ ] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [ ] Passes all existing automated tests
* [ ] New functions include new tests
* [ ] New functions are documented (with a description, list of inputs, and expected output)
* [ ] Placeholder code is flagged
* [ ] Visually tested in supported browsers and devices
* [ ] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)

### CODE REVIEW

**Comment by ascott1** [comment]
@KimberlyMunoz This looks great!

Waht does `snyk protect` do in the build? Could that be removed from the Travis file/build?

**Comment by KimberlyMunoz** [comment]
I'll remove it and see how Travis responds.

**Comment by ascott1** [comment]
:+1:

**Comment by jimmynotjim** [comment]
:+1:

**Pull request merged**
