### PR TITLE
Mega menu: Adjustments to featured links

### PR DESCRIPTION
**Pull request by anselmbradford**
Removes DS list classes, since more needed to be overridden than was being applied. It was only used for setting the left padding value to zero. 

## Removals

- Code comment to move menu-specific variable to DS, which doesn't make sense.

## Changes

- Removes DS list classes.
- Moves featured link icons into their associated links.

## Testing

1. Pull branch and build and visit homepage. 
2. Expand menu and visit featured links.
3. Resize page to see at responsive sizes.
4. compare to beta.consumerfinance.gov

## Screenshots

hover

## Todos

- External link utility needs adjusting to work again.

### CODE REVIEW

**Comment by anselmbradford** [comment]
@contolini

**Comment by huetingj** [comment]
@anselmbradford let's change the featured item's star icon to black on hover to fall more in line with the hover behavior of the links below it. thank you!

**Comment by contolini** [comment]
> let's change the featured item's star icon to black on hover to fall more in line with the hover behavior of the links below it

It'd also be dope if the entire featured card was clickable (star included) but we can save that for a future PR.

**Comment by contolini** [comment]
> let's change the featured item's star icon to black on hover to fall more in line with the hover behavior of the links below it

It'd also be dope if the entire featured card was clickable (star included) but we can save that for a future PR.

**Comment by chosak** [comment]
@anselmbradford pushed icon fix in 580a14a, but now icon is too close to text:
image

**Pull request merged**
