### PR TITLE
Fix paginator bug

### PR DESCRIPTION
**Pull request by kurtw**
@jimmynotjim

### CODE REVIEW

**Comment by jimmynotjim** [comment]
This fixes the 500 error, but now the filtering message is missing. I think the issue is really that posts.paginator doesn't exist.

**Comment by kurtw** [comment]
Should be ready

**Comment by kave** [comment]
:+1: pow

**Comment by jimmynotjim** [comment]
Working, thanks. I'll address the spacing issue in another PR

**Pull request merged**
