### PR TITLE
Update fallback meta description text

### PR DESCRIPTION
**Pull request by Scotchester**
Not prototyping anymore!

## Changes

- Fallback meta description text

## Review

- @anselmbradford 
- @schaferjh 

## Checklist

* [ ] Changes are limited to a single goal (no scope creep)
* [ ] Code can be automatically merged (no conflicts)
* [ ] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [ ] Passes all existing automated tests
* [ ] New functions include new tests
* [ ] New functions are documented (with a description, list of inputs, and expected output)
* [ ] Placeholder code is flagged
* [ ] Visually tested in supported browsers and devices
* [ ] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)

### CODE REVIEW

**Comment by jimmynotjim** [comment]
👍

**Comment by anselmbradford** [comment]
Can we put the else block on its own line 😄 

👍

**Comment by Scotchester** [comment]
Updated Jinja formatting. I _think_ that'll format the output as desired, but someone may want to test.

**Comment by schaferjh** [comment]
Woot! 👍

**Comment by anselmbradford** [comment]
👍

**Pull request merged**
