### PR TITLE
Removing padding and width from CTA

### PR DESCRIPTION
**Pull request by sebworks**
Removing padding and width from CTA

## Changes

- Modified `cfgov/unprocessed/css/molecules/call-to-action.less` to remove padding and width from the Call to Action molecule. This brings it back inline with our Atomic philosophy. 

## Testing

- Add a Call To Action to a Sub-landing page
- Preview and verify that it has no top / bottom margin or padding.

## Screenshots
- 
screen shot 2017-04-20 at 2 39 57 pm

## Notes

- There is essentially no margin on the CTA within the Full Width Text organism.  You will have to control spacing using the Rich Text Editor.
- Wrapping everything in a block is a mistake, if you aren't going to allow editors to control spacing for the block from Wagtail. 

## Todos

-

## Checklist

* [ ] PR has an informative and human-readable title
* [ ] Changes are limited to a single goal (no scope creep)
* [ ] Code can be automatically merged (no conflicts)
* [ ] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [ ] Passes all existing automated tests
* [ ] New functions include new tests
* [ ] New functions are documented (with a description, list of inputs, and expected output)
* [ ] Placeholder code is flagged
* [ ] Visually tested in supported browsers and devices
* [ ] Project documentation has been updated
* [ ] Reviewers requested with the [Assignee tool](https://help.github.com/articles/assigning-issues-and-pull-requests-to-other-github-users/) :arrow_right:

### CODE REVIEW

**Comment by Scotchester** [comment]
I do not like the idea of encouraging/requiring editors to put blank paragraphs in a rich text field to get adequate margin above the CTA button.

**Comment by anselmbradford** [comment]
> I do not like the idea of encouraging/requiring editors to put blank paragraphs in a rich text field to get adequate margin above the CTA button.

Agreed, but it's current behavior already :\

**Comment by Scotchester** [comment]
> Agreed, but it's current behavior already :\

What do you mean? Then what's the point of this PR?

**Comment by jimmynotjim** [comment]
I'm confused, we're getting rid of it because "it's not atomic" which I agree with, but instead we're going to leave it up to content editors to manipulate the rich text to do as they wish? Just because folks are already doing that doesn't really justify breaking a spacing pattern. Shouldn't the padding and grid styles be moved to the parent rather than be removed all together?

**Comment by Scotchester** [comment]
NM, Ans, I looked closer at the proposed changes and see what you mean. This isn't affecting the space _before_ a CTA.

But yeah, as @jimmynotjim said, the Full Width Text organism should be determining spacing between its child molecules, right?

**Comment by sebworks** [comment]
The CTA is used within the Full Width Text Organism and outside it.  If it's outside it then it typically will get wrapped in a block. Inside it, I don't think it makes sense to try and control the spacing via CSS or Jinja

I would much rather have them use the Rich Text Editor, as an interim solution. Using CSS or wrapping the elements doesn't give consistency across the pages. You simply can't account for the various combinations of components with CSS or Jinja. You won't end up with consistent spacing.

The ultimate solution is to allow them to control all spacing from Wagtail using the interface. They also need the ability to ensure the spacing they are setting isn't violating a Design Manual guideline. 

The padding and width were added when we weren't wrapping everything in blocks.

**Comment by jimmynotjim** [comment]
@sebworks can you link to what this is fixing currently so I can understand the context a bit more?

**Comment by Scotchester** [comment]
Leaving spacing to people putting empty lines in the rich text field is not a recipe for consistency.

**Comment by sebworks** [comment]
It's really just a bug @jimmynotjim

**Pull request merged**
