### PR TITLE
Use Yarn instead of npm

### PR DESCRIPTION
**Pull request by contolini**
Yarn simplifies aspects of Node dependency management, notably dependency version locking (`npm-shrinkwrap.json` with npm, `yarn.lock` with yarn). Shrinkwrapping has proven painful for us and our CI environments.

## Additions

- Yarn's lock file.

## Removals

- npm's shrinkwrap file.

## Changes

- All npm install commands replaced with yarn.
- Updated Travis' nvm version and told it to use yarn.

## Testing

- Pull down `yarn` branch.
- `./setup.sh`
- Confirm that there are no console errors and the site works locally as expected.

### CODE REVIEW

**Comment by sebworks** [comment]
What's the deal on this?

**Comment by anselmbradford** [comment]
Now that package-lock is in, do we still think we'll go a yarn route some day?

**Comment by sebworks** [comment]
@anselmbradford, yeah, I don't think we need it anymore.

**Comment by anselmbradford** [comment]
@contolini

**Pull request closed without merging**
