### PR TITLE
Hook up glossary terms to PortalSearchPages

### PR DESCRIPTION
**Pull request by richaagarwal**
### Overview
- As a follow-up to #5000, this hooks up glossary terms to PortalSearchPage results for the category "Key terms".  Instead of displaying answer pages tagged with the portal category "Key terms", glossary term snippets for the given portal topic will be displayed.

- This only impacts the portal_category_page and not the portal_topic_page for a PortalSearchPage.  Answer pages that are tagged "Key terms" for a given topic will continue to show up on the portal_topic_page. 

### Testing 
- Pull down the most recent data dump
- Look at various key terms pages 
  - http://localhost:8000/consumer-tools/mortgages/answers/key-terms/
  - http://localhost:8000/consumer-tools/student-loans/answers/key-terms/
  - http://localhost:8000/es/obtener-respuestas/cuentas-bancarias/respuestas/palabras-claves/

### Screenshots
Screen Shot 2019-05-15 at 6 31 11 PM

Screen Shot 2019-05-15 at 6 30 28 PM

### TODO
- [x] Add tests
- [x] Finalize language for link text to answer page URL - should it be "Read full answer" or something else? @sonnakim 
- [x] Some of the text requires clean-up in production  (e.g. the `<div id="negative-amortization">Negative amortization</div>` you can see in the screenshot above) - until that is done, we should not merge this.

### CODE REVIEW

**Comment by sonnakim** [comment]
@richa This looks great. Could the links appear inline with the paragraph, as shown below?  The English link language should be "Read more":  

image

image

**Comment by sonnakim** [comment]
> Some of the text requires clean-up in production (e.g. the <div id="negative-amortization">Negative amortization</div> you can see in the screenshot above) - until that is done, we should not merge this. 

Another clean-up note before merging: some of the Spanish definitions have placeholder strings where I need to re-introduce line breaks.

**Comment by richa** [comment]
wrong Richa. @richaagarwal is the correct one :)

**Comment by richaagarwal** [comment]
This is ready for a final review!

**Pull request merged**
