### PR TITLE
Update GitHub actions node to 12.x

### PR DESCRIPTION
**Pull request by anselmbradford**
## Changes

- Change GitHub actions node to 12.x from 10.x
- Updates docs to make Node 12 the default minimum.

## How to test this PR

1. See GitHub actions in this PR

### CODE REVIEW

**Comment by contolini** [comment]
Change [this line](https://github.com/cfpb/cfgov-refresh/blob/master/package.json#L16) as well.

**Comment by anselmbradford** [comment]
Y'all we have too many node version settings spread everywhere.

**Comment by contolini** [comment]
Eek yeah we probably don't need every sub-package.json to list an engine. I bet we copied the main package.json when we created those apps and didn't bother to remove unnecessary stuff.

**Comment by willbarton** [comment]
We're now building in Node 12! Let's do this!

**Pull request merged**
