### PR TITLE
Tweak Docker setup for local development

### PR DESCRIPTION
**Pull request by willbarton**
This PR makes a few tweaks to our (wonderful) docker local development setup.

## Additions

- Adds `eval $(docker-machine env)` to shell.sh and attach.sh in case the user forgets to run it (as I frequently find myself doing)
- Adds `.python_env` to `.gitignore`
- Adds a `docker` argument to `setup.sh` and `runserver.sh` to allow them to still be used for setup and running.
- Adds the ability to run a command directly with `shell.sh`, i.e. `./shell.sh cfgov/manage.py migrate`

## Changes

- Fixes the link to the usage document in the installation instructions
- Fixes the comment formatting in the `.gitignore` file
- Updates the documentation for the above changes.

## Checklist

* [x] PR has an informative and human-readable title
* [ ] Changes are limited to a single goal (no scope creep)
* [ ] Code can be automatically merged (no conflicts)
* [ ] Code follows the standards laid out in the [development playbook](https://github.com/cfpb/development)
* [ ] Passes all existing automated tests
* [ ] Any *change* in functionality is tested
* [ ] New functions are documented (with a description, list of inputs, and expected output)
* [ ] Placeholder code is flagged
* [ ] Visually tested in supported browsers and devices
* [ ] Project documentation has been updated
* [ ] Reviewers requested with the [Reviewer tool](https://help.github.com/articles/about-pull-request-reviews/) :arrow_right:

### CODE REVIEW

**Comment by rosskarchner** [comment]
I agree about .python_env--

The other change would break things for people who *aren't* using Docker machine (say, a user with the official Docker for mac installed, or a Linux user). I think that's worth avoiding? Maybe it's acceptable, though

In the docs, I brought up the possibility of using autoenv for that.

**Comment by willbarton** [comment]
@rosskarchner but aren't shell.sh and attach.sh only useful with docker? How does adding the eval there break non-docker folks?

**Comment by willbarton** [comment]
I've also added a proposed modification to `setup.sh` and `runserver.sh` so that they can be run as they are now, *or* with `docker` as the first argument. 

If `setup.sh` is run as `setup.sh docker` then the `mac-virtualbox-init.sh` script is run. 

If `runserver.sh` is run as runserver.sh docker` then the `docker-compose up` is run. 

@rosskarchner, what do you think of that? That'd make the broad-strokes of the current workflow similar for both approaches.

**Comment by rosskarchner** [comment]
not "Non-Docker", but "Non-Docker-Machine".

Docker Machine is only a necessary piece where you need to run the docker daemon in a VM. The official "Docker for Mac" does some other magic, which uses the native OS X hypervisor. On Linux (and I think, Windows, in some scenarios at least) Docker runs natively and Docker Machine isn't neccessary.

**Comment by rosskarchner** [comment]
I like the runserver and setup changes!

**Comment by rosskarchner** [comment]
Should update the docs, tho ;)

**Comment by willbarton** [comment]
Alrighty, updated the documentation and added the frontend setup to running `setup.sh docker`.

**Pull request merged**
