### PR TITLE
Post CSS cleanup

### LINKED ISSUE #271: Post entry footer needs a clearfix
Some blog posts and all event posts have a floating sidebar inside the `post_body` content. If this sidebar is taller than the body copy, the sidebar floats to the right of the tags, which are in the post's `<footer>`. This element should have a clearfix applied, e.g. `clear: both;`.

Screenshot:
screen shot 2015-02-23 at 3 18 23 pm

### PR DESCRIPTION
**Pull request by anselmbradford**
Cleans up post CSS type.

## Additions

- Fixes #271 - adds clearfix to post body.

## Removals

- None.

## Changes

- Changes `post_header` class to be `post_heading`, to be consistent
with the `summary_heading` and be more semantically correct.
- Changes the `post_dek` to paragraph, because that’s what it is.
- Fixes typo in cheat sheet.
- Includes elements in cheat sheet and fixes structural issues and
missing elements from the cheat sheet.

## Testing

- Visit a blog entry with a sidebar and remove the body content till the post aside sidebar is higher in height than the blog body copy.

## Review

- @jimmynotjim 
- @sebworks 
- @Scotchester 

## Preview

Before:
screen shot 2015-02-23 at 4 20 43 pm

After:
screen shot 2015-02-23 at 4 21 58 pm

### CODE REVIEW

**Comment by jimmynotjim** [comment]
:+1:

Should this be merged into gh-pages since it's existing and outside the Sprint? I'm ok with it waiting till Sprint-21 gets merged in, but figured I'd ask.

**Comment by anselmbradford** [comment]
I figure it's easier in sprint-21 so it gets another review when all the pieces are in. Probably better to do all work (outside e.g. Readme updates) on the sprint branch, and do more rigorous checks every two weeks when sprint branch goes into gh-pages.

**Comment by jimmynotjim** [comment]
Sounds good. You'll need to pull the latest from sprint-21 to get a merge.

**Comment by anselmbradford** [comment]
Done!

**Pull request merged**
