### PR TITLE
Add requirements.txt file for Snyk to consume

### PR DESCRIPTION
**Pull request by Scotchester**
This file's purpose is to be checked for vulnerabilities by Snyk, which requires a file named `requirements.txt`.

## Additions

- `requirements.txt` file for Snyk

## Testing

We won't be able to test this until we merge and use the Snyk UI to try and add this file to watch it.

## Notes

- I'm not certain Snyk will use the `-r` directive to pull in the dependencies from the other files. I guess we'll have to try it and see.
- Another potential solution would be to put each requirements file in a subdirectory of its name, and then have the files all be named `requirements.txt`. We could then add one or more of those files to what Snyk is monitoring. Both that and the solution proposed here are inelegant, but this seems preferable to me.

## Checklist

- [x] PR has an informative and human-readable title
- [x] Changes are limited to a single goal (no scope creep)
- [x] Code can be automatically merged (no conflicts)
- [x] Code follows the standards laid out in the [CFPB development guidelines](https://github.com/cfpb/development)
- [x] Passes all existing automated tests
- [x] Any _change_ in functionality is tested
- [x] New functions are documented (with a description, list of inputs, and expected output)
- [x] Placeholder code is flagged / future todos are captured in comments
- [x] Visually tested in supported browsers and devices (see checklist below :point_down:)
- [x] Project documentation has been updated
- [x] Reviewers requested with the [Reviewers tool](https://help.github.com/articles/requesting-a-pull-request-review/) :arrow_right:

### CODE REVIEW

**Comment by marcesher** [comment]
@Scotchester this makes sense to me, provided that snyk is smart enough to follow included dependencies files.

**Comment by ascott1** [comment]
I think that we need to merge it to test. An alternative would be to create a dummy repo for testing this approach.

**Comment by willbarton** [comment]
image

**Comment by Scotchester** [comment]
No good :(

screen shot 2019-02-06 at 11 44 38

**Comment by marcesher** [comment]
huh, bummer.

I wonder:

1. perhaps we can submit a support ticket, user voice, or some other thing to snyk for consideration
2. would github actions open up an easy way to just automatically copy the contents of deploy.txt into requirements.txt when changes are made to it? I'm thinking: what are options we have for getting the benefit of snyk here without creating a ton of work on maintaining duplicate files

**Comment by anselmbradford** [comment]
Hmm my latest PR is getting this now:
screen shot 2019-02-06 at 1 50 44 pm

**Comment by ascott1** [comment]
👍 Thanks for taking a wack at this @Scotchester

**Comment by willbarton** [comment]
I feel really uncomfortable with option 2, since that would require us to have our requirements specified in two places *committed in the repo* that could easily get out-of-sync if someone's not careful.

**Comment by chosak** [comment]
Snyk's command line tool offers additional flexibility that the web UI does not, for example [specifying alternate filenames for requirements.txt](https://snyk.io/docs/cli-test/#manifest-files-with-custom-names). Could we use the command line tool to monitor for vulnerabilities instead of relying on the web UI?

**Comment by willbarton** [comment]
I would add, GitHub seems to have no issue reading separate requirements files:

https://github.com/cfpb/cfgov-refresh/network/alerts?q=is%3Aclosed

**Comment by anselmbradford** [comment]
> Snyk's command line tool offers additional flexibility that the web UI does not, for example [specifying alternate filenames for requirements.txt](https://snyk.io/docs/cli-test/#manifest-files-with-custom-names). Could we use the command line tool to monitor for vulnerabilities instead of relying on the web UI?

For the node modules we already have the snyk cli set up at `npm test`, so this may be fairly straightforward to adjust.

**Comment by Scotchester** [comment]
The nice thing about getting it monitored in the Snyk.io app is that it monitors proactively and emails us, it doesn't just happen on PR checks.

But, perhaps we can live with only doing it on PR checks for cfgov-refresh, given the amount of traffic it gets.

**Comment by willbarton** [comment]
What's the advantage of Snyk over GitHub's built-in vulnerability monitoring?

**Comment by Scotchester** [comment]
> What's the advantage of Snyk over GitHub's built-in vulnerability monitoring?

I'm not sure. Possibly none? @ascott1?

**Comment by ascott1** [comment]
Snyk does a much more thorough job. It uses both CVE and NVD's vulnerability databases as well as maintaining their own independent list that is compiled from several other sources and security researches at Snyk. IIRC Github only uses CVE.

**Comment by ascott1** [comment]
And I agree that we should work with Snyk to encourage them to implement a way to scan multiple and uniquely named requirement files. In the meantime, I don't think it's _that_ awful of an anti-pattern to explore pulling the production dependencies into a `requirements.txt` file. 

That said, I would also be comfortable with running the `snyk-cli` on Python dependencies as part of Travis build, if it's that big of a sticking point for y'all.

**Comment by willbarton** [comment]
Let's run `snyk-cli` in Travis then. I'm strongly opposed to committing a generated `requirements.txt` file.

**Pull request merged**
