### PR TITLE
Removed all forms from project

### PR DESCRIPTION
**Pull request by KimberlyMunoz**
Since we aren't including forms our v1 launch, they are being removed from the project. Content may need to rework the content, I think it should happen after this PR so they can easily see what they have to work with once we remove the content on the flapjack branch.

## Review
- @jimmynotjim 
- @anselmbradford 
- @sebworks 
- @richaagarwal

### CODE REVIEW

**Comment by richaagarwal** [comment]
This looks good to me. At least, it resolves some of my failing tests :)

**Comment by jimmynotjim** [comment]
I hadn't realized we were removing them all. :+1: on cutting scope!

**Comment by KimberlyMunoz** [comment]
One sec, I just realized there's form tests that need to be removed too!

**Comment by KimberlyMunoz** [comment]
Removed!

**Comment by anselmbradford** [comment]
Yeah, I didn't know we were removing them either :+1:

**Comment by kave** [comment]
:+1:

**Pull request merged**
