### PR TITLE
Update external link/icons logic

### PR DESCRIPTION
**Pull request by richaagarwal**
Anything that's not an internal page, including other .gov pages, should show the external link icon.  Anything that's leaving .gov pages should take the user to the external-site page.

## Testing

- Go to [http://localhost:8000/cfpb-ombudsman/ombudsman-faqs/](http://localhost:8000/cfpb-ombudsman/ombudsman-faqs/) & confirm that under "Do the other federal financial agencies have an ombudsman?", the links show the external icon but DO NOT take you to the external-site page.
- Click on the facebook icon & confirm that it takes you to the external-site page. (I can't find an example of a link that's not already an icon, but if you can, confirm that it shows the external icon as well). 
- View any cf.gov links and confirm they neither show the icon or take you to the external-site page.

## Review

- @kave @rosskarchner @kurtw 

## Screenshots

screen shot 2016-03-29 at 12 54 19 pm

## Checklist

* [x] Changes are limited to a single goal (no scope creep)
* [x] Code can be automatically merged (no conflicts)
* [ ] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [x] Passes all existing automated tests
* [ ] New functions include new tests
* [ ] New functions are documented (with a description, list of inputs, and expected output)
* [ ] Placeholder code is flagged
* [ ] Visually tested in supported browsers and devices
* [x] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)

### CODE REVIEW

**Comment by rosskarchner** [comment]
Works as advertised :+1: 

Is @schaferjh's feedback about the extra space something can be done?

**Comment by richaagarwal** [comment]
Oh, right, forgot to respond about that.  I think it is possibly, but it might be a front end thing?  They were the ones that added the CSS for the icon, right?

If everything looks good otherwise, I'll go ahead and merge.

**Comment by Scotchester** [comment]
The space between the text and the icon has to be created by including a space character on both sides of the `<span>` element within the `<a>`, e.g.:

```html
<a class="icon-link icon-link__external-link" href="#"> <span class="icon-link_text">link text</span> </a>
```

Can the HTML output by this code be made to include that?

**Comment by richaagarwal** [comment]
@Scotchester oh thanks! I can do that then.

**Pull request merged**
