### PR TITLE
About us page content fixes & browser test fixes

### PR DESCRIPTION
**Pull request by KimberlyMunoz**
A bunch of fixes to the content of the about us page. Mostly changing things to sentence case.

While I was fixing a browser test, I also fixed a few broken ones in the footer.

## Testing

- Visit /about-us/, half blob titles should be in sentence case now

## Review

- @jimmynotjim 
- @sebworks 
- @anselmbradford 

## Checklist

* [ ] Changes are limited to a single goal (no scope creep)
* [ ] Code can be automatically merged (no conflicts)
* [ ] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [ ] Passes all existing automated tests
* [ ] New functions include new tests
* [ ] New functions are documented (with a description, list of inputs, and expected output)
* [ ] Placeholder code is flagged
* [ ] Visually tested in supported browsers and devices
* [ ] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)

### CODE REVIEW

**Comment by sebworks** [comment]
:+1:

**Comment by schaferjh** [comment]
Just going through this page again on beta and realized there are a handful of the links that are now broken due to URL changes -- were these part of this work? (Trying to remember, let me know if not and if they need to be logged separately!)

**Comment by KimberlyMunoz** [comment]
No, this is just changes on the `/about-us/` pages. Are those broken links all on office pages?

**Comment by schaferjh** [comment]
They're on `/about-us/` -- I added a comment to the jira task this morning.

**Comment by sebworks** [comment]
@KimberlyMunoz , I pushed an update to the branch which directed the `.gov` links to the external redirect page. This was part of the reason the test were failing.

**Comment by jimmynotjim** [comment]
:+1:

**Comment by sebworks** [comment]
:+1:

**Pull request merged**
