### PR TITLE
Add newsletter subscription form to Offices index

### PR DESCRIPTION
**Pull request by virginiacc**

### CODE REVIEW

**Comment by himedlooff** [comment]
Merge conflicts!

**Comment by jimmynotjim** [comment]
@virginiacc Do you want one of the new FEWDs to update this for the conflicts? Didn't want to start grabbing work if it's already in-progress.

**Comment by jimmynotjim** [comment]
Looks like this conflict only needed a bump from `gh-pages`. I'm not exactly sure what's changing here, @Scotchester want to look it over when you have a second? Once it's good I'll merge it locally and push it back up to `origin`

**Comment by virginiacc** [comment]
Sorry, @jimmynotjim, just saw this. The merge conflicts should be resolved now. 

Basically, this pr adds a newsletter subscription form to the offices page when an office has opted in by providing a govdelivery code, & adapts the email subscription form to accept a govdelivery code as an alternative to a query.

**Comment by jimmynotjim** [comment]
@virginiacc sounds good to me. Merging!

**Pull request merged**
