### PR TITLE
Update and remove unneeded dependencies

### PR DESCRIPTION
**Pull request by anselmbradford**
Fixes high severity security issues noted by snyk.

## Removals

- Apparently unused `marked` dependency.

## Changes

- Make async gulp tasks return that weren't properly.
- Update `is-reachable`, `localtunnel`, and `snyk`.

## Testing

1. `npm install`
2. `gulp audit:perf` should pass and show no error at the end.

### CODE REVIEW

**Comment by jimmynotjim** [comment]
No errors, assuming the output is expected?

```
Threshold of 70 not met with score of 51
```

**Comment by anselmbradford** [comment]
> No errors, assuming the output is expected?

Yup! All good.

**Comment by Scotchester** [comment]
@anselmbradford The merging of this PR started failing Jenkins builds:

``` bash
> node scripts/npm/apps-install

./cfgov/unprocessed/apps/analytics-gtm's npm output: added 4 packages in 5.354s

./cfgov/unprocessed/apps/owning-a-home's npm output: added 50 packages in 10.14s

./cfgov/unprocessed/apps/regulations3k's npm output: added 142 packages in 6.147s

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 1584 packages in 106.157s
Building project…
module.js:549
    throw err;
    ^

Error: Cannot find module 'ansi-colors'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/lib/jenkins/jobs/cf.gov-ansible-build/workspace/cfgov/gulp/tasks/test.js:1:82)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at requireDir (/var/lib/jenkins/jobs/cf.gov-ansible-build/workspace/cfgov/node_modules/require-dir/index.js:126:33)
    at Object.<anonymous> (/var/lib/jenkins/jobs/cf.gov-ansible-build/workspace/cfgov/gulpfile.js:15:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
```

**Comment by anselmbradford** [comment]
Huh, uh okay. I might just remove that altogether and inline the red color. It's only used in one place. I'll open a PR.

**Pull request merged**
