### PR TITLE
Be less "clever" when setting BaseURL

### PR DESCRIPTION
**Pull request by rosskarchner**
The 'master' version of this fix should probably use environment variables (but default to localhost if the variable is unset)

### CODE REVIEW

**Comment by willbarton** [comment]
This looks okay, I'm not sure I understand what using localhost will do here though.

**Comment by rosskarchner** [comment]
When PDF reactor needs to reach back to Django to retrieve assets (like CSS and images) , it uses the Base URL to resolve relative URL's

**Comment by willbarton** [comment]
Ah, alright.

:+1:

**Comment by anselmbradford** [comment]
Perhaps this is too clever, but would it ever not be `localhost`? Like should it use https://github.com/cfpb/cfgov-refresh/blob/master/.env_SAMPLE#L121 or equivalent?

**Comment by willbarton** [comment]
@anselmbradford We've talked about moving pdfreactor off to its own server (or dockerization, or some way to isolate it). In that case, it would not be localhost.

**Comment by rosskarchner** [comment]
I'm going to go ahead and merge this, since I made the change live on prod anyways

**Comment by chosak** [comment]
> I'm going to go ahead and merge this, since I made the change live on prod anyways

I insist that we get T-shirts with this @willbarton.

**Comment by willbarton** [comment]
:+1:

**Comment by rosskarchner** [comment]
I've done that twice today, but I swear, it's never happened before!

**Pull request merged**
