### PR TITLE
Fail Python unit tests if anything writes to stdout

### PR DESCRIPTION
**Pull request by willbarton**
This PR is a proposal for capturing stdout while unit tests run and then failing the tests if anything writes to it. It does this by capturing all stdout during the test run and asserting that it is empty at the end. It uses `redirect_stdout` from Python 3's `contextlib` and a function that approximates it in Python 2.

One disadvantage to this approach is that you don't know where the text came from necessarily. The test run looks like this:

```
Creating test database for alias 'default'...
applying migration wagtail.wagtailcore.migrations.0002_initial_data
applying migration wagtail.wagtailcore.migrations.0025_collection_initial_data
.
----------------------------------------------------------------------
Ran 1 test in 0.113s

OK
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)

    … (typical traceback) …

AssertionError: there is content in stdout: this is a test

ERROR: InvocationError: '/Users/bartonw/repos/platform/cfgov-refresh/.tox/py27/bin/coverage run --source=. manage.py test cfgov.tests'
_____________________________________________________________________________________________________________________ summary _____________________________________________________________________________________________________________________
ERROR:   fast: commands failed
```

But it's a proposal. I'd love to hear thoughts, and maybe other ideas.

## Checklist

* [x] PR has an informative and human-readable title
* [x] Changes are limited to a single goal (no scope creep)
* [x] Code can be automatically merged (no conflicts)
* [x] Code follows the standards laid out in the [development playbook](https://github.com/cfpb/development)
* [x] Passes all existing automated tests
* [x] Any *change* in functionality is tested
* [x] New functions are documented (with a description, list of inputs, and expected output)
* [ ] Placeholder code is flagged
* [ ] Visually tested in supported browsers and devices
* [ ] Project documentation has been updated
* [x] Reviewers requested with the [Reviewer tool](https://help.github.com/articles/about-pull-request-reviews/) :arrow_right:

### CODE REVIEW

**Comment by willbarton** [comment]
The tests will presently fail because of import order. See #3799.

**Comment by richaagarwal** [comment]
Do we have any information on if this slows down the tests or not?  I'm OK with it if it doesn't slow down Travis. But if it does, I don't know if it's worth it, particularly if it doesn't tell us which test has the print statement(s).

**Comment by willbarton** [comment]
@chosak that's a good point. This could be in a subclass of TestDataTestRunner that we only use when running the tests on Travis.

**Comment by willbarton** [comment]
@richaagarwal quick and dirty timing locally (without recreating the venv):

```shell
%> git checkout master
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.
%> time tox -e fast
…
tox -e fast  59.86s user 1.66s system 96% cpu 1:04.01 total
%> git checkout test-print 
Switched to branch 'test-print'
Your branch is up-to-date with 'origin/test-print'.
%> time tox -e fast       
…
tox -e fast  60.69s user 1.83s system 94% cpu 1:06.04 total
```

Seems to be within acceptable margins.

**Comment by willbarton** [comment]
@chosak I broke our an `StdoutCapturingTestRunner` and added a `TEST_RUNNER` env var that we can use to select it. What do you think?

**Comment by chosak** [comment]
@willbarton works as advertised 👍 

How would you feel about making the error message a little more explanatory? "there is content in stdout" might not be super clear to someone new to the repository, as opposed to something like "Python unit tests should avoid writing to stdout".

Also, what's happening with the failing Travis build here? Shouldn't failing Python3 tests not fail the entire build?

**Comment by willbarton** [comment]
@chosak :+1:

I think the failure is my tweaks to the travis.yml file.

**Comment by willbarton** [comment]
> How would you feel about making the error message a little more explanatory? "there is content in stdout" might not be super clear to someone new to the repository, as opposed to something like "Python unit tests should avoid writing to stdout".

Current messaging: `AssertionError: unit tests should avoid writing to stdout`

**Comment by willbarton** [comment]
@higs4281 Just in test running. If you're writing unittests, and they're testing code that writes to stdout, you should probably be capturing stdout to check the output.

For right now, this is only enabled when `TEST_RUNNER=cfgov.test.StdoutCapturingTestRunner`, and this PR enables that for Travis. We'd need to set that variable in other places we'd want to enforce it.

**Comment by willbarton** [comment]
On the documenting in cfpb/development, we should definitely do that. I think I'd feel better seeing how it plays out here first before dictating that "this is what we do!" I'm still thinking of this as an experiment.

**Pull request merged**
