### PR TITLE
Disables GTM in return to top link

### PR DESCRIPTION
**Pull request by anselmbradford**
## Changes

- Addendum to https://github.com/cfpb/cfgov-refresh/pull/1729

## Testing

- `gulp build`, resize to mobile, click back to top should still work.

## Review

- @sebworks 
- @jimmynotjim 
- @KimberlyMunoz

### CODE REVIEW

**Comment by jimmynotjim** [comment]
:+1: Pending the restarted test.

**Comment by sebworks** [comment]
:+1:

**Comment by anselmbradford** [comment]
Just have to update or move the test to acceptance tests. I discovered if you reference a script from a unit test that refers to `document`, the jsdom defined dom won't carry over (which makes sense). Our atomic components work fine in the unit tests since the reference to the dom is passed in.

**Comment by anselmbradford** [comment]
Moved to https://github.com/cfpb/cfgov-refresh/pull/1735

**Pull request closed without merging**
