### PR TITLE
Fixes #477 - moves chosen overrides to own file

### LINKED ISSUE #477: Move Chosen Overrides
Chosen overrides should live in their own file that's imported into `main.less`

[See discussion](https://github.com/cfpb/cfgov-refresh/pull/474#issuecomment-93424770) in #474

### PR DESCRIPTION
**Pull request by anselmbradford**
Fixes #477 - moves chosen overrides to their own file.

## Changes

- Moves Chosen CSS overrides.
- Regenerates CSS assets.

## Testing

- Should be no change.

## Review

- @sebworks 
- @KimberlyMunoz 
- @jimmynotjim

### CODE REVIEW

**Comment by KimberlyMunoz** [comment]
Can you commit the built files too?

**Comment by KimberlyMunoz** [comment]
This looks pretty straightforward. Most of the actual css was already written otherwise I would dig a little more to see if we could refactor `!important`s.

**Comment by anselmbradford** [comment]
@KimberlyMunoz from `grunt css` only `main.css.map` is updated, I guess because it's just moving the code—not changing it—so the concatenated output is the same.

**Comment by KimberlyMunoz** [comment]
@anselmbradford Huh. I could have sworn I had a different output with my `git log` when I reviewed this yesterday. I thought at the time that it was just a single line in spacing.

Looks good to me.

**Comment by anselmbradford** [comment]
@KimberlyMunoz Hah life wouldn't be complete without git weirdness. Also, agreed on the working toward eliminating `!important`.

**Pull request merged**
