### PR TITLE
Putting the 404 back in 404 pages

### PR DESCRIPTION
**Pull request by jameshupp**
## Changes
* Updated the title and description to be slightly more descriptive, if not excitingly so.
* Made the 404 error message the h1, similar to the 500.

## Review
@Scotchester 
@jimmynotjim

### CODE REVIEW

**Comment by Scotchester** [comment]
For the record, I wasn't saying that I didn't support making "Something's disconnected" the main heading, just that I would like to see 404 in the page content _somewhere_.

**Comment by jimmynotjim** [comment]
I love this branch name :)

**Comment by jameshupp** [comment]
Well, this seemed like the easiest option, since it's parallel to the other error message and it was in the original copy. But I didn't want to put the pun right next to the number, since it could be read as us not actually understanding what status 404 actually means. And we got pretty clear feedback not to trivialize the error too much, given what's at stake for people with some of our content.

**Comment by Scotchester** [comment]
Alrighty. Good enough for me.

**Pull request merged**
