### PR TITLE
Remove empowerment page

### PR DESCRIPTION
**Pull request by virginiacc**
Remove hard-coded empowerment page in preparation for release of Wagtail replacement page on 12/8

## Removals

- Remove empowerment template
- Remove urls.py entry for empowerment page

## Testing

1. Check out branch
2. Navigate to [http://localhost:8000/practitioner-resources/economically-vulnerable/](http://localhost:8000/practitioner-resources/economically-vulnerable/) and verify that page 404s

## Checklist

* [ ] PR has an informative and human-readable title
* [ ] Changes are limited to a single goal (no scope creep)
* [ ] Code can be automatically merged (no conflicts)
* [ ] Code follows the standards laid out in the [development playbook](https://github.com/cfpb/development)
* [ ] Passes all existing automated tests
* [ ] Any *change* in functionality is tested
* [ ] New functions are documented (with a description, list of inputs, and expected output)
* [ ] Placeholder code is flagged
* [ ] Visually tested in supported browsers and devices
* [ ] Project documentation has been updated
* [ ] Reviewers requested with the [Reviewer tool](https://help.github.com/articles/about-pull-request-reviews/) :arrow_right:

### CODE REVIEW

**Comment by Scotchester** [comment]
Does it matter how quickly this gets deployed or is there a specific time they want it deployed? If so, we should probably feature-flag the URL removal.

**Comment by virginiacc** [comment]
@Scotchester The plan is to deploy early this afternoon, so I was thinking we'd just publish the new page right before pushing the removal code to production. I could add a flag though if that seems like a safer approach.

**Comment by Scotchester** [comment]
@virginiacc Cool, that plan seems fine. Thanks!

**Comment by virginiacc** [comment]
Thanks, @Scotchester!

**Pull request merged**
