### PR TITLE
Image compression

### PR DESCRIPTION
**Pull request by KimberlyMunoz**
Compressed a lot of images. This commit runs all of the images through the ImageOptim lossless
compressor. For the images that are over 100KB, it runs them through the lossy compressor at 80% quality.

## Testing

- Check out the images in the unprocessed/images folder

## Review

- @jimmynotjim 
- @ajbush 
- @duelj 

## Screenshots

Before: 
image

After: 
image

## Notes

- I initially wanted to look at having a gulp task do this, but the imagemin is limited in how much it can compress files and the cli for the tool I use requires settings that will probably [have issues on our CI tools](https://github.com/JamieMason/ImageOptim-CLI#jpegmini-and-support-for-assistive-devices). Additionally image compression is a long step to add and really should only be done once instead of each time we build. Happy to hear other thoughts on this.

## Checklist

* [ ] Changes are limited to a single goal (no scope creep)
* [ ] Code can be automatically merged (no conflicts)
* [ ] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [ ] Passes all existing automated tests
* [ ] New functions include new tests
* [ ] New functions are documented (with a description, list of inputs, and expected output)
* [ ] Placeholder code is flagged
* [ ] Visually tested in supported browsers and devices
* [ ] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)

### CODE REVIEW

**Comment by Scotchester** [comment]
What are your screenshots showing?

**Comment by KimberlyMunoz** [comment]
https://okor.github.io/justice/

**Comment by Scotchester** [comment]
On the homepage?

Doesn't seem like as much savings as we expected, given the numbers Adam noted (posted by you in #2175).

**Comment by cfarm** [comment]
@Scotchester looks like you're comparing apples to oranges - the stats here refer to load time, not byte size like in the link you posted.

**Comment by Scotchester** [comment]
@cfarm That's true. Maybe image size wasn't causing any perceivable slowness, ultimately.

**Comment by KimberlyMunoz** [comment]
The file size from the hero has decreased from 336004 bytes to 41309 bytes, which is a decrease of 87.71%. Performance is a lot of small victories to get a better performance and this can make a HUGE difference to people on poor 3G connections.

```
(cfgov-refresh)~/Projects/cfgov-refresh compress* 🐐  git diff compress flapjack --stat
 cfgov/unprocessed/img/application-process-round-300x300.png       | Bin 5275 -> 6943 bytes
 cfgov/unprocessed/img/applying-video-screenshot.png               | Bin 155483 -> 686707 bytes
 cfgov/unprocessed/img/bar-graph-round-300x300.png                 | Bin 2311 -> 4486 bytes
 cfgov/unprocessed/img/beta-illustration_lg.png                    | Bin 39664 -> 40511 bytes
 cfgov/unprocessed/img/beta-illustration_lg@2x.png                 | Bin 76428 -> 77083 bytes
 cfgov/unprocessed/img/beta-illustration_sm.png                    | Bin 26700 -> 27108 bytes
 cfgov/unprocessed/img/beta-illustration_sm@2x.png                 | Bin 67736 -> 68297 bytes
 cfgov/unprocessed/img/careers_image.png                           | Bin 9550 -> 45699 bytes
 cfgov/unprocessed/img/cfpb_video_cover_card_1380x776.png          | Bin 7921 -> 21955 bytes
 cfgov/unprocessed/img/clipboard-round-300x300.png                 | Bin 4340 -> 8474 bytes
 cfgov/unprocessed/img/computer-and-cup-round-300x300.png          | Bin 3470 -> 6208 bytes
 cfgov/unprocessed/img/computer-round-300x300.png                  | Bin 6521 -> 8924 bytes
 cfgov/unprocessed/img/deputy-director-silberman-high-res.jpg      | Bin 5427954 -> 5589167 bytes
 cfgov/unprocessed/img/deputy-director-silberman-low-res.jpg       | Bin 13438 -> 96053 bytes
 cfgov/unprocessed/img/deputy-director-silberman-round-200x200.jpg | Bin 20144 -> 74725 bytes
 cfgov/unprocessed/img/deputy-director-silberman-round-300x300.jpg | Bin 40778 -> 160779 bytes
 cfgov/unprocessed/img/director-cordray-300x400.jpg                | Bin 13039 -> 14079 bytes
 cfgov/unprocessed/img/director-cordray-3238x3672.jpg              | Bin 3313971 -> 3457037 bytes
 cfgov/unprocessed/img/director-cordray-round-200x200.jpg          | Bin 5599 -> 6465 bytes
 cfgov/unprocessed/img/director-cordray-round-300x300.jpg          | Bin 8620 -> 9465 bytes
 cfgov/unprocessed/img/educate.png                                 | Bin 3530 -> 7612 bytes
 cfgov/unprocessed/img/empower.png                                 | Bin 3964 -> 8869 bytes
 cfgov/unprocessed/img/enforce.png                                 | Bin 4056 -> 9852 bytes
 cfgov/unprocessed/img/fmc-about-us-540x300.jpg                    | Bin 12600 -> 13569 bytes
 cfgov/unprocessed/img/fmc-poly-com-540x300.jpg                    | Bin 19057 -> 20248 bytes
 cfgov/unprocessed/img/gavel-round-300x300.png                     | Bin 6343 -> 9280 bytes
 cfgov/unprocessed/img/grad-cap-round-300x300.png                  | Bin 3491 -> 6146 bytes
 cfgov/unprocessed/img/hero-large.png                              | Bin 29785 -> 72885 bytes
 cfgov/unprocessed/img/hero-small.png                              | Bin 23202 -> 52294 bytes
 cfgov/unprocessed/img/hero-working-at-cfpb-1200x300.png           | Bin 84385 -> 87508 bytes
 cfgov/unprocessed/img/hero-working-at-cfpb-660x300.png            | Bin 60917 -> 63213 bytes
 cfgov/unprocessed/img/home-answers_150.png                        | Bin 5215 -> 6684 bytes
 cfgov/unprocessed/img/home-complaint_150.png                      | Bin 1894 -> 3099 bytes
 cfgov/unprocessed/img/home-goals_150.png                          | Bin 3148 -> 4457 bytes
 cfgov/unprocessed/img/home-hero_lg.jpg                            | Bin 41309 -> 336004 bytes
 cfgov/unprocessed/img/home-hero_med.jpg                           | Bin 32174 -> 262489 bytes
 cfgov/unprocessed/img/home-hero_sm.jpg                            | Bin 19242 -> 136709 bytes
 cfgov/unprocessed/img/innovate.png                                | Bin 6750 -> 7976 bytes
 cfgov/unprocessed/img/lead.png                                    | Bin 4501 -> 5618 bytes
 cfgov/unprocessed/img/logo.png                                    | Bin 2057 -> 2062 bytes
 cfgov/unprocessed/img/logo_sm-exec.png                            | Bin 3437 -> 4073 bytes
 cfgov/unprocessed/img/nav-about-us-video.png                      | Bin 71781 -> 76267 bytes
 cfgov/unprocessed/img/plug.png                                    | Bin 8118 -> 10347 bytes
 cfgov/unprocessed/img/serve.png                                   | Bin 3664 -> 4732 bytes
 cfgov/unprocessed/img/server-rack.png                             | Bin 36755 -> 53422 bytes
 cfgov/unprocessed/img/us-flag_22x13.png                           | Bin 201 -> 202 bytes
 cfgov/unprocessed/img/usa-jobs-round-300x300.png                  | Bin 5526 -> 7466 bytes
 cfgov/unprocessed/img/video-play-btn.png                          | Bin 1045 -> 2029 bytes
 cfgov/unprocessed/img/warning-icon.png                            | Bin 383 -> 594 bytes
 cfgov/unprocessed/img/white-house-round-300x300.png               | Bin 3469 -> 6982 bytes
```

**Comment by KimberlyMunoz** [comment]
> Maybe image size wasn't causing any perceivable slowness, ultimately

We perceive speed very differently on our powerful Macbook Pros than people who rely on mobile connections. [More and more low-income families rely on their smartphones (which might be a couple years old) and do not have broadband at home.](http://www.pewinternet.org/2015/12/21/home-broadband-2015/)

**Comment by Scotchester** [comment]
Definitely true.

**Comment by jimmynotjim** [comment]
I didn't realize the imagemin plugin wasn't squeezing out everything we could. Great work on this. 👍 

I'd add a note or open an issue to address images uploaded to Wagtail. Unless I'm mistaken, we're currently not doing anything to improve the delivery of those images.

**Comment by ajbush** [comment]
Looks good to me @KimberlyMunoz 👍

**Pull request merged**
