### PR TITLE
WIP: Adding 30px margin Well / FCM

### PR DESCRIPTION
**Pull request by sebworks**
WIP: Adding 30px margin Well / FCM

##

## Screenshots

screen shot 2017-02-10 at 10 20 48 am
screen shot 2017-02-10 at 10 20 24 am
screen shot 2017-02-10 at 10 20 17 am

## Changes

- Modifeid `cfgov/jinja2/v1/browse-basic/index.html` to remove the `block__flush-sides` class.
- Modified `cfgov/jinja2/v1/browse-filterable/index.html` to remove the `block__flush-sides` class.
- Modifed `cfgov/jinja2/v1/newsroom/index.html` to remove the block__flush-sides` class.
- Modifed cfgov/jinja2/v1/sublanding-page/index.html` to remove the `block__flush-sides` class. 

## Testing

- Run `gulp styles`.
- Visit `http://localhost:8000/about-us/the-bureau/`
- Visit `http://localhost:8000/consumer-tools/prepaid-cards/`.

## Notes

- The featured content module, which contains a video player, will need to be refactored. The share buttons get cropped at breakpoints lower than 950px:

screen shot 2017-02-10 at 8 50 47 am

## Todos

-

## Checklist

* [ ] PR has an informative and human-readable title
* [ ] Changes are limited to a single goal (no scope creep)
* [ ] Code can be automatically merged (no conflicts)
* [ ] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [ ] Passes all existing automated tests
* [ ] New functions include new tests
* [ ] New functions are documented (with a description, list of inputs, and expected output)
* [ ] Placeholder code is flagged
* [ ] Visually tested in supported browsers and devices
* [ ] Project documentation has been updated
* [ ] Reviewers requested with the [Assignee tool](https://help.github.com/articles/assigning-issues-and-pull-requests-to-other-github-users/) :arrow_right:

### CODE REVIEW

**Comment by Scotchester** [comment]
@sebworks I think all we really need to do is remove [this kind of logic](https://github.com/cfpb/cfgov-refresh/blob/00a8201262f026385a3a44103db93b6ec100181b/cfgov/jinja2/v1/sublanding-page/index.html#L26-L30) from each of the page templates that allow FCMs and Wells.

**Comment by Scotchester** [comment]
And remove the `classname` from the Well definition: https://github.com/cfpb/cfgov-refresh/blob/a5a3320ac4b2874b6213334cee32c0c498b6700d/cfgov/v1/atomic_elements/organisms.py#L30

**Comment by sebworks** [comment]
@Scotchester, I agree 1000000%. It just got out of control at the end man. Wrapping things in blocks, logic in templates, class names in logic, parse_links, etc...

**Comment by sebworks** [comment]
@Scotchester, I've updated the code to remove the CSS and just use the blocks. This honestly feels like the wrong approach though. This approach forces you to wrap every featured content module and well in a `div.block`. It also forces you write an if statement in every template you want to use the those components. I'm going with this for now because it's how we are currently doing things. 

I'm now working on refactoring the featured content module video player.

**Comment by Scotchester** [comment]
We're already wrapping them in `div.block` though, and not just for FCM and Wells, but for every Wagtail module. Because of that, you should be able to actually remove the entire `{% if 'featured_content' in block.block_type %}` condition from those templates.

**Comment by sebworks** [comment]
> We're already wrapping them in div.block though, and not just for FCM and Wells, but for every Wagtail module. Because of that, you should be able to actually remove the entire {% if 'featured_content' in block.block_type %} condition from those templates.


Unfortunately, you can't do that because some components aren't wrapped and others use different block modifiers.

**Comment by Scotchester** [comment]
> Unfortunately, you can't do that because some components aren't wrapped and others use different block modifiers.

You can, I promise :)

If the `{% if 'featured_content' in block.block_type %}` condition fails, [the `else` is to just go to `render_block`](https://github.com/cfpb/cfgov-refresh/blob/master/cfgov/jinja2/v1/browse-basic/index.html#L19-L21), in which [all blocks get a `div.block` wrapper](https://github.com/cfpb/cfgov-refresh/blob/master/cfgov/jinja2/v1/_includes/templates/render_block.html#L2).

**Comment by sebworks** [comment]
@Scotchester, have you looked at: https://github.com/cfpb/cfgov-refresh/blob/master/cfgov/jinja2/v1/sublanding-page/index.html? 

if you are wrapping every block in a div then just handle it with CSS. Why have the `else` logic in the template?

**Comment by jimmynotjim** [comment]
Should we close this in favor of the discussions going on in the Design Manual?

**Comment by sebworks** [comment]
> Should we close this in favor of the discussions going on in the Design Manual?

Yep, with pleasure.

**Pull request closed without merging**
