### PR TITLE
Created event agenda calendar

### PR DESCRIPTION
**Pull request by jimmynotjim**
Created a new event agenda calendar table

## Additions

- Created new event agenda macro based on leadership calendar macro

## Removals

- None

## Changes

- Updated mock data to include agenda object with child time blocks
- Updated single template to include and render agenda macro

## Testing

- navigate to `/events/spring-2014-rulemaking-agenda/`

## Review

- @sebworks 
- @anselmbradford 
- @duelj 

## Preview

screen shot 2015-02-24 at 10 53 15 am

## Notes

- Had some trouble with the `format_time()` macro so I skipped it for the time being.
- Not entirely happy with using `<br>` after street address but it's an existing pattern elsewhere in the site.

### CODE REVIEW

**Comment by himedlooff** [comment]
Don't fear the `<br>` :fearful: we used it because it seems like the proper use for it.

> br elements must be used only for line breaks that are actually part of the content, as in poems or addresses.

http://www.w3.org/TR/html5/text-level-semantics.html#the-br-element

**Comment by Scotchester** [comment]
Good point, Mike, but once a decision is made on cfpb/front-end#11, the addresses should get enough markup structure that it becomes no longer necessary.

**Comment by jimmynotjim** [comment]
Turns out we can't use the default table behavior for the agenda. Temporarily closing this until the correct behavior is added.

**Comment by anselmbradford** [comment]
Should `event-agenda-table.html` go in `/_includes/` or `/events/`? Will it be used outside of the events?

**Comment by jimmynotjim** [comment]
After some discussion with the team we came up with a simplified design that can be reused throughout the site. 

@duelj @ajbush @juidai @schaferjh - I kept the small labels above location and speakers. I feel like it's still important to define the content that follows them (especially the speakers, location is a bit more self explanatory), but I'm definitely open to discuss them.

screen shot 2015-02-25 at 12 57 11 pm

**Comment by jimmynotjim** [comment]
@anselmbradford yeah, I feel like most of these macros that aren't global should really be moved to their associated directories. Will do that here before merging.

**Comment by anselmbradford** [comment]
Also prefix with an underscore: `_event-agenda-table.html`.

**Comment by jimmynotjim** [comment]
Going to wait to move the macro location until @sebworks is finished with his work.

**Pull request merged**
