### PR TITLE
Merging Flapjack into Master

### PR DESCRIPTION
**Pull request by sebworks**
Merging Flapjack into Master

## Review

- @chosak 
- @richaagarwal 
- @contolini 

## Checklist

* [ ] Changes are limited to a single goal (no scope creep)
* [ ] Code can be automatically merged (no conflicts)
* [ ] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [ ] Passes all existing automated tests
* [ ] New functions include new tests
* [ ] New functions are documented (with a description, list of inputs, and expected output)
* [ ] Placeholder code is flagged
* [ ] Visually tested in supported browsers and devices
* [ ] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)

### CODE REVIEW

**Comment by contolini** [comment]
Should we just delete `flapjack`?

**Comment by sebworks** [comment]
Yeah, I think it's time

**Comment by willbarton** [comment]
If we delete flapjack, what does that do to the remaining open PRs to flapjack?

**Comment by sebworks** [comment]
@willbarto, I'm going the one I have open against Flapjack. I'll reopen it against master.

**Pull request merged**
