### PR TITLE
House Keeping Items

### PR DESCRIPTION
**Pull request by kave**
Just handling some lingering items

## Changes
- renamed preprocessed folder to unprocessed
- defaulted setup.sh to install local requirements so you no longer have to type `./setup local`
- fixed typo in events admin page

## Testing
- run `./setup.sh` and then run tests `gulp test` 

## Review
- @kurtw 
- @rosskarchner 
- @anselmbradford 
- @KimberlyMunoz 
- @jimmynotjim 

## Todos after Merge:
- Update Jenkins Job `flapjack-demo-frontend-build-flapjack`
- Update Jenkins Job `flapjack-demo-frontend-build-refresh`

### CODE REVIEW

**Comment by anselmbradford** [comment]
Fixes https://github.com/cfpb/cfgov-refresh/issues/1079

**Comment by anselmbradford** [comment]
:+1: LGTM

**Comment by kurtw** [comment]
Looks good. Just remember to update the Jenkins jobs for the new setup.sh.

**Comment by kave** [comment]
@kurtw donzo

**Pull request merged**
