### PR TITLE
Spellcheck: Installation.md

### PR DESCRIPTION
**Pull request by Newman101**
Documentation spellcheck: Installation.md. 

## Changes

Couple of small spelling amendments:

Github -> GitHub
Reinstall -> Re-install. 

No functional changes to code.

## Checklist

* [x] Changes are limited to a single goal (no scope creep)
* [x] Code can be automatically merged (no conflicts)
* [x] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [ ] Passes all existing automated tests
* [ ] New functions include new tests
* [ ] New functions are documented (with a description, list of inputs, and expected output)
* [ ] Placeholder code is flagged
* [ ] Visually tested in supported browsers and devices
* [ ] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)

### CODE REVIEW

**Comment by Newman101** [comment]
Hi. Yes, there is actually. The reason is consistency. Re-install appears in usage.md too, so I thought it might be good to make those consistent.

**Comment by higs4281** [comment]
OED uses no hyphen, but CFPB's style guide is based on AP, which calls for the hyphen. I vote for the change.

**Comment by willbarton** [comment]
> Re-install appears in usage.md too, so I thought it might be good to make those consistent.

Heh, so it does. Consistency is always good. I think "reinstall" would be preferable, in both places.

**Comment by Scotchester** [comment]
@higs4281 I think you're mistaken about AP, at least in the 2015 version on my desk. It says follow _Webster's New World College Dictionary_, but hyphenate if the last letter of the prefix is the same as the first letter after the prefix.

**Comment by higs4281** [comment]
I'm looking at the AP guide available via our library.

**Comment by higs4281** [comment]
On the second ballot, I change my vote to reinstall everywhere. Sorry, @Newman101

**Comment by Newman101** [comment]
Sure, I'll just change the original one to reinstall then. No worries.

**Comment by Newman101** [comment]
Consistency issue is now amended, as requested. Branch updated.

**Comment by Scotchester** [comment]
Thanks, @Newman101! Your contributions are very much appreciated.

**Pull request merged**
