### PR TITLE
Small copy tweak

### PR DESCRIPTION
**Pull request by jameshupp**
"Reload" isn't accurate, at least from user's perspective.

### CODE REVIEW

**Comment by jimmynotjim** [comment]
Would "open" be more appropriate since the users we're most concerned about are also most likely the least web savvy.

**Comment by jameshupp** [comment]
Well, if we're going to get non-technical, "We'll take you to the page in"? Attributing the action to the page itself reads just a little like a bomb countdown.

**Comment by jimmynotjim** [comment]
Haha, good point, lets not create bomb scares. :+1: to your last text suggestion too

**Comment by sebworks** [comment]
:+1:

**Pull request merged**
