### PR TITLE
Adds top and first-level nav items configuration file

### PR DESCRIPTION
**Pull request by anselmbradford**
Adds top and first-level nav items configuration file to remove hardcoded
navigation menu items.

## Additions

- Added top and first-level navigation items config file for removing hardcoded navigation menu items in the main menu.
- Adds TODO comment for commented out Español code block.

## Changes

- Builds main menu from global nav-items configuration file.

## Testing

- Main menu should function/look the same.

## Review

- @jimmynotjim 
- @KimberlyMunoz 
- @sebworks 

## Notes

- Part of DF-1963, because I need a list for the sidenav menu to build the structure from. This is a self-contained change so I wanted to spin it off for feedback while I worked on the sidenav implementation.

### CODE REVIEW

**Comment by anselmbradford** [comment]
Pushed an edit in https://github.com/cfpb/cfgov-refresh/commit/30257a21a8351b915835f60096e12fa1474430c8, forgot that the About button needs an empty href to show the hand cursor and that the empty menu items were producing hidden submenu HTML.

**Comment by jimmynotjim** [comment]
:+1: I'm not sure if the Spanish content is ever going to come back, would be worth checking in on but not something that needs to happen here.

**Comment by jimmynotjim** [comment]
Let's get another sign-off so we can merge this one.

**Comment by sebworks** [comment]
:+1:

**Comment by jimmynotjim** [comment]
In @anselmbradford's absence I'm going to go ahead and merge this so we can review the Sprint PR

**Pull request merged**
