### PR TITLE
Remove feature flags from mega menu for things that have launched

### PR DESCRIPTION
**Pull request by virginiacc**
Remove feature flags for mega menu items that have been released (hold until after Debt Collection release on 1/12)

## Additions

- Add feature-flagged items directly to `nav_items`  and `media_items` in  `_vars-mega-menu.html`

## Removals

- Remove feature flag conditions from  `_vars-mega-menu.html`

## Testing

- Check out branch
- Verify that megamenu links still appear & work as expected: `Prepaid Cards` & `Debt Collection` links under `Consumer Tools`, and `Consumer Credit Trends` under `Data & Research`
- Verify that debt collection featured menu content appears under `Consumer Tools`

## Screenshots
screen shot 2017-01-11 at 8 53 20 pm

screen shot 2017-01-11 at 8 04 35 pm

## Checklist

* [x] Changes are limited to a single goal (no scope creep)
* [x] Code can be automatically merged (no conflicts)
* [x] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [x] Passes all existing automated tests
* [x] New functions include new tests
* [x] New functions are documented (with a description, list of inputs, and expected output)
* [x] Placeholder code is flagged
* [x] Visually tested in supported browsers and devices
* [x] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)
* [x] Reviewers requested with the [Assignee tool](https://help.github.com/articles/assigning-issues-and-pull-requests-to-other-github-users/) :arrow_right:

### CODE REVIEW

**Comment by virginiacc** [comment]
@jimmynotjim Yes, missed that one -- thanks!

**Comment by jimmynotjim** [comment]
Thanks 👍

**Comment by sebworks** [comment]
@virginiacc, what are your feelings about migrating this to Django?

**Comment by willbarton** [comment]
@virginiacc thanks for doing this!! Is there a reason it's on hold?

**Comment by Scotchester** [comment]
> Is there a reason it's on hold?

Probably because this was opened before the debt collection stuff went live. Should be good now, I think!

**Comment by virginiacc** [comment]
@willbarton Yes, I added the hold tag in an abundance of caution before the debt collection portal release. :)

**Comment by virginiacc** [comment]
> what are your feelings about migrating this ( vars file ) to Django?

@sebworks I'm definitely interested in that. Did you have an approach in mind?

**Comment by sebworks** [comment]
>> Did you have an approach in mind?

Just a light and easy model which would allow us to update slugs, text, and images conditionally.  No migrations.

**Comment by jimmynotjim** [comment]
Anything preventing this from being merged?

**Comment by Scotchester** [comment]
Not that I know of. Perhaps @virginiacc doesn't realize that self-merging-after-approval is the norm for this repo.

**Comment by sebworks** [comment]
No. I should have merged it. Doing that now.

**Pull request merged**
