### PR TITLE
add decorator to help model __str__ method in python 2

### PR DESCRIPTION
**Pull request by higs4281**
Snippets need str method with python 2 handling

### CODE REVIEW

**Comment by Scotchester** [comment]
Is there a simple way for me to test this locally?

**Comment by higs4281** [comment]
If you have a cfgov instance working, yes. If you pull it in and have a recent production db load, it should let Resource snippets appear.

**Comment by Scotchester** [comment]
@higs4281 Meaning that a recent prod db should contain the data necessary to reproduce the bug, before running on this branch?

**Comment by higs4281** [comment]
@Scotchester Yes. Or you could create your own Resource snippet and add some non-ascii characters to test.

**Comment by chosak** [comment]
Or write automated unit tests that check it... :trollface: (31f534b)

**Comment by higs4281** [comment]
Were I still on platform, I would want this T-shirt:

> Listen to the Andy on your shoulder

**Pull request merged**
