### PR TITLE
Fix Spanish translation of "required" in form-field-with-button

### PR DESCRIPTION
**Pull request by Scotchester**
## Changes

- Corrects the Spanish translation of "required" for the Form Field with Button.

## Testing

1. Pull branch
2. Runserver
3. Create an Email Sign-up block, mark the field as required, and set that page's language to Spanish
4. Preview the page and see the updated text

## Checklist

* [x] PR has an informative and human-readable title
* [x] Changes are limited to a single goal (no scope creep)
* [x] Code can be automatically merged (no conflicts)
* [x] Code follows the standards laid out in the [development playbook](https://github.com/cfpb/development)
* [x] Passes all existing automated tests
* [x] Any *change* in functionality is tested
* [x] New functions are documented (with a description, list of inputs, and expected output)
* [x] Placeholder code is flagged
* [x] Visually tested in supported browsers and devices
* [x] Project documentation has been updated
* [x] Reviewers requested with the [Reviewer tool](https://help.github.com/articles/about-pull-request-reviews/) :arrow_right:

### CODE REVIEW

**Comment by sebworks** [comment]
Do you need regenerate the `django.mo` file?

**Comment by Scotchester** [comment]
@sebworks Hmm... apparently, I do. When I try to run the command to do so, I get an error:

```
CommandError: Can't find msgfmt. Make sure you have GNU gettext tools 0.15 or newer installed.
```
Any idea how to remedy that?

**Comment by sebworks** [comment]
@Scotchester, same issue I'm having here: https://github.com/cfpb/retirement/pull/206. You might be able to install using brew or pip.

**Comment by Scotchester** [comment]
Nevermind, I'm an idiot. I had switched back to the `master` branch fro reasons I can't recall.

**Comment by Scotchester** [comment]
Fix pushed. Rebased from master, so re-pull the branch if you've already pulled it.

**Comment by sebworks** [comment]
LGTM

**Pull request merged**
