### PR TITLE
Create app-specific asset tasks

### PR DESCRIPTION
**Pull request by anselmbradford**
Apps coming in from the outside of cfgov-refresh sometimes come with their own images, CSS, and JS. To manage these assets it may be helpful to deliver them in their own namespaced directory from unprocessed/apps/. This PR creates a tasks for assets originating from the /unprocessed/apps/ directory.

## Additions

- `images:general` and `images:apps` tasks in gulp.
- `copy:jsonKBYO` to copy know before you owe timeline JSON file to /static_built/apps/.

## Removals

- images config in gulp config file.

## Changes

- Changes `styles:stylesOAH` to `styles:apps`.
- Changes `scripts:oah` to `scripts:apps`.
- Changes task to copy timelinejs to /static_built/apps/ directory instead of /static_built/.
- Moves OAH scripts to /unprocessed/apps/owning-a-home/js/ directory instead of /unprocessed/js/routes/owning-a-home/ and /unprocessed/js/apps/owning-a-home.
- Renames `copy:codeJson` task `copy:jsonCode`.

## Testing

1. `gulp build` should pass and collect app-specific assets in /static_built/apps/
2. The following URLs should work as before:
  a. http://localhost:8000/know-before-you-owe/ 
  b. http://localhost:8000/owning-a-home/mortgage-closing/ 
  c. http://localhost:8000/owning-a-home/mortgage-estimate/
  d. http://localhost:8000/consumer-tools/financial-well-being/

## Notes

- Includes https://github.com/cfpb/cfgov-refresh/pull/3802

### CODE REVIEW

**Comment by sebworks** [comment]
This looks really good. How would you feel about getting rid of the `css` and `js` folders? This would obviously flatten the structure and provide a simpler view.

**Comment by anselmbradford** [comment]
> This looks really good. How would you feel about getting rid of the css and js apps folders? This would obviously flatten the structure and provide a simpler view.

Is there a performance reason or something else to do so? I'd lean toward keeping them, since things like timelinejs are coming in with them.

**Comment by sebworks** [comment]
>> Is there a performance reason or something else to do so? I'd lean toward keeping them, since things like timelinejs are coming in with them.

No, it's not performance related. I just think it makes it much easier when all the files ( less, HTML template, JS, readme ) are located in the same folder. I admit, it might not scale well in cases where there large amounts of files. https://www.ebayinc.com/assets/Uploads/Blog/2014/09/before_after.png

**Comment by sebworks** [comment]
can the `imagesApps` and `imagesGeneral` tasks be combined?

**Comment by anselmbradford** [comment]
> can the imagesApps and imagesGeneral tasks be combined?

Looks like it! Added a shared helper function in https://github.com/cfpb/cfgov-refresh/pull/3806/commits/6d78a6ce32bf13e176294a53681984c8b4149802

**Comment by sebworks** [comment]
Merge it, it's golden

**Pull request merged**
