### PR TITLE
Complaint landing page - Move it into cfgov-refresh

### PR DESCRIPTION
**Pull request by mistergone**
Currently, the [complaint satellite app](https://github.com/cfpb/complaint) only serves one page that's still in use: the [Consumer Complaints Landing Page](https://www.consumerfinance.gov/data-research/consumer-complaints/). This PR moves that landing page into cfgov-refresh, so that we can stop including the complaint satellite app and deprecate its repo.

## Additions
- A view, template, test file, and assets for the Complaint landing page. We ported all relevant functionality from the complaint repo with minor edits. See individual commit messages for details.

## Removals
- We no longer pull in the complaint satellite app

## Testing
1. When running cfgov-refresh, view the page at http://localhost:8000/data-research/consumer-complaints/

## Todos
- [ ] ???

## Checklist
- [x] PR has an informative and human-readable title
- [x] Changes are limited to a single goal (no scope creep)
- [ ] Code can be automatically merged (no conflicts)
- [x] Code follows the standards laid out in the [development playbook](https://github.com/cfpb/development)
- [x] Passes all existing automated tests
- [x] Any _change_ in functionality is tested
- [x] New functions are documented (with a description, list of inputs, and expected output)
- [x] Placeholder code is flagged / future todos are captured in comments
- [ ] Visually tested in supported browsers and devices (see checklist below :point_down:)
- [ ] Project documentation has been updated
- [ ] Reviewers requested with the [Reviewers tool](https://help.github.com/articles/requesting-a-pull-request-review/) :arrow_right:

### Browsers

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Internet Explorer 8, 9, 10, and 11
- [ ] Edge
- [ ] iOS Safari
- [ ] Chrome for Android

### Accessibility

- [ ] Keyboard friendly
- [ ] Screen reader friendly

### Other

- [ ] Is useable without CSS
- [ ] Is useable without JS
- [ ] Flexible from small to large screens
- [ ] No linting errors or warnings
- [ ] JavaScript tests are passing

### CODE REVIEW

**Comment by chosak** [comment]
@mistergone your recent commit 4d4f15e modified numerous `package-lock.json` files. Is that intentional?

**Comment by mistergone** [comment]
@chosak - There were conflicts in the file, so I made a new `package-lock.json` by running a fresh `npm install`.

**Comment by chosak** [comment]
@mistergone what version of npm are you using?

This change also seems to modify unrelated files from other projects, like `analytics-gtm`, `owning-a-home`, and changes explicitly pinned versions with version ranges in some places. I might be wrong (ping @anselmbradford @cfarm @Scotchester) don't we want to pin versions in those files so that builds always pull in specific tested versions?

**Comment by Scotchester** [comment]
I'm not sure why this PR would need to be changing any `package-lock.json` files. If I understand the purpose and workings of those, they should only change if something has changed in `package.json`, correct?

**Comment by mistergone** [comment]
If I understand this issue, it looks like it has to do with a change in `npm6` where the versions tracked in `package-lock.json` now used carats (`^`) in their notation.

[Here's a relevant issue on the npm repo](https://github.com/npm/npm/issues/20891).

So nothing has actually changed here _except_ the format of `package.json` due to my use of `npm v6.1.0` and others using `v5.x.x`.

We're discussing next steps. 😀

**Comment by mistergone** [comment]
All the `package-lock.json` files have been reverted to their `npm v5` syntax! Thus, there should be no diffs in those files.

**Pull request merged**
