### PR TITLE
Add Teachers' Digital Platform to optional apps and urls

### PR DESCRIPTION
**Pull request by willbarton**
This PR adds the Teachers' Digital Platform app to the optional apps in settings and to the urls with a `TDP_RELEASE` flag wrapped around it. The URL is currently temporary

## Additions

- `TDP_RELEASE` feature flag that enables the Teachers' Digital Platform url
- Added `teachers_digital_platform` app to optional apps in settings
- Added `teachers_digital_platform` to `requirements/optional-public.txt`
## Testing

1. Go through the docker setup
2. Checkout https://github.com/cfpb/teachers-digital-platform into `develop-apps/`
3. Enable the `TDP_RELEASE` feature flag in the Wagtail Admin
4. Visit http://localhost:8000/tdp

## Checklist

* [ ] PR has an informative and human-readable title
* [ ] Changes are limited to a single goal (no scope creep)
* [ ] Code can be automatically merged (no conflicts)
* [ ] Code follows the standards laid out in the [development playbook](https://github.com/cfpb/development)
* [ ] Passes all existing automated tests
* [ ] Any *change* in functionality is tested
* [ ] New functions are documented (with a description, list of inputs, and expected output)
* [ ] Placeholder code is flagged
* [ ] Visually tested in supported browsers and devices
* [ ] Project documentation has been updated
* [ ] Reviewers requested with the [Reviewer tool](https://help.github.com/articles/about-pull-request-reviews/) :arrow_right:

### CODE REVIEW

**Comment by rosskarchner** [comment]
This PR should add wheel building: https://github.com/cfpb/teachers-digital-platform/pull/10

**Comment by rosskarchner** [comment]
Wheels, now in two great flavors: https://github.com/cfpb/teachers-digital-platform/releases/tag/0.0.2

**Comment by willbarton** [comment]
> Wheels, now in two great flavors: 

WOOHOOO! Two wheels are even better than one.

**Comment by Scotchester** [comment]
Is this waiting on anything?

**Pull request merged**
