### PR TITLE
Match-all-tags page filtering

### PR DESCRIPTION
**Pull request by higs4281**
Editors helped us discover a combination of page tags and the use of
"match-all-topic-tags" that locked up the version of mysql that we run
on servers. This PR reduces some of the query complexity and, in the case
of "match-all," forces a query evaluation before starting the recursive
tag filtering routine.

I replicated the mysql lockup by editing page #10848 inside a docker VM that 
uses with the same db version used in production. When I checked the 
"match-all-topic-tags" box, the page locked up mysql when it was rendered. 
This PR stopped the lockups for me.

#### Notes
When the final query succeeded, applying "match-all" to all 9 tags, 
the result was zero related pages. All this trouble for a null!

This addresses GHE issue 1805

### CODE REVIEW

**Comment by rosskarchner** [comment]
When checkout this branch, open up admin, and restore a problematic version of page 10848, I'm unable to preview or view the published page.

**Comment by higs4281** [comment]
I'll try restoring a revision.

**Comment by higs4281** [comment]
Rats. Restoring a revision brings back the problem for me, too. 
Back to the taggithole.

**Comment by rosskarchner** [comment]
Been there!

**Pull request closed without merging**
