### PR TITLE
Support for django-sheerlike: less code this time

### PR DESCRIPTION
**Pull request by rosskarchner**
This was #748-- I thought I could re-create the branch without closing the pull request.

### CODE REVIEW

**Comment by anselmbradford** [comment]
:+1:

**Comment by jimmynotjim** [comment]
:+1:

**Comment by anselmbradford** [comment]
@rosskarchner Hope it's okay to merge this! Looked like you were waiting on us. FYI We have established a team precedent for who opens, closes, but I know that's unusual at CFPB. See [GHE]/flapjack/Getting-started-with-Flapjack/blob/master/02-developer_docs/workflow-guide.md#who-merges-the-code

**Comment by rosskarchner** [comment]
That is a useful document to know about ;)

**Pull request merged**
