### PR TITLE
Fixes DF-1599 - rsvp/livestream gap

### PR DESCRIPTION
**Pull request by anselmbradford**
Adds 1/2/1 ratio proportioned gap between items in the RSVP/livestream aside on the event details page.

## Additions

- Adds `.event-status_rsvp` and `.event-status_rsvp` classes.
- Wraps top-two and bottom-two paragraphs in divs.
- Adjusts line-height and margin of text in aside to map a visually approximate 15px/30px/15px horizontal gaps.

## Testing

- Visit /events/two-years-of-standing-up-for-consumers/

## Review

- @duelj 
- @jimmynotjim 
- @sebworks 

## Preview

screen shot 2015-03-10 at 5 43 50 pm

## Notes

- I adjusted the margin amounts to compensate for the line-height of the font. Is this the appropriate approach?

### CODE REVIEW

**Comment by jimmynotjim** [comment]
I think the 10px on the `p` is fine, but you may want to add a note so that no one tries to change it to 15px later. Other than that, this looks good to me.

**Comment by anselmbradford** [comment]
I have this comment a little further up, will that do? https://github.com/cfpb/cfgov-refresh/pull/342/files#diff-fa565f0e47b46f5f61b2d051095880f4R139

**Comment by jimmynotjim** [comment]
I saw that but looking at it I wouldn't immediately know which one was manually adjusted. Figured you could shorten that and put it above the `p:first-child` to make it clearer.

**Comment by anselmbradford** [comment]
Comment updated in https://github.com/cfpb/cfgov-refresh/commit/b46e2a787fe225a2fb43d58b39e709dfe1efabe0

**Comment by jimmynotjim** [comment]
:+1:

**Pull request merged**
