### PR TITLE
Removing unused functions from utilities

### PR DESCRIPTION
**Pull request by KimberlyMunoz**
I'm writing some unit tests for our utilities and saw some functions weren't being used. Opening up a PR to remove them or at least discuss how we want to treat these. (Unit tests will be in a PR to follow!)

## Removals

- Removed unused functions in `utilities.js`

## Review

- @anselmbradford 
- @sebworks 

## Preview

[Preview this PR without the whitespace changes](?w=0)

### CODE REVIEW

**Comment by KimberlyMunoz** [comment]
I realized getViewportDimensions is really the only thing that is in `utilities.js` anymore, so I'm going to break that into its own proper module and make sure that the utilities file isn't being used to call `typecheckers`

**Comment by anselmbradford** [comment]
Found some [history](https://github.com/cfpb/cfgov-refresh/commit/c59813a5d4c364b4ca58664169fc04c14deef736#diff-ee7180f4440d1423f09238b125df7a31) on these. Can we verify https://github.com/cfpb/cfgov-refresh/blob/flapjack/src/static/js/modules/jquery/type-and-filter.js#L7-L14 isn't still needed? And if not that code comment should be removed too. 

They also appear have been originally used in the `cf_pagination.js` [initialization code](https://github.com/cfpb/cfgov-refresh/commit/c59813a5d4c364b4ca58664169fc04c14deef736#diff-6d7870f99d3f759dc8b9f7a6969f1129L386). I'm not clear why at the time I deleted that initialization code and didn't create a module like `init-chosen.js` to replace it. It's possible I forgot to copy that bit over, or it isn't needed. Wasn't there an issue around the pagination? I can't find it now.

**Comment by sebworks** [comment]
cf_pagination.js can be deleted. It was going to be used to try and implement ajax based pagination but there are serious flaws in the code. When we move to Django we should revisit using ajax for pagination.

**Comment by KimberlyMunoz** [comment]
I think https://github.com/cfpb/cfgov-refresh/blob/flapjack/src/static/js/modules/jquery/type-and-filter.js#L7-L14 was just an example of how that jQuery plugin could be extended. Since it seems like the contact-us page will be drastically simplified I'm removing it.

I dug in deeper to history and it looks like that block was [commented out of the code about a year ago](https://github.com/cfpb/cfgov-refresh/commit/7f3d70d3f5c7c610fda90f4120dc9829d56133e2). Since it's not needed for cf_pagination now, let's leave it removed for the time being.

**Comment by anselmbradford** [comment]
> I think https://github.com/cfpb/cfgov-refresh/blob/flapjack/src/static/js/modules/jquery/type-and-filter.js#L7-L14 was just an example of how that jQuery plugin could be extended. Since it seems like the contact-us page will be drastically simplified I'm removing it.

Sounds good. Want to remove `cf_pagination.js` per @sebworks comment while you're at it. It looks like it's included but never actually used.

> I dug in deeper to history and it looks like that block was commented out of the code about a year ago. Since it's not needed for cf_pagination now, let's leave it removed for the time being.

Ah, didn't notice that. That explains why it didn't get copied over.

**Comment by KimberlyMunoz** [comment]
Cool. `cf_pagination` is gone now. :wave:

**Comment by sebworks** [comment]
:+1:

**Comment by anselmbradford** [comment]
:+1:

**Pull request merged**
