### PR TITLE
Convert helper text to text from array

### PR DESCRIPTION
**Pull request by anselmbradford**
Helper text for content with anchor was an array instead of a string of text.

## Changes

- Converts helper text array to string of text.
- Re-words helper text to be clearer that the text with still have auto-generated components.

## Testing

1. Create a new blog page in wagtail.
2. Add a content with anchor component.

## Screenshots

Before:

screen shot 2017-08-11 at 10 49 51 am

After:

screen shot 2017-08-11 at 10 55 56 am

## Notes

- Hope I'm not abusing a semicolon 😃

### CODE REVIEW

**Comment by Scotchester** [comment]
> Hope I'm not abusing a semicolon

You are ;) The second statement is not an independent clause by virtue of being introduced by the coordinating conjunction "or". Check out http://theoatmeal.com/comics/semicolon

I might suggest being a little more explicit about what we recommend: "Enter some human-friendly text, or a big, ugly, semi-random ID will be generated on save."

**Comment by Scotchester** [comment]
Ah, I see.

**Comment by anselmbradford** [comment]
@Scotchester is this better??

screen shot 2017-08-14 at 1 01 09 pm

**Comment by Scotchester** [comment]
:+1: Please condense your migrations to a single migration with a meaningful name before merging.

**Comment by anselmbradford** [comment]
Argh, keep forgetting that step, thanks!

**Pull request merged**
