### PR TITLE
Copy edits to /about-us/

### PR DESCRIPTION
**Pull request by KimberlyMunoz**
Doesn't need to be merged this sprint.

## Changes
- Made copy edits to `/about-us/` per @sarahsimpson09's email

## Testing
- Visit localhost:7000/about-us/

### CODE REVIEW

**Comment by sebworks** [comment]
:+1:

**Comment by sarahsimpson09** [comment]
The removal of the link to the org chart under Bureau Leadership was an oversight, there should be a link under Cordray and Antonakes/Fuchs that should say "See how we're organized"

Thanks for catching that, @KimberlyMunoz!

**Comment by KimberlyMunoz** [comment]
@sarahsimpson09 
michelle-tanner-you-got-it-dude-full-house

**Comment by jimmynotjim** [comment]
:+1:

**Pull request merged**
