### PR TITLE
Add sidebar to Wagtail JobListingPage

### PR DESCRIPTION
**Pull request by chosak**
This PR adds the job listing page sidebar to the new Wagtail `JobListingPage`, copying it from [the legacy Django template](https://github.com/cfpb/cfgov-refresh/blob/master/cfgov/jinja2/v1/about-us/careers/_single.html#L132).

## Changes

- Added hardcoded sidebar content to `cfgov/jinja2/v1/job-description-page/index.html`.
- Added a bit of logic to the template to handle the (unlikely) case that there are no specified regions or grades for a job. 

## Testing

- Create a new `JobListingPage` in the Wagtail admin, and preview. Compare the generated sidebar with one on the live site that uses the Django template, for example [this page](http://www.consumerfinance.gov/about-us/careers/enforcement-economist-cn-6060/).

## Review

- @sebworks 

## Screenshots

Page with no grades or regions specified (again, this is unlikely, but better to show something than just have a blank):
image

## Todos

- Per @schaferjh for now we are going to hardcode this content, but in future it would be nice to have it default to something but be configurable through the standard Wagtail sidebar editor.

## Checklist

* [X] Changes are limited to a single goal (no scope creep)
* [X] Code can be automatically merged (no conflicts)
* [X] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [ ] Passes all existing automated tests
* [ ] New functions include new tests
* [ ] New functions are documented (with a description, list of inputs, and expected output)
* [ ] Placeholder code is flagged
* [ ] Visually tested in supported browsers and devices
* [ ] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)

### CODE REVIEW

**Comment by sebworks** [comment]
👍

**Comment by schaferjh** [comment]
> Added a bit of logic to the template to handle the (unlikely) case that there are no specified regions or grades for a job.

* Did you mean type/division rather than region? The screenshot doesn't include the region listing. 
* "All divisions" seems like a fine fall back for no division/office
* The dummy data for expiration date and grade strikes me as potentially more confusing/harmful than helpful. Could those two fields display "- -" ?
* Actually, could expiration date and grade be required fields in the admin? So the cms throws an error if someone tries to publish without those?

**Comment by chosak** [comment]
@schaferjh Sorry for the confusion; I did mean region.

I believe our data model specifies that each job "should" have 1 or more regions and 1 or more grades, but the Wagtail editor interface does not enforce this, and lets you select 0.

This PR includes a change where if no regions are specified, I just remove that line from the job header. Otherwise you'd just see "REGION: " with nothing after it.

Division and expiration date are currently required field, as are minimum/maximum salary. So these will always appear.

I mentioned enforcing region/grade as a TODO in [the PR where these pages were created](https://github.com/cfpb/cfgov-refresh/pull/2314)). This is a bit tricky because it's page-level validation as opposed to field-level.

**Comment by schaferjh** [comment]
ok, well for now, in the required fields, if nothing is selected for expiration date and max/min salary they should get a - - rather than placeholder information. I suppose it's fine for the actual grade to be blank, and "All divisions" is fine for divisions.

**Comment by chosak** [comment]
Sorry, I'm not sure if that requires additional changes (or if that's in scope for this PR). Currently in the Wagtail admin the editor for those fields looks like this:

image

Note the stars for required fields, so editors can't even save a page without specifying a close date and salary range.

I created a new backlog task for enforcing at least one Region or Grade; the change here was only meant to prevent a blank element on the page until that is done.

**Comment by schaferjh** [comment]
ok, I think this was all a miscommunication. I assumed all the things in your screenshot were the result of items being left blank in the admin. I was skimming too quickly and not clearly understanding what the screenshot was showing. Your original solution of no grade and no region if those are empty is fine.

New backlog task to enforce at least one Region or Grade sounds great. thanks.

Re: the focus of this PR, I assume the hardcoded sidebar looks just like the sidebar live on the site today? i.e. here: http://www.consumerfinance.gov/about-us/careers/enforcement-economist-cn-6060/

If so then 👍

**Comment by chosak** [comment]
@schaferjh yep, the hardcoded sidebar matches the legacy Django page sidebar exactly. Thanks for the review.

**Pull request merged**
