### PR TITLE
Fix linter warnings

### PR DESCRIPTION
**Pull request by anselmbradford**
## Changes

- Fixes some JS linter warnings.

### CODE REVIEW

**Comment by sebworks** [comment]
let's turn off the linter warning on Travis.  I think you just want to see the errors on Travis.

**Comment by anselmbradford** [comment]
> let's turn off the linter warning on Travis. I think you just want to see the errors on Travis.

Sounds good, but where would we do that? ESLint relies on .eslintrc on a per-directory basis, since there's already one in the home directory, we'd need the Travis config to edit that one somehow, or add a config to package.json, but only for Travis.

**Comment by sebworks** [comment]
So gulp scripts ` gulp:scripts --quiet` runs just the errors. We could do it here: https://github.com/cfpb/cfgov-refresh/blob/3bac3b585331d48890a9b980586480cee1c0baed/gulp/tasks/lint.js#L18

**Comment by jimmynotjim** [comment]
Have we ever looked into having travis measure the increase or decrease in warnings? If they're not being run in travis I fear they're just going to keep getting worse.

**Comment by Scotchester** [comment]
I like the idea of making Travis fail if the number of warnings goes up.

**Pull request merged**
