### PR TITLE
Replace PSI with Lighthouse for performance audit

### PR DESCRIPTION
**Pull request by anselmbradford**
PageSpeed Insights npm module appears to be [abandoned](https://github.com/addyosmani/psi/issues/93). There are also security issues with it and it requires localtunnel. Let's replace it with Google Lighthouse, which provides a more robust report.

## Changes

- Replaces `psi` with `lighthouse` for `gulp audit:perf` task.

## Testing

1. `./frontend.sh`
1. `./runserver.sh`
1. `gulp audit:perf`
1. `open ./logs/lighthouse_report.html` to view report.

## Screenshots

screen shot 2018-07-19 at 10 45 41 am

## Notes

- We could set this up to take a provided URL at the command-line, but for now it will audit the homepage, as PSI did.

### CODE REVIEW

**Comment by Scotchester** [comment]
Updated the testing steps to add `./runserver.sh`. This doesn't work in the Docker setup, though. It would be nice to fix that, or at least add a note to the `gulp audit:perf` test to that effect.

**Comment by anselmbradford** [comment]
> "Pay no attention to the accessibility results. This tool is not useful for accessibility auditing."

Lighthouse allows selectively setting the audits. Should we exclude the accessibility ones for the report?

**Comment by anselmbradford** [comment]
> This doesn't work in the Docker setup, though. 

What happens?

**Comment by jimmynotjim** [comment]
> Lighthouse allows selectively setting the audits. Should we exclude the accessibility ones for the report?

I think that's smart for now, especially when we already have other accessibility tests in place.

**Comment by Scotchester** [comment]
Docker results:

```
~/Projects/cf.gov/cfgov-refresh replace_psi_with_lighthouse* ⚓ gulp audit:perf
[10:31:41] Requiring task ./gulp/tasks/audit.js
[10:31:41] Using gulpfile ~/Projects/cf.gov/cfgov-refresh/gulpfile.js
[10:31:41] Starting 'audit:perf'...
  ChromeLauncher Waiting for browser. +0ms
  ChromeLauncher Waiting for browser... +1ms
  ChromeLauncher Waiting for browser..... +511ms
  ChromeLauncher Waiting for browser.....✓ +2ms
  ChromeLauncher Killing Chrome instance 70614 +664ms
Runtime error encountered: The url provided should have a proper protocol and hostname.
Error: The url provided should have a proper protocol and hostname.
    at Function.run (/Users/cranfills/Projects/cf.gov/cfgov-refresh/node_modules/lighthouse/lighthouse-core/runner.js:79:17)
    at lighthouse (/Users/cranfills/Projects/cf.gov/cfgov-refresh/node_modules/lighthouse/lighthouse-core/index.js:47:17)
    at chromeP.then._ (/Users/cranfills/Projects/cf.gov/cfgov-refresh/node_modules/lighthouse/lighthouse-cli/run.js:161:12)
    at <anonymous>
[10:31:44] 'audit:perf' errored after 3.12 s
[10:31:44] Error: exited with error code: 1
    at ChildProcess.onexit (/Users/cranfills/Projects/cf.gov/cfgov-refresh/node_modules/end-of-stream/index.js:39:36)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
```

**Comment by anselmbradford** [comment]
@Scotchester Does the psi `gulp audit:perf` command work for you on the master branch? Perhaps we could use the localtunnel setup psi uses to get it working in docker.

**Comment by anselmbradford** [comment]
This now excludes the accessibility audit in the test report.

**Comment by Scotchester** [comment]
> Does the psi gulp audit:perf command work for you on the master branch? Perhaps we could use the localtunnel setup psi uses to get it working in docker.

Yeah, it does.

**Comment by wpears** [comment]
I can confirm this works in the docker setup, provided you manually export the appropriate envvars. @Scotchester run `export TEST_HTTP_HOST=localhost && export DJANGO_HTTP_PORT=8000` and try again.

We probably want to think about providing defaults to these values in `./config/environment.js` or make sure that specifically `DJANGO_HTTP_PORT` doesn't default to commented out in `.env` (or exists at all in `.python_env`.

I'd say a little work in making environment variables work the same across the two setups is time well-spent, I'll do a little digging.

**Pull request merged**
