### PR TITLE
Responsive Consumer Credit Trends charts with CSS: upgrade to cfpb-chart-builder version 2.0.1

### PR DESCRIPTION
**Pull request by cfarm**
Upgrades to latest chart-builder at v2.0.0 with CSS media queries to make responsive charts. Also includes a bug fix for the projected date labels on charts, which was off by one month.

See [release notes](https://github.com/cfpb/cfpb-chart-builder/releases/tag/v2.0.0) for more info!

## Testing

1. check out branch, run `./setup.sh` to make sure you get dependencies + latest database
1. `./runserver.sh`
1. look at pretty responsive charts at the following URLs:
 - http://localhost:8000/data-research/consumer-credit-trends/auto-loans/borrower-risk-profiles/
 - http://localhost:8000/data-research/consumer-credit-trends/auto-loans/origination-activity/
 - http://localhost:8000/data-research/consumer-credit-trends/auto-loans/lending-neighborhood-income-level/
 - http://localhost:8000/data-research/consumer-credit-trends/auto-loans/lending-borrower-age/

## Screenshots

screen shot 2017-07-25 at 2 17 31 pm
screen shot 2017-07-25 at 2 18 09 pm
screen shot 2017-07-25 at 2 18 48 pm

## Notes

-

## Todos

- "Seasonally adjusted" text is cut off on one breakpoint (between 900 and 925px wide screens), working on a fix for this to come in separate PR

## Checklist

* [ ] PR has an informative and human-readable title
* [ ] Changes are limited to a single goal (no scope creep)
* [ ] Code can be automatically merged (no conflicts)
* [ ] Code follows the standards laid out in the [development playbook](https://github.com/cfpb/development)
* [ ] Passes all existing automated tests
* [ ] New functions include new tests
* [ ] New functions are documented (with a description, list of inputs, and expected output)
* [ ] Placeholder code is flagged
* [ ] Visually tested in supported browsers and devices
* [ ] Project documentation has been updated
* [ ] Reviewers requested with the [Assignee tool](https://help.github.com/articles/assigning-issues-and-pull-requests-to-other-github-users/) :arrow_right:

### CODE REVIEW

**Comment by contolini** [comment]
Niiiiice @cfarm! From just eyeballing that last screenshot it looks like the y-axis label `Volume of originations (in billions)` is now top-aligned instead of centered. Is that something worth correcting in this PR? Also, the darker line is ~ 1px thicker than what's on the live site. I'm fine either ignoring these discrepancies or updating them in a future release.

**Comment by cfarm** [comment]
@contolini good eye! Yup that left label alignment is happening on some charts and not on others. I would like to look into it separately and log it as a bug for follow up.

I'll ask @ajbush about that darker line thickness. It's come up before so I likely messed it up when re-doing the CSS.

**Comment by cfarm** [comment]
@ajbush requested I update the line thickness to 3px so I'll make an update in chart-builder for that before this gets merged.

**Comment by hillaryj** [comment]
Found something interesting - on bar charts when made smaller, the bars become not uniformly sized. Is this an issue or an artifact of the responsiveness?

screen shot 2017-07-25 at 3 55 45 pm

**Comment by cfarm** [comment]
Here is the line thickness fix. https://github.com/cfpb/cfpb-chart-builder/pull/63

**Comment by cfarm** [comment]
The varied bar widths issue @hillaryj describes seems to be the case on the live site and a pre-existing issue. I'll log a bug so it can be addressed separately from this release. Thanks for catching that, Hillary!

**Comment by cfarm** [comment]
Looks like I messed up publishing the npm package, cuz checking out this branch now and updating doesn't upgrade the styles properly. I'm looking into this now.

**Comment by contolini** [comment]
@cfarm you may want to publish a new version that includes the couple PRs that were just merged into cfpb-chart-builder.

**Comment by cfarm** [comment]
@contolini will do

**Comment by hillaryj** [comment]
I upgraded `nvm` to 8.2.1 (and deleted `package-lock.json` and now after running `./setup.sh` I'm getting correct graphs!

screen shot 2017-07-25 at 5 13 55 pm
screen shot 2017-07-25 at 5 14 10 pm

**Comment by cfarm** [comment]
Adding package-lock.json, which was missing as I hadn't upgraded my node to v8.

**Comment by cfarm** [comment]
@contolini published + upgraded to v2.0.1 https://github.com/cfpb/cfpb-chart-builder/releases/tag/v2.0.1

**Comment by cfarm** [comment]
Here's the CSS fixes for the line thickness + "Seasonally adjusted" text working locally:

screen shot 2017-07-25 at 5 46 19 pm

**Pull request merged**
