### PR TITLE
Cards: Update design-system to 0.1.x

### PR DESCRIPTION
**Pull request by anselmbradford**
## Changes

- Updates design-system to 0.1.x
- Removes card component less files from cfgov-refresh, which are delivered through cfpb-layout.

## Testing

1. Pull branch and run `./frontend.sh`.
2. Cards on homepage and on http://localhost:8000/ask-cfpb should be unchanged from production.

### CODE REVIEW

**Comment by anselmbradford** [comment]
@wpears Maybe we could put some instructions in the wiki or something on how to gracefully update packages? Not sure what I'm doing wrong.

**Comment by contolini** [comment]
> Maybe we could put some instructions in the wiki or something on how to gracefully update packages?

Yes plz. I think most people edit `.yarnrc`, update packages and then reset `.yarnrc`.

**Comment by anselmbradford** [comment]
> Yes plz. I think most people edit .yarnrc, update packages and then reset .yarnrc. I'm not sure what the proper process is.

I use [`yarn-check`](https://www.npmjs.com/package/yarn-check) for the updates, which obviously misses a step.

**Comment by Scotchester** [comment]
> > Maybe we could put some instructions in the wiki or something on how to gracefully update packages?
> 
> Yes plz. I think most people edit `.yarnrc`, update packages and then reset `.yarnrc`.

That should definitely not be necessary, right?

If memory serves, doesn't it come down to needing to use `yard add package` for everything and not manually updating `package.json`?

**Comment by contolini** [comment]
> If memory serves, doesn't it come down to needing to use yard add package for everything and not manually updating package.json?

Ah, cool, I remember it being flaky but I guess that's not the case anymore.

**Comment by wpears** [comment]
I've been testing this a bit, I think the truly foolproof command is:

`yarn cache clean && yarn add w@x.y.z`

I think if you have a package in your global yarn cache you won't get one generated in the yarn offline cache local to the project. This is imo a completely backwards design decision which I still need to validate. If it is indeed true, then I was thinking of just adding a small command to the package.json to smooth this a bit.

**Comment by wpears** [comment]
Just added a few docs in dev tips: https://github.com/cfpb/cfgov-refresh/pull/5632

**Comment by anselmbradford** [comment]
Thanks @wpears !

**Comment by anselmbradford** [comment]
Review plz!

**Pull request merged**
