### PR TITLE
Project standardize

### PR DESCRIPTION
**Pull request by jimmynotjim**
Reorganizing FJ to conform to directory structure used in the CF Generator and other CFPB projects
 
## Additions
 
- Adds `/src` directory for source files
 
## Removals
 
- Removes `/static` from project root (not yet completed, waiting to pull in in-progress changes)
 
## Changes
 
- Moves all html files, templates, processors, and assets into `/src`
- Updates gruntfile to copy non-compiled files from `/src` to `/dist`
- Updates gruntfile to compile assets from `/src/static` to `/dist/static`
 
## Testing
 
- checkout branch
- run `npm install && npm update`
- run `bower install && bower update`
- run `grunt compile-cf`
- run `grunt`
- `cd ./dist`
- start sheer and open browser
 
## Review
 
- @sebworks 
- @anselmbradford 
- @dpford 
- @Scotchester 
 
## Preview
 
None
 
## Notes
 
- __This is not ready for merging yet, simply for review by delivery at this moment__
- servers will need to be configured to point to `/dist` directory path
- deployment scripts will need to be configured to run necessary npm, bower and grunt commands
- to avoid the number of conflict fixes I'm waiting to merge in new upstream changes until this is entirely ready

### CODE REVIEW

**Comment by jimmynotjim** [comment]
@dpford do you think this will be able to make it in this Sprint or should we push it back to the next one?

**Comment by dpford** [comment]
I vote we push it to next sprint, if that doesn't cause a bunch of extra work

**Comment by jimmynotjim** [comment]
Not really, I haven't pulled in new commits since I started, I wanted to wait to avoid the number of fixes for merge conflicts. That's going to be the hardest part and I'd like to do it just once.

**Comment by sebworks** [comment]
:+1:

**Comment by jimmynotjim** [comment]
Closing because this needs to be broken up to avoid a large monolithic change.

**Pull request closed without merging**
