### PR TITLE
Updated the dep dir page title to include "Acting"

### PR DESCRIPTION
**Pull request by jimmynotjim**
Duplication of https://github.com/cfpb/cfgov-refresh/pull/997 to get it onto beta before the freeze

mr-freeze-evil-plan

### CODE REVIEW

**Comment by sebworks** [comment]
:+1: , lol.

**Comment by jimmynotjim** [comment]
Uh, no idea why this is failing, maybe because of all the other changes we've had to make in the fj branch?

**Comment by sebworks** [comment]
Looks all green now.

**Comment by jimmynotjim** [comment]
I better merge it before something else happens ;)

**Pull request merged**
