### PR TITLE
Add a script that can generate a changelog from GitHub

### PR DESCRIPTION
**Pull request by willbarton**
This PR has a script that can generate a changelog from a GitHub tag or between two tags.

The script takes a GitHub user/org, repository name, and tag or two tags.

```
$ python changelog.py -m cfpb cfgov-refresh 4.6.5
```

Or

```
$ python changelog.py -m cfpb cfgov-refresh 4.6.5 4.6.6
```

Will result in:

```
- Move es5-shim into deps from dev deps [2721](https://github.com/cfpb/cfgov-refresh/pull/2721)
- Add shrinkwrap file [2720](https://github.com/cfpb/cfgov-refresh/pull/2720)
- Fixes for build [2715](https://github.com/cfpb/cfgov-refresh/pull/2715)
- Bump chart builder to v1.1.1 [2719](https://github.com/cfpb/cfgov-refresh/pull/2719)
- Update knowledgebase requirement to 2.2.7 [2717](https://github.com/cfpb/cfgov-refresh/pull/2717)
- Use travis's containerized build [2718](https://github.com/cfpb/cfgov-refresh/pull/2718)
- Update knowledgebase requirement to 2.2.6 [2711](https://github.com/cfpb/cfgov-refresh/pull/2711)
- Make sure smoke tests that fail exit with an appropriate status [2714](https://github.com/cfpb/cfgov-refresh/pull/2714)
- Update CHANGELOG.md for 4.6.4 [2713](https://github.com/cfpb/cfgov-refresh/pull/2713)
- Fix for Google Map image of Washington DC on /archive-past-events/ page. [2710](https://github.com/cfpb/cfgov-refresh/pull/2710)
- Updated CHANGELOG.md for 4.6.3 [2709](https://github.com/cfpb/cfgov-refresh/pull/2709)
- Correctly show 'live + draft' status for unshared pages [2700](https://github.com/cfpb/cfgov-refresh/pull/2700)
- Don't always delete $NODE_DIR [2705](https://github.com/cfpb/cfgov-refresh/pull/2705)
- add decorator to help model __str__ method in python 2 [2706](https://github.com/cfpb/cfgov-refresh/pull/2706)
- 4.6.2 changelog [2704](https://github.com/cfpb/cfgov-refresh/pull/2704)
- Use the latest version of Node v6 in Travis builds [2703](https://github.com/cfpb/cfgov-refresh/pull/2703)
````

You can see it in use in the [4.6.6 release notes](https://github.com/cfpb/cfgov-refresh/releases/tag/4.6.6)

## Additions

- changelog.py script and tests

## Checklist

* [ ] Changes are limited to a single goal (no scope creep)
* [ ] Code can be automatically merged (no conflicts)
* [ ] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [ ] Passes all existing automated tests
* [ ] New functions include new tests
* [ ] New functions are documented (with a description, list of inputs, and expected output)
* [ ] Placeholder code is flagged
* [ ] Visually tested in supported browsers and devices
* [ ] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)
* [ ] Reviewers requested with the [Assignee tool](https://help.github.com/articles/assigning-issues-and-pull-requests-to-other-github-users/) :arrow_right:

### CODE REVIEW

**Comment by chosak** [comment]
@willbarton this script was useful for generating the [4.7.1 release](https://github.com/cfpb/cfgov-refresh/releases/tag/4.7.1), which I did using an annotated git tag that I created locally and then pushed (you still have to manually create the "release" in GitHub).

Would it make more sense for this script to live with the rest of the deployment code, versus in this repo? It might be useful for other projects as well.

**Comment by willbarton** [comment]
@chosak it would be useful for other projects, but we had a lively discussion last time that resulted in an understanding that scripts like that don't seem to belong with the deployment code. 

I'm happy to reopen that discussion though. It's also possible that this would be useful as a standalone Python package/command-line utility that is pip-installable. Thoughts?

**Comment by willbarton** [comment]
Thinking about it, I'm fairly certain I'd like to make it a pip-installable utility.

**Comment by willbarton** [comment]
Closing in favor of https://github.com/cfpb/github-changelog

**Pull request closed without merging**
