### PR TITLE
Travis, meet tox. Tox, meet travis

### PR DESCRIPTION
**Pull request by rosskarchner**
Configures Travis to run our python test suite, after all of the gulp stuff

### CODE REVIEW

**Comment by rosskarchner** [comment]
Tests pass!

**Comment by anselmbradford** [comment]
This change shouldn't be needed, `gulp test:unit` runs tox tests --> https://github.com/cfpb/cfgov-refresh/blob/flapjack/gulp/tasks/test.js#L229

Actual command to run here --> https://github.com/cfpb/cfgov-refresh/blob/flapjack/gulp/tasks/test.js#L48-L57

**Comment by rosskarchner** [comment]
Ah, interesting-- It might be worth pulling them apart at some point, so that they can run in parallel, but that'd be a whole different PR. Thanks!

**Comment by anselmbradford** [comment]
Gulp and `child.spawn` is asynchronous so they should currently have some parallelization capability.

**Comment by rosskarchner** [comment]
They thing I've seen (but haven't dug in to how to actually do), is have different sorts of tests running as different separate Travis builds, so we could, say, tell at a glance whether it's a Django error or part of the front end build (or a code quality metric, or some other sort of test we might run)

**Comment by rosskarchner** [comment]
Or, if we take advantage of tox's ability to test against a matrix of Python and Django versions, those could all show up a distinct builds, and pass or fail independently.

**Comment by rosskarchner** [comment]
Like this:

screen shot 2015-12-17 at 2 28 56 pm

**Pull request closed without merging**
