### PR TITLE
Update deployment jobs and descriptions to match reality

### PR DESCRIPTION
**Pull request by willbarton**
This is a brief update to the docs to update the deployment job names and their description to match the current Jenkins-as-code reality.

## Changes

- Reflect the change in name of the frontend-build and deploy-django jobs.
- Change the description of running the jobs, as they run through the pipeline build now.

## Review

- @cfpb/cfgov-platform 

* [X] Changes are limited to a single goal (no scope creep)
* [X] Code can be automatically merged (no conflicts)
* [ ] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [ ] Passes all existing automated tests
* [ ] New functions include new tests
* [ ] New functions are documented (with a description, list of inputs, and expected output)
* [ ] Placeholder code is flagged
* [ ] Visually tested in supported browsers and devices
* [X] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)

### CODE REVIEW

**Comment by higs4281** [comment]
One thought: link to cfpb/jenkins-automation from the Jenkins-as-code reference?

**Comment by willbarton** [comment]
@higs4281 I so very much want to, but all the URLs I could give (the job definition, the Jenkinses themselves) are internal URLs. 😞

**Comment by higs4281** [comment]
👍

**Comment by rosskarchner** [comment]
👍

**Pull request merged**
