### PR TITLE
Updating 404 image

### PR DESCRIPTION
**Pull request by sebworks**
Updating 404 image

## Changes
- Updated  ' static/img/plug.png' to new image. 

## Test
- Navigate to 'http://localhost:7000/404 '.

## Review 
- @jimmynotjim  
- @anselmbradford 
- @Scotchester  
- @KimberlyMunoz 

## Screenshots

Mobile
screen shot 2015-05-12 at 10 31 09 am

Tablet
screen shot 2015-05-12 at 10 30 58 am

Desktop
screen shot 2015-05-12 at 10 30 30 am

### CODE REVIEW

**Comment by Scotchester** [comment]
Was the change in dimensions intentional?

**Comment by sebworks** [comment]
@Scotchester yes, there was unnecessary space in the previous image.

**Comment by Scotchester** [comment]
:+1:

Sidenote: We can't fit the plug into the tablet-width display?

**Comment by sebworks** [comment]
@Scotchester, the image will display until 800px.

**Pull request merged**
