### PR TITLE
Moving /students into cfgov-refresh

### PR DESCRIPTION
**Pull request by sebworks**
Moving /students into cfgov-refresh

## Changes

- Created Jinja template and modified css code to move `/students` into cfgov-refresh. I had to modify the header / footer css to use the new cf4 atomic styles. I left the existing styles in place until all the Wordpress pages could be converted.

## Testing

1. Visit `localhost:8000/students`.
2. Compare it to `/students` on consumerfinance.gov.
3. View source on ` localhost:8000/students`; Verify the meta tags and og tags are correct.
4. Visit `http://localhost:8000/students/knowbeforeyouowe/`.
5. Compare it to `/students` on consumerfinance.gov.
6. View source on ` http://localhost:8000/students/knowbeforeyouowe/`; Verify the meta tags and og tags are correct.
7. Visit `http://localhost:8000/students/helping-borrowers-find-ways-to-stay-afloat/`.
8. Compare it to `/students` on consumerfinance.gov.
9. View source on `http://localhost:8000/students/helping-borrowers-find-ways-to-stay-afloat/`; Verify the meta tags and og tags are correct.

## Notes

- I didn't include include the `link` tags listed below:

```

<link rel='https://api.w.org/' href='https://www.consumerfinance.gov:443/wp-json/' />
<link rel="canonical" href="https://www.consumerfinance.gov:443/students/" />
<link rel='shortlink' href='https://www.consumerfinance.gov:443/?p=8331' />
<link rel="alternate" type="application/json+oembed" href="https://www.consumerfinance.gov:443/wp-json/oembed/1.0/embed?url=https%3A%2F%2Fwww.consumerfinance.gov%3A443%2Fstudents%2F" />

```
I can if folks deem it necessary.

## Todos

-

## Checklist

* [ ] PR has an informative and human-readable title
* [ ] Changes are limited to a single goal (no scope creep)
* [ ] Code can be automatically merged (no conflicts)
* [ ] Code follows the standards laid out in the [development playbook](https://github.com/cfpb/development)
* [ ] Passes all existing automated tests
* [ ] New functions include new tests
* [ ] New functions are documented (with a description, list of inputs, and expected output)
* [ ] Placeholder code is flagged
* [ ] Visually tested in supported browsers and devices
* [ ] Project documentation has been updated
* [ ] Reviewers requested with the [Assignee tool](https://help.github.com/articles/assigning-issues-and-pull-requests-to-other-github-users/) :arrow_right:

### CODE REVIEW

**Comment by anselmbradford** [comment]
A few differences in the footer from live that I'm not sure if they're intentional. The font on the top links (Contact Us, Newsroom, …) are slightly different locally and on live. Looks like a different Avenir reference in each. 

The middle links (FOIA, Plain Writing, …) are in a slightly different arrangement.

Locally the flag icon at the bottom-left is missing.

Local:

screen shot 2017-08-30 at 9 49 31 am


Live:

screen shot 2017-08-30 at 9 49 36 am

Let me know if those are of concern or not.

**Comment by anselmbradford** [comment]
`/students/helping-borrowers-find-ways-to-stay-afloat/` doesn't have "Students and young consumers" in the breadcrumb navigation at the top, like is present on the live site.

**Comment by sebworks** [comment]
> A few differences in the footer from live that I'm not sure if they're intentional. The font on the top links (Contact Us, Newsroom, …) are slightly different locally and on live. Looks like a different Avenir reference in each.

Fixed in https://github.com/cfpb/cfgov-refresh/pull/3255/commits/6d8bbd30f9ba9649761fedd6c5ccb854ec0eac6f

> The middle links (FOIA, Plain Writing, …) are in a slightly different arrangement.

The links on the live site are wrong, the nemo footer is out of date. 

 > Locally the flag icon at the bottom-left is missing.

Please run `gulp:copy`, the `/students` pages are now using the regular footer markup. 

> /students/helping-borrowers-find-ways-to-stay-afloat/ doesn't have "Students and young consumers" in the breadcrumb navigation at the top, like is present on the live site.

I've fixed the issue on the breadcrumbs.

**Comment by sebworks** [comment]
@anselmbradford, please take another look when you get a chance.

**Comment by mistergone** [comment]
Note that your __Testing__ section lists urls which are in other PRs. ;-)

**Pull request merged**
