### PR TITLE
Fixes DF-1680 download list consistency

### PR DESCRIPTION
**Pull request by anselmbradford**
Makes downloadable icon lists consistent. Refactors code to remove placeholder scoping and changes underlying layout for multi-line lists.

## Additions

- Creates new `list_text` class and adds it in the content where needed.

## Removals

- Removes extraneous whitespace and newlines.
- Removes scoping to multi-line lists introduced in https://github.com/cfpb/cfgov-refresh/pull/422.

## Changes

- Refactors multi-line `list__icons` to use `table-cell` display value instead of absolute positioning.
- Gives new cf-enhancements patterns the correct family and tag name.
- Changes list on /budget/funding-request/ to using `<time>` elements instead of `<span>`. 
- Re-generates assets via `grunt`.

## Testing

Updated icon and text on:
- /doing-business-with-us/past-awards/
- /budget/performance-plan-report/
- /budget/financial-report/
- /budget/funding-request/
- /the-bureau/bureau-structure/
- /newsroom/press-resources/
- /contact-us/

## Review

- @jimmynotjim 
- @sebworks 
- @Scotchester  

## Preview

screen shot 2015-03-26 at 7 59 11 pm

screen shot 2015-03-26 at 7 59 19 pm

screen shot 2015-03-26 at 7 59 26 pm

screen shot 2015-03-26 at 7 59 34 pm

screen shot 2015-03-26 at 7 59 45 pm

## Notes

- I was trying to avoid using `display:table-cell` because it requires wrapping the text within a `li` with a `span`, but I found it to require the least amount of code for ensuring the icon lists remain multi-line capable. Absolute positioning ran into collisions if the list items contained things that are relatively positioned already.
- I also updated the content related to the budget and past award lists on `build` and `content`. I changed date wrapping spans into `time` elements, removed `title` attributes (considered harmful), added `target="_blank"`, and did general formatting.

### CODE REVIEW

**Comment by Scotchester** [comment]
> Absolute positioning ran into collisions if the list items contained things that are relatively positioned already.

Is there an existing example of this, or just hypothetical?

**Comment by anselmbradford** [comment]
> Is there an existing example of this, or just hypothetical?

Kind of a mix of both. I ran into a particular difficulty with this, but I could hypothetically there could be multi-line lists with icons that used different link styles that could cause issues due to the `a` element being between the `li` element and its content.

Here's the context: There are `list__icons` that look like:

```html
<ul class="list list__icons">
    <li class="list_item u-break-word">
        <span class="cf-icon cf-icon-email list_icon"></span>
        <a class="list_link" href="mailto:info@consumerfinance.gov">
            info@consumerfinance.gov
        </a>
    </li>
    ...                          
</ul>
```
(http://beta.consumerfinance.gov/contact-us/)


And...

```html
<ul>
    <li>
        <a href="/f/201502_cfpb_transfer-request-letter_q1.pdf">
            <span>October 8, 2014</span> funding request letter to the Federal Reserve Board
        </a>
    </li>
...
</ul>
```
(http://beta.consumerfinance.gov/budget/funding-request/)

The former has classes and html markup for the icon, while latter is pulling in content from WP, so has all styles added through Less mixins. In the latter, the icon is added through a `:before` pseudoselector on the `a`.

Now to position the icon using absolute positioning, ideally it would be relative to the `li`, but the lists on `/budget/funding-request/` use jump links, which add relative positioning to the `a`, so several overrides are needed to accommodate for the jump link positioning ([here](https://github.com/cfpb/cfgov-refresh/blob/flapjack/static/css/budget.less#L30-L35), [here](https://github.com/cfpb/cfgov-refresh/blob/flapjack/static/css/budget.less#L44), and [here](https://github.com/cfpb/cfgov-refresh/blob/flapjack/static/css/budget.less#L48)).

Unfortunately, this messes up the appearance of the former pattern, since the icons are added with a `span` that is next to the text content, not a parent of it. Scoping these multi-line styles to certain pages was necessary to get this out to beta (added in https://github.com/cfpb/cfgov-refresh/pull/422).

Working with these styles it feels very brittle because an item in a `list__icons` list may or may not have a link inside that may or may not be pulling in a particular link style with its own positioning, optical offsets, etc. It may or may not be adding the icon to a `span`, or it may be adding it to the parent container with a `:before`.

Table display values may have a bad taste because they evoke memories of table-based layouts, but semantically they're fine, and there are several advantages I see: 
 - They can be used in fragments and the necessary parent elements will be created as [anonymous boxes in the box model](http://dev.w3.org/csswg/css-display/#anonymous-box).
 - They are unaffected by relative positioning settings in the parent element tree.
 - They're well supported.

The downside is that to not become visually stacked (icon and text on its own line), the text content needs to be wrapped in a `span`. So the structure looks like (w/o links):

```
ul.list__icons
    li.list_item
       span.list_icon
       span.list_text
           text content
```

Or...

```
ul
    li
       span
           text content
```

I'd argue though that wrapping the text content in a span is a good practice, because it allows the text to be targeted directly without having to resort to styling the parent element and possibly colliding with styles on the icon. I suppose an empty `span` could be added next to the text content in WP, but the purpose of this doesn't seem as clear to me as just wrapping the text in a span.

Hope that all makes sense!

**Comment by anselmbradford** [comment]
Fixed conflicts w/ `flapjack` and adjusted code comments per https://github.com/cfpb/cfgov-refresh/pull/451#discussion_r27670337.

How's this PR l@@kin'?

**Comment by sebworks** [comment]
@anselmbradford , it looks good to me but do you want to wait on feedback from @Scotchester ?

**Comment by Scotchester** [comment]
Sorry, forgot about this one. That all seems very well-thought-out. Thanks, @anselmbradford! :+1:

**Comment by anselmbradford** [comment]
No worries!

**Pull request merged**
