### PR TITLE
Molecules tests

### PR DESCRIPTION
**Pull request by richaagarwal**
@rosskarchner @kave @kurtw  - Just adds some more tests for molecules. 

- Refresh db 
- Run `gulp test:acceptance:wagtail --specs=molecules.js`

### CODE REVIEW

**Comment by kurtw** [comment]
Each one failed for me :( Are there any other things I must do?

**Comment by richaagarwal** [comment]
I would make sure you've reset the database. Ideally we would just have that as part of the test script; not sure why we don't :\

**Comment by rosskarchner** [comment]
I got 2/8 --

When you say "refresh DB", do you mean run initial-test-data.sh, or load a recent snapshot of the 'refresh' server?

**Comment by rosskarchner** [comment]
it worked! 👍

**Pull request merged**
