### PR TITLE
Adding rel="noopener noreferrer" property to target blank links

### PR DESCRIPTION
**Pull request by sebworks**
Adding rel="noopener noreferrer" property to target blank links

## Changes

- Modified files to add  rel="noopener noreferrer" property to links which had the `_target=blank`.

## Testing

1. Visit modified pages and ensure modified links work correctly. 

## Notes

- Timeline.js is a bit of a tricky one and I'll have to address that in a different fashion.
- I didn't update some legacy pages that are dead and can be removed.

## Checklist

* [ ] PR has an informative and human-readable title
* [ ] Changes are limited to a single goal (no scope creep)
* [ ] Code can be automatically merged (no conflicts)
* [ ] Code follows the standards laid out in the [development playbook](https://github.com/cfpb/development)
* [ ] Passes all existing automated tests
* [ ] Any *change* in functionality is tested
* [ ] New functions are documented (with a description, list of inputs, and expected output)
* [ ] Placeholder code is flagged
* [ ] Visually tested in supported browsers and devices
* [ ] Project documentation has been updated
* [ ] Reviewers requested with the [Reviewer tool](https://help.github.com/articles/about-pull-request-reviews/) :arrow_right:

### CODE REVIEW

**Comment by lfatty** [comment]
@sebworks, looks good to me. I will run another test once it is merged.

**Comment by Scotchester** [comment]
Cross-posting this comment I made on the platform to be sure it gets addressed before we merge this:

> Do we really need the `noreferrer` on this? If I understand correctly, it seems like `noopener` would be sufficient, without hurting the data that sites we link to receive about the fact that we're linking to them.
>
> But say we did want to block referrers universally, setting the Referrer-Policy header would be a better approach.

**Comment by lfatty** [comment]
“**noreferrer**” for Firefox and old browsers

“**noopener**” for Chrome and Opera

**Comment by Scotchester** [comment]
@lfatty Do you have an article or something we can reference?

**Comment by sebworks** [comment]
thanks @Scotchester, I'm trying to get up to speed as well.

**Comment by lfatty** [comment]
@Scotchester, google is your best friend for a quick answer,  but I would love to point to:
https://mathiasbynens.github.io/rel-noopener/. Look under Recommendations.
https://blog.templatetoaster.com/rel-noreferrer-noopener-seo/

**Comment by Scotchester** [comment]
@lfatty I had found that first link, but it still wasn't clear about why exactly `noreferrer` would help. Upon further review, I followed the link from that page to [`rel="noopener"` spec](https://html.spec.whatwg.org/multipage/links.html#link-type-noreferrer) and discovered the answer:

> For historical reasons, the `noreferrer` keyword implies the behavior associated with the `noopener` keyword when present on a hyperlink that creates a new browsing context. That is, `<a href="..." rel="noreferrer" target="_blank">` has the same behavior as `<a href="..." rel="noreferrer noopener" target="_blank">`.

So, I change my position! Go forth and be merry with `noopener noreferrer` when placing on `target="_blank"` links.

**Comment by lfatty** [comment]
@Scotchester, I glad that you found the answer.

**Pull request merged**
