### PR TITLE
Don't force superusers to reset their passwords

### PR DESCRIPTION
**Pull request by chosak**
When developing locally, the `initial-data.sh` script creates an `admin` superuser with the password defined in the `WAGTAIL_ADMIN_PW` environment variable. Current password policy requires that all new users must change their passwords right away, which adds an extra step to getting up and running with a new database.

This PR modifies the way that password policy is enforced by exempting superusers from having to change their passwords right away after creation.

## Additions

- New unit tests around the `User` [post-save callback](https://github.com/cfpb/cfgov-refresh/blob/master/cfgov/v1/signals.py#L31).

## Changes

- New users that have `is_superuser=True` do not have to change their passwords right away.

## Testing

- Run `tox -e fast` to run all Python unit tests or just `tox -e fast v1.tests.test_signals` to run tests for this specific logic.
- Run the following commands to (optionally) drop and recreate your local database, and verify that you can login as the `admin` user to Wagtail:

 ```sh
 $ ./drop-db.sh
 $ ./create-mysql-db.sh
 $ WAGTAIL_ADMIN_PW=toomanysecrets ./initial-data.sh
 $ ./runserver.sh
 ```
 Open your browser to [http://localhost:8000/admin](http://localhost:8000/admin), and login with username `admin` and password `toomanysecrets`.

## Review

- @grapesmoker @richaagarwal @willbarton 

## Notes

- It's still a good idea for "real" superusers to change their passwords from the initial ones that they're given.

## Checklist

* [X] Changes are limited to a single goal (no scope creep)
* [X] Code can be automatically merged (no conflicts)
* [ ] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [X] Passes all existing automated tests
* [X] New functions include new tests
* [ ] New functions are documented (with a description, list of inputs, and expected output)
* [ ] Placeholder code is flagged
* [ ] Visually tested in supported browsers and devices
* [ ] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)

### CODE REVIEW

**Comment by higs4281** [comment]
- tested superuser creation in master and in this branch, and the password policy works as advertised.
- tests pass

👍 to clearing up a dev hindrance and adding the lovely tests.

**Comment by willbarton** [comment]
giphy

Fantastic. The only request I would have is, could you add a quick bit about this to the installation docs? Perhaps under [Optional Steps](http://cfpb.github.io/cfgov-refresh/installation/#optional-steps)? Because `initial_data.sh` is called by `backend.sh` (called by `setup.sh`), this is also pertinent to users setting it up for the first time. (Maybe also a note about the `WAGTAIL_ADMIN_PW` in .env as well?

**Comment by willbarton** [comment]
@chosak Looks good!

**Comment by willbarton** [comment]
:shipit:

**Pull request merged**
