### PR TITLE
Docs: Tweak Docker in-container command and Python testing instructions

### PR DESCRIPTION
**Pull request by Scotchester**
## Changes

- On the "Running Docker" page, renames "Run Django management commands" to "Commands that must be run from within a Docker container" and moves the "Access a container's shell" section into that

### CODE REVIEW

**Comment by willbarton** [comment]
Could I push a couple of changes to the test docs to accompany this change?

**Comment by Scotchester** [comment]
> Could I push a couple of changes to the test docs to accompany this change?

@willbarton By all means!

**Comment by willbarton** [comment]
I pushed the testing docs I was talk about — in the commit message, I do note that the Docker setup doesn't currently work for running tests, but I'm actively working on fixing that.

**Comment by willbarton** [comment]
@cfarm FYI, the testing docs updates here are the ones I started after we paired a few weeks ago about how to get set up to actually run the tests. It'd be great to have your eyes on them too.

**Comment by willbarton** [comment]
From @marteki's experience with translation I also have some updates I need to make to the translation docs.

**Comment by Scotchester** [comment]
Note to self: Revisit after getting #5434 merged.

**Comment by Scotchester** [comment]
@willbarton I'm going to go ahead and merge this to get it out of the queue. Please open a new PR for your translation doc updates.

**Pull request merged**
